### ISSUE TITLE
Feature request: Pass ID as string/value rather using resource id

### ISSUE THREAD

**Issue by bensonarokiadoss** [rancher/terraform-provider-rancher2#100]
Its not an issue, feature request.
In certain scenario, where we wont use state file. we might like to keep cloud credentials  and node template created just once
For nodetemplate we pass cloud_credential_id and for nodepool we pass node_template_id, can this be made option and allow support of Credentials name and node template names instead of resource ids 

Any suggestion or workaround welcome.

**Comment by rawmind0** [comment]
@bensonarokiadoss , have you consider to use datasources?? Not available for node_template, but should work for [cloudCredential](https://www.terraform.io/docs/providers/rancher2/d/cloudCredential.html)

**Comment by bensonarokiadoss** [comment]
thanks @rawmind0 yes i was able to use data source to solve the cloud credential. For the Node_tempalte i have to end up creating templates for each cluster. Are you aware of any action or plan to support data source option for template

**Comment by rawmind0** [comment]
yeah, definitely datasource for node_template will be added. It's on the backlog. :)

**Comment by bensonarokiadoss** [comment]
thanks @rawmind0

**Comment by rawmind0** [comment]
Merged PR adding node_template datasource. Please, reopen issue if needed.
