### ISSUE TITLE
rancher2_cluster errors when using 1.24.2 as admission_configurations is changed from a map to a list

### ISSUE THREAD

**Issue by burgerjeffrey** [rancher/terraform-provider-rancher2#1011]
Unable to run `terraform plan/apply/destroy` for any resource that has rancher2_cluster as a dependency for rancher2_cluster using terraform provider 1.24.2.  rancher2_cluster resource was created using 1.24.1 provider.

Error message from a `terraform plan/apply/destroy:`

`Error: missing expected [`

When I compared terraform states for the rancher2_cluster resource, this popped out to me:
`"admission_configuration": {},`  is what pre-124.2 looked like
`"admission_configuration": [],` is what 1.24.2 looks like

I had to delete my terraform state for resource `rancher2_cluster` and import it again to resolve itself.

Most likely related to this change that came in 1.24.2.: https://github.com/rancher/terraform-provider-rancher2/pull/909

**Comment by richard-mck** [comment]
I'm seeing this same error in CI/CD using gitlab with pipelines that were previously working. 

Downgrading to 1.24.1 resolves the issue on my side.

**Comment by ajchiarello** [comment]
I'm also seeing this error, and downgrading to 1.24.1 also worked.

**Comment by SebastiaanBASF** [comment]
Same error here

**Comment by Typositoire** [comment]
> I'm also seeing this error, and downgrading to 1.24.1 also worked.

Hitting the same issue and this also fixed it for us.

**Comment by elixxx** [comment]
Hitting the same issue, for now a downgrade to 1.24.1 solve the issue

**Comment by HarrisonWAffel** [comment]
Hello everyone, my sincere apologies for this issue. The PR introducing this schema change will be reverted and the next release will not encounter this problem. Until then it is suggested that you continue to use v1.24.1 if you have defined the `admission_configuration` field for your cluster, and upgrade directly to v1.24.3 when it is available. The documentation for v1.24.2 will be updated to mention this problem, and I will update this issue when the next release is made available.

**Comment by HarrisonWAffel** [comment]
The change which introduced this issue has been reverted and v1.25.0 should no longer encounter this issue.

**Comment by alnitech73** [comment]
Just had the same issue after upgrading to 1.25.0. 
```
│ Error: Failed to decode resource from state
│
│ Error decoding "module.cluster-blue[0].rancher2_cluster.cluster[0]" from previous state: missing expected {
╵
╷
│ Error: missing expected {
│
│   with module.cluster-blue[0].rancher2_cluster.cluster[0],
│   on ../../terraform-modules/terraform-rancher-k8s/main.tf line 1, in resource "rancher2_cluster" "cluster":
│    1: resource "rancher2_cluster" "cluster" {```


Reverting to 1.24.2 fixed it.

**Comment by HarrisonWAffel** [comment]
@alnitech73 This issue will impact clusters created before 1.24.2 which then move to 1.24.2. Similarly, it will impact clusters which were created on 1.24.2 which then move to 1.25.0 (or any version other than 1.24.2). You will likely have to rebuild the terraform state by reimporting the cluster. Sorry about this

**Comment by alnitech73** [comment]
got it! yes. I just noticed the plan was ok, but then the apply failed.
