### ISSUE TITLE
RKE2 mirror endpoints get sorted

### ISSUE THREAD

**Issue by gregsidelinger** [rancher/terraform-provider-rancher2#1028]
The provider is sorting the list of mirror end points I provide taking away my ability to decide on the order mirrors should be tried in.

**Comment by snasovich** [comment]
@annablender , could you please fill out more information to help QA test this issue? Also, please help backporting it (creating backport issue now).

**Comment by a-blender** [comment]
Backport issue is in. I need to verify how to test this/will add a test template on Monday

**Comment by a-blender** [comment]
## Testing template

#### Root cause

The TFP rancher2 is incorrectly sorting the list of rke2 registry mirror endpoints, thus not giving the user the ability to sort them in the way they want.
 
#### What was fixed, or what changes have occurred

Sort has been removed [here](https://github.com/rancher/terraform-provider-rancher2/pull/1091/commits/3468d21160c5f56365d54a15619535bb5c6dc09c).

#### Areas or cases that should be tested

Test `registries.mirrors.endpoint` sort by running a terraform plan.

Steps
* Write a main config file for an rke2 cluster, specify a list of registry mirror endpoints
* Run `terraform init`
* Run `terraform apply` and observe endpoints field in output

<details>

<summary>main.tf</summary>

```
terraform {
  required_providers {
    rancher2 = {
      source = "terraform.local/rancher2"
      version = "3.0.0-rcx"
    }
  }
}

provider "rancher2" {
  api_url   = var.rancher_api_url 
  token_key = var.rancher_admin_bearer_token
  insecure  = true
}

# Create amazonec2 cloud credential
resource "rancher2_cloud_credential" "foo" {
  name = "foo"
  amazonec2_credential_config {
    access_key = var.aws_access_key
    secret_key = var.aws_secret_key
  }
}

# Create amazonec2 machine config v2
resource "rancher2_machine_config_v2" "foo" {
  generate_name = "ablender-machine"
  amazonec2_config {
    ami            = var.aws_ami
    region         = var.aws_region
    security_group = [var.aws_security_group_name]
    subnet_id      = var.aws_subnet_id
    vpc_id         = var.aws_vpc_id
    zone           = var.aws_zone_letter
    root_size      = var.aws_root_size
  }
}

# Create a new rancher v2 amazonec2 RKE2 Cluster v2
resource "rancher2_cluster_v2" "ablender-rke2" {
  name = var.rke2_cluster_name
  kubernetes_version = "v1.25.6+rke2r1"
  enable_network_policy = false
  default_cluster_role_for_project_members = "user"
  rke_config {
    machine_pools {
      name = "pool1"
      cloud_credential_secret_name = rancher2_cloud_credential.foo.id
      control_plane_role = true
      etcd_role = true
      worker_role = true
      quantity = 1
      machine_config {
        kind = rancher2_machine_config_v2.foo.kind
        name = rancher2_machine_config_v2.foo.name
      }
    }
    registries { 
      mirrors {
        hostname = "<http://docker.io|docker.io>"
        endpoints = [
          "<https://my-pullthrough-proxy.example1.com>",
          "<https://my-pullthrough-proxy.example2.com>",
          "<https://docker.io>"
        ]
      }
    }
  }
}
```

</details>

<details>

<summary>Expected output</summary>

```
+ registries {

              + mirrors {
                  + endpoints = [
                      + "<https://my-pullthrough-proxy.example1.com>",
                      + "<https://my-pullthrough-proxy.example2.com>",
                      + "<https://docker.io>",
                    ]
                  + hostname  = "<http://docker.io|docker.io>"
                }
            }
```

</details>
 
#### What areas could experience regressions ?

None
 
#### Are the repro steps accurate/minimal ?

Yes.

**Comment by Josh-Diamond** [comment]
rancher2 provider [v3.0.0-rc2](https://github.com/rancher/terraform-provider-rancher2/releases/tag/v3.0.0-rc2) has been released. Ready to-test now.

**Comment by Josh-Diamond** [comment]
Ticket #1028 - Test Results - ✅ 
---

With Docker on a single-node instance using Rancher `v2.7.2-rc8`:

Reproduced w/ rancher2 provider `v1.25.0`:
1. Fresh install of rancher `v2.7.2-rc8`
2. Using TF, create a `main.tf` to request a downstream RKE2 Node driver cluster w/ multiple registry mirror endpoints, in a specific order
3. Run `terraform init`, then run `terraform apply`
4. Observe mirror endpoints get sorted
5. Reproduced

`main.tf`
```terraform
registries { 
      mirrors {
        hostname = "<http://docker.io|docker.io>"
        endpoints = [
          "<https://z-my-pullthrough-proxy.example1.com>",
          "<https://k-my-pullthrough-proxy.example2.com>",
          "<https://a-docker.io>"
        ]
      }
    }
``` 

`terraform plan - sorted`
<img width="523" alt="Screenshot 2023-04-10 at 9 58 52 AM" src="https://user-images.githubusercontent.com/46494969/230951791-71fea0b8-08a7-44f8-915f-044f152d6edb.png">

---

Verified w/ rancher2 provider `v3.0.0-rc2`:
1. Fresh install of rancher `v2.7.2-rc8`
2. Using TF, create a `main.tf` to request a downstream RKE2 Node driver cluster w/ multiple registry mirror endpoints, in a specific order
3. Run `terraform init`, then run `terraform apply`
4. Observe mirror endpoints NOT sorted
5. Verified - mirror endpoint sort removed

`main.tf`
```terraform
registries { 
      mirrors {
        hostname = "<http://docker.io|docker.io>"
        endpoints = [
          "<https://z-my-pullthrough-proxy.example1.com>",
          "<https://k-my-pullthrough-proxy.example2.com>",
          "<https://a-docker.io>"
        ]
      }
    }
```

`terraform plan`
<img width="520" alt="Screenshot 2023-04-10 at 10 05 31 AM" src="https://user-images.githubusercontent.com/46494969/230952844-c8973ac1-beec-4ed0-a379-abbdb22ea236.png">
