### ISSUE TITLE
Setting up azure ad authentication does not work via terraform but with gui

### ISSUE THREAD

**Issue by ajfriesen** [rancher/terraform-provider-rancher2#104]
I am getting a wired issue when trying to setup the azuread authentication system.

Code:
```
resource "rancher2_auth_config_azuread" "azuread" {
  application_id = "<AZUREAD_APP_ID>"
  application_secret = "<AZUREAD_APP_SECRET>"
  auth_endpoint = "<AZUREAD_AUTH_ENDPOINT>"
  graph_endpoint = "<AZUREAD_GRAPH_ENDPOINT>"
  rancher_url = "<RANCHER_URL>"
  tenant_id = "<AZUREAD_TENANT_ID>"
  token_endpoint = "<AZUREAD_TOKEN_ENDPOINT>"
  access_mode           = "unrestricted"
}
```

Error:
```
Error: [ERROR] No api_url provided

  on <empty> line 0:
  (source code not available)
```

I can assure that setting this up via GUI works 100% since I just did that to verify if the error is in azure ad or some bad secret or misspelling.

How can I debug this?
I am using terraform 0.12.6 and this provider in version 1.4.1

**Comment by rawmind0** [comment]
It seems a problem with the provider configuration. are you are providing rancher2 api_url??

**Comment by ajfriesen** [comment]
You are totally right. This was my mistake.

I did not setup the provider in the rancher cluster module.

I also can not do this because this module bootstraps the rancher cluster.
And I first need a cluster before I can have a token which is needed to configure azure ad.

**Comment by rawmind0** [comment]
On v1.4.1, bootstrap has some improvements. You could configure the provider twice (bootstrap and admin modes) in same tf file, https://www.terraform.io/docs/providers/rancher2/index.html#example-usage
