### ISSUE TITLE
Add support for third party Node Templates

### ISSUE THREAD

**Issue by ntoljic** [rancher/terraform-provider-rancher2#105]
Currently the `rancher2_node_template` resource only supports some of the built-in Node Drivers.

What I would like to see is a generic configuration option for Node Templates from other Node Drivers.
Would this even be possible? From my limited understanding the challenge stems from the fact that each Node Driver requires its own configuration. Is there a least common denominator that would sacrifice some flexibility by imposing default values?

Alternatively, is there a roadmap for adding support for more Node Drivers. In particular, I would be interested in support for Hetzner Cloud (a UI Driver already exists [here](https://mxschmitt.github.io/ui-driver-hetzner), but it is not built-in).

I am just getting started with rancher, k8s and terraform, but have some experience with docker and go. With the right pointers I would be willing to get my hands dirty and submit a PR :)

**Comment by rawmind0** [comment]
@ntoljic as you've mentioned, the problem around generic `rancher2_node_template` stems from the fact that each node driver requires its own configuration. There is no common denominator on that, every single node driver is asking its own parameters. 

Anyway, generic `rancher2_node_template` would be possible using terraform maps instead lists for params, but it would generate a problem to check/verify parameters and probably a bunch of user issues. The provider would be harder to support.

By the moment, no any other node template implementation is on the roadmap. More than happy if you submit a PR to support Hetzner Cloud node driver. :)

To start, take a look to the current node templates implementation. You need to define its schema and structure files, and add the new option to the node_template schema, structure and resource.

https://<RANCHER_URL>/v3/schemas/hetznerconfig 

```
{
  "baseType": "schema",
  "id": "hetznerconfig",
  "links": {
  "self": "…/v3/schemas/hetznerconfig"
  },
  "pluralName": "hetznerconfigs",
  "resourceFields": {
    "apiToken": {
    "create": true,
    "default": "",
    "description": "Project-specific Hetzner API token",
    "dynamicField": true,
    "type": "string",
    "update": true
    },
    "existingKeyId": {
    "create": true,
    "default": "0",
    "description": "Existing key ID to use for server; requires --hetzner-existing-key-path",
    "dynamicField": true,
    "type": "string",
    "update": true
    },
    "existingKeyPath": {
    "create": true,
    "default": "",
    "description": "Path to existing key (new public key will be created unless --hetzner-existing-key-id is specified)",
    "dynamicField": true,
    "type": "string",
    "update": true
    },
    "image": {
    "create": true,
    "default": "ubuntu-18.04",
    "description": "Image to use for server creation",
    "dynamicField": true,
    "type": "string",
    "update": true
    },
    "imageId": {
    "create": true,
    "default": "0",
    "description": "Image to use for server creation",
    "dynamicField": true,
    "type": "string",
    "update": true
    },
    "networks": {
    "create": true,
    "description": "Network IDs or names which should be attached to the server private network interface",
    "dynamicField": true,
    "type": "array[string]",
    "update": true
    },
    "serverLocation": {
    "create": true,
    "default": "",
    "description": "Location to create machine at",
    "dynamicField": true,
    "type": "string",
    "update": true
    },
    "serverType": {
    "create": true,
    "default": "cx11",
    "description": "Server type to create",
    "dynamicField": true,
    "type": "string",
    "update": true
    },
    "userData": {
    "create": true,
    "default": "",
    "description": "Cloud-init based User data",
    "dynamicField": true,
    "type": "string",
    "update": true
    },
    "volumes": {
    "create": true,
    "description": "Volume IDs or names which should be attached to the server",
    "dynamicField": true,
    "type": "array[string]",
    "update": true
    }
  },
  "type": "schema",
  "version": {
  "group": "management.cattle.io",
  "path": "/v3",
  "version": "v3"
  }
}
```

**Comment by ntoljic** [comment]
@rawmind0, thank you for your pointers. I have started adding the Hetzner Cloud configuration.

However, it seems to me that I will also have to add support for Cloud Credentials for Hetzner Cloud. Is this assumption correct or can I add node template support without cloud credentials?

**Comment by rawmind0** [comment]
@ntoljic , due to Hetzner Cloud driver is not built in, you don't need to add rancher cloud credentials. You just need to manage node driver api keys or token inside the resource. Take care to select this fields as sensitive on terraform. :)

**Comment by ntoljic** [comment]
Thanks for the clarification :)

I managed to make some progress but unfortunatelly, I have hit another speedbump.
The driver name that I configured (`hetzner`) yields the following error when creating the `node_template` with the provider:

```
Error: [ERROR] Getting Node Driver hetzner: Bad response statusCode [404]. Status [404 Not Found]. Body: [baseType=error, code=NotFound, message=nodedrivers.management.cattle.io "hetzner" not found] from [https://<RANCHER_URL>/v3/nodedrivers/hetzner]
```

This is because `node_driver`s that are not built in, get generated ID which is not equal to the driver's name. However, this is the case for the built-in drivers.

Where e.g. the driver named `openstack` has an ID of `openstack`, my driver named `hetzner` has an ID of i.e. `nd-vblw2`. The generated ID of course changes every time I run `terraform apply` from scratch.

So the provider cannot create the template because it cannot find the driver to create it with, since the Rancher API endpoint that is used is expecting the driver ID which the provider cannot know ahead of time.

But there is also good news. While the endpoint to access node drivers requires the ID to be used, the [rancher2_node_driver](https://www.terraform.io/docs/providers/rancher2/r/nodeDriver.html#id) returns this very ID during creation.
The only missing link here would be to extend the config for `rancher2_node_template` to allow an optional `driver_id` attribute. Its value could be hardcoded for the built-in drivers for backwards-compatibility, but would allow third-party drivers to be added over time.

Another idea, that would keep the provider config untouched, would be to search for drivers by name, using the following URL:

https://<RANCHER_URL>/v3/nodeDrivers?name=hetzner

This would require that all node driver related functions to be changed from `id` to `name` as their param.

Any thoughts?

**Comment by ntoljic** [comment]
Nevermind, I found a better solution.
I simply borrowed some code from `dataSourceRancher2NodeDriverRead` in `data_source_rancher2_node_driver.go` to get the driver's ID based on its name :)

Will do some more manual testing and cleanup, before I submit a PR.

A pointer on how to implement automated testing without cloud credentials would be nice though.

**Comment by rawmind0** [comment]
@ntoljic , node_driver from name could be got like that...

```
filters := map[string]interface{}{
    "name": name,
}
listOpts := NewListOpts(filters)

nodeDrivers, err := client.NodeDriver.List(listOpts)
if err != nil {
    return err
}

// nodeDrivers would be a `NodeDriverCollection`. `nodeDrivers.Data` would be a NodeDriver array
```

**Comment by rawmind0** [comment]
Please reopen issue if needed.

**Comment by emrahcetiner** [comment]
@ntoljic can you share how you configure hetzner driver?

**Comment by ntoljic** [comment]
@emrahcetiner, let me get back to you after the holidays, so I can clean stuff up before sharing ;)

**Comment by ntoljic** [comment]
@emrahcetiner, I have submitted the PR https://github.com/terraform-providers/terraform-provider-rancher2/pull/216

Maybe we should reopen this issue (and possibly rename it). @rawmind0, what do you think?

**Comment by tibuntu** [comment]
Hey @ntoljic, I am currently doing the same changes to support 'OpenNebula' node templates. I faced the same issue regarding the node_driver id. Would you mind sharing a code snippet with the required changes so that the name is used rather than the id?

@rawmind0  should I create a PR to support OpenNebula, too?

**Comment by rawmind0** [comment]
> @rawmind0 should I create a PR to support OpenNebula, too?

@tibuntu sure, this PR would be more than appreciated.
