### ISSUE TITLE
Feature request: Add keyPairName support on eks_config while rancher2_cluster cluster creation

### ISSUE THREAD

**Issue by sub2u** [rancher/terraform-provider-rancher2#106]
right now we can't provide custom keyPairName from AWS to eks_config while cluster creation.

Please provide support as rancher 2.27 supports it.

**Comment by ishantanu** [comment]
@rawmind0 ~Mind if I give this a try?~ Already made the changes and testing. I can see that we can provide keypair options via GUI and rancher does support it. So, adding `key_pair_name` to the provisioner should be possible. Correct me if I am wrong.

**Comment by rawmind0** [comment]
Submitted PR #114 with the enhancement

**Comment by rawmind0** [comment]
Merged PR that add the feature. Please, reopen if needed.
