### ISSUE TITLE
[Backport release/v2] No way to configure vmAffinity for Harvester clusters 

### ISSUE THREAD

**Issue by a-blender** [rancher/terraform-provider-rancher2#1069]
Backport for https://github.com/rancher/terraform-provider-rancher2/issues/1009

### Is your feature request related to a problem? Please describe.

Maybe I'm missing the config somewhere, but I've looked all over and can't find a way to configure node scheduling rules for Harvester deployments. Here's a screenshot from the UI of what I'm trying to configure:

<img width="1744" alt="image" src="https://user-images.githubusercontent.com/5328577/197367874-83ce2c5c-e088-4f3b-87c0-1562eed7a416.png">

I was expecting to find a spot to configure this in `rancher2_machine_config_v2`, since it seems this setting gets applied to the property `vmAffinity` for the resulting `HarvesterConfig`.  E.g. value:

```
vmAffinity: eyJub2RlQWZmaW5pdHkiOnsicmVxdWlyZWREdXJpbmdTY2hlZHVsaW5nSWdub3JlZER1cmluZ0V4ZWN1dGlvbiI6eyJub2RlU2VsZWN0b3JUZXJtcyI6W3sibWF0Y2hFeHByZXNzaW9ucyI6W3sia2V5IjoidG9wb2xvZ3kua3ViZXJuZXRlcy5pby96b25lIiwib3BlcmF0b3IiOiJJbiIsInZhbHVlcyI6WyJ5eXoyIl19XX1dfX19
```

which decodes to
```
{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"topology.kubernetes.io/zone","operator":"In","values":["yyz2"]}]}]}}}
```

This is important so I can ensure nodes deploy across availability zones. Right now, they're all going into one. Thanks for any help!

### Describe the solution you'd like

`vmAffinity` field added to the Terraform rancher2 provider.

**Comment by a-blender** [comment]
See test plan for original issue https://github.com/rancher/terraform-provider-rancher2/issues/1009#issuecomment-1435309647.

**Comment by a-blender** [comment]
Blocked -- waiting on Terraform 2.0.0 for Rancher v2.6.x.

**Comment by snasovich** [comment]
Same as https://github.com/rancher/terraform-provider-rancher2/issues/1009#issuecomment-1437795825

**Comment by a-blender** [comment]
@snasovich See my comment here https://github.com/rancher/terraform-provider-rancher2/issues/1009#issuecomment-1438622005.

**Comment by a-blender** [comment]
@sowmyav27 This is ready to test using Terraform rancher2 [v2.0.0-rc1](https://github.com/rancher/terraform-provider-rancher2/releases/tag/v2.0.0-rc1). Please setup local testing on the rc version of the provider with this command

```
./setup-provider.sh rancher2 2.0.0-rc1
```

**Comment by slickwarren** [comment]
@a-blender could you add a testing template? I'm not seeing the option for vmAffinity per:
https://github.com/rancher/terraform-provider-rancher2/blob/v2.0.0-rc1/docs/resources/machine_config_v2.md
Looking at:
[https://github.com/rancher/terraform-provider-rancher2/commit/f9e53eae19df0c063df42cc922bac6b8228d0b27#diff-d038de94a45a49d2[…]592e071695401a82df547](https://github.com/rancher/terraform-provider-rancher2/commit/f9e53eae19df0c063df42cc922bac6b8228d0b27#diff-d038de94a45a49d2f55af5132e1bb3077cc2f92bcea592e071695401a82df547) cc @irishgordo

**Comment by a-blender** [comment]
@slickwarren The field is named `vm_affinity` and it actually is listed in [the machine_config_v2.md docs](https://github.com/rancher/terraform-provider-rancher2/blob/v2.0.0-rc1/docs/resources/machine_config_v2.md) in the Harvester cluster config.

<img width="837" alt="image" src="https://user-images.githubusercontent.com/12955547/225332318-31a9f45c-616c-4143-92ae-86e40a364e04.png">

**Comment by irishgordo** [comment]
Hi @a-blender thanks for that insight :smile: 

When testing this on Rancher v2.6.11, the (./setup-provider.sh rancher2 2.0.0-rc1) and w/ Harvester v1.1.2-rc5 with the main.tf of:
```terraform
# Get imported harvester cluster info
data "rancher2_cluster_v2" "test-harvester-clstr" {
  name = "harvester-test"
}

# Create a new Cloud Credential for an imported Harvester cluster
resource "rancher2_cloud_credential" "harvester-test-cc-terraform" {
  name = "harvester-test"
  harvester_credential_config {
    cluster_id = data.rancher2_cluster_v2.test-harvester-clstr.cluster_v1_id
    cluster_type = "imported"
    kubeconfig_content = data.rancher2_cluster_v2.test-harvester-clstr.kube_config
  }
}

# Create a new rancher2 machine config v2 using harvester node_driver
resource "rancher2_machine_config_v2" "foo-harvester-v2-cloud-provider" {
  generate_name = "foo-harvester-v2-cloud-provider"
  harvester_config {
    vm_namespace = "default"
    cpu_count = "4"
    memory_size = "8"
    disk_size = "40"
    network_name = "default/vlan1"
    image_name = "default/ubuntu-20.04-server-cloudimg-amd64-disk-kvm.img"
    ssh_user = "ubuntu"
    vm_affinity = "eyJub2RlQWZmaW5pdHkiOnsicmVxdWlyZWREdXJpbmdTY2hlZHVsaW5nSWdub3JlZER1cmluZ0V4ZWN1dGlvbiI6eyJub2RlU2VsZWN0b3JUZXJtcyI6W3sibWF0Y2hFeHByZXNzaW9ucyI6W3sia2V5IjoidG9wb2xvZ3kua3ViZXJuZXRlcy5pby96b25lIiwib3BlcmF0b3IiOiJJbiIsInZhbHVlcyI6WyJ1cy1mcmVtb250LTFhIl19XX1dfX19"
  }
}

# Create a new harvester rke2 cluster with harvester cloud provider
resource "rancher2_cluster_v2" "foo-harvester-v2-cloud-provider" {
  name = "foo-harvester-v2-cloud-provider"
  kubernetes_version = "v1.24.10+rke2r1"
  rke_config {
    machine_pools {
      name = "pool1"
      cloud_credential_secret_name = rancher2_cloud_credential.harvester-test-cc-terraform.id
      control_plane_role = true
      etcd_role = true
      worker_role = true
      quantity = 1
      machine_config {
        kind = rancher2_machine_config_v2.foo-harvester-v2-cloud-provider.kind
        name = rancher2_machine_config_v2.foo-harvester-v2-cloud-provider.name
      }
    }
    machine_selector_config {
      config = {
        cloud-provider-config = file("${path.module}/foo-harvester-v2-cloud-provider-kubeconfig")
        cloud-provider-name = "harvester"
      }
    }
    machine_global_config = <<EOF
cni: "calico"
disable-kube-proxy: false
etcd-expose-metrics: false
EOF
    upgrade_strategy {
      control_plane_concurrency = "10%"
      worker_concurrency = "10%"
    }
    etcd {
      snapshot_schedule_cron = "0 */5 * * *"
      snapshot_retention = 5
    }
    chart_values = <<EOF
harvester-cloud-provider:
  clusterName: foo-harvester-v2-cloud-provider
  cloudConfigPath: /var/lib/rancher/rke2/etc/config-files/cloud-provider-config
EOF
  }
}
```

And the provider.tf of:
```terraform
terraform {
  required_providers {
    harvester = {
      source = "harvester/harvester"
      version = "0.6.0"
    }
    rancher2 = {
      source = "terraform.local/local/rancher2"
      version = "2.0.0-rc1"
    }
  }
}

provider "rancher2" {
  api_url = "https://REDACTED"
  insecure = true
  access_key = "token-g5kfd"
  secret_key = "ws9l2z7gmdk2zmq78x8cw4vwmmvddjppg79bq8r954vzbk9b4vv7xr"
}
```

I ended up needing to modify the `setup-provider` script since I was noticing that I think the `VERSION_TAG`  - but I'm not 100% sure it seemed it wasn't necessarily getting filled out:
```bash

./setup-provider.sh rancher2 2.0.0-rc1
this is provider
rancher2
this is version
2.0.0-rc1
this is VERSION_TAG
.0.0-rc1
now fixing VERSION_TAG but hardcoding...
this is os platform:
linux_amd64
this is dir
/home/mike/.terraform.d/plugins/terraform.local/local/rancher2/2.0.0-rc1/linux_amd64
this is waht
https://github.com/rancher/terraform-provider-rancher2/releases/download/2.0.0-rc1/terraform-provider-rancher2_2.0.0-rc1_linux_amd64.zip
overriding whatever it is previously... downloading it hardcoded mostly as: https://github.com/rancher/terraform-provider-rancher2/releases/download/v2.0.0-rc1/terraform-provider-rancher2_2.0.0-rc1_linux_amd64.zip
Terraform provider rancher2 2.0.0-rc1 is ready to test!
Please update the required_providers block in your Terraform config file

terraform {
  required_providers {
    rancher2 = {
      source = terraform.local/local/rancher2
      version = 2.0.0-rc1
    }
  }
}

```

Then ultimately the rancher 2 directories for the plugin I think is good with:
```
ls -alh ~/.terraform.d/plugins/terraform.local/local/rancher2 
total 20K
drwxrwxr-x 5 mike mike 4.0K Apr  3 18:13 .
drwxrwxr-x 4 mike mike 4.0K Apr  3 17:55 ..
drwxrwxr-x 3 mike mike 4.0K Apr  3 17:55 .0.0-rc1
drwxrwxr-x 3 mike mike 4.0K Apr  3 18:13 2.0.0
drwxrwxr-x 3 mike mike 4.0K Apr  3 18:12 2.0.0-rc1
```

And under the `2.0.0-rc1`:
```
╭─mike at suse-workstation-team-harvester in ~/Projects/crop-bushels/terraform/applications/docker-rancher269 on main✘✘✘
╰─± ls -alh ~/.terraform.d/plugins/terraform.local/local/rancher2/2.0.0-rc1/linux_amd64/terraform-provider-rancher2 
-rwxrwxr-x 1 mike mike 57M Apr  3 18:12 /home/mike/.terraform.d/plugins/terraform.local/local/rancher2/2.0.0-rc1/linux_amd64/terraform-provider-rancher2
```

I too made sure that the `terraform-provider-rancher2` was set with a `chmod +x` within it because before then I was seeing:
```
╭─mike at suse-workstation-team-harvester in ~/Projects/terraform-vmaffinity-test
╰─○ terraform plan                                                                              
╷
│ Error: Failed to load plugin schemas
│ 
│ Error while loading schemas for plugin components: Failed to obtain provider schema: Could not load the schema for provider
│ terraform.local/local/rancher2: failed to instantiate provider "terraform.local/local/rancher2" to obtain schema: fork/exec
│ .terraform/providers/terraform.local/local/rancher2/2.0.0-rc1/linux_amd64/terraform-provider-rancher2: permission denied.
```

Terraform init, refresh and plan then all looked good.

But what I'm encountering now is:
```
rancher2_cloud_credential.harvester-test-cc-terraform: Creating...
rancher2_machine_config_v2.foo-harvester-v2-cloud-provider: Creating...
rancher2_cloud_credential.harvester-test-cc-terraform: Creation complete after 3s [id=cattle-global-data:cc-4qtnr]
rancher2_machine_config_v2.foo-harvester-v2-cloud-provider: Creation complete after 3s [id=fleet-default/nc-foo-harvester-v2-cloud-provider-4768n]
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for rancher2_cluster_v2.foo-harvester-v2-cloud-provider to include new values learned so far during apply, provider
│ "terraform.local/local/rancher2" produced an invalid new value for .rke_config[0].machine_pools[0].cloud_credential_secret_name: was
│ cty.StringVal(""), but now cty.StringVal("cattle-global-data:cc-4qtnr").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

```

And it seems the `foo-harvester-v2-cloud-provider provisioning` is seeing that.
Additionally, I made sure that the:
```
curl -k -X POST ${RANCHER_SERVER_URL}/k8s/clusters/${HARVESTER_CLUSTER_ID}/v1/harvester/kubeconfig \
   -H 'Content-Type: application/json' \
   -u ${RANCHER_ACCESS_KEY}:${RANCHER_SECRET_KEY} \
   -d '{"clusterRoleName": "harvesterhci.io:cloudprovider", "namespace": "default", "serviceAccountName": "'${CLUSTER_NAME}'"}' | xargs | sed 's/\\n/\n/g' > ${CLUSTER_NAME}-kubeconfig
```
From https://github.com/rancher/terraform-provider-rancher2/blob/v2.0.0-rc1/docs/resources/cluster_v2.md#creating-rancher-v2-harvester-cluster-v2-with-harvester-cloud-provider - was downloaded and inside the directory so that the 
```terraform
        cloud-provider-config = file("${path.module}/foo-harvester-v2-cloud-provider-kubeconfig")
```
could pick it up.

Perhaps my configuration is bad somewhere?

**Comment by a-blender** [comment]
@irishgordo Hello,

Thank you for tweaking the test script. There's an example on how to run it

https://github.com/rancher/terraform-provider-rancher2/blob/a7d6bfd0125817b1c4c6b711b7bdedeff62eebd5/setup-provider.sh#L11-L12

I believe you were missing the "v" in the version. It should be `v3.0.0-rc1` not `3.0.0-rc1.` Thank you for the note about `chmod +x`, I think I've run into that once before. I'll include it in this update PR https://github.com/rancher/terraform-provider-rancher2/pull/1085. It hasn't been merged yet due to pending testing on an additional script I've added to test the TFP provider on windows (I just tested that this morning and it should be good to go now!)

This is a known bug. You are seeing that terraform apply error because Terraform sees a known value of "" for a duplicate `cloud_credential_secret_name` in the `rancher2_cluster_v2` schema.  This workaround https://github.com/rancher/terraform-provider-rancher2/pull/1070 needs to be backported. I'll do that and cut a new rc to unblock you.

**Comment by a-blender** [comment]
@irishgordo There's an example in the test script on how to run it

```
# Example
# ./setup-provider.sh rancher2 v3.0.0-rc1
```

I believe you were missing the "v" in the <version>. Thank you for the note about `chmod +x` though, I think I've run into that once before. I'll include it in this update PR https://github.com/rancher/terraform-provider-rancher2/pull/1085

**Comment by a-blender** [comment]
@irishgordo Test script updates have been merged and rc [v2.0.0-rc3](https://github.com/rancher/terraform-provider-rancher2/releases/tag/v2.0.0-rc3) has been cut. Please pull the latest changes from `release/v2` and use the following command to setup the new provider rc locally again

```
./setup-provider rancher2 v2.0.0-rc3
```

Please let me know if there are any script errors.

Please try testing vmAffinity again and let us know your results, thank you ;)

**Comment by irishgordo** [comment]
**validation issue/failure**

Hi @a-blender  thanks for the fix to the test script - the new script works out awesome :smile: !!

Upon snagging the v2.0.0-rc3 retesting w/ Harvester v1.1.2-rc5 & Rancher v2.6.11- we're finding that the `spec.affinity.nodeAffinity` is not being set on the VM that represents the `rancher2_cluster_v2` that is created - to represent the JSON base64 encoded blob of:
```json
{
    "nodeAffinity": {
        "requiredDuringSchedulingIgnoredDuringExecution": {
            "nodeSelectorTerms": [
                {
                    "matchExpressions": [
                        {
                            "key": "topology.kubernetes.io/zone",
                            "operator": "In",
                            "values": [
                                "us-fremont-1a"
                            ]
                        }
                    ]
                }
            ]
        }
    }
}
```
Though it does provision successfully :smile: 

![Screenshot from 2023-04-06 10-45-58](https://user-images.githubusercontent.com/5370752/230460420-4969a997-a074-4d46-942f-fa39e3a96d17.png)

cc: @noahgildersleeve 
Utilizing relatively the same `main.tf` from prior test run.

Also just double-checked to make sure that nodeAffinity w/ the toplogy.kubernetes.io/zone key would work for a vm `test` in v1.1.2-rc5 as well, following loosely the kubevirt docs:
https://kubevirt.io/api-reference/master/definitions.html#_k8s_io_api_core_v1_nodeaffinity

And it looks like in v1.1.2-rc5 the nodeAffinity is working as expected.

![Screenshot from 2023-04-06 11-23-27](https://user-images.githubusercontent.com/5370752/230464480-95c81fd4-92ba-426f-b099-2cdafe9f49b3.png)
![Screenshot from 2023-04-06 11-22-50](https://user-images.githubusercontent.com/5370752/230464483-987f4e55-e2b4-47a6-bdf9-765b4fefcf25.png)
![Screenshot from 2023-04-06 11-22-20](https://user-images.githubusercontent.com/5370752/230464485-266c6a29-58af-498d-8ccc-5d6b12355128.png)


So as a baseline, it looks like on the v1.1.2-rc5 side that is still good -yet the issue still persists with the `vm_affinity` property on the `rancher2_machine_config_v2` the rke2 vm that got created doesn't seem to have that.

**Comment by irishgordo** [comment]
Also just double-checked to make sure that nodeAffinity w/ the toplogy.kubernetes.io/zone key would work for a vm `test` in v1.1.2-rc5 as well, following loosely the kubevirt docs:
https://kubevirt.io/api-reference/master/definitions.html#_k8s_io_api_core_v1_nodeaffinity

And it looks like in v1.1.2-rc5 the nodeAffinity is working as expected.

![Screenshot from 2023-04-06 11-23-27](https://user-images.githubusercontent.com/5370752/230464480-95c81fd4-92ba-426f-b099-2cdafe9f49b3.png)
![Screenshot from 2023-04-06 11-22-50](https://user-images.githubusercontent.com/5370752/230464483-987f4e55-e2b4-47a6-bdf9-765b4fefcf25.png)
![Screenshot from 2023-04-06 11-22-20](https://user-images.githubusercontent.com/5370752/230464485-266c6a29-58af-498d-8ccc-5d6b12355128.png)

**Comment by a-blender** [comment]
Won't backport
