### ISSUE TITLE
When a node pool is created and quality set to 0 still it create a node and following run deletes it

### ISSUE THREAD

**Issue by bensonarokiadoss** [rancher/terraform-provider-rancher2#107]
When a node pool is created and quantity set to 0 still it create a node

Step 1: During first terraform execution a node pool is created with 1 node
Step 2: During second terraform execution the node created before will be deleted

**Comment by rawmind0** [comment]
The minimum and the default quantity for node-pool is 1, same on rancher UI. What would be the sense to create a node pool with quantity set to 0??

**Comment by bensonarokiadoss** [comment]
My use case we dont use state files and in certain scenarios we might need to create the node template and leave it for the AZ. So we are fine with how it works as we would create a node pool using the template if we need to set up nodes on the AZ. This is more of an observation when i set to  0 it makes sense it create the node with 1 as that how it works in the UI. But on the second run it goes and delete those since set to 0. 

Reason for the raising as expecting either one of the below

1. Fails/Error out for 0
2. Create node pool but leave the node count to 0 (Preferred - Since it give my customer the ability to add nodes if needed on those pools)
3. Create a min of 1 node if set to 0 but dont delete on the second run

Feel free to close out if you feel not appropriate

**Comment by rawmind0** [comment]
It's completely approppiate, thanks for reporting it.

We'll address it following one of your suggestions.

**Comment by rawmind0** [comment]
Submitted PR #121 to address it.

**Comment by rawmind0** [comment]
Merged PR #121 to address issue. Please, reopen it if needed.
