### ISSUE TITLE
[v2.6] RKE2 mirror endpoints get sorted

### ISSUE THREAD

**Issue by snasovich** [rancher/terraform-provider-rancher2#1072]
Backport of https://github.com/rancher/terraform-provider-rancher2/issues/1028 for Terraform Provider v2.0.x line (for Rancher v2.6.x).

**Comment by a-blender** [comment]
@sowmyav27 Please use this [test template](https://github.com/rancher/terraform-provider-rancher2/issues/1028#issuecomment-1485311175) on TFP rancher2 2.0.0-rcx.

**Comment by Josh-Diamond** [comment]
Ticket #1072 - Test Results - ✅ 
---

With Docker on a single-node instance using Rancher `v2.6.11`:

Reproduced w/ rancher2 provider `v1.25.0`:
1. Fresh install of rancher `v2.6.11`
2. Using TF, create a `main.tf` to request a downstream RKE2 Node driver cluster w/ multiple registry mirror endpoints, in a specific order
3. Run `terraform init`, then run `terraform apply`
4. Observe mirror endpoints get sorted
5. Reproduced

`main.tf`
```terraform
registries { 
      mirrors {
        hostname = "<http://docker.io|docker.io>"
        endpoints = [
          "<https://z-my-pullthrough-proxy.example1.com>",
          "<https://k-my-pullthrough-proxy.example2.com>",
          "<https://a-docker.io>"
        ]
      }
    }
``` 

`terraform plan - sorted`
<img width="526" alt="Screenshot 2023-03-30 at 10 14 33 AM" src="https://user-images.githubusercontent.com/46494969/228913876-c5917e5e-fc88-4816-9990-17fb61b140c8.png">

---

Verified w/ rancher2 provider `v2.0.0-rc2`:
1. Fresh install of rancher `v2.6.11`
2. Using TF, create a `main.tf` to request a downstream RKE2 Node driver cluster w/ multiple registry mirror endpoints, in a specific order
3. Run `terraform init`, then run `terraform apply`
4. Observe mirror endpoints NOT sorted
5. Verified - mirror endpoint sort removed

`main.tf`
```terraform
registries { 
      mirrors {
        hostname = "<http://docker.io|docker.io>"
        endpoints = [
          "<https://z-my-pullthrough-proxy.example1.com>",
          "<https://k-my-pullthrough-proxy.example2.com>",
          "<https://a-docker.io>"
        ]
      }
    }
```

`terraform plan`
<img width="521" alt="Screenshot 2023-03-30 at 10 43 21 AM" src="https://user-images.githubusercontent.com/46494969/228920224-3c3ef46c-2853-4fc1-938b-d3e66e915012.png">
