### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by duemila2** [rancher/terraform-provider-rancher2#1076]
### Rancher Server Setup
- Rancher version: 2.7.1
- Installation option (Docker install/Helm Chart): Docker

### Information about the Cluster
- Kubernetes version: v1.24.8-eks-ffeb93d
- Cluster Type (Local/Downstream): AWS EKS imported

### User Information
- What is the role of the user logged in? Admin

### Provider Information
- What is the version of the Rancher v2 Terraform Provider in use? 1.25.0
- What is the version of Terraform in use? 1.2.3

### Describe the bug
We have a recurrent pipeline that every day recreate an EKS cluster and every day it fails with the error:

```
│ Error: [ERROR] waiting for cluster (c-6l966) to be created: timeout while waiting for state to become 'pending' (last state: 'active', timeout: 10m0s)
│ 
│   with module.flairbit_rancher_eks.rancher2_cluster.cluster,
│   on ../../modules/flairbit_rancher_eks/0.0.7/cluster.tf line 11, in resource "rancher2_cluster" "cluster":
│   11: resource "rancher2_cluster" "cluster" {
│ 
╵
```
I checked and the cluster on Rancher is in state "active", but terraform script is waiting for the cluster to be "pending", I don't know why. Could you please help me?

**Comment by a-blender** [comment]
This is a duplicate of https://github.com/rancher/terraform-provider-rancher2/issues/1003. Closing this one
