### ISSUE TITLE
[RFE] Setup automation for QA to Test Terraform with RCs

### ISSUE THREAD

**Issue by a-blender** [rancher/terraform-provider-rancher2#1083]
### Is your feature request related to a problem? Please describe.

Terraform has originally been tested with the _released_ versions published on the registry. This is not ideal since QA should be validating that Terraform fixes and features work before the provider is released, but it never bottlenecked work before so it went unnoticed.

This issue is to update this process.

### Describe the solution you'd like

After discussion with Hostbusters team and QA, we've agreed that QA should test Terraform issues prior to release with Terraform RCs. These will not be published to the registry to avoid Hashicorp being slow with publishing a release, but instead will be tested locally. The script in this PR will automate the process of downloading the rc binary and setting it up locally for a QA engineer so testing runs smoothly and efficiently. The test team mostly uses osx and linux so the script supports those platforms but if any others (win32, freebsd, openbsd) need to be added then let me know.

@snasovich @sowmyav27 have signed off on the following workflow

To test a Terraform issue, QA will
* Call a script `setup-provider.sh <provider> <version>` which will download the correct binary and copy it to their local system
* Update `required_providers` block in their config file (which they would've had to do anyway) to

```
terraform {
  required_providers {
    rancher2 = {
      source = "terraform.local/local/<provider>"
      version = "<version>"
    }
  }
}
```

* Test

**Comment by a-blender** [comment]
Terraform provider rancher2 [v3.0.0-rc1](https://github.com/rancher/terraform-provider-rancher2/releases/tag/v3.0.0-rc1) for rancher 2.7.x and [v2.0.0-rc1](https://github.com/rancher/terraform-provider-rancher2/releases/tag/v2.0.0-rc1) for rancher 2.6.x have been tagged. Waiting for review on automation script to move issues To Test

**Comment by a-blender** [comment]
Automation script has been merged! Relevant issues moved To Test

**Comment by a-blender** [comment]
Worked on the following

* Updated the unix/Mac test script with a few fixes and comment from Harvester team to add `chmod +x` to the downloaded binary.
* Tested and added / updated working version of win32 script
* Created backport issue https://github.com/rancher/terraform-provider-rancher2/issues/1101
* Back ported both scripts to `release/v2` so they will be available in the TFP rancher2 release line that is loosely coupled with Rancher 2.6.

**Comment by a-blender** [comment]
# Test plan

@slickwarren Test plan, thanks for pointing out this still needs post-merge validation from QA! I'll slow down on trying to get things 'closed' ;)

# Problem

  
Terraform has originally been tested with the released versions published on the registry. This is not ideal since QA should be validating that Terraform fixes and features work before the provider is released, but it never bottlenecked work before so it went unnoticed.

# Solution

  
New QA process to test TF issues using RCs instead of testing them after release. Added scripts for Mac, linux, and windows for QA engineers on different platforms to setup RCs locally just by running the script.

# Testing

 
## Engineering Testing

### Manual Testing

 
### Automated Testing


Verify script works with QA engineers on Mac / linux / windows.

Test steps
* Clone rancher/terraform-provider-rancher2 repo, checkout `master`
* Run `./setup-provider.sh <provider> <version>` on Mac / linux OR
* Run `./setup-provider-windows.ps1 <provider> <version>` from powershell on a win32 OS

Update main.tf

```
terraform {
  required_providers {
    rancher2 = {
      source = "terraform.local/local/rancher2"
      version = "3.0.0-rc1"
    }
  }
}
```

Run `terraform init` and verify RC is installed successfully
Run `terraform apply` and make sure that you can successfully provision infra with the local RC. Optional: run whatever tests are on your plate.
 
## QA Testing Considerations

  
### Regressions Considerations

**Comment by thaneunsoo** [comment]
Tested on windows and it seems to be working as expected.
![image](https://github.com/rancher/terraform-provider-rancher2/assets/108360907/8aff6bdc-037c-402f-bde5-2c3c5ca214f8)
