### ISSUE TITLE
[BUG] Can't add new revision to existing rke cluster template

### ISSUE THREAD

**Issue by rwl50** [rancher/terraform-provider-rancher2#1086]
### Rancher Server Setup
- Rancher version: v2.6.9
- Installation option (Docker install/Helm Chart): 
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details:

### Information about the Cluster
- Kubernetes version: 1.22.13
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

### User Information
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

Admin

### Provider Information
- What is the version of the Rancher v2 Terraform Provider in use?
- What is the version of Terraform in use?

rancher2 1.22.2

terraform 0.14.2

### Describe the bug
I am trying to add a new revision to an existing RKE1 cluster template and it's not working:
Error: Updating ClusterTemplateRevision cattle-global-data:ctr-w27sv: Bad response statusCode [422]. Status [422 Unprocessable Entity]. Body: [baseType=error, code=InvalidAction, message=Cannot update the clusterTemplateRevision until Clusters are referring it] from [https://rancherm-lab/v3/clusterTemplateRevisions/cattle-global-data:ctr-w27sv]

### To Reproduce
Try adding a new revision using terraform rancher2 provider to an existing RKE1 cluster template; even though no changes are proposed for the existing revisions it still fails with the above error

### Actual Result
`An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.rke_templates.rancher2_cluster_template.cluster_template will be updated in-place
  ~ resource "rancher2_cluster_template" "cluster_template" {
        id                  = "cattle-global-data:ct-7c9jb"
        name                = "cluster_rke_template"
        # (4 unchanged attributes hidden)

      + template_revisions {
          + annotations = (known after apply)
          + default     = false
          + enabled     = true
          + labels      = (known after apply)
          + name        = "v2023.03.08-4"

          + cluster_config {
              + enable_cluster_alerting   = false
              + enable_cluster_monitoring = false
              + enable_network_policy     = false
              + windows_prefered_cluster  = false

              + cluster_auth_endpoint {
                  + enabled = true
                }

              + rke_config {
                  + addon_job_timeout     = 0
                  + enable_cri_dockerd    = false
                  + ignore_docker_version = true
                  + ssh_agent_auth        = false
                  + ssh_key_path          = "*************"

                  + authentication {
                      + sans     = [
                          + "*.dev.<redacted>",
                        ]
                      + strategy = "x509"
                    }

                  + network {
                      + mtu     = 0
                      + options = (known after apply)
                      + plugin  = "canal"
                    }

                  + private_registries {
                      + is_default = true
                      + password   = (sensitive value)
                      + url        = "<redacted>"
                      + user       = (sensitive value)
                    }
                  + private_registries {
                      + is_default = false
                      + password   = (sensitive value)
                      + url        = "<redacted>"
                      + user       = (sensitive value)
                    }

                  + services {
                      + etcd {
                          + extra_args = (known after apply)
                          + gid        = 0
                          + snapshot   = false
                          + uid        = 0

                          + backup_config {
                              + enabled        = true
                              + interval_hours = 6
                              + retention      = 30
                              + safe_timestamp = false
                              + timeout        = 0
                            }
                        }

                      + kube_api {
                          + always_pull_images       = false
                          + extra_args               = (known after apply)
                          + pod_security_policy      = false
                          + service_cluster_ip_range = "10.43.0.0/16"
                        }

                      + kube_controller {
                          + cluster_cidr             = "10.42.0.0/16"
                          + extra_args               = (known after apply)
                          + service_cluster_ip_range = "10.43.0.0/16"
                        }

                      + kubelet {
                          + cluster_dns_server           = "10.43.0.10"
                          + extra_args                   = {
                              + "image-gc-high-threshold" = "65"
                              + "image-gc-low-threshold"  = "50"
                            }
                          + fail_swap_on                 = false
                          + generate_serving_certificate = false
                        }
                    }

                  + upgrade_strategy {
                      + drain                        = false
                      + max_unavailable_controlplane = "1"
                      + max_unavailable_worker       = "1"
                    }
                }
            }

          + questions {
              + default  = "v1.22.13-rancher1-1"
              + required = false
              + type     = "string"
              + variable = "rancherKubernetesEngineConfig.kubernetesVersion"
            }
          + questions {
              + required = true
              + type     = "string"
              + variable = "localClusterAuthEndpoint.fqdn"
            }
          + questions {
              + required = false
              + type     = "string"
              + variable = "localClusterAuthEndpoint.caCerts"
            }
        }
        # (3 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.`

Upon applying the above plan:

`Error: Updating ClusterTemplateRevision cattle-global-data:ctr-w27sv: Bad response statusCode [422]. Status [422 Unprocessable Entity]. Body: [baseType=error, code=InvalidAction, message=Cannot update the clusterTemplateRevision until Clusters are referring it] from [https://rancherm-lab-clj.platform.orange.intra/v3/clusterTemplateRevisions/cattle-global-data:ctr-w27sv]`

### Expected Result
I expected the addition to work. I managed to create a new revision using the GUI, but our entire configuration is kept as code (gitops), as such we cannot drift from this and create anything manually.

### Additional context
Code:

`module "rke_templates" {
  source = "../../modules/rancher/global/tools/rke_templates/0.0.4"

  template_name = var.rke_template.template_name

  template_revisions = [for template_revision in var.rke_template.template_revisions : {
    revision_name = template_revision.revision_name
    default_k8s_version = template_revision.default_k8s_version
    is_default = template_revision.is_default
    sans = template_revision.sans

    private_registries = [for private_registry in template_revision.private_registries : {
      url: private_registry.url
      is_default: private_registry.is_default
      user: data.vault_generic_secret.registries_credentials.data[private_registry.credentials.username_key]
      password: data.vault_generic_secret.registries_credentials.data[private_registry.credentials.password_key]
    }]

    kubelet_extra_args = {
      image-gc-high-threshold = try(template_revision.kubelet_extra_args.image-gc-high-threshold, null)
      image-gc-low-threshold = try(template_revision.kubelet_extra_args.image-gc-low-threshold, null)
    }

    #use default values
    etcd_backup_config = null
    upgrade_strategy = null
  }]

  providers = {
    rancher2 = rancher2.clj
  }
}
`
module code:

`locals {
  defaults = {
    etcd_backup_config = {
      enabled = true
      interval_hours = "6"
      retention = "30"
    }

    upgrade_strategy = {
      drain = false
      max_unavailable_controlplane = "1"
      max_unavailable_worker = "1"
    }
  }
}

resource "rancher2_cluster_template" "cluster_template" {
  name = var.template_name

  description = "Standard RKE template for cluster creation"

  dynamic "template_revisions" {
    for_each = var.template_revisions

    content {
      name = template_revisions.value.revision_name

      cluster_config {
        rke_config {
          ssh_key_path = "~/.ssh/id_rsa"

          network {
            plugin = "canal"
          }

          dynamic "private_registries" {
            for_each = template_revisions.value.private_registries

            content {
              is_default = private_registries.value.is_default
              url = private_registries.value.url
              user = private_registries.value.user
              password = private_registries.value.password
            }
          }

          services {
            kube_api {
              service_cluster_ip_range = "10.43.0.0/16"
            }

            kube_controller {
              cluster_cidr = "10.42.0.0/16"
              service_cluster_ip_range = "10.43.0.0/16"
            }

            kubelet {
              cluster_dns_server = "10.43.0.10"
              extra_args = template_revisions.value.kubelet_extra_args != null ? {
                image-gc-high-threshold: "${template_revisions.value.kubelet_extra_args.image-gc-high-threshold}"
                image-gc-low-threshold: "${template_revisions.value.kubelet_extra_args.image-gc-low-threshold}"
              } : null
            }

            etcd {
              backup_config {
                enabled = coalesce(template_revisions.value.etcd_backup_config, local.defaults.etcd_backup_config).enabled
                interval_hours = coalesce(template_revisions.value.etcd_backup_config, local.defaults.etcd_backup_config).interval_hours
                retention = coalesce(template_revisions.value.etcd_backup_config, local.defaults.etcd_backup_config).retention
              }
            }
          }

          authentication {
            strategy = "x509"
            sans = template_revisions.value.sans
          }

          upgrade_strategy {
            drain = coalesce(template_revisions.value.upgrade_strategy, local.defaults.upgrade_strategy).drain
            max_unavailable_controlplane = coalesce(template_revisions.value.upgrade_strategy, local.defaults.upgrade_strategy).max_unavailable_controlplane
            max_unavailable_worker = coalesce(template_revisions.value.upgrade_strategy, local.defaults.upgrade_strategy).max_unavailable_worker
          }
        }

        cluster_auth_endpoint {
          enabled = true
        }
      }

      questions {
        default = template_revisions.value.default_k8s_version
        required = false
        type = "string"
        variable = "rancherKubernetesEngineConfig.kubernetesVersion"
      }

      questions {
        default = ""
        required = true
        type = "string"
        variable = "localClusterAuthEndpoint.fqdn"
      }

      questions {
        default = ""
        required = false
        type = "string"
        variable = "localClusterAuthEndpoint.caCerts"
      }

      default = template_revisions.value.is_default
    }
  }
}
`
Should you require further information please let me know.

Thanks,
Raoul

------
SURE-6145

**Comment by snasovich** [comment]
Moving to blocked while we're awaiting for some more information from the linked ticket.

**Comment by snasovich** [comment]
Still Blocked as awaiting more information after some back-and-forth

**Comment by Sahota1225** [comment]
Closing this issue as jira was closed because the customer did not provide any information that was requested
