### ISSUE TITLE
Deleting a rancher2_cluster_driver for a built-in driver should just disable it, not delete it

### ISSUE THREAD

**Issue by nlowe** [rancher/terraform-provider-rancher2#109]
If I want to ensure the `AWS EKS` driver is enabled, I added this resource to my terraform manifest:

```hcl
resource "rancher2_cluster_driver" "eks" {
  active  = true
  builtin = true
  name    = "amazonElasticContainerService"
  url     = ""
}
```

However, upon `terraform destroy`'ing my manifest, the cluster driver was deleted!

![image](https://user-images.githubusercontent.com/794251/63799372-fc6d7100-c8d9-11e9-9fcc-8b2012daee20.png)

I can't `terraform create` it again either:

```txt
Error: Error applying plan:

1 error(s) occurred:

* rancher2_cluster_driver.eks: 1 error(s) occurred:

* rancher2_cluster_driver.eks: Bad response statusCode [422]. Status [422 Unprocessable Entity]. Body: [baseType=error, code=MissingRequired, fieldName=url, message=] from [https:/rancher.mydomain.net/v3/kontainerdrivers]
```

How do I restore the built-in driver? It looks like I need a URL to the driver binary but that's not set on a working copy of rancher that I have elsewhere.

(To be completely fair, the API probably shouldn't let you delete built-in drivers if you can't re-add them).

**Comment by rawmind0** [comment]
@nlowe, you are right. I've submitted a PR to address it, just non built-in drivers will be deleted on tf destroy. 

BTW, on rancher v2.3, API will not let you delete built-in drivers.

In order to restore the built in driver, just restart rancher server instances. It going to download and activate all built-in cluster drivers again.

**Comment by rawmind0** [comment]
Merged PR to address this issue. Please, reopen it if needed.
