### ISSUE TITLE
[BUG] Can not delete `rancher2_cluster_role_template_binding` resources

### ISSUE THREAD

**Issue by spkane** [rancher/terraform-provider-rancher2#1093]
### Rancher Server Setup
- Rancher version: v2.6.9
- Installation option (Docker install/Helm Chart): Helm

### Information about the Cluster
- Kubernetes version: v1.24.6
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Imported AKS

### User Information
- What is the role of the user logged in? Cluster Owner
  - If custom, define the set of permissions:

### Provider Information
- What is the version of the Rancher v2 Terraform Provider in use? v1.25.0
- What is the version of Terraform in use? 0.14.11

### Describe the bug

- Unable to destroy `rancher2_cluster_role_template_binding`

### To Reproduce

- Import a cluster via the rancher2 provider and add one or two `rancher2_cluster_role_template_binding` resources.
- Try to run `terraform destroy`
  - **Note**: It is possible that this was actually occurring when the Rancher API endpoint was not reachable. However, even so, this is not the behavior that I would expect from the provider.
- Watch it eventually time out trying to remove these.

### Actual Result

- This is the end of the run (via Github actions) that was trying to destroy the role template bindings.

```text
rancher2_cluster_role_template_binding.azad_contributor: Still destroying... [id=c-lhkqx:c-lhkqx-contributor, 18m30s elapsed]
rancher2_cluster_role_template_binding.azad_owner: Still destroying... [id=c-lhkqx:c-lhkqx-owner, 18m30s elapsed]
rancher2_cluster_role_template_binding.azad_owner: Still destroying... [id=c-lhkqx:c-lhkqx-owner, 18m40s elapsed]
rancher2_cluster_role_template_binding.azad_contributor: Still destroying... [id=c-lhkqx:c-lhkqx-contributor, 18m40s elapsed]
rancher2_cluster_role_template_binding.azad_owner: Still destroying... [id=c-lhkqx:c-lhkqx-owner, 18m50s elapsed]
rancher2_cluster_role_template_binding.azad_contributor: Still destroying... [id=c-lhkqx:c-lhkqx-contributor, 18m50s elapsed]
rancher2_cluster_role_template_binding.azad_contributor: Still destroying... [id=c-lhkqx:c-lhkqx-contributor, 19m0s elapsed]
rancher2_cluster_role_template_binding.azad_owner: Still destroying... [id=c-lhkqx:c-lhkqx-owner, 19m0s elapsed]
rancher2_cluster_role_template_binding.azad_owner: Still destroying... [id=c-lhkqx:c-lhkqx-owner, 19m10s elapsed]
rancher2_cluster_role_template_binding.azad_contributor: Still destroying... [id=c-lhkqx:c-lhkqx-contributor, 19m10s elapsed]
rancher2_cluster_role_template_binding.azad_contributor: Still destroying... [id=c-lhkqx:c-lhkqx-contributor, 19m20s elapsed]
rancher2_cluster_role_template_binding.azad_owner: Still destroying... [id=c-lhkqx:c-lhkqx-owner, 19m20s elapsed]
rancher2_cluster_role_template_binding.azad_contributor: Still destroying... [id=c-lhkqx:c-lhkqx-contributor, 19m30s elapsed]
rancher2_cluster_role_template_binding.azad_owner: Still destroying... [id=c-lhkqx:c-lhkqx-owner, 19m30s elapsed]
rancher2_cluster_role_template_binding.azad_contributor: Still destroying... [id=c-lhkqx:c-lhkqx-contributor, 19m40s elapsed]
rancher2_cluster_role_template_binding.azad_owner: Still destroying... [id=c-lhkqx:c-lhkqx-owner, 19m40s elapsed]
rancher2_cluster_role_template_binding.azad_owner: Still destroying... [id=c-lhkqx:c-lhkqx-owner, 19m50s elapsed]
rancher2_cluster_role_template_binding.azad_contributor: Still destroying... [id=c-lhkqx:c-lhkqx-contributor, 19m50s elapsed]
rancher2_cluster_role_template_binding.azad_owner: Still destroying... [id=c-lhkqx:c-lhkqx-owner, 20m0s elapsed]
rancher2_cluster_role_template_binding.azad_contributor: Still destroying... [id=c-lhkqx:c-lhkqx-contributor, 20m0s elapsed]

Error: [ERROR] waiting for cluster role template binding (c-lhkqx:c-lhkqx-contributor) to be removed: timeout while waiting for state to become 'removed' (last state: 'active', timeout: 20m0s)

Error: [ERROR] waiting for cluster role template binding (c-lhkqx:c-lhkqx-owner) to be removed: timeout while waiting for state to become 'removed' (last state: 'active', timeout: 20m0s)
```

- It also appears that the Rancher cluster is left in a strange state. These role template bindings still show up in the UI and it does not seem possible to remove them there (at least after this has taken place))

### Expected Result

- The role template bindings are deleted quickly so that `terraform` can delete the cluster from Rancher and move on

OR

- The provider errors within about 60 seconds stating that it can not reach the Rancher endpoint.

### Screenshots
N/A

**Comment by spkane** [comment]
cc / @jmarhee (Added some small updates here)

**Comment by spkane** [comment]
cc/ @keeganmccallum @srujansagi

**Comment by spkane** [comment]
We have now been able to reproduce this numerous times. The Rancher API is definitely reachable during all of these runs, so there appears to be some issue related to actually removing these `rancher2_cluster_role_template_binding`s properly. Something that should take a minute at most never completes successfully.

```
module.rancher_fleet_registration[0].rancher2_cluster_role_template_binding.azad_contributor: Still destroying... [id=c-ndmkr:c-ndmkr-contributor, 3m30s elapsed]
module.rancher_fleet_registration[0].rancher2_cluster_role_template_binding.azad_owner: Still destroying... [id=c-ndmkr:c-ndmkr-owner, 3m30s elapsed]
module.rancher_fleet_registration[0].rancher2_cluster_role_template_binding.azad_contributor: Still destroying... [id=c-ndmkr:c-ndmkr-contributor, 3m40s elapsed]
```

**Comment by spkane** [comment]
Would this occur is the cluster agent was no longer connected? Terraform is busy tearing down the system and the cluster agent deployment has already been removed.

If this is the issue, is there a way to force the removal via terraform, since the whole point is to destroy the cluster at this point.

**Comment by JonCrowther** [comment]
Hi @spkane, I'm trying to reproduce this bug but am having trouble doing so. From your description this is what I tried:

1. Create an azure cluster via terraform
2. Create a test user to apply the role template bindings to
3. Using terraform, create two rancher2_cluster_role_template_binding
4. Use terraform to delete those role template bindings

This successfully deleted the role template bindings. I think I need more details on how to reproduce it. For starters could I see what the terraform files look like? Or at the very least what the rancher2_cluster_role_template_binding resources look like?

Additionally I could use some more detail on the "import" portion. I created an azure cluster via terraform and the "azurerm" provider and installed rancher on it. Did you create a separate azure cluster and then import it via the "rancher2_cluster" resource? More detail here would be valuable.

**Comment by spkane** [comment]
@JonCrowther So, we have a central Rancher cluster, and then we are using Terraform to spin up a new AKS cluster, register it with the existing Rancher cluster, create a few `rancher2_cluster_role_template_binding`s and then install the Rancher components into the new Kubernetes cluster.

```hcl
...

resource "azurerm_kubernetes_cluster" "runway_ok8" {
  name                = "${var.devexp_cluster_name}-${var.devexp_cluster_num}-${var.location}"
  location            = var.location
  ...
}

resource "rancher2_cluster" "runway_cluster_import_rancher" {
  name = var.cluster_name
  description = "Runway imported cluster"
  ...
}

data "rancher2_principal" "azad_owner" {
  name = var.azad_mgmt_group_owner[var.app_sdlc_environment]
  type = "group"
}

resource "rancher2_cluster_role_template_binding" "azad_owner" {
  name = "${rancher2_cluster.runway_cluster_import_rancher.id}-owner"
  cluster_id = rancher2_cluster.runway_cluster_import_rancher.id
  role_template_id = "cluster-owner"
  group_principal_id = data.rancher2_principal.azad_owner.id
}

resource "kubernetes_deployment" "cattle_cluster_agent" {
  lifecycle {
    ignore_changes = all
  }
  metadata {
    name      = "cattle-cluster-agent"
    namespace = "cattle-system"
    annotations = {
      "management.cattle.io/scale-available" = "2"
    }
   ...
}

...
```

This works fine, but our experience has been that tearing this down is tricky at best. We ran into this problem, in addition to an issue with the finalizer on the `cattle-system` namespace.

As a workaround, the workflow that tears down the cluster, now removes the finalizer from the `cattle-system` namespace and also directly de-registers the cluster from the Rancher API, so that the `terraform destroy` works without timing out.

If you think there is more of the HCL that will be helpful, let me know. I'd need to skip our workaround logic to try and reproduce it again on this side, but it you continue to have trouble reproducing it, I can give it a try again from our side.

**Comment by JonCrowther** [comment]
@spkane Thanks for the update. I was able to create and import an aks cluster and add two CRTBs. I was then able to successfully delete everything with `terraform destroy`. I think the only possible difference would be how we import the cluster. I use the following:
```
resource "rancher2_cluster" "secondary" {
  name = azurerm_kubernetes_cluster.secondary_cluster.name
  description = "Terraform AKS cluster"
  aks_config_v2 {
    cloud_credential_id = rancher2_cloud_credential.foo-aks.id
    resource_group = data.azurerm_resource_group.primary.name
    resource_location = data.azurerm_resource_group.primary.location
    imported = true
  }
}
```
I noticed that you didn't show that you used `aks_config_v2` to import it (as documented [here](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster#importing-aks-cluster-from-rancher-v2-using-aks_config_v2-for-rancher-v260-or-above)) and I'm wondering if you omitted it in the comment or if you don't use it at all? It also meant I didn't have to create a `kubernetes_deployment` resource to get my cluster registered in rancher.

**Comment by idogada-akamai** [comment]
What's the status on this?
How was this resolved?

**Comment by JonCrowther** [comment]
Hi @idogada-akamai, we closed this issue because I was not able to reproduce the bug and we stopped receiving responses. If you're experiencing a similar bug, please open a new issue for it with the terraform, rancher version and reproduction steps that are causing the bug. You can tag me in the issue too and I'll look into it.

**Comment by voliveira-tmx** [comment]
I'm having the same problem as well.
