### ISSUE TITLE
[Backport release/v2] Setup automation for QA to Test Terraform with RCs

### ISSUE THREAD

**Issue by a-blender** [rancher/terraform-provider-rancher2#1101]
### Is your feature request related to a problem? Please describe.

Backport of https://github.com/rancher/terraform-provider-rancher2/issues/1083

**Comment by a-blender** [comment]
# Test plan

# Problem

  
Terraform has originally been tested with the released versions published on the registry. This is not ideal since QA should be validating that Terraform fixes and features work before the provider is released, but it never bottlenecked work before so it went unnoticed.

# Solution

  
New QA process to test TF issues using RCs instead of testing them after release. Added scripts for Mac, linux, and windows for QA engineers on different platforms to setup RCs locally just by running the script.

# Testing

 
## Engineering Testing

### Manual Testing

 
### Automated Testing


Verify script works with QA engineers on Mac / linux / windows.

Test steps
* Clone rancher/terraform-provider-rancher2 repo, checkout `release/v2`
* Run `./setup-provider.sh <provider> <version>` on Mac / linux OR
* Run `./setup-provider-windows.ps1 <provider> <version>` from powershell on a win32 OS

Update main.tf

```
terraform {
  required_providers {
    rancher2 = {
      source = "terraform.local/local/rancher2"
      version = "2.0.0-rc4"
    }
  }
}
```

Run `terraform init` and verify RC is installed successfully
Run `terraform apply` and make sure that you can successfully provision infra with the local RC. Optional: run whatever tests are on your plate.
 
## QA Testing Considerations

  
### Regressions Considerations

**Comment by Josh-Diamond** [comment]
Tested and validated using arm64 (mac m1 chip) - ✅ ( i have used this multiple times to validate multiple tickets, signing-off on arm64 support)

**Comment by jameson-mcghee** [comment]
I validated that I was able to execute this script using WSL, and so I am signing of on Windows support.
