### ISSUE TITLE
[BUG] GKE fails to provision supported k8s versions w/ rancher2 provider

### ISSUE THREAD

**Issue by Josh-Diamond** [rancher/terraform-provider-rancher2#1106]
### Rancher Server Setup
- Rancher version: `v2.6.12-rc1`
- Installation option (Docker install/Helm Chart): HA Helm env, RKE1 local, using RKE `v1.3.19`
- Proxy/Cert Details: `byo-valid`

### Information about the Cluster
- Kubernetes version: `v1.24.12-gke.500`
- Cluster Type (Local/Downstream):
Downstream, tf-rancher2-provider provisioned GKE cluster

### User Information
- What is the role of the user logged in? `Admin`

### Provider Information
- What is the version of the Rancher v2 Terraform Provider in use? `v2.0.0`
- What is the version of Terraform in use? `0.13.7`

### Describe the bug
Googleapi error is encountered when attempting to provision ANY supported GKE version w/ rancher2 provider - [`see screenshot below`]

### To Reproduce
1. Fresh install of Rancher `v2.6.12-rc1`
2. Using tf-rancher2-provider `v2.0.0`, provision a downstream GKE cluster w/ any supported k8s version
3. Reproduced

### Actual Result
Googleapi: Error 400: Master version "1.24.12-gke.500" is unsupported., badRequest

### Expected Result
Cluster expected to successfully provision, as it does via Rancher UI.

### Screenshots
![image (21) (1)](https://user-images.githubusercontent.com/46494969/232930640-9b6b198b-aa58-477b-a7f2-6ad4ae6a6608.png)

### Additional context
Cluster successfully provisions via Rancher UI, but error is encountered w/ rancher2 provider

Here is the `main.tf` used, (and please reach out internally, for any env specific configurations or a reproduced env):

```terraform
terraform {
  required_providers {
    rancher2 = {
      source  = "rancher/rancher2"
      version = "2.0.0"
    }
  }
}

provider "rancher2" {
  api_url   = "<REDACTED>"
  token_key = "<REDACTED>"
  insecure  = true
}

resource "rancher2_cloud_credential" "rancher2_cloud_credential" {
  name = "tf-creds-gke"
  google_credential_config {
    auth_encoded_json = jsonencode(<REDACTED>)
  }
}

resource "rancher2_cluster" "rancher2_cluster" {
  name = "jkeslar-gke-cluster"
  gke_config_v2 {
    name                     = "jkeslar-gke-cluster"
    google_credential_secret = rancher2_cloud_credential.rancher2_cloud_credential.id
    region                   = "<REDACTED>"
    project_id               = "<REDACTED>"
    kubernetes_version       = "1.24.12-gke.500"
    network                  = "default"
    subnetwork               = "default"
    node_pools {
      initial_node_count  = 2
      max_pods_constraint = 110
      name                = "jkeslar-pool1"
      version             = "1.24.12-gke.500"
    }
  }
}
```

**Comment by snasovich** [comment]
@pgonin @kkaempf , since this is for GKE I think this is for your team. Also since it's for 2.6.x moving it to 2.7.x.

**Comment by kkaempf** [comment]
Is this a terraform-provider or a gke-operator problem ?

**Comment by snasovich** [comment]
@kkaempf , I'm not sure without looking deeper into it. Please note that TF provider is a shared ownership component and whichever team owns a specific functionality is responsible for handling TF features/issues related to that functionality.

**Comment by cpinjani** [comment]
Provisioning is working with below are details:

Rancher: `v2.7.5-rc4`
Terraform: `v1.4.5`
Rancher2 Provider: `2.0.0`

main.tf:
```
terraform {
  required_providers {
    rancher2 = {
      source  = "rancher/rancher2"
      version = "2.0.0"
    }
  }
}
               
provider "rancher2" {
  api_url    = "<REDACTED>"
  access_key = "<REDACTED>"
  secret_key = "<REDACTED>"
  insecure = true
}
               
resource "rancher2_cloud_credential" "rancher2_cloud_credential" {
  name = "GCP"
  google_credential_config {
    auth_encoded_json = file(<REDACTED>.json)
  }
}
               
resource "rancher2_cluster" "rancher2_cluster" {
  name = "cpinjani-tf-hosted"
  gke_config_v2 {
    name = "cpinjani-tf-hosted"
    google_credential_secret = rancher2_cloud_credential.rancher2_cloud_credential.id
    region = "<REDACTED>"
    project_id = "<REDACTED>"
    kubernetes_version = "1.24.12-gke.500"
    network = "default"
    subnetwork = "default"
    node_pools {
      name = "node-pool1"
      max_pods_constraint = 110
      initial_node_count = 2
      version = "1.24.12-gke.500"
    }
  }
}
```
![image](https://github.com/rancher/terraform-provider-rancher2/assets/73099870/289e62df-426a-4244-be94-1f3d992b4372)

@Josh-Diamond As discussed closing this, feel free to reopen if issue resurfaces.
