### ISSUE TITLE
rancher2_etcd_backup resource not working as expected.

### ISSUE THREAD

**Issue by jamiebuxxx** [rancher/terraform-provider-rancher2#111]
Hello,

We using the Terraform rancher2 provider(v1.4.1) `rancher2_etcd_backup` resource to create the backup plan for the cluster. The Terraform run appears to be working as expected:

``` 
rancher2_etcd_backup.k8s_cluster: Creating... 
annotations.%: "" => "<computed>" 
backup_config.#: "" => "1" 
backup_config.0.enabled: "" => "true" 
backup_config.0.interval_hours: "" => "1" 
backup_config.0.retention: "" => "12" 
backup_config.0.s3_backup_config.#: "" => "1" 
backup_config.0.s3_backup_config.0.access_key: "<sensitive>" => "<sensitive>" 
backup_config.0.s3_backup_config.0.bucket_name: "" => "sandbox-etcd" 
backup_config.0.s3_backup_config.0.endpoint: "" => "s3.us-west-2.amazonaws.com" 
backup_config.0.s3_backup_config.0.region: "" => "us-west-2" 
backup_config.0.s3_backup_config.0.secret_key: "<sensitive>" => "<sensitive>" 
cluster_id: "" => "c-s68hp" 
labels.%: "" => "<computed>" 
manual: "" => "false" 
name: "" => "sandbox-usw2-etcd-backup" 
namespace_id: "" => "<computed>" 
``` 
However, when we look at the setting from the Rancher2 UI, these settings are not reflected.

<img width="1246" alt="Screen Shot 2019-08-27 at 12 58 14 PM" src="https://user-images.githubusercontent.com/1173214/63812672-f11d4400-c8df-11e9-9d70-22f84ec9c07e.png">

And if we run the `terraform apply` command again, it goes back and forth with switching the interval time and retention.

``` 
rancher2_etcd_backup.k8s_cluster: Modifying... (ID: c-s68hp:sandbox-etcd-backup) 
backup_config.0.interval_hours: "12" => "1" 
backup_config.0.retention: "6" => "12" 
```
It also appears that the initial backup(even though its local) it getting stuck on the first run. I assume this is because we have built a new cluster?

**Comment by rawmind0** [comment]
Hi @jamiebuxxx, the main etcd backup config for the cluster (what is shown in the cluster UI), should be set on the cluster config, https://www.terraform.io/docs/providers/rancher2/r/cluster.html#backup_config-1

```
resource "rancher2_cluster" "foo" {
  name = "foo"
  rke_config {
    network {
      plugin = "canal"
    }
    services {
      etcd {
        creation = "6h"
        retention = "24h"
        backup_config {
          enabled = true
          interval_hours = 20
          retention = 10
          s3_backup_config {
            access_key = "access_key"
            bucket_name = "bucket_name"
            endpoint = "endpoint"
            folder = "/folder"
            region = "region"
            secret_key = "secret_key"
          }
        }
      }
    }
  }
}
```

`rancher2_etcd_backup` resources are indeed to define extra etcd backups for clusters.

**Comment by jamiebuxxx** [comment]
Ah, that's good to know. It's interesting that you can define multiple etcd backups. I was misled by that resource.

I was able to get this work! Howerer, the only thing I'm not available in the above example is the `folder` argument. 

Also, because the `access_key` and `secret_key` are required arguments, there isn't a way to use IAM instance roles with the module currently. I know this was fixed in recently here: https://github.com/rancher/rancher/issues/21623. Will this features be added in coming releases?

**Comment by rawmind0** [comment]
`folder` argument is available from rancher v2.2.7 and above.

`access_key` and `secret_key` arguments were already updated as optional in PR #103.

**Comment by rawmind0** [comment]
Please, reopen issue if needed.

**Comment by jamiebuxxx** [comment]
@rawmind0 I updated the provider plugins to the latest versions.

```
Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "template" (2.1.2)...
- Downloading plugin for provider "vault" (2.2.0)...
- Downloading plugin for provider "aws" (2.26.0)...
- Downloading plugin for provider "rancher2" (1.4.1)...

...

* provider.aws: version = "~> 2.26"
* provider.rancher2: version = "~> 1.4"
* provider.template: version = "~> 2.1"
* provider.vault: version = "~> 2.2"

```
But I'm still getting errors regarding the required/invalid arguments.

```
Error: rancher2_cluster.k8s_rancher_cluster: "rke_config.0.services.0.etcd.0.backup_config.0.s3_backup_config.0.access_key": required field is not set

Error: rancher2_cluster.k8s_rancher_cluster: "rke_config.0.services.0.etcd.0.backup_config.0.s3_backup_config.0.secret_key": required field is not set

Error: rancher2_cluster.k8s_rancher_cluster: rke_config.0.services.0.etcd.0.backup_config.0.s3_backup_config.0: invalid or unknown key: folder
```
Can you confirm which version of the plugin you are using?

**Comment by jamiebuxxx** [comment]
Looks like latest version of master has been built/shipped to Terraform yet. I will try to build a version of the plugin next week to try it out.

**Comment by rawmind0** [comment]
Yeah, new provider version should be released this week.

**Comment by jamiebuxxx** [comment]
Sounds good! Is there a release schedule for plugin releases?
