### ISSUE TITLE
[BUG] rancher2 provider does NOT currently support configuring taints, labels, and maxSurge node pool values for AKS clusters

### ISSUE THREAD

**Issue by Josh-Diamond** [rancher/terraform-provider-rancher2#1115]
With the recent [AKS enhancements](https://github.com/rancher/dashboard/issues/8073), to allow users to configure taints, labels and maxSurge values for node pools, there seems to be missing functionality in rancher2, with regards to these enhancements, which are expected to be supported, as the feature has come `to-test`.  This ticket was created to track the integration of these enhancements into rancher2 provider.

---

### Rancher Server Setup
- Rancher version: `v2.7-8e049e524d5d03fab49b17bf92c767ca5797b49d-head`
- Installation option (Docker install/Helm Chart): `HA Helm`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): local `RKE` cluster running k8s `v1.25.9`
- Proxy/Cert Details: `byo-valid`

### Information about the Cluster
- Kubernetes version: `v1.25.6`
- Cluster Type (Local/Downstream): Downstream rancher2 provisioned AKS cluster

### User Information
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
`admin`

### Provider Information
- What is the version of the Rancher v2 Terraform Provider in use? `v3.0.0`
- What is the version of Terraform in use? `v1.3.7`

### Describe the bug
When attempting to configure taints, labels and maxSurge values for node pools in a downstream rancher2 provisioned AKS cluster, `terraform apply` results in `not expected to be here`, for these fields.

### To Reproduce
1. Fresh install of rancher v2.7-head
2. Using rancher2 provider `v3.0.0` and terraform `v1.3.7`, attempt to provision a downstream AKS cluster with taints, labels and maxSurge values configured for node pools
3. Reproduced

### Actual Result
For all the mentioned fields - [`taints`, `labels`, `max_surge`] - rancher2 provider responds with `Error: Unsupported argument`

An argument named "`taints || labels || max_surge`" is not expected here.

### Expected Result
Rancher2 provider should successfully create these resouces, as outlined in the `main.tf` file

### Screenshots
<img width="764" alt="Screenshot 2023-05-04 at 11 55 02 AM" src="https://user-images.githubusercontent.com/46494969/236301666-f311c7cd-167b-4e47-9587-9800193e6346.png">

**Comment by mjura** [comment]
I will look on this

**Comment by mjura** [comment]
Fix for terraform https://github.com/rancher/terraform-provider-rancher2/pull/1122

**Comment by Josh-Diamond** [comment]
Requesting QA Template
---

@mjura was there an RC cut for rancher2 provider to test out these changes?  Looking for clarification to proceed w/ validations.

RC for rancher2 provider workflow highlighted [here](https://github.com/rancher/terraform-provider-rancher2/issues/1083#issuecomment-1499365724)

**Comment by a-blender** [comment]
@mjura This appears to have not been smoke tested.

Admittedly, there's not a lot of documentation about the new Terraform RC testing process for QA so this may be understandable :)

Please do the following here and for future issues,

1. Test the new Terraform AKS cluster fields with a local setup.
3. Add a QA test template with your test steps to the GH issue so QA knows how to test it.

QA test template

```
# QA Test Template

Issue: <!-- link the issue or issues this PR resolves here -->
<!-- If your PR depends on changes from another pr link them here and describe why they are needed on your solution section. -->
  
# Problem
<!-- Describe the root cause of the issue you are resolving. This may include what behavior is observed and why it is not desirable. If this is a new feature describe why we need this feature and how it will be used. -->
  
# Solution
<!-- Describe what you changed to fix the issue. Relate your changes back to the original issue / feature and explain why this addresses the issue. -->
  
# Testing
<!-- Note: Confirm if the repro steps in the GitHub issue are valid, if not, please update the issue with accurate repro steps. -->
 
## Engineering Testing

### Manual Testing
<!-- Describe what manual testing you did (if no testing was done, explain why). -->
 
### Automated Testing
<!--If you added/updated unit/integration/validation tests, describe what cases they cover and do not cover. -->
 
## QA Testing Considerations
<!-- Highlight areas or (additional) cases that QA should test -->
  
### Regressions Considerations
<!-- Dedicated section to specifically call out any areas that with higher chance of regressions caused by this change, include estimation of probability of regressions -->
```

3. Cut or request a Terraform RC for QA. In this case, your fix was merged [after v3.0.0](https://github.com/rancher/terraform-provider-rancher2/compare/v3.0.0...master) so you need to cut `rancher/terraform-rancher2-provider:master v3.1.0-rc1`. Terraform RCs enable QA to test features and bug fixes before the next Terraform version is released. This process also has parity with how Rancher is tested and released which Terraform mirrors in most other ways as well.
4. Move To Test
5. QA uses the test plan and the Terraform RC to test the Terraform AKS cluster fields using [this script](https://github.com/rancher/terraform-provider-rancher2/blob/master/setup-provider.sh). How to instructions are included in the script.
6. If validation passes, issue is closed. If not, it is reopened.

**Comment by mjura** [comment]
## Testing template

#### Root cause

The TFP rancher2 didn't support taints, labels and maxSurge node pool values .
 
#### What was fixed, or what changes have occurred

Fix was refactoring of aks-operator and fixes applied in https://github.com/rancher/terraform-provider-rancher2/pull/1122

#### Areas or cases that should be tested

Test node pool with mode system by running a terraform plan.

Steps
* Write a main config file for an aks cluster, specify a node pool with taints, labels, and maxSurge node pool values for AKS clusters.

* Run `terraform init`
* Run `terraform apply` and node pools with taints, labels, and maxSurge node pool values.

<details>

<summary>main.tf</summary>

```
# Terraform resources 

# Random ID
resource "random_id" "instance_id" {
 byte_length = 3
}

# Rancher cloud credentials
resource "rancher2_cloud_credential" "credential_az" {
  name = "Azure Credentials"
  azure_credential_config {
    client_id = var.az-client-id
    client_secret = var.az-client-secret
    subscription_id = var.az-subscription-id
  }
}

# Rancher cluster
resource "rancher2_cluster" "cluster_az" {
  name         = "aks-${random_id.instance_id.hex}"
  description  = "Terraform"

  aks_config_v2 {
    cloud_credential_id = rancher2_cloud_credential.credential_az.id
    name = var.az-aks-cluster
    resource_group = var.az-resource-group
    resource_location = var.az-region
    dns_prefix = "mjura-dns"
    kubernetes_version = "1.25.6"
    network_plugin = "kubenet"
    node_pools {
      availability_zones = ["1", "2", "3"]
      name = "azng1"
      mode = "System"
      count = 1
      orchestrator_version = "1.25.6"
      os_disk_size_gb = 128
      vm_size = "Standard_DS2_v2"
      labels = {
        "test1" = "data1"
        "test2" = "data2"
      }
      taints = [ "none:PreferNoSchedule" ]
    }
    node_pools {
      availability_zones = ["1", "2", "3"]
      name = "azng2"
      count = 1
      mode = "User"
      orchestrator_version = "1.25.6"
      os_disk_size_gb = 128
      vm_size = "Standard_DS2_v2"
      max_surge = "25%"
      labels = {
        "test1" = "data1"
        "test2" = "data2"
      }
      taints = [ "none:PreferNoSchedule" ]
    }
  }
}

# Delay hack part 1
resource "null_resource" "before" {
  depends_on = [rancher2_cluster.cluster_az]
}

# Delay hack part 2
resource "null_resource" "delay" {
  provisioner "local-exec" {
    command = "sleep ${var.delaysec}"
  }

  triggers = {
    "before" = "null_resource.before.id"
  }
}

# Kubeconfig file
resource "local_file" "kubeconfig" {
  filename = "${path.module}/.kube/config"
  content = rancher2_cluster.cluster_az.kube_config
  file_permission = "0600"

  depends_on = [null_resource.delay]
}

```

</details>
 
#### What areas could experience regressions ?

None
 
#### Are the repro steps accurate/minimal ?

Yes.

**Comment by Josh-Diamond** [comment]
Ticket #1115 - Test Results - ✅ 
---

Verified with TFP `v3.1.0-rc1` on Rancher `v2.7-f0d4078f4fa75b303ce276c3f4b12fc465b1ba2a-head`:
1. Fresh install of Rancher `v2.7-head`
2. Using TFP `v3.1.0-rc1` (locally), provision a downstream AKS cluster w/ taints, labels, and maxSurge values configured for node pools, using the `main.tf` provided below:
```terraform
terraform {
  required_providers {
    rancher2 = {
      source  = "terraform.local/local/rancher2"
      version = "3.1.0-rc1"
    }
  }
}

provider "rancher2" {
  api_url   = "https://<REDACTED>"
  token_key = "<REDACTED>"
  insecure  = true
}

resource "rancher2_cloud_credential" "rancher2_cloud_credential" {
  name = "tf-aks"
  azure_credential_config {
    client_id       = "<REDACTED>"
    client_secret   = "<REDACTED>"
    subscription_id = "<REDACTED>"
  }
}

resource "rancher2_cluster" "rancher2_cluster" {
  name = "jkeslar-terraform-aks-cluster"
  aks_config_v2 {
    cloud_credential_id = rancher2_cloud_credential.rancher2_cloud_credential.id
    resource_group      = "<REDACTED>"
    resource_location   = "<REDACTED>"
    dns_prefix          = "<REDACTED>"
    kubernetes_version  = "1.26.3"
    network_plugin      = "kubenet"
    node_pools {
      availability_zones   = ["1", "2", "3"]
      name                 = "pool1"
      count                = 1
      orchestrator_version = "1.26.3"
      os_disk_size_gb      = 128
      vm_size              = "Standard_DS2_v2"
      taints = [ "taintkey1=taintvalue1:PreferNoSchedule" ]
      labels = {
        "label1" = "value1"
        "label2" = "value2"
      }
      max_surge = "20%"
    }
    node_pools {
      availability_zones   = ["1", "2", "3"]
      name                 = "pool2"
      count                = 1
      orchestrator_version = "1.26.3"
      os_disk_size_gb      = 128
      vm_size              = "Standard_DS2_v2"
      mode                 = "System"
      taints = [ "taintkey2=taintvalue2:PreferNoSchedule", "taintkey3=taintvalue3:PreferNoSchedule" ]
      labels = {
        "label11" = "value11"
        "label22" = "value22"
      }
      max_surge = "2"
    }
    node_pools {
      availability_zones   = ["1", "2", "3"]
      name                 = "pool3"
      count                = 1
      orchestrator_version = "1.26.3"
      os_disk_size_gb      = 128
      vm_size              = "Standard_DS2_v2"
      mode                 = "User"
      taints = [ "taintkey4=taintvalue4:PreferNoSchedule" ]

      labels = {
        "label111" = "value111"
        "label222" = "value222"
      }
      max_surge = "15%"
    }
  }
}
```
3. Verified - cluster successfully provision w/ configured taints, labels and maxSurge for node pools
4. Once cluster is `active` and stable, update taints, labels and maxSurge values for node pools, using TFP `v3.1.0-rc1`
5. Verified - cluster taints, tabels, and maxSurge successfully update; as expected
6. Run `terraform destroy -auto-approve`
7. Verified - resources successfully deleted
