### ISSUE TITLE
[BUG] rancher2 provider does NOT currently support configuring system mode node pools for AKS clusters

### ISSUE THREAD

**Issue by Josh-Diamond** [rancher/terraform-provider-rancher2#1116]
With the recent [AKS enhancement](https://github.com/rancher/dashboard/issues/8105), to allow users to configure system mode node pools, there seems to be missing functionality in rancher2, with regards to this enhancement, which is expected to be supported, as the feature has come `to-test`.  This ticket was created to track the integration of this enhancement into rancher2 provider.

---

### Rancher Server Setup
- Rancher version: `v2.7-8e049e524d5d03fab49b17bf92c767ca5797b49d-head`
- Installation option (Docker install/Helm Chart): `HA Helm`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): local `RKE` cluster running k8s `v1.25.9`
- Proxy/Cert Details: `byo-valid`

### Information about the Cluster
- Kubernetes version: `v1.25.6`
- Cluster Type (Local/Downstream): Downstream rancher2 provisioned AKS cluster

### User Information
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
`admin`

### Provider Information
- What is the version of the Rancher v2 Terraform Provider in use? `v3.0.0`
- What is the version of Terraform in use? `v1.3.7`

### Describe the bug
When attempting to configure system mode node pools in a downstream rancher2 provisioned AKS cluster, `terraform apply` results in an accurate plan, however, once the infrastructure is delivered, all system mode node pools configured in the main.tf file are truly user mode node pools in Rancher.

### To Reproduce
1. Fresh install of rancher v2.7-head
2. Using rancher2 provider `v3.0.0` and terraform `v1.3.7`, attempt to provision a downstream AKS cluster with system mode node pools configured
3. Reproduced

### Actual Result
Terraform plan and the main.tf file reflect an accurate request to create system mode node pools, however, user mode node pools are actually provisioned and delivered

### Expected Result
Rancher2 provider should successfully create the requested system mode node pools

### Screenshots

`Terraform plan`
![image (25)](https://user-images.githubusercontent.com/46494969/236325825-f69253bf-50a6-4bc8-9777-69bf07c44aa8.png)

`Node pool delivered in Rancher`
![image_png](https://user-images.githubusercontent.com/46494969/236326550-27811d13-1137-4802-a339-edb6cd870dd5.png)

**Comment by kkaempf** [comment]
@a-blender this won't make it into Q2, please move to Q3

**Comment by mjura** [comment]
I have tested it with latest Rancher v2.7.5 and fixes from https://github.com/rancher/terraform-provider-rancher2/issues/1115

It seems to work fine

![rancher-mode-system](https://github.com/rancher/terraform-provider-rancher2/assets/4455471/ed2ec4ee-84c1-488b-905e-85d8f02a39d6)

**Comment by Josh-Diamond** [comment]
Requesting QA Template
---

@mjura was there an RC cut for rancher2 provider to test out these changes?  Looking for clarification to proceed w/ validations.

RC for rancher2 provider workflow highlighted [here](https://github.com/rancher/terraform-provider-rancher2/issues/1083#issuecomment-1499365724)

**Comment by a-blender** [comment]
@mjura I'm confused on why this wasn't investigated https://github.com/rancher/terraform-provider-rancher2/issues/1116#issuecomment-1550885105

* You were unable to repro and saw system mode pools being created when Josh did not?
* Did you use the exact same Rancher commit that he did?
* What tf version did you use?
* Did you test including the fixes from https://github.com/rancher/terraform-provider-rancher2/issues/1115 on your local setup and found that those fixes resolved this bug? The new process here is to determine that by locally testing using an rc.

More details would be helpful.

**Comment by mjura** [comment]
> @mjura I'm confused on why this wasn't investigated [#1116 (comment)](https://github.com/rancher/terraform-provider-rancher2/issues/1116#issuecomment-1550885105)
> 
> * You were unable to repro and saw system mode pools being created when Josh did not?

Original issue was related to aks-operator which was fixed with during latest refactoring. So there is nothing to investigate.

> * Did you use the exact same Rancher commit that he did?

I have tested everything with latest Rancher v2.7.5.

> * What tf version did you use?

Rancher v2.7.5

> * Did you test including the fixes from [[BUG] rancher2 provider does NOT currently support configuring taints, labels, and maxSurge node pool values for AKS clusters #1115](https://github.com/rancher/terraform-provider-rancher2/issues/1115) on your local setup and found that those fixes resolved this bug? The new process here is to determine that by locally testing using an rc.

Fixes from https://github.com/rancher/terraform-provider-rancher2/issues/1115 are not required.

**Comment by mjura** [comment]
## Testing template

#### Root cause

The TFP rancher2 couldn't provision node pools with mode "system".
 
#### What was fixed, or what changes have occurred

Fix was refactoring of aks-operator and fixes applied in https://github.com/rancher/terraform-provider-rancher2/pull/1122

#### Areas or cases that should be tested

Test node pool with mode system by running a terraform plan.

Steps
* Write a main config file for an aks cluster, specify a node pool mode sytem
* Run `terraform init`
* Run `terraform apply` and node pools with mode system

<details>

<summary>main.tf</summary>

```
# Terraform resources 

# Random ID
resource "random_id" "instance_id" {
 byte_length = 3
}

# Rancher cloud credentials
resource "rancher2_cloud_credential" "credential_az" {
  name = "Azure Credentials"
  azure_credential_config {
    client_id = var.az-client-id
    client_secret = var.az-client-secret
    subscription_id = var.az-subscription-id
  }
}

# Rancher cluster
resource "rancher2_cluster" "cluster_az" {
  name         = "aks-${random_id.instance_id.hex}"
  description  = "Terraform"

  aks_config_v2 {
    cloud_credential_id = rancher2_cloud_credential.credential_az.id
    name = var.az-aks-cluster
    resource_group = var.az-resource-group
    resource_location = var.az-region
    dns_prefix = "mjura-dns"
    kubernetes_version = "1.25.6"
    network_plugin = "kubenet"
    node_pools {
      availability_zones = ["1", "2", "3"]
      name = "azng1"
      mode = "System"
      count = 1
      orchestrator_version = "1.25.6"
      os_disk_size_gb = 128
      vm_size = "Standard_DS2_v2"
      labels = {
        "test1" = "data1"
        "test2" = "data2"
      }
      taints = [ "none:PreferNoSchedule" ]
    }
    node_pools {
      availability_zones = ["1", "2", "3"]
      name = "azng2"
      count = 1
      mode = "User"
      orchestrator_version = "1.25.6"
      os_disk_size_gb = 128
      vm_size = "Standard_DS2_v2"
      max_surge = "25%"
      labels = {
        "test1" = "data1"
        "test2" = "data2"
      }
      taints = [ "none:PreferNoSchedule" ]
    }
  }
}

# Delay hack part 1
resource "null_resource" "before" {
  depends_on = [rancher2_cluster.cluster_az]
}

# Delay hack part 2
resource "null_resource" "delay" {
  provisioner "local-exec" {
    command = "sleep ${var.delaysec}"
  }

  triggers = {
    "before" = "null_resource.before.id"
  }
}

# Kubeconfig file
resource "local_file" "kubeconfig" {
  filename = "${path.module}/.kube/config"
  content = rancher2_cluster.cluster_az.kube_config
  file_permission = "0600"

  depends_on = [null_resource.delay]
}

```

</details>
 
#### What areas could experience regressions ?

None
 
#### Are the repro steps accurate/minimal ?

Yes.

**Comment by Josh-Diamond** [comment]
Ticket #1116 - Test Results - ✅ 
---

Verified with TFP `v3.1.0-rc1` on Rancher `v2.7-f0d4078f4fa75b303ce276c3f4b12fc465b1ba2a-head`:
1. Fresh install of Rancher `v2.7-head`
2. Using TFP `v3.1.0-rc1` (locally), provision a downstream AKS cluster w/ at least 1 "system" mode + 1 "user" mode node pool, using the `main.tf` provided below:
```terraform
terraform {
  required_providers {
    rancher2 = {
      source  = "terraform.local/local/rancher2"
      version = "3.1.0-rc1"
    }
  }
}

provider "rancher2" {
  api_url   = "https://<REDACTED>"
  token_key = "<REDACTED>"
  insecure  = true
}

resource "rancher2_cloud_credential" "rancher2_cloud_credential" {
  name = "tf-aks"
  azure_credential_config {
    client_id       = "<REDACTED>"
    client_secret   = "<REDACTED>"
    subscription_id = "<REDACTED>"
  }
}

resource "rancher2_cluster" "rancher2_cluster" {
  name = "jkeslar-terraform-aks-cluster"
  aks_config_v2 {
    cloud_credential_id = rancher2_cloud_credential.rancher2_cloud_credential.id
    resource_group      = "<REDACTED>"
    resource_location   = "<REDACTED>"
    dns_prefix          = "<REDACTED>"
    kubernetes_version  = "1.26.3"
    network_plugin      = "kubenet"
    node_pools {
      availability_zones   = ["1", "2", "3"]
      name                 = "pool1"
      count                = 1
      orchestrator_version = "1.26.3"
      os_disk_size_gb      = 128
      vm_size              = "Standard_DS2_v2"
      taints = [ "taintkey1=taintvalue1:PreferNoSchedule" ]
      labels = {
        "label1" = "value1"
        "label2" = "value2"
      }
      max_surge = "20%"
    }
    node_pools {
      availability_zones   = ["1", "2", "3"]
      name                 = "pool2"
      count                = 1
      orchestrator_version = "1.26.3"
      os_disk_size_gb      = 128
      vm_size              = "Standard_DS2_v2"
      mode                 = "System"
      taints = [ "taintkey2=taintvalue2:PreferNoSchedule", "taintkey3=taintvalue3:PreferNoSchedule" ]
      labels = {
        "label11" = "value11"
        "label22" = "value22"
      }
      max_surge = "2"
    }
    node_pools {
      availability_zones   = ["1", "2", "3"]
      name                 = "pool3"
      count                = 1
      orchestrator_version = "1.26.3"
      os_disk_size_gb      = 128
      vm_size              = "Standard_DS2_v2"
      mode                 = "User"
      taints = [ "taintkey4=taintvalue4:PreferNoSchedule" ]

      labels = {
        "label111" = "value111"
        "label222" = "value222"
      }
      max_surge = "15%"
    }
  }
}
```
3. Verified - cluster successfully provisions w/ configured "system" and "user" mode node pools
4. Run `terraform destroy -auto-approve`
5. Verified - resources successfully deleted

**Comment by a-blender** [comment]
@Josh-Diamond Thanks for testing both those reopened issues so fast, you rock!!
