### ISSUE TITLE
Change default kubernetes_version for eks_config

### ISSUE THREAD

**Issue by ishantanu** [rancher/terraform-provider-rancher2#112]
Hi,

The default value for `kubernetes_version` is currently set to `1.10` whereas currently, AWS EKS supports `kubernetes_version` values from `1.11` onwards up to `1.13`.

Specifically, this: https://github.com/terraform-providers/terraform-provider-rancher2/blob/40199a8a59c3eb04e594f9f5f03a53687e8ca2e0/rancher2/schema_cluster_eks_config.go#L67-L71

I am more than ready to create a PR once the convention of the default value for `kubernetes_version` is agreed.

**Comment by rawmind0** [comment]
Submitted PR #114 to address the issue. Instead of updating `kubernetes_version` argument default value, it is set to `Required` with no default.
