### ISSUE TITLE
Pod Security Admission Configuration Template not available in rancher2_cluster and rancher2_cluster_v2

### ISSUE THREAD

**Issue by nickvth** [rancher/terraform-provider-rancher2#1129]
### Is your feature request related to a problem? Please describe.
we can't configure PSS/PSA in a simple way

### Describe the solution you'd like

- https://github.com/rancher/rke1-docs/issues/21
- https://rke.docs.rancher.com/config-options/services/pod-security-admission
- https://github.com/rancher/rancher/releases/tag/v2.7.3
- https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/pod-security-standards

**Comment by nickvth** [comment]
duplicate https://github.com/rancher/terraform-provider-rancher2/issues/1112

**Comment by git-ival** [comment]
Closing as this is a duplicate issue and the issue has been resolved
