### ISSUE TITLE
[ERROR] Bootsrap mode activated. Token_key or access_key and secret_key can not be provided

### ISSUE THREAD

**Issue by Ilya-Kuchaev** [rancher/terraform-provider-rancher2#113]
I have newly provisioned by Ansible Rancher server.

```
provider "rancher2" {
  alias = "bootstrap"

  api_url = "https://localhost:8443"
  bootstrap = true
  insecure = true 
}

resource "rancher2_bootstrap" "admin" {
  provider = "rancher2.bootstrap"

  password = "randompass"
  telemetry = false
}
```
I'm trying to proceed with the server bootstrap with 
`terraform apply -target=rancher2_bootstrap.admin`
But receive the following error.
```
Error: [ERROR] Bootsrap mode activated. Token_key or access_key and secret_key can not be provided

  on rancher.tf line 1, in provider "rancher2":
   1: provider "rancher2" {
```
What am I doing wrong?

**Comment by rawmind0** [comment]
Have you checked if `RANCHER_TOKEN_KEY` or `RANCHER_ACCESS_KEY` and `RANCHER_SECRET_KEY` env variables are set in your shell?? If so, you need to unset them.

**Comment by Ilya-Kuchaev** [comment]
They are. Thanks!!!
