### ISSUE TITLE
Support to set TLS Alternate Names  in cluster_rancher2_v2

### ISSUE THREAD

**Issue by nickvth** [rancher/terraform-provider-rancher2#1139]
### Is your feature request related to a problem? Please describe.
can't set tls-san through terraform for RKE2

### Describe the solution you'd like
set tls alternate names: https://ranchermanager.docs.rancher.com/v2.6/reference-guides/cluster-configuration/rancher-server-configuration/rke2-cluster-configuration#tls-alternate-names

**Comment by belfhi** [comment]
you can set it in machine_global_config:
```
    machine_global_config = <<-EOT
      cni: "cilium"
      disable-kube-proxy: true
      disable-cloud-controller: true
      etcd-expose-metrics: false
      cluster-cidr: ${var.k8s_cluster_cidr}
      service-cidr: ${var.k8s_service_cidr}
      cluster-dns: ${var.k8s_cluster_dns}
      tls-san: [${join(", ", var.k8s_tls_sans)}]
      EOT
```

**Comment by a-blender** [comment]
@nickvth Have you tried the above configuration for tls-san?

**Comment by nickvth** [comment]
Yes already implemented in our code, i will close this

**Comment by a-blender** [comment]
@nickvth Thank you! We need to add more clear documentation that you need to specify `tls_san` in Machine Global Config in the provider docs.

**Comment by Tejeev** [comment]
Can we provide or link to a clear description and example of how to fill the machine_global_config block?
I believe it's implied from the example in belfhi's comment that this uses a linux agent config?  Perhaps we can say as much in the provider doc, provide a generalized version of their example, and link to where the syntax of that config is defined (if I understand usage correctly)?

**Comment by snasovich** [comment]
Closing, same as https://github.com/rancher/terraform-provider-rancher2/issues/1238#issuecomment-1930249016
