### ISSUE TITLE
[RFE] JSON dump representation of objects in test output

### ISSUE THREAD

**Issue by a-blender** [rancher/terraform-provider-rancher2#1148]
### Is your feature request related to a problem? Please describe.

All of the expander test cases are written like this:

```
if !reflect.DeepEqual(output, tc.ExpectedOutput) {
	t.Fatalf("Unexpected output from expander.\nExpected: %#v\nGiven: %#v", tc.ExpectedOutput, output)
}
```

When a deep equals fails, only the pointer for complex objects is output. This forces devs to serialize and output the objects via manual test statements to figure out what the problem is. This happened to me today with adding Agent Customization support to the tests. I received

```
Output:          *AgentDeploymentCustomization(x00000920c)
Expected Output: *AgentDeploymentCustomization(x00000300d)
```

from an expander function test.

### Describe the solution you'd like

Add json dump representation of `output, expectedOutput` to Terraform tests. This will increase test output readability and debugging efficiency, saving time as we update tests.

**Comment by raul** [comment]
FYI I'm not the maintainer you're referring to 😜

**Comment by felipe-colussi** [comment]
@a-blender , @snasovich 

My main first idea is to import the [testify](https://github.com/stretchr/testify) package and use it (we already use it on rancher).  Is it ok? 

--- 

This is not the scope of the card, but if I'm changing the tests I may as well do it, want to double check with you. 

The test cases are written in the following way: 
```

	cases := []struct {
		Input type
		ExpectedOutput type
	}{
		LIST OF CASES 
	}
	for _, tc := range cases {
		output := funcCall(tc.Input)
		if !reflect.DeepEqual(output, tc.ExpectedOutput) {
			t.Fatalf("...")
		}
	}

```
This way if the 1st test case fails the second one don't run. 

My idea is to change it fore something like this: 

```

	cases := []struct {
		Input type
		ExpectedOutput type
	}{
		LIST OF CASES 
	}
	for number, tc := range cases {
		t.Run(fmt.Sprintf("case %d", number), func(t *testing.T) {
			output := funcCall(tc.Input)
			assert.Equal(t, output, tc.ExpectedOutput, "...")
		})

	}
}

```
That way tests can be run individually on an IDE and all cases always will be executed. Can I do that change too?

**Comment by felipe-colussi** [comment]
After talking with @a-blender  we decided to just to use testify and to not wrap the test loop under the t.Run() function.

**Comment by a-blender** [comment]
@felipe-colussi Merged! Please add a brief QA test template outlining what commands should be run (`make test ./rancher2`, etc.) to verify all tests including acc are working.

**Comment by felipe-colussi** [comment]
## Validation Template

## Root Cause

Test fails were bad to read. 

## What was fixed, or what change have occurred

We started using testify so the print is prettier and easier to read. 

## Areas or cases that should be tested

IMO this dosen't need a test, but if you would test I probably would messup some code and run a test to check if it works. 
Otherwise the build should be enough to  test this.

## What areas could experience regressions

Any

## Are the repro steps accurate/minimal?

There is no repro steps, If I had to test: 
* go test ./... (no acc test).  This should work.
* Break some test case go test ./...   This should print a prettier dump.
* Run the Drone test.

**Comment by Josh-Diamond** [comment]
Verified - testify is now seen + used in rancher2 tests to better format test outputs ✅
