### ISSUE TITLE
[BUG] harvester disk_size default value is not set correctly

### ISSUE THREAD

**Issue by futuretea** [rancher/terraform-provider-rancher2#1150]
### Rancher Server Setup
- Rancher version: 2.7.4
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

### Information about the Cluster
- Kubernetes version:
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

### User Information
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

### Provider Information
- What is the version of the Rancher v2 Terraform Provider in use? 3.0.1
- What is the version of Terraform in use?

### Describe the bug

if users use the Rancher Terraform provider with the "new style" disk_info and network_info, they will see the following changes after reapply
```hcl
	# (6 unchanged attributes hidden)  ~ harvester_config {
	  - disk_size    = "0" -> null
		# (6 unchanged attributes hidden)
	}
```
### To Reproduce

1. Setup a Harvester v1.1.2 cluster, refer to https://docs.harvesterhci.io/v1.1/install/iso-install
2. Add a cloud image `harvester-public/focal-server` and a vlan network `harvester-public/mgmt-vlan1` to the Harvester by using terraform-provider-harvester
```hcl
terraform {
  required_version = ">= 0.13"
  required_providers {
    harvester = {
      source  = "harvester/harvester"
      version = "0.6.2"
    }
  }
}

provider "harvester" {
 kubeconfig = "<the kubeconfig file path of the harvester cluster>"
}

resource "harvester_image" "focal-server" {
  name      = "focal-server"
  namespace = "harvester-public"

  display_name = "focal-server-cloudimg-amd64.img"
  source_type  = "download"
  url          = "https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img"
}

data "harvester_clusternetwork" "mgmt" {
  name = "mgmt"
}

resource "harvester_network" "mgmt-vlan1" {
  name      = "mgmt-vlan1"
  namespace = "harvester-public"

  vlan_id = 1

  route_mode           = "auto"
  route_dhcp_server_ip = ""

  cluster_network_name = data.harvester_clusternetwork.mgmt.name
}
```
4. Setup a Rancher 2.7.4 server
5. Import Harvester cluster to the Rancher cluster in `Virtualization Management`, use  `foo-harvester` as the cluster name
6. Create a guest RKE2 cluster using the following test config:
```hcl
terraform {
  required_providers {
    rancher2 = {
      source = "rancher/rancher2"
      version = "3.0.1"
    }
  }
}


provider "rancher2" {
  api_url    = "<change me>"
  access_key = "<change me>"
  secret_key = "<change me>"
  insecure = true
}


data "rancher2_cluster_v2" "foo-harvester" {
  name = "foo-harvester"
}

# Create a new Cloud Credential for an imported Harvester cluster
resource "rancher2_cloud_credential" "foo-harvester" {
  name = "foo-harvester"
  harvester_credential_config {
    cluster_id = data.rancher2_cluster_v2.foo-harvester.cluster_v1_id
    cluster_type = "imported"
    kubeconfig_content = data.rancher2_cluster_v2.foo-harvester.kube_config
  }
}

# Create a new rancher2 machine config v2 using harvester node_driver
resource "rancher2_machine_config_v2" "foo-harvester-v2" {
  generate_name = "foo-harvester-v2"
  harvester_config {
    vm_namespace = "default"
    cpu_count = "2"
    memory_size = "4"
    disk_info = <<EOF
    {
        "disks": [{
            "imageName": "harvester-public/focal-server",
            "size": 40,
            "bootOrder": 1
        }]
    }
    EOF
    network_info = <<EOF
    {
        "interfaces": [{
            "networkName": "harvester-public/mgmt-vlan1"
        }]
    }
    EOF
    ssh_user = "ubuntu"
    user_data = "I2Nsb3VkLWNvbmZpZwpwYWNrYWdlX3VwZGF0ZTogdHJ1ZQpwYWNrYWdlczoKICAtIHFlbXUtZ3Vlc3QtYWdlbnQKICAtIGlwdGFibGVzCnJ1bmNtZDoKICAtIC0gc3lzdGVtY3RsCiAgICAtIGVuYWJsZQogICAgLSAnLS1ub3cnCiAgICAtIHFlbXUtZ3Vlc3QtYWdlbnQuc2VydmljZQo="
  }
}

resource "rancher2_cluster_v2" "foo-harvester-v2" {
  name = "foo-harvester-v2"
  kubernetes_version = "v1.25.9+rke2r1"
  rke_config {
    machine_pools {
      name = "pool1"
      cloud_credential_secret_name = rancher2_cloud_credential.foo-harvester.id
      control_plane_role = true
      etcd_role = true
      worker_role = true
      quantity = 1
      machine_config {
        kind = rancher2_machine_config_v2.foo-harvester-v2.kind
        name = rancher2_machine_config_v2.foo-harvester-v2.name
      }
    }
    machine_selector_config {
      config = {
        cloud-provider-name = ""
      }
    }
    machine_global_config = <<EOF
cni: "calico"
disable-kube-proxy: false
etcd-expose-metrics: false
EOF
    upgrade_strategy {
      control_plane_concurrency = "10%"
      worker_concurrency = "10%"
    }
    etcd {
      snapshot_schedule_cron = "0 */5 * * *"
      snapshot_retention = 5
    }
    chart_values = ""
  }
}
```
```bash
terraform init
terraform apply
```
7. Check plan again
```bash
terraform apply
```
8. Run `terraform plan`

### Actual Result

the state of disk_size changed after reapply

### Expected Result

the state of disk_size should not be changed after reapply

**Comment by lanfon72** [comment]
Tested with `v3.0.2-rc1` worked, same as https://github.com/harvester/harvester/issues/4097#issuecomment-1594445585

Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **v1.2.0-rc2**
* **ui-source** Option: **Auto**
* Rancher Version: **v2.7-c5d73e160652ff127fa4e6fed30bd7414b3dc6a5-head** (Docker Image: **sha256:584a4032d1c065ce2022cc9aa2735fa4bb4b347abf5725974ba715a711866a47**)
* Terraform Rancher Provider: **v3.0.2-rc1** (Download from https://github.com/rancher/terraform-provider-rancher2/releases/tag/v3.0.2-rc1)
