### ISSUE TITLE
service_account_password left empty

### ISSUE THREAD

**Issue by nheinemans** [rancher/terraform-provider-rancher2#116]
We configure our Rancher2 server through terraform. One of the last steps is configuring the openldap authentication. All required parameters are correctly configured, however the service_account_password is emtpy. 

We use the following tf code for this:
  service_account_distinguished_name = "cn=${var.ldap_sa},ou=Users,o=xxx"
  service_account_password = "${var.ldap_pass}"

All other settings are correct after running. Only the password is emtpy.

**Comment by rawmind0** [comment]
Where is `service_account_password` empty?? on tf state file??

**Comment by nheinemans** [comment]
It's only empty in the Rancher server. The value is correct in the tfstate file, as if it is never submitted when performing the tf apply.

**Comment by rawmind0** [comment]
Passwords or sensible data can not be accessed by rancher api. The password is submitted and saved in rancher but not accessible by api. Is the auth provider working fine??

**Comment by nheinemans** [comment]
After running the tf apply, the ldap authentication in Rancher is not working. The password field is emtpy (in the web UI). After I manually add the password to the auth config in Rancher, it works as expected (and when opening the config again, the password field is not empty).

**Comment by rawmind0** [comment]
Once you apply auth config, the service account password is not visible until you edit config. Do you mean it is empty when you edit auth config?? It's empty because `serviceAccountPassword` is not accessible by API as you can check at https://<RANCHER_URL>/v3/openLdapConfigs/openldap

What is the error you got once auth config is applied and you try to auth with ldap user??

**Comment by rawmind0** [comment]
I've tested provider openldap auth in our lab and is working fine. As mentioned, `service_account_password` is empty on UI  due to is not accessible from API, but provider should configure auth fine.

**Comment by nheinemans** [comment]
Looks like I made a typo in my config, which modified the port number on every terraform run. Opening and saving the config in the web UI corrected this. Thanks a lot for your help!
