### ISSUE TITLE
Terraform provider rancher2 missing user/group search filter options

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/terraform-provider-rancher2#1198]
Issue description:
Terraform provider rancher2 missing openldap configuration

Business impact:
blocking infrastructure provisioning using Terraform

Workaround:
manually setting group "group search filter" parameter when setting up an openldap credential configuration.

Actual behavior:
Terraform provider rancher2 missing openldap configuration

Expected behavior:
erraform provider rancher2 should be present in openldap configuration

Files, logs, traces:
not provided

Additional notes:
The Rancher user interface includes this parameter but no way found for setting it in Terraform so we need to set it manually at the moment.

**Comment by MKlimuszka** [comment]
This needs to be reproduced in 2023-Q1-2.6x, 2023-Q1-2.7x, and if it cannot be reproduced in those, 2.6.5
SURE-5493

**Comment by stormqueen1990** [comment]
Both user search filter and group search filter are unavailable in the rancher/rancher2 Terraform provider versions v1.24.0, v1.24.1, v1.24.2, and v1.25.0. This issue is not related to the Rancher version directly, since it refers to missing fields in the `rancher2_auth_config_openldap` Terraform resource.

**Comment by ronhorton** [comment]
**missing another value**
working on this, i discovered that we're also missing 'start_tls' in TF 3.0.2.
we have 'tls'
without the start_tls, getting error `ERROR] Unknown error: Error creating ssl connection: LDAP Result Code 200 "Network Error": EOF`

source: https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/auth_config_openldap#certificate

**Comment by a-blender** [comment]
@eliyamlevy Merged! Please add a QA test template and list Terraform RC v3.0.2-rc2 as the one to use for testing.

**Comment by eliyamlevy** [comment]
Added QA Considerations to the PR.

**Comment by a-blender** [comment]
# QA Test Template

RC: v3.2.0-rc3

Please do end-to-end testing using [this test plan from the PR](https://github.com/rancher/terraform-provider-rancher2/pull/1173#issue-1812582763). It includes a Terraform auth config with examples of the added fields. Thank you!

**Comment by ronhorton** [comment]
**Pass** verified in terraform `v3.2.0-rc3`

Able to use the `user_search_filter` and `group_search_filter` options successfully. 

Config:
<img width="1003" alt="2023-10-11_15-49-54" src="https://github.com/rancher/terraform-provider-rancher2/assets/89212856/1cb2562a-e2a5-4d7e-9ee3-2483d16b3c31">

To test different search filters, refer to this page as a starting point: https://confluence.atlassian.com/kb/how-to-write-ldap-search-filters-792496933.html
