### ISSUE TITLE
Allow creation of regional GKE clusters through terraform provider

### ISSUE THREAD

**Issue by Oats87** [rancher/terraform-provider-rancher2#120]
Upstream work to enable regional GKE clusters can be found tagged to the Rancher issue here: https://github.com/rancher/rancher/issues/17099

This issue is to help track the requirement to be able to create regional GKE clusters with the terraform provider release that will coincide with the Rancher 2.3 release.

**Comment by rawmind0** [comment]
PR to address this isssue is merged on master. It will be included on next release. Plesse, reopen issue if needed.
