### ISSUE TITLE
[RFE] Graceful Shutdown of vSphere VM

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/terraform-provider-rancher2#1222]
Terraform side of https://github.com/rancher/rancher/issues/42308

**Comment by jiaqiluo** [comment]
can be validated in https://github.com/rancher/terraform-provider-rancher2/releases/tag/v4.0.0-rc3

**Comment by slickwarren** [comment]
tested the following on rancher v2.8-head (6376016):
* rke2 fresh cluster, default settings -> delete a node in the cluster -> non-graceful shutdown
* rke2 fresh cluster, default settings -> delete the cluster -> non-graceful shutdown
* rke1 fresh cluster, default settings -> delete a node in the cluster -> non-graceful shutdown
* rke1 fresh cluster, default settings -> delete the cluster -> non-graceful shutdown
* rke2 fresh cluster, 0 for graceful shutdown in settings -> delete a node in the cluster -> non-graceful shutdown
* rke2 fresh cluster, 0 for graceful shutdown in settings -> delete the cluster -> non-graceful shutdown
* rke1 fresh cluster,  0 for graceful shutdown in settings -> delete a node in the cluster -> non-graceful shutdown
* rke1 fresh cluster, 0 for graceful shutdown in settings -> delete the cluster -> non-graceful shutdown
* rke2 fresh cluster, 10 for graceful shutdown in settings -> delete a node in the cluster -> attempt at graceful shutdown, then non-graceful shutdown after 10 seconds
* rke2 fresh cluster, 10 for graceful shutdown in settings -> delete the cluster -> attempt at graceful shutdown, then non-graceful shutdown after 10 seconds
* rke1 fresh cluster, 10 for graceful shutdown in settings -> delete a node in the cluster -> attempt at graceful shutdown, then non-graceful shutdown after 10 seconds
* rke1 fresh cluster, 10 for graceful shutdown in settings -> delete the cluster -> attempt at graceful shutdown, then non-graceful shutdown after 10 seconds

* rke2 fresh cluster, 100 for graceful shutdown in settings -> delete a node in the cluster -> successful graceful shutdown
* rke2 fresh cluster, 100 for graceful shutdown in settings -> delete the cluster -> successful graceful shutdown
* rke1 fresh cluster, 100 for graceful shutdown in settings -> delete a node in the cluster -> successful graceful shutdown
* rke1 fresh cluster, 100 for graceful shutdown in settings -> delete the cluster -> successful graceful shutdown


to test: upgrade rke1, rke2 from rancher setup without graceful shutdown available -> with it available, edit cluster and delete node. Ensure policy applies correctly.

**Comment by slickwarren** [comment]
upgrades for rke1 and rke2 are actually only supported on the node-pool level. Meaning that, any existing nodes after an upgrade, even if the pool now has graceful_shutdown set, must be removed. Newly created nodes will have the correct settings available and applied. This is known behavior for both engines.
