### ISSUE TITLE
[Backport release/v3] Remove keypair_name from machine_config_v2 documentation 

### ISSUE THREAD

**Issue by thatmidwesterncoder** [rancher/terraform-provider-rancher2#1226]
This is a backport for https://github.com/rancher/terraform-provider-rancher2/issues/1192

Original Issue below:

---

**Other details**
Underlying Infrastructure: AWS
Downstream clusters bootstrapped with Terraform

**Issue description**
The `keypair_name` argument appears to not be supported in the context of Rancher provisioning EC2. Comparing with previous issues ([1](https://github.com/rancher/rancher/issues/25765), [2](https://github.com/rancher/terraform-provider-rancher2/issues/948), [3](https://github.com/rancher/terraform-provider-rancher2/issues/148)) and [rancher/machine](https://github.com/rancher/machine/blob/master/drivers/amazonec2/amazonec2.go#L77C7-L77C7) this argument in the documentation for the terraform provider can add confusion.

**Expected behavior:**
Non implemented features should be removed from documentation

**Comment by thatmidwesterncoder** [comment]
## QA Test Template

### Root cause
Fields that existed in the terraform provider were not used by rancher, namely the keypair_name fields from the openstack and aws providers.

### What was fixed, or what changes have occurred
The fields were removed from the terraform provider. 
 
### Areas or cases that should be tested
**Terraform RC v4.0.0-rc2**. Just sanity checking to make sure the provider still works. Since the fields weren't working before it shouldn't effect anything.

### What areas could experience regressions?
N/A
  
### Are the repro steps accurate/minimal?
No repro steps necessary. 

For testing - use the `v3.2.0-rc3` release.

**Comment by thaneunsoo** [comment]
Waiting for v4.0.0-rc2
