### ISSUE TITLE
Unable to create namespace as cluster is not ready

### ISSUE THREAD

**Issue by andrejonathan** [rancher/terraform-provider-rancher2#123]
When provisioning a new cluster a new namespace is not able to be created as the cluster state is not active.

This code
```
data "rancher2_project" "system" {
  cluster_id         = "${rancher2_cluster.subatomic-cluster-tf.id}"
  name = "System"
}

resource "rancher2_namespace" "bison-cloud" {
  name = "bison-cloud"
  project_id = "${data.rancher2_project.system.id}"
  description = "A namespace called bison-cloud"
  resource_quota {
    limit {
      limits_cpu = "100m"
      limits_memory = "100Mi"
      requests_storage = "1Gi"
    }
  }
}
```

Results in the following error:
```
Error: [ERROR] Creating Namespace: Cluster ID c-5snls is not active

  on modules/rancher/kube_cluster.tf line 64, in resource "rancher2_namespace" "bison-cloud":
  64: resource "rancher2_namespace" "bison-cloud" {
```

Resources that require the cluster to be in ready state should wait for the cluster to be in ready state before running

**Comment by rawmind0** [comment]
[`wait_for_cluster`](https://www.terraform.io/docs/providers/rancher2/r/namespace.html#wait_for_cluster) argument already exist in namespace and project resources. It is indeed just for that.

**Comment by rawmind0** [comment]
Duplicated of #72 . Please reopen issue if needed.

**Comment by andrejonathan** [comment]
Thank you. Is the wait_for_cluster available on other resources or exclusively this one?

**Comment by rawmind0** [comment]
It's available in [`rancher2_namespace`](https://www.terraform.io/docs/providers/rancher2/r/namespace.html#wait_for_cluster) and [`rancher2_project`](https://www.terraform.io/docs/providers/rancher2/r/project.html#wait_for_cluster) . These are the 2 provider resources that check if cluster is active.

**Comment by andrejonathan** [comment]
Great stuff thank you
