### ISSUE TITLE
[RFE] Improve docs and config examples in Terraform rancher2

### ISSUE THREAD

**Issue by a-blender** [rancher/terraform-provider-rancher2#1238]
### Is your feature request related to a problem? Please describe.

Terraform rancher2 customers find docs confusing/unclear and are needing to web-scour for examples to understand how to provision a certain cluster feature.

These docs need to be improved/have more config examples,

- [x] Tls-san v2, configured in machine_global_config https://github.com/rancher/terraform-provider-rancher2/issues/1139
- [x] Machine global config v2
- [x] Machine selector config v2

Please add docs to this list as needed.

### Additional context

Related issues
https://github.com/rancher/terraform-provider-rancher2/issues/1139

SURE-6515

**Comment by Tejeev** [comment]
It would be helpful if 

- The examples in the machine global config doc included configuration for the kubelet_args/kubelet-args
- The examples included configuration for s3 backups (customer based their code off of https://github.com/rancher/terraform-provider-rancher2/issues/947 )
- There was clarification in the description and examples of how to disable/enable “System Services” like CoreDNS, NGINX Ingress, and Metrics Server like you can when creating a custom cluster in the UI 
- `rancher2_cluster_v2.cluster_agent_deployment_customization` has no description on the nested configuration blocks.  As per the examples, it seems like we can use `append_tolerations`, `override_affinity`, and `override_resource_requirements` under it, but we have to find the example as it’s not directly linked to the description. Some examples are found here: https://github.com/rancher/terraform-provider-rancher2/issues/993 
- `rancher2_cluster_v2.fleet_agent_deployment_customization` had a description and example of nested configuration blocks.
- `rancher2_cluster_v2.default_pod_security_admission_configuration_template_name` had a description of the expected values. From the UI, it can be inferred that we can use "rancher-restricted" or "rancher-privileged" but the meaning and the outcome of choosing one or the other is not clear.
- `skip_wait_for_delete_timeout_seconds` had a description of what it does (other than that it’s a drain option).
- `override_resource_requirements` description or example specified what units are expected/assumed here
- We had a description and example for setting pod and svc CIDR in the documentation.  This may be useful: https://github.com/rancher/terraform-provider-rancher2/issues/1139
- The description of the force option made it clear that this is how to set delete standalone pods upgrade per https://github.com/rancher/terraform-provider-rancher2/issues/808
- The description clarified what precisely “delete standalone pods” means/what is meant by “standalone”?  (are they pods without deployments? Pods without specific annotations linking them to something?). What else does force do in this context?
- `local_auth_endpoint` description was clear that partial config (enable=true) can block the first master node from joining the cluster (which blocks creation of `cluster_kubeconfig` as output)

**Comment by snasovich** [comment]
Closing as the documentation has been updated and is available on published TF provider, see https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster_v2
