### ISSUE TITLE
RKE examples

### ISSUE THREAD

**Issue by ryudice** [rancher/terraform-provider-rancher2#126]
Are there any examples when using RKE? I'm adding the nodes to the rke_config of rancher2_cluster but they are never setup by RKE or added to rancher.

**Comment by rawmind0** [comment]
You have some examples in the docs, https://www.terraform.io/docs/providers/rancher2/r/cluster.html#example-usage

You shouldn't add nodes to rke_config. 
If you want infrastructure integration, you should use `rancher2_node_pool` and `rancher2_node_template`.
If you just want custom cluster, you should get the `node_command` from generated [cluster_registration_token](https://www.terraform.io/docs/providers/rancher2/r/cluster.html#cluster_registration_token-1), ${rancher2_cluster.<cluster_tf_name>.cluster_registration_token.0.node_command} and execute it in your node (like is done in the UI)

**Comment by Ilya-Kuchaev** [comment]
```
You shouldn't add nodes to rke_config.
```
Why? What is this section for than?

**Comment by donovanmuller** [comment]
@rawmind0 Would it be possible to provide a full example of using the `cluster_registration_token` attribute to execute on the node, specifically for custom clusters.

**Comment by lapfrank12** [comment]
@donovanmuller `rancher2_cluster.myresourcename.cluster_registration_token[0].node_command`
