### ISSUE TITLE
Ability to wait for entire cluster to be ready

### ISSUE THREAD

**Issue by andrejonathan** [rancher/terraform-provider-rancher2#127]
We are provisioning an AVI cloud with Terraform after we call the Rancher Provider, however the AVI provider just rans and does not check if the Rancher cloud is completely ready. By ready we mean masters, workers and infra nodes  have the property (node["state"] == "active" and node['transitioning'] == "no") . 

We have had to write a polling Python script to check if the Rancher cluster is ready. If we just ran without this the AVI deployment fails as the nodes are not available.

Having the provider hold until the cluster is fully ready would be a big help. Thanks

**Comment by rawmind0** [comment]
Merged PR #131 to fix this issue. Please, reopen it if needed.

**Comment by andrejonathan** [comment]
Great stuff, will check and test and comment, thank you
