### ISSUE TITLE
Bootstrap mode does not authenticate correctly

### ISSUE THREAD

**Issue by mKeRix** [rancher/terraform-provider-rancher2#13]
**EDIT:** issue described in this post was due to user error - please refer to posts below for more info.

---

When using the bootstrap mode of the provider at the moment you are required to set the credential properties to empty strings like this:

```
provider "rancher2" {
  api_url = "https://rancher.example.com"
  access_key = ""
  secret_key = ""
  token_key = ""
  bootstrap = true
}
```

If you don't, like shown in the documentation, it will throw the error that credentials may not be set in bootstrap mode. The [check](https://github.com/terraform-providers/terraform-provider-rancher2/blob/3525f726116a4fcb1a168a207646c26a048655d6/rancher2/provider.go#L153) seems to be assuming wrong default values. I would expect the bootstrap mode to work without providing empty credential strings.

Using Terraform v0.11.13 and rancher2 provider version 1.0.0.

**Comment by rawmind0** [comment]
@mKeRix, i couldn't reproduce your issue. For me, bootstrap is working just fine, without providing empty credential strings. 
```
provider "rancher2" {
  api_url = "https://rancher.example.com"
  bootstrap = true
}

resource "rancher2_bootstrap" "admin" {
  password = "secure_pass"
}
``` 

Could you please check that env variables for access_key (RANCHER_ACCESS_KEY), secret_key (RANCHER_SECRET_KEY) nor token_key (RANCHER_TOKEN_KEY) are set in your shell?? https://www.terraform.io/docs/providers/rancher2/index.html#argument-reference

**Comment by mKeRix** [comment]
Indeed, my bad. I was running the job in a GitLab group that had these keys defined, which were then set in the CI runners.

Now I'm seeing a different issue though - adding resources on the bootstrap provider leads to the following error:

```
rancher2_cluster.demo: Bad response statusCode [401]. Status [401 Unauthorized]. Body: [message=must authenticate] from [https://rancher.example.com/v3]
```

Using the following config:

```
provider "rancher2" {
  api_url = "https://rancher.example.com"
  bootstrap = true
}

resource "rancher2_bootstrap" "admin" {
  password = "secure_pass"
  telemetry = true
}

resource "rancher2_cluster" "demo" {
  name = "demo"
  description = "Imported demo cluster"
}
```

**Comment by rawmind0** [comment]
@mKeRix, bootstrap resource is a special resource. You couldn't mix any other provider resource with bootstrap. 

You should bootstrap first,  

```
provider "rancher2" {
  api_url = "https://rancher.example.com"
  bootstrap = true
}

resource "rancher2_bootstrap" "admin" {
  password = "secure_pass"
  telemetry = true
}
```

And then take generated token to manage any other resources using distinct tf file and tfstate file with bootstrap= false. 

```
 provider "rancher2" {
  api_url = "https://rancher.example.com"
  token_key = <token>
}

resource "rancher2_cluster" "demo" {
  name = "demo"
  description = "Imported demo cluster"
}
```

**Comment by mKeRix** [comment]
Thanks for your input! Just for future reference: you can make it work in one .tf file by using the following config:

```
provider "rancher2" {
  alias = "bootstrap"

  api_url = "rancher.example.com"
  bootstrap = true
}

resource "rancher2_bootstrap" "admin" {
  provider = "rancher2.bootstrap"

  password = "randompass"
  telemetry = true
}

provider "rancher2" {
  api_url = "${rancher2_bootstrap.admin.url}"
  token_key = "${rancher2_bootstrap.admin.token}"
}
```

In your CI (or wherever you execute Terraform) you will now have to run `terraform apply -target=rancher2_bootstrap.admin` at least once before deploying any other Rancher 2 resources.

**Comment by rawmind0** [comment]
Thanks for the reference @mKeRix
