### ISSUE TITLE
[BUG] rancher2_cluster_v2 > machine_selector_config: │ Inappropriate value for attribute "config": string required.

### ISSUE THREAD

**Issue by zerofai** [rancher/terraform-provider-rancher2#1305]
### Rancher Server Setup
- Rancher version: 2.8.1
- Installation option (Docker install/Helm Chart):
   Rancher Install on k3s, version v1.27.9+k3s1, connect to Harvester v.1.2.1 as cloud provider.
- Proxy/Cert Details:
  No proxy

### Information about the Cluster
- Kubernetes version: Provision v1.27.8+rke2r1 as downstream cluster, via Harvester Cloud provider
- Cluster Type (Local/Downstream):
   Downstream RKE2 on Harvester, provision via Terraform 

### User Information
- Admin

### Provider Information
- What is the version of the Rancher v2 Terraform Provider in use?
3.2.0
- What is the version of Terraform in use?
1.4

### Describe the bug
With refer to
https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster_v2
Example: Creating Rancher v2 harvester cluster v2 with harvester cloud provider
Terraform cannot validate, report below:
│   on main.tf line 33, in resource "rancher2_cluster_v2" "target-rke2-cluster":
│   33:       config = {
│   34:         cloud-provider-config = file(var.harvester-cloud-provider-kubeconfig)
│   35:         cloud-provider-name = "harvester"
│   36:         }
│ 
│ Inappropriate value for attribute "config": string required.

### To Reproduce
Use the example to creating Rancher v2 harvester cluster v2 with harvester cloud provider 

### Actual Result
Terraform validation failed

### Expected Result
RKE2 cluster should provision properly with Harvester Cloud Provider install

**Comment by zerofai** [comment]
Issue still exist in v 4.0.0. provider


`Initializing provider plugins...
- Finding rancher/rancher2 versions matching "4.0.0"...
- Installing rancher/rancher2 v4.0.0...
- Installed rancher/rancher2 v4.0.0 (signed by a HashiCorp partner, key ID 2EEB0F9AD44A135C)
Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html
Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.
Terraform has been successfully initialized!
╷
│ Error: Incorrect attribute value type
│ 
│   on main.tf line [33](https://mygit.g2019.net/homelab/gitlab-terraform-rke2/-/jobs/320#L33), in resource "rancher2_cluster_v2" "target-rke2-cluster":
│   33:       config = {
│   [34](https://mygit.g2019.net/homelab/gitlab-terraform-rke2/-/jobs/320#L34):         cloud-provider-config = file(var.harvester-cloud-provider-kubeconfig)
│   [35](https://mygit.g2019.net/homelab/gitlab-terraform-rke2/-/jobs/320#L35):         cloud-provider-name = "harvester"
│   [36](https://mygit.g2019.net/homelab/gitlab-terraform-rke2/-/jobs/320#L36):       }
│ 
│ Inappropriate value for attribute "config": string required.`

**Comment by SebPlv** [comment]
Hi,
I encountered the same issue.
Simply upgrading from rancher2 provider from 3.1.1 to 4.0.0 and I got the same error :

│ Error: Incorrect attribute value type
│ 
│   on create_cluster_rke2.tf line 185, in resource "rancher2_cluster_v2" "moncluster":
│  185:         config = {
│  186:           system-default-registry = "myregistry.foo.com",
│  187:           protect-kernel-defaults = false,
│  188:           cloud-provider-name = "rancher-vsphere"
│  189:         }
│ 
│ Inappropriate value for attribute "config": string required.

I managed to fix this by converting the attribute to this format :

 config = <<EOF
system-default-registry: "myregistry.foo.com"
protect-kernel-defaults: false
cloud-provider-name: "rancher-vsphere"
EOF

If this is the only supported syntax, the documentation should be updated. This syntax is mentioned in only one example (https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster_v2#create-a-cluster-with-machine-global-config-or-machine-selector-config)

Edit: It must be related to PR [1223](https://github.com/rancher/terraform-provider-rancher2/pull/1223)

**Comment by mallardduck** [comment]
@SebPlv - I think that's a great fix/workaround, since it seems like the schema did change going from 3.1.1 -> 4.x.

One note is that I think the PR that caused the change is different than the one you linked. The one linked reverts it from a string field, to a map field. Notably, that change only affects `clusterV2RKEConfigSystemConfigFieldsV0` which is the function preserved as part of the schema migration method terraform provides.

Essentially that just ensures that the state format is updated correctly, however AFAIK end-users still need to update their plans format to match the new syntax manually.

---

Again that's very close, but long story short the PR responsible for the new behavior (and not the migrations) is here: https://github.com/rancher/terraform-provider-rancher2/pull/1181 . And overall I believe the "official answer" (which this is not) will be that plans should be updated to use strings.

**Comment by SebPlv** [comment]
@mallardduck Thanks for these precisions and pointing out the right PR !

**Comment by albinsun** [comment]
Hi,
Does this fix already included in any releases?

**Comment by albinsun** [comment]
Still get the same error in `v4.1.0`

```
$ ../bin/terraform -version
Terraform v1.8.5
on linux_amd64
+ provider registry.terraform.io/rancher/rancher2 v4.1.0
```

![image](https://github.com/rancher/terraform-provider-rancher2/assets/2773781/9971093f-2341-4f24-83d5-94e97cd7326a)

**Comment by mallardduck** [comment]
@albinsun - this issue is closed and I believe @matttrach did this because the correct solution is to do what Seb suggested. Please adjust your terraform plan accordingly, so that the `config` value is a string like:
```
config = <<EOF
system-default-registry: "myregistry.foo.com"
protect-kernel-defaults: false
cloud-provider-name: "rancher-vsphere"
EOF
```

**Comment by albinsun** [comment]
> @albinsun - this issue is closed and I believe @matttrach did this because the correct solution is to do what Seb suggested. Please adjust your terraform plan accordingly, so that the `config` value is a string like:


Thank you @mallardduck and @matttrach,
I just try to follow an example in latest doc to set `machine_selector_config`: https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster_v2#create-a-node-driver-cluster-with-harvester-as-both-the-infrastructure-provider-and-cloud-provider

![image](https://github.com/rancher/terraform-provider-rancher2/assets/2773781/42be1363-7a14-43ae-8892-1e4613bbba57)

Is the problem from the `file()` or `path.module`?
If so, how to leverage them in the string form config?

---

**Update**

It works by `jsonencode` the original object.
```
    ...
    machine_selector_config {
      config = jsonencode({
        cloud-provider-config = file("${path.module}/kubeconfig")
        cloud-provider-name = "harvester"
      })
    }
    ...
```

**Comment by mallardduck** [comment]
@matttrach - Seems like we may have a docs issue, maybe the examples didn't get updated for the change?
