### ISSUE TITLE
The right way to use answers and values_yaml in rancher2_app resource

### ISSUE THREAD

**Issue by vkruoso** [rancher/terraform-provider-rancher2#137]
Im using the rancher2 provider with a great success. But one problem I have is that the plan is always changing, regardless of actual changes on the app configuration. That is not a major drawback as the chart upgrades very fast, but it generates a revision on rancher that does not have any difference, creating noise.

Below is an example of a rancher2_app:

```terraform
resource "rancher2_app" "nginx_ingress" {
  catalog_name     = "helm"
  name             = "nginx-ingress"
  description      = "Nginx Ingress"
  project_id       = "${rancher2_project.my_project.id}"
  template_name    = "nginx-ingress"
  template_version = "1.20.0"
  target_namespace = "${rancher2_namespace.nginx_ingress.name}"

  values_yaml = <<DEFINITION
---
rbac:
  create: true
controller:
  publishService:
    enabled: true
  service:
    type: LoadBalancer
DEFINITION
}
```

After applying this object, and then planning again, the following output follows:

```
  # module.rancher_config.rancher2_app.nginx_ingress will be updated in-place
  ~ resource "rancher2_app" "nginx_ingress" {
        annotations      = {
            "lifecycle.cattle.io/create.helm-controller_c-vnpxm" = "true"
        }
      + answers          = (known after apply)
        catalog_name     = "helm"
        description      = "Nginx Ingress"
        external_id      = "catalog://?catalog=helm&template=nginx-ingress&version=1.20.0"
        force_upgrade    = false
        id               = "p-rx99l:nginx-ingress"
        labels           = {
            "cattle.io/creator" = "norman"
        }
        name             = "nginx-ingress"
        project_id       = "c-vnpxm:p-rx99l"
        revision_id      = "apprevision-tcr49"
        target_namespace = "nginx-ingress"
        template_name    = "nginx-ingress"
        template_version = "1.20.0"
      ~ values_yaml      = <<~EOT
            ---
            rbac:
              create: true
            controller:
              publishService:
                enabled: true
              service:
                type: LoadBalancer
        EOT
    }
```

Note the ```+ answers          = (known after apply)``` (that is always like that) and the ```
~ values_yaml      = <<~EOT``` part, that indicates a difference, but no difference is actually pointed.

Am I doing something wrong in the way to use the resource?

**Comment by rawmind0** [comment]
@vkruoso, you are not doing anything wrong, it's a bug with multilines values comparison on terraform. We are working on a fix to set `values_yaml` base64 encoded.

Until fix is merged, app should work fine using `answers` argument instead,

```
resource "rancher2_app" "nginx_ingress" {
  catalog_name     = "helm"
  name             = "nginx-ingress"
  description      = "Nginx Ingress"
  project_id       = "${rancher2_project.my_project.id}"
  template_name    = "nginx-ingress"
  template_version = "1.20.0"
  target_namespace = "${rancher2_namespace.nginx_ingress.name}"
  answers = {
    "controller.publishService.enabled" = "true"
    "controller.service.type" = "LoadBalancer"
    "rbac.create" = "true"
  }
}
```

**Comment by vkruoso** [comment]
Thanks @rawmind0 for the fast answer. Will change my resources to use answers instead. My initial block on using answers were the fact that rancher charts may have the questions.yml file, and the answers field were limited to those questions. Also copy/paste the full yaml is also easier when testing out new apps.

**Comment by rawmind0** [comment]
Yeah, i get your point, but multiline argument comparison on terraform is a little bit tricky. 

You can add any helm chart parameter as `answers`. The difference on UI is use "Edit as form" (use `answers`) or "Edit as yaml" (use `values_yaml`)

Fix to use `values_yaml` base64 encoded is on the way.

**Comment by rawmind0** [comment]
Merged PR to fix this issue. Please, reopen it if needed.
