### ISSUE TITLE
[BUG] OpenTofu registry is missing GPG keys

### ISSUE THREAD

**Issue by egrosdou01** [rancher/terraform-provider-rancher2#1385]
### Rancher Server Setup
- Rancher version: **2.8.5**
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): **Helm chart installation on support platform**.
- Proxy/Cert Details:

### Provider Information
- What is the version of the Rancher v2 Terraform Provider in use? **v4.1.0**
- What is the version of ~~Terraform~~ OpenTofu in use? **OpenTofu v1.8.1 on darwin_arm64**

### Describe the bug
Basically, the GPG keys of this provider are missing in the OpenTofu module registry. When performing `tofu init` we can see the below message.

```bash
- Installing rancher/rancher2 v4.1.0...
- Installed rancher/rancher2 v4.1.0. Signature validation was skipped due to the registry not containing GPG keys for this provider
```

### To Reproduce
1. [Install OpenTofu](https://opentofu.org/docs/intro/install/)
2. Execute `tofu init`

### Actual Result
```bash
- Installing rancher/rancher2 v4.1.0...
- Installed rancher/rancher2 v4.1.0. Signature validation was skipped due to the registry not containing GPG keys for this provider
```

### Expected Result
The rancher2 provider should be downloaded and verified.

**Comment by matttrach** [comment]
We don't specifically support open Tofu directly, we had an issue with GPG keys in the Terraform registry a while back which we resolved by extending the expiration date. It is possible that this was resolved at the same time, but we don't have any testing process in place to validate. @egrosdou01 has this been resolved?

**Comment by egrosdou01** [comment]
Hi @matttrach, thanks for the prompt reply. That means that if and when you will officially support OpenTofu, this issue should be resolved.

The link below can be used to update the provider signature.

- [Submit new Provider Signing Key](https://github.com/opentofu/registry/issues/new?assignees=&labels=provider-key%2Csubmission&projects=&template=provider_key.yml&title=Provider+Key%3A+)

**Comment by matttrach** [comment]
I am going to close this in favor of #1437.
