### ISSUE TITLE
[BUG] rancher2_custom_user_token, argument renew = false doesn't work

### ISSUE THREAD

**Issue by char-iot** [rancher/terraform-provider-rancher2#1397]
### Rancher Server Setup
- Rancher version: `2.8.5`
- Installation option (Docker install/Helm Chart): `helm chart`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `RKE1`
- Proxy/Cert Details: `no proxy, self-signed`

### Information about the Cluster
- Kubernetes version:  `v1.29.6+rke2r1`
- Cluster Type (Local/Downstream): `Downstream`
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): `Imported`

### User Information
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) `Project Member`
  - If custom, define the set of permissions:

### Provider Information
- What is the version of the Rancher v2 Terraform Provider in use? `5.0.0`
- What is the version of Terraform in use? `Terraform enterprise v202404-2, the Terraform version used for runs in this workspace is 1.8.1`

### Describe the bug

argument renew = false doesn't work

### To Reproduce

```terraform
# Create a rancher2 Token
resource "rancher2_user" "foo" {
  name     = "foo"
  username = "foo"
  password = "changeme"
  enabled  = true
}

resource "rancher2_global_role_binding" "foo-login" {
  name           = "foo-login-binding"
  global_role_id = "user-base"
  user_id        = rancher2_user.foo.id
}

resource "rancher2_custom_user_token" "foo" {
  username    = rancher2_user.foo.username
  password    = rancher2_user.foo.password
  renew       = false
  description = "foo token"
  ttl         = 0

  depends_on = [
    rancher2_global_role_binding.foo-login
  ]
}
```
### Actual Result

`when trys to rerun or any kind of change to repo, token would be renewed.`

### Expected Result

`when trys to rerun or any kind of change to repo, token shouldn't be renewed.`
### Screenshots

![image](https://github.com/user-attachments/assets/ffa70e80-6ede-4728-b326-27c7c1472d4e)
### Additional Question

`Is there a way to say renew only when older than 60days or expired?`

**Comment by char-iot** [comment]
problem is with ttl being forced replaced with 7776000 every run.

**Comment by dennislapchenko** [comment]
@char-iot did you find a solution for this? What explains you closing the issue?
I'm on newest version of provider and still with this issue

**Comment by char-iot** [comment]
@dennislapchenko they didn't respond. so I worked around the issue with:
```
# Create a rancher2 Token
resource "rancher2_user" "foo" {
  name     = "foo"
  username = "foo"
  password = "changeme"
  enabled  = true
}

resource "rancher2_global_role_binding" "foo-login" {
  name           = "foo-login-binding"
  global_role_id = "user-base"
  user_id        = rancher2_user.foo.id
}

resource "rancher2_custom_user_token" "foo" {
  username    = rancher2_user.foo.username
  password    = rancher2_user.foo.password
  description = "foo token"
  renew       = false
  ttl         = 7776000
  lifecycle {
    replace_triggered_by = [
      time_static.rotate
    ]
  }
}

  depends_on = [
    rancher2_global_role_binding.foo-login
  ]
}


resource "time_rotating" "rotate" {
  rotation_days = 60
}

resource "time_static" "rotate" {
  rfc3339 = time_rotating.rotate.rfc3339
}
```

**Comment by dennislapchenko** [comment]
@char-iot thanks for replying.
Just FYI, in my case i solved it by figuring out that there is a rancher `setting` called `auth-token-max-ttl-minutes` which has to be set to 0, after this tokens with `ttl = 0` stay that way.

```
resource "rancher2_setting" "settings" {
  name     = "auth-token-max-ttl-minutes"
  value    = "0"
}
```
