### ISSUE TITLE
[BUG] Certain new users cannot create clusters with Terraform

### ISSUE THREAD

**Issue by matttrach** [rancher/terraform-provider-rancher2#1398]
### Rancher Server Setup
- Rancher version: v2.7.9
- Installation option (Docker install/Helm Chart): unknown
- Proxy/Cert Details: unknown

### Information about the Cluster
- Kubernetes version: unknown
- Cluster Type (Local/Downstream): downstream, harvester

### User Information
- What is the role of the user logged in? unknown

### Provider Information
- What is the version of the Rancher v2 Terraform Provider in use? v4.2.0
- What is the version of Terraform in use? unknown

### Describe the bug

A specific group of users is not able to start the cluster using Terraform.
From UI the cluster creation works for the same users.

See SURE-8955 for more details

**Comment by matttrach** [comment]
This involves ldap integration. It appears that the user(s) is being denied when they have many different groups attached.
The user suggested updating the machine config code so that forbidden responses would be subject to timeouts.
https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/resource_rancher2_machine_config_v2.go#L51-L78

**Comment by matttrach** [comment]
I think the user's suggestion may not work because if we are getting a timeout from ldap due to having to parse a user with a lot of groups then a retry won't have a different result. Instead, the ldap integration may need to be configured with longer timeouts, which is not configured in this resource.

**Comment by matttrach** [comment]
I have requested more information from the user regarding the Terraform config. If there is another resource generating the user in the same apply then potentially this could be fixed in the Terraform dependency chain, otherwise I may need to get some advice from the team that maintains the ldap integration.

**Comment by matttrach** [comment]
Got a second option on this one and it turns out I was wrong. It looks like the user's suggestion is a good idea, so I will proceed in making the suggested change.

**Comment by joesims22** [comment]
Validated on v2.10-head id `691f7ae` and tfp `v6.0.0-rc1` successfully.
