### ISSUE TITLE
[BACKPORT v4] Can't update any rancher2_role_template due to new external_rules attribute

### ISSUE THREAD

**Issue by matttrach** [rancher/terraform-provider-rancher2#1406]
tracking #1396 as backport of #1389 addressing #1381

**Comment by k0da** [comment]
We desperately need that to be released, it blocks our delivery pipeline.

**Comment by joesims22** [comment]
Validated on v2.8-head id `68e5d43`. 

| \#  | Priority | Description & Link                                        | PASS/FAIL |
| --- | -------- | --------------------------------------------------------- | --------- |
| 1   | P0       | Verify updating RT via TFP is successful                        | ✅ PASS    |
| 2   | P0       |  Verify TFP sets external attribute to false by default                       | ✅ PASS    |
| 3   | P0      | Verify external rules value is set to nil if external attribute is not set                                  | ✅ PASS    |
| 4   | P0       | Verify external rules cannot be set when updating RT via TFP while external is set to false                        | ✅ PASS    |
| 5   | P0       |  Verify external rules can be set when updating RT via TFP after setting external to true                                 | ✅ PASS    |
| 6   | P1       | Verify external rules cannot be set  via kubectl when external is set to false | ✅ PASS    |
| 7   | P1      | Verify external rules can be set when updating RT via kubectl after setting external to true                                      | ✅ PASS    |
| 8   | P0       | Verify external rules are removed when external set to false via TFP                                      | ✅ PASS    |
| 9   | P0       | Upgrade: Verify updating RT via TFP is successful upon upgrading Rancher                                      | ✅ PASS    |
