### ISSUE TITLE
[DOC] Remove extra backticks from node_template.md

### ISSUE THREAD

**Issue by matttrach** [rancher/terraform-provider-rancher2#1408]
tracking #1394 

## Issue: 
Backticks appearing at the end of the `node_template` doc:
![image](https://github.com/user-attachments/assets/2ba66620-7a46-485d-b18a-3721a91ecc56)

**Comment by jiaqiluo** [comment]
The extra backticks do not exist anymore  at the end of the [node_template doc](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/node_template)


<img width="1444" alt="image" src="https://github.com/user-attachments/assets/d6bf1860-a19b-4eae-b401-d661c92d5edb">
