### ISSUE TITLE
Support for Keycloak auth provider

### ISSUE THREAD

**Issue by donovanmuller** [rancher/terraform-provider-rancher2#142]
There currently (as of 1.5.0) doesn't appear to be a specific Keycloak auth provider. 
However, based on the arguments for similar SAML based auth providers ([ADFS](https://www.terraform.io/docs/providers/rancher2/r/authConfigADFS.html), [Ping](https://www.terraform.io/docs/providers/rancher2/r/authConfigPing.html)), would either of those providers work for Keycloak as well? If not and there is auth provider specific requirements, could this please be added.

**Comment by rawmind0** [comment]
Support for `keycloak` and `OKTA` auth providers added on PR #143

**Comment by rawmind0** [comment]
Merged PR that solves this issue. Please, reopen it if needed.
