### ISSUE TITLE
[BUG] Creating a rancher2_catalog_v2 with an OCI Helm Repository never finishes creation

### ISSUE THREAD

**Issue by AlexisDaciuk** [rancher/terraform-provider-rancher2#1421]
### Rancher Server Setup
- Rancher version: 2.9.2
- Installation option (Docker install/Helm Chart): Docker Install
- Proxy/Cert Details: Included LetsEncrypt, no proxy

### Information about the Cluster
- Kubernetes version: v1.29.8 +rke2r1
- Cluster Type (Local/Downstream): RKE2 deployed in EC2

### User Information
- What is the role of the user logged in? Admin (using rancher_bootstrap token)

### Provider Information
- What is the version of the Rancher v2 Terraform Provider in use? 5.1.0
- What is the version of Terraform in use? 1.9.6
- What is the version of Terragrunt in use? v0.66.9

### Describe the bug
When creating a **rancher2_catalog_v2 resource**, the providers expects a `Downloaded` state, but when using an OCI repository the state is `OCIDownloaded` so the provider never ends the resource creation

### To Reproduce
Create a rancher2_catalog_v2 

```hcl
resource "rancher2_catalog_v2" "private_catalogs" {
  cluster_id = var.RANCHER_CLUSTER_ID
  name       = var.NAME
  url        = var.URL
  secret_name = var.SECRET_NAME
  secret_namespace = var.SECRET_NAMESPACE
}
```
And the terragrunt / terraform execution gets stuck at 

```
[DEBUG] provider.terraform-provider-rancher2_v5.1.0: 2024/10/02 16:30:06 [DEBUG] Waiting for state to become: [downloaded]
```

Taking a look into the YAML of the created catalog we can see that the state is `OCIDownloaded`

```yaml
status:
  conditions:
    - lastUpdateTime: '2024-10-02T19:19:57Z'
      status: 'True'
      type: FollowerDownloaded
    - lastUpdateTime: '2024-10-02T19:19:59Z'
      status: 'True'
      type: OCIDownloaded
```

So the provider will never end because it is waiting for a state that won't exist in a OCI repository

### Actual Result

The provider creates the repository but the Terragrunt / Terraform executions gets stuck

### Expected Result
The provider creates the repository without getting stuck

### Screenshots
Taking a look into the created catalog, is in an `Active` state and the Charts that it contains can be seen and used from within Rancher

![Screenshot_20241002_161126](https://github.com/user-attachments/assets/e888e182-3810-42eb-873d-0dc2c03baa6e)

The state of the repo is `OCIDownloaded`

![Screenshot_20241002_162250](https://github.com/user-attachments/assets/9c04cea8-2a35-4e11-b259-cc810eaeb0db)

But the provider is waiting for `Download`

![Screenshot_20241002_165317](https://github.com/user-attachments/assets/f4aaf8fe-f2df-4cb6-b189-2029339cb77e)

Cheers
Alex

**Comment by matttrach** [comment]
This was merged in Nov and has been released in https://github.com/rancher/terraform-provider-rancher2/releases/tag/v6.0.0
