### ISSUE TITLE
[BACKPORT v5] Bump default azure image

### ISSUE THREAD

**Issue by matttrach** [rancher/terraform-provider-rancher2#1431]
This is a backport of https://github.com/rancher/terraform-provider-rancher2/pull/1429 to v5

**Comment by Josh-Diamond** [comment]
Ticket# 1431 - Test Results - ✅ 
---

Verified on Rancher `v2.9.3` with Rancher2 `v5.2.0-rc1`
| Scenario | Test Case | Result|
|---|---|---|
| 1. | Verify default Azure image for RKE1 Node driver clusters | ✅ |

---

Scenario 1 - ✅ 
1. Run `terraform apply` with no image defined in the `rancher2_node_template` resource for a downstream RKE1 Azure Node driver cluster
2. Verified - Image defaults to `+ image  = "canonical:ubuntu-24_04-lts:server-gen1:latest"`
3. Provision the downstream cluster
4. Verified - cluster successfully provisions; all pods `active` and stable; as expected
