### ISSUE TITLE
Bump default azure image

### ISSUE THREAD

**Issue by matttrach** [rancher/terraform-provider-rancher2#1434]
https://github.com/rancher/rancher/issues/44944
Standard_A2 is currently not available in location 'westus'

This issue is tracking https://github.com/rancher/terraform-provider-rancher2/pull/1429

**Comment by Josh-Diamond** [comment]
Ticket# 1434 - Test Results - ✅ 
---

Verified on Rancher `v2.10.0` with Rancher2 `v6.0.0-rc3`
| Scenario | Test Case | Result|
|---|---|---|
| 1. | Verify default Azure image for RKE1 Node driver clusters | ✅ |

---

Scenario 1 - ✅ 
1. Run `terraform apply` with no image defined in the `rancher2_node_template` resource for a downstream RKE1 Azure Node driver cluster
2. Verified - Image defaults to `+ image  = "canonical:ubuntu-24_04-lts:server-gen1:latest"`
3. Provision the downstream cluster
4. Verified - cluster successfully provisions; all pods `active` and stable; as expected
