### ISSUE TITLE
[BACKPORT] rke2 machineSelectorFiles.fileSources have multiple duplicate entries

### ISSUE THREAD

**Issue by matttrach** [rancher/terraform-provider-rancher2#1438]
Backport #1426 to provider v5 targeting Rancher v1.9x.

**Comment by matttrach** [comment]
#1441 merged

**Comment by Josh-Diamond** [comment]
Ticket #1438 - Test Results - ✅ 
---

Verified on Rancher `v2.9.3` with Rancher2 `v5.2.0-rc1`:

| Scenario | Test Result | Result |
|---|---|---|
| 1. | Provision downstream RKE2 AWS Node driver cluster => edit cluster and force reconciliation => confirm no duplicate entries are seen in `machineSelectorFiles.fileSources` | ✅ |

---

Scenario 1 - ✅ 
1. Provision a downstream RKE2 AWS Node driver cluster
2. Once `active`, modify `snapshot_retention` and apply changes
3. Once cluster updates and is `active`, `edit YAML` of cluster object and verify `machineSeletorFiles.fileSources`
4. Verified - No duplicates seen in `machineSelectorFiles.fileSources` after cluster update; as expected
