### ISSUE TITLE
Ability to force refresh of rancher2_catalog

### ISSUE THREAD

**Issue by donovanmuller** [rancher/terraform-provider-rancher2#147]
Would it be possible to add the functionality to force a refresh of a custom catalog.
The equivalent of:

```
HTTP/1.1 POST /v3/catalogs/custom-cat?action=refresh
```

**Comment by rawmind0** [comment]
It would be possible to add the function, but refresh function doesn't save any state. Are you proposing a catalog refresh every single time that you run terraform or on any catalog update??

**Comment by donovanmuller** [comment]
The use case is as part of a build pipeline for charts that make up a custom catalog, we want to refresh the catalog at the end of the build to pick up the updated charts.

Perhaps using the Terraform provider isn't the best mechanism and instead we should be calling the API directly but would be nice to keep the automation mechanism consistent.

**Comment by rawmind0** [comment]
Please reopen issue if needed
