### ISSUE TITLE
How to use existing Keypair from AWS

### ISSUE THREAD

**Issue by ryudice** [rancher/terraform-provider-rancher2#148]
I'm trying to setup a node template like the following, however I get this error when it starts creating the nodes:

![image](https://user-images.githubusercontent.com/125211/66137770-ceefa380-e5ba-11e9-90c0-219e556a5d1f.png)

I have the keypair on that path in my local terraform files. This is my terraform script:

```
resource "rancher2_node_template" "control-plane" {
  name = "${local.cluster_name}-control-plane"
  #   description = "foo test"
  amazonec2_config {
          ami =  "${data.aws_ami.distro.id}"
    security_group = [aws_security_group.main-sg.name]
    subnet_id      = "subnet"
    vpc_id         = "${var.vpc_id}"
    zone           = "b"
    tags           = ""
    ssh_user       = "core"
     region = "eu-west-1"
       instance_type = "t3.medium"
    keypair_name = "RancherKeyPair"
    ssh_keypath = "../ssh/RancherKeyPair.pem"
  }
}
```

**Comment by bensonarokiadoss** [comment]
@ryudice i was hitting the same issue. Even though its referenced on the terraform rancher provider documentation, i am not sure does rancher support bring your own key yet. Internally they use docker-machine to provision those ec2 instances which dont have access to local key that we would point within terraform code. Unless the api call copies the key. Someone from rancher side correct me if any of my understanding is wrong

**Comment by ajfriesen** [comment]
tried the same as @ryudice 
Also reverting the changes on the notetemplate to use rancher generated keypairs did not work.
We saw a change in terraform and applied but the nodes did come up with the same error again.

**Comment by wd** [comment]
As the error said: key file not found, maybe we should put the keys on the rancher master?

**Comment by rawmind0** [comment]
Use existing keypair on AWS node_pool is not supported from Rncher2, https://forums.rancher.com/t/aws-keypairs-when-creating-host/7357
