### ISSUE TITLE
LDAP username error for project permissions

### ISSUE THREAD

**Issue by mattmattox** [rancher/terraform-provider-rancher2#149]
Bug

It looks when assigning permissions to a project in Rancher. The Rancher2 Terraform module is using the shortname for the LDAP username but the Rancher API needs the LDAP CN for the username.

**Comment by rawmind0** [comment]
The Rancher2 tf provider can use user id or principial user id (same for groups) when assigning permissions to a project https://www.terraform.io/docs/providers/rancher2/r/projectRole.html#user_principal_id

Have you tried using user_principal_id ??

**Comment by seanwcom** [comment]
Just tried this ... It works if I know the user_principal_id. We use LDAP, so this is what the principal ids look like for a user:

```
"principalIds": [
  "openldap_user://CN=Username (Organization),OU=Users,OU=Standard Users,OU=Users and Computers,OU=Atlanta Corporate,OU=FOO,DC=BAR,DC=com",
  "local://u-hrbefrdwph"
]
```
So then if I plan/apply this, it works:

```
resource "rancher2_project_role_template_binding" "test-id1" {
  name = "test-id1"
  project_id = "c-df7fx:p-428w8"
  role_template_id = "rt-s2gmk"
  user_principal_id = "local://u-hrbefrdwph"
}
```
However, if I try to replace the local:// with an ldap username, it won't work. 

Now flip over to the CLI for a sec, running this works:

```
rancher project add-member-role myldapusername rt-s2gmk
```
You can see here, I'm able to just use a plain username. I had hoped to `--debug` that command and get some API output to see what it's doing, but it doesn't output anything.

**Comment by rawmind0** [comment]
Every external user is mapped to a representation of local user and a principal. It works if you know the local principal id, the local id and/or the openldap DN (used as principal id)

In your example, this should also work

```
resource "rancher2_project_role_template_binding" "test-id1" {
  name = "test-id1"
  project_id = "c-df7fx:p-428w8"
  role_template_id = "rt-s2gmk"
  user_principal_id = "openldap_user://CN=Username (Organization),OU=Users,OU=Standard Users,OU=Users and Computers,OU=Atlanta Corporate,OU=FOO,DC=BAR,DC=com"
}
```

and/or this too

```
resource "rancher2_project_role_template_binding" "test-id1" {
  name = "test-id1"
  project_id = "c-df7fx:p-428w8"
  role_template_id = "rt-s2gmk"
  user_id = "u-hrbefrdwph"
}
```

CLI is using principal ID, https://github.com/rancher/cli/blob/master/cmd/project.go#L199
and searching member by principal name, not loginname, https://github.com/rancher/cli/blob/master/cmd/common.go#L155

**Comment by rawmind0** [comment]
Please reopen issue if needed
