### ISSUE TITLE
Cannot Import rancher2_namespace with projectId null

### ISSUE THREAD

**Issue by draco-rapid** [rancher/terraform-provider-rancher2#153]
Getting this error when attempting to import the resource with a null projectId

`
terraform import rancher2_namespace null.consul
`
Error: Bad response statusCode [404]. Status [404 Not Found]. Body: [baseType=error, code=NotFound, message=clusters.management.cattle.io "null" not found] from [https://testcluster.net/v3/clusters/null]
`

**Comment by rawmind0** [comment]
Null project_id is not supported for import namespaces. Provider needs to know at least the cluster where to import from. Please, take a look at the doc, https://www.terraform.io/docs/providers/rancher2/r/namespace.html#import
