### ISSUE TITLE
rancher2_project changes every plan

### ISSUE THREAD

**Issue by drpebcak** [rancher/terraform-provider-rancher2#154]
Every time `terraform plan` gets ran, terraform wants to remove the annotations that Rancher adds by default.

**Comment by rawmind0** [comment]
Are you adding any additional annotation in the `rancher2_project` definition?? If yes, it's related to #27 , take a look to the workaround.

Working on a way to address it.

**Comment by drpebcak** [comment]
In my case I'm not specifying any additional labels or annotations:
```
resource "rancher2_project" "thing2" {
  name        = "thing2"
  cluster_id  = rancher2_cluster_sync.imported.id
  description = "disposable project for thing1"
}
```

**Comment by drpebcak** [comment]
This might be related to when another resource changes though, so I will look to see if I can nail down exactly when it happens.

**Comment by rawmind0** [comment]
I could reproduce the issue. The problem occurs duet to bad sync with `resource_quota` and `container_resoruce_limit` info.

I submitted PR #175 to fix issue.

**Comment by rawmind0** [comment]
PR is merged into master. Please, reopen issue if needed.
