### ISSUE TITLE
how to create a cluster, add cusom nodes and all with terraform on rancher 2?

### ISSUE THREAD

**Issue by malolnaor** [rancher/terraform-provider-rancher2#159]
I know there is a way to export node_command, but there is anyway to add custom nodes + run the node_command using ssh from rancher2 provider? 
I tried using

> node {}

I saw that a new resource was created but I can't see the new node in the cluster.

**Comment by rawmind0** [comment]
@malolnaor , rancher2 provider  can manage node-templates and node-pools to deploy vm's and build the k8s cluster from rancher. But it doesn't support ssh access to vm to execute node_command. You could get node_command from rancher2_cluster and use another tf provider to  execute node_command on vm's.

**Comment by michtam** [comment]
@malolnaor you can try use **Null Resource** for executing **node_command**
How are you spawning your nodes?

**Comment by rawmind0** [comment]
Please reopen issue if needed
