### ISSUE TITLE
[Feature Request] Resource for management of Namespace -> Project assignment

### ISSUE THREAD

**Issue by nazarewk** [rancher/terraform-provider-rancher2#161]
It would be lovely to have some kind of resource for management of just relations between existing Kubernetes `Namespace` and existing Rancher `Project`, right now i have to import whole `rancher2_namespace` resource and then update it with specific `project_id`, which is namespace-deletion prone approach (would have to use `terraform state rm ...`).

The only thing i want to manage is Project assignment of Namespace and nothing else.

**Comment by iridian-ks** [comment]
So, Rancher uses annotations and labels to do a lot of things like this. Here's what I've done:

```
data "rancher2_cluster" "mycluster" {
  name = "mycluster-name"
}

// can be a Resource or Data source, you just need something that returns a project id
data "rancher2_project" "myproj" {
  cluster_id = data.rancher2_cluster.mycluster.id
  name        = "System"
}

resource "kubernetes_namespace" "myns" {
  metadata {
    name = "myns"

    labels = {
      "field.cattle.io/projectId = data.rancher2_project.id
    }
  }
}
```

Unfortunately, this still requires an import, but if the namespace already exists the Kubernetes provider will fail so at least you're somewhat protected

The Terraform paradigm is it expects to manage the entire lifecycle of any resources it manages. Importing resources outside of `terraform import` isn't something I've generally seen in Terraform providers.

Additionally, if you want to protect from deletion you can also add this:

```
resource "kubernetes_namespace" "myns" {
  lifecycle {
    prevent_destroy = true
  }
}
```

(this also applies to any Terraform resource)

If you want to go outside the normal Terraform paradigm you could also have Terraform execute a script that can run a kubectl apply. That script just needs to do the same thing Terraform would do and you can template in the project id.

```
resource "null_resource" "label" {
  triggers = {
    project_id = data.rancher2_project.id
  }

  provisioner "local-exec" {
    command = "myscript.sh ${data.rancher2_project.id}"
  }
}
```

Disclaimer: Code is not tested

I think this is the best you can probably do within the boundaries of Terraform.

**Comment by ntkach** [comment]
Thanks, I was looking for a way to get namespaces into projects without absolutely needing to use rancher2_namespace!  I have code that worked for me at least
```
data "rancher2_cluster" "mycluster" {
  name = "mycluster-name"
}

// can be a Resource or Data source, you just need something that returns a project id
data "rancher2_project" "myproj" {
  cluster_id = data.rancher2_cluster.mycluster.id
  name        = "System"
}

resource "kubernetes_namespace" "myns" {
  metadata {
    name = "myns"

   annotations = {
      "field.cattle.io/projectId" = data.rancher2_project.myproj.id
    }
  }
}
```
For whatever reason my experience was it didn't work when you put it in the labels.  I also used terraform 0.12.16 FWIW.

**Comment by rawmind0** [comment]
@ntkach, Rancher use annotations nor labels for namespace project assignment. Your code should work fine. 

Please, reopen issue if needed.
