### ISSUE TITLE
[Feature Request] Discovery-based data sources

### ISSUE THREAD

**Issue by nazarewk** [rancher/terraform-provider-rancher2#162]
Current data sources model is: knowing exact `name`/`id` of a resource I can retrieve it's details.

Addition of discovery would help tremendously: knowing filter/search values i want to discover which resources are available.

For example i want to search for Projects matching `label` `project-role=microservices`

**Comment by tumd** [comment]
I too have hit this limitation.
In my use-case I need to retrieve a list of available `rancher2_cluster_template`'s and their data, before I create any new such resources.

**Comment by kkaempf** [comment]
closing stale issues
