### ISSUE TITLE
[bug] can't move namespace. Project ... has resource quota set

### ISSUE THREAD

**Issue by nazarewk** [rancher/terraform-provider-rancher2#163]
I'm trying to move namespaces into provider created project, but I'm getting this error from title `can't move namespace. Project ... has resource quota set` even though I'm not setting any kind of quotas in Project:
```
resource "rancher2_project" "apps" {
  cluster_id  = data.rancher2_cluster.this.id
  name = "apps"
}
```

I have successfully created the Namespace inside the project from Rancher UI, but after moving it out of the project I cannot move it back inside the project due to mentioned error.

**Comment by nazarewk** [comment]
Update: it is working again after destroying and recreating the configuration, I don't know how to reproduce it.

Note 1: i did not edit anything about the Project outside Terraform.

Note 2: it generated permanent diff on quotas even though i never set them, to suppress the diff i had to add the entries manually:
```
  resource_quota {
    namespace_default_limit {}
    project_limit {}
  }
```

**Comment by nazarewk** [comment]
After a few minutes of doing absolutely nothing plan yields me following diff:

```
  # rancher2_project.apps will be updated in-place
  ~ resource "rancher2_project" "apps" {
        annotations               = {
            "authz.management.cattle.io/creator-role-bindings"                   = jsonencode(
                {
                    created  = [
                        "project-owner",
                    ]
                    required = [
                        "project-owner",
                    ]
                }
            )
            "lifecycle.cattle.io/create.mgmt-project-rbac-remove"                = "true"
            "lifecycle.cattle.io/create.project-namespace-auth_c-4xgjq"          = "true"
            "lifecycle.cattle.io/create.project-precan-alert-controller_c-4xgjq" = "true"
        }
        cluster_id                = "c-4xgjq"
        description               = "<REDACTED>"
        enable_project_monitoring = false
        id                        = "c-4xgjq:p-szld6"
        labels                    = {
            "cattle.io/creator" = "norman"
        }
        name                      = "<REDACTED>"
        wait_for_cluster          = false

      - container_resource_limit {}

        project_monitoring_input {}

      - resource_quota {
          - namespace_default_limit {}

          - project_limit {}
        }
    }
```

Possibly related to #154

**Comment by rawmind0** [comment]
Submitted PR #175 to fix issue.

**Comment by rawmind0** [comment]
PR is merged into master. Please, reopen issue if needed.

**Comment by nemobis** [comment]
I'm still getting this error when trying to import a namespace which was created into the same project from the UI. May require use of the steve API: https://github.com/rancher/rancher/issues/40495#issuecomment-2380154730
