### ISSUE TITLE
Offer support for modifying existing alert rules, groups, etc. 

### ISSUE THREAD

**Issue by ebauman** [rancher/terraform-provider-rancher2#164]
Currently this provider is only able to create new alert rules, etc. It cannot, for instance, modify an existing alert group to attach a notifier. That would be a good feature to have.

**Comment by rawmind0** [comment]
@ebauman, for existing alert rule/group you could import them,  [alert rules](https://www.terraform.io/docs/providers/rancher2/r/clusterAlertRule.html#import) and [alert groups](https://www.terraform.io/docs/providers/rancher2/r/clusterAlertGroup.html#import) and then manage them from terraform.

**Comment by rawmind0** [comment]
Please reopen issue if needed
