### ISSUE TITLE
terraform created project_alert_rules are immediately removed

### ISSUE THREAD

**Issue by ajchiarello** [rancher/terraform-provider-rancher2#165]
When I create a rancher2_project_alert_rule (per https://www.terraform.io/docs/providers/rancher2/r/projectAlertRule.html) I see the rule appear briefly, and then it switches to a "Removing" status and disappears. Rules made via the gui do not show this behaviour.

**Comment by rawmind0** [comment]
Not able to reproduce the issue using [alert rule example](https://www.terraform.io/docs/providers/rancher2/r/projectAlertRule.html). It generates the project, the alert group and the alert rule as expected.

Could you please provide more info to reproduce the issue??

**Comment by ajchiarello** [comment]
Here is the code I'm using - just ran it, and saw the reported behaviour:

>  ...
> resource "rancher2_project" "utilities" {
>   name                      = "Utilities"
>   cluster_id                = data.rancher2_cluster.cluster.id
>   enable_project_monitoring = "true"
> }
> 
> resource "rancher2_project_alert_group" "utilities" {
>   name       = "utilities_alerts"
>   project_id = rancher2_project.utilities.id
>   recipients {
>     notifier_id = rancher2_notifier.default.id
>   }
> }
> 
> resource "rancher2_project_alert_rule" "metallb_controller" {
>   name       = "metallb_controller_status"
>   project_id = rancher2_project.utilities.id
>   group_id   = rancher2_project_alert_group.utilities.id
>   workload_rule {
>     workload_id = "metallb-controller"
>   }
> }
>

**Comment by ajchiarello** [comment]
OK - I think I know what is happening. I had the workload_id wrong. It should have been "deployment:metallb-system:metallb-controller"

I guess rancher automatically removes loads with an incorrect workload_id, even though it lets the rule be created?

**Comment by rawmind0** [comment]
I think so @ajchiarello ..

**Comment by ajchiarello** [comment]
Ok. If there is a way to have terraform catch this, that would be good - it's a little confusing to see the rule appear and then clean up. But if it isn't easily checkable, then it is what it is. Thanks!

**Comment by rawmind0** [comment]
Error should be checked by the API, not easy to check from terraform. Please, reopen issue if needed.
