### ISSUE TITLE
[Feature Request] Add support for Azure managed disks

### ISSUE THREAD

**Issue by acastle** [rancher/terraform-provider-rancher2#166]
Currently the azure_config block for the rancher2_node_template resource does not allow for creating VMs with Azure Managed Disks. Support for managed disks from the UI / API appears to have been added with the v2.3.0 release.

For reference:
https://github.com/rancher/rancher/issues/15788
https://github.com/rancher/rancher/issues/22074

**Comment by rawmind0** [comment]
PR merged into master. Please reopen issue if needed
