### ISSUE TITLE
New resource: "rancher2_token"

### ISSUE THREAD

**Issue by headcr4sh** [rancher/terraform-provider-rancher2#169]
I am in need to automatically create Rancher 2 tokens to hook my Rancher 2 installation into some automation mechanisms.

The API that I am talking about can be found under `/v3/tokens` on any Rancher 2.x installation.

#### Example of possible API usage

```hcl
resource "random_string" "bot_password" {
  length  = 16
   special = true
}

resource "rancher2_user" "bot" {
   username    = "r-bot"
   name        = "Your friendly Rancher2 bot"
   description = "Cattle-Bot"
   password    = random_string.bot_password.result
}
 
resource "rancher2_token" "bot" {
   user_id     = rancher2_user.bot.id
   description = "Token to be used by the bot application to control the bot user"
 }
```

#### Possbile implementation

Our own in-house developed (and now deprecated) Rancher 2 provider plugin offered this functionality and it is the final blocker that keeps us from fully adopting the official Rancher 2 provider plugin.

I assume it might be rather easy to copy my code over (with just some minor tweaks) to be used here:
https://github.com/iplabs/terraform-provider-rancher2/blob/master/rancher2/resource_token.go

**Comment by rawmind0** [comment]
Hey @headcr4sh, is you code working?? 

May be i'm missing something, but afaik you can't manage tokens for other users on rancher2, just your own tokens. When you create a token by the rancher2 API, no matter what you set at `user_id`, the token is created with the user id of the user that do the request.

To manage other users tokens, tf provider would need to relogin as other users to manage them. Username and password or user token would be needed to define other user token. Then, tf provider would relogin as proper user, create token and relogin back as provider user. Same for read, update and/or delete operation. Not sure that it's a good way.

BTM, i'm finishing a PR implementing Rancher2 tokens but just to manage "current" user tokens. It could be useful with terraform modules.

**Comment by headcr4sh** [comment]
> May be i'm missing something, but afaik you can't manage tokens for other users on rancher2, just your own tokens. When you create a token by the rancher2 API, no matter what you set at user_id, the token is created with the user id of the user that do the request.

Mh... I am not quite sure if the code works as supposed to. I was indeed only creating tokens for the currently logged in user...

**Comment by rawmind0** [comment]
Merged PR to provide rancher2_token resource
