### ISSUE TITLE
Invalid default values for Openstack Cloud Provider load balancer monitor

### ISSUE THREAD

**Issue by davidarcher** [rancher/terraform-provider-rancher2#17]
When using this provider to create a rancher-launched cluster in OpenStack, the default values that are set for load_balancer monitor_delay and monitor_timeout are invalid. Specifically, these values are being set as integers with defaults of "60" and "30" respectively. These DO NOT work as they should be a duration string with a time unit "1m" and "30s".

Related issue in main rancher repo:
https://github.com/rancher/rancher/issues/14577

**Comment by rawmind0** [comment]
@davidarcher , thanks for the feedback.

Submitted PR #21 to fix it.

**Comment by rawmind0** [comment]
Related rancher issue rancher/rancher#14577 , would be addressed on rancher v2.2.4. Once rancher v2.2.4 is released, rancher2 provider would be released with the fix included.

**Comment by rawmind0** [comment]
PR #21 is included in new release [v1.2.0](https://github.com/terraform-providers/terraform-provider-rancher2/releases/tag/v1.2.0)

Please, reopen issue if needed.
