### ISSUE TITLE
New Resource/Datasource: rancher2_node

### ISSUE THREAD

**Issue by DJAyth** [rancher/terraform-provider-rancher2#171]
Thought to put this out there as it's a major issue for me now. There is no way of interacting with the nodes of the K8S/Rancher cluster, specifically I want the IP addresses for the nodes, however, more information can be useful.

**Comment by mc-meta** [comment]
We are automating vsphere backed clusters managed by rancher and for ingress part we need workers ip address to form some needed resources (i.e external load balancers). There's an alternative way to get this info indirectly from cloud providers, but that may eventually pose idempotency problems for some resources and moreover will be cloud provider specific.

Having a native method to look at node properties will simplify code to a great extent while providing more robust semantics.

**Comment by caiconkhicon** [comment]
Same problem here. The `rancher2_cluster` resource does not wait until the cluster is ready, so there's no information about the nodes.

**Comment by DJAyth** [comment]
There is a cluster sync resource that you can use after you create the cluster, that will wait for the cluster to complete, but again it doesn't pull back much info about the cluster.

**Comment by kkaempf** [comment]
closing stale issues.
If the problem still persists in Rancher v2.8.0 pleas reopen.
