### ISSUE TITLE
Required/optional attributes inconsistencies for `rancher2_etcd_backup`

### ISSUE THREAD

**Issue by rossigee** [rancher/terraform-provider-rancher2#180]
Hi,

I copied and pasted the example HCL from the documentation page, and amended it to my needs:

https://www.terraform.io/docs/providers/rancher2/r/etcdBackup.html

It suggests that `endpoint` is required and that `region` is optional. However, when applying a such a configuration, it suggests that `region` is actually required (and that `folder` is not an attribute as per the docs)...

```
$ terraform apply -target=module.rancher2

Error: Missing required argument

  on modules/rancher2/main.tf line 22, in resource "rancher2_etcd_backup" "backup":
  22:     s3_backup_config {

The argument "region" is required, but no definition was found.


Error: Unsupported argument

  on modules/rancher2/main.tf line 27, in resource "rancher2_etcd_backup" "backup":
  27:       folder = "/production/etcd"

An argument named "folder" is not expected here.
```

**Comment by rossigee** [comment]
I just found this note on a related closed bug...

https://github.com/terraform-providers/terraform-provider-rancher2/issues/111#issuecomment-526240137

This is something that should probably be documented on the resource page for `rancher2_etcd_backup`, as it is not obvious that this resource is only for secondary backups and is a likely source of much confusion/frustration for users who might inadvertently be trying to set their main cluster backup using it, like I was.

I found it especially confusing as when applying this resource without having set anything up in the `etcd` section of the `rancher2_cluster` resource, it claims it will update the retention settings that I made in the cluster page in the UI (i.e. the main backup).

```
Terraform will perform the following actions:

  # module.rancher2.rancher2_etcd_backup.backup will be updated in-place
  ~ resource "rancher2_etcd_backup" "backup" {
        annotations = {
            "lifecycle.cattle.io/create.etcdbackup-controller" = "true"
        }
        cluster_id  = "c-nn2nx"
        filename    = "production-etcd-backups_2019-11-02T03:41:22Z.zip"
        id          = "c-nn2nx:production-etcd-backups"
        labels      = {
            "cattle.io/creator" = "norman"
        }
        manual      = false
        name        = "production-etcd-backups"

      ~ backup_config {
            enabled        = true
            interval_hours = 12
          ~ retention      = 6 -> 14

            s3_backup_config {
                access_key  = (sensitive value)
                bucket_name = "backups-sg-blahblah"
                endpoint    = "s3.ap-southeast-1.amazonaws.com"
                region      = "ap-southeast-1"
                secret_key  = (sensitive value)
            }
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

I've since found the reference for the 'etcd' section buried deep in the resource page for `rancher2_cluster`, but only as a result of reading the note on the closed bug report.

**Comment by rawmind0** [comment]
Hi @rossigee , thanks for the feedback. Submitted PR updating `rancher2_etcd_backup` documentation as you suggested.

**Comment by rawmind0** [comment]
Merged PR to address this issue
