### ISSUE TITLE
feature request: Azure cloud provider loadBalancerSku

### ISSUE THREAD

**Issue by ajchiarello** [rancher/terraform-provider-rancher2#183]
In the rancher2_cluster resource, under the rke_config>cloud_provider>azure_cloud_provider, please allow for setting the loadBalancerSku setting (documented here: https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/docs/cloud-provider-config.md)

Thanks

**Comment by ajchiarello** [comment]
It looks like the dependency has been met - should I look for this in the next release?

**Comment by rawmind0** [comment]
Feature is added on PR #338 , that is already merged into master. It will be include in the next provider release. Please reopen issue if needed.
