### ISSUE TITLE
rancher2_cluster etcd_backup access denied

### ISSUE THREAD

**Issue by drpebcak** [rancher/terraform-provider-rancher2#184]
I'm getting this error when trying to configure s3 backups for etcd in a cluster at the same time I am creating the cluster:

`Unable to validate S3 backup target configration: Access Denied`

Here is my `rancher2_cluster` resource:
```hcl
resource "rancher2_cluster" "cluster" {
  name        = "${local.name}"
  description = "Terraform managed RKE cluster"

  rke_config {
    kubernetes_version = "v1.15.5-rancher1-2"
    cloud_provider {
      name = "aws"
    }

    services {
      etcd {
        backup_config {
          enabled        = true
          interval_hours = 6
          retention      = 12
    
          s3_backup_config {
            access_key  = aws_iam_access_key.etcd_backup_user.id
            bucket_name = aws_s3_bucket.etcd_backups.id
            endpoint    = "s3.${aws_s3_bucket.etcd_backups.region}.amazonaws.com"
            region      = aws_s3_bucket.etcd_backups.region
            secret_key  = aws_iam_access_key.etcd_backup_user.secret
          }
        }
      }
    }
  }
}
```

I'm using terraform `0.12.3` and rancher2 provider `1.6.0`. My rancher server is HA, running `2.3.2`

The first apply fails but the second one succeeds. I've also tried adding `depends_on = [aws_iam_user_policy.etcd_backup_user, aws_s3_bucket.etcd_backups, aws_iam_access_key.etcd_backup_user]` etc... to my `rancher2_cluster` just to ensure that all those resources actually are created before the cluster, but it makes no difference.

**Comment by serverbaboon** [comment]
Not sure if it makes a difference but we are pretty much doing the same thing but we have already created the bucket as a global resource in a separate Terraform Job and we configure the the clusters to backup to a different folder.  I think your sample Terraform code in your repo  also creates the bucket at the same time?

We do also  use iam roles attached to the ec2 instances but not sure that would make a difference

**Comment by drpebcak** [comment]
@serverbaboon in the past I have done it that way as well with no issue. Currently I'm trying to create the bucket and user in the same TF run.

It works if I use the separate `rancher2_etcd_backup` resource to set up the backup, but that seems like it shouldn't be necessary.

**Comment by serverbaboon** [comment]
ok , did think that would be the case after some thought , but I had already posted.

I am a little unsure on some of the dependency ordering as well, I am investigating an app deployment that has just started failing with a name space issue when the same terraform script also creates the target namespace the app is deployed to.

I have not attempted the depends on yet, but I don't feel should need too really.

**Comment by kkaempf** [comment]
closing stale issues.
If the problem still persists in Rancher v2.8.0 pleas reopen.
