### ISSUE TITLE
resource that allows running arbitrary manifests

### ISSUE THREAD

**Issue by drpebcak** [rancher/terraform-provider-rancher2#187]
It would be super useful to be able to essentially `kubectl apply` arbitrary manifests to managed clusters using the rancher2 provider - this would allow doing things like installing cert-manager from static manifests while leveraging `rancher2_namespace` to be able to put it in a project.

**Comment by junkiebev** [comment]
I would like this as well. In the current setup, I'm having to call other providers because I'm unable to get coverage under the rancher2 provider for things like flows and outputs.

**Comment by kkaempf** [comment]
closing stale issues.
If the problem still persists in Rancher v2.8.0 please reopen.

**Comment by drpebcak** [comment]
this is not related in any way to the rancher 2.8.0 release.. and it is still needed
