### ISSUE TITLE
Cannot pass ISTIO app answers in Cluster Creation Resource

### ISSUE THREAD

**Issue by serverbaboon** [rancher/terraform-provider-rancher2#188]
The ability to enable istio on the creation of a cluster using the rancher2_cluster resource was introduced in provider 1.6 just like the existing enable_cluster_monitoring feature.

However unlike the monitoring feature you are unable to pass a set of answers for customising the Istio application such as Load balancer, pilot tracing levels and group access. 

With the monitoring feature you get to customise the settings for your use case and Rancher manages the name creation dependencies etc.

The lack of this feature means using the application resource and the name resource to install a customised istio which does work but I have experienced  a couple of occasions where the application deployment starts before the namespace has been created. IT also means that to be safe/cautious I need add a lifecycle ignore to the rancher2_cluster resource to ignore the enable_istio setting.

**Comment by rawmind0** [comment]
@serverbaboon , the way to properly install istio has been updated. Please take a look at https://github.com/rancher/terraform-provider-rancher2/issues/226#issuecomment-654468248

Also updated at provider docs [rancher2_cluster examples](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster#example-usage) `Creating Rancher v2 RKE cluster enabling/customizing monitoring and istio`

Please reopen issue if needed.
