### ISSUE TITLE
ssh_key in nodes of rke_config is empty in terraform.tfstate

### ISSUE THREAD

**Issue by sriharsha99** [rancher/terraform-provider-rancher2#192]
# Create a new rancher2 imported Cluster
resource "rancher2_cluster" "foo-imported" {
  name = "foo-imported"
 description = "Foo rancher2 imported cluster"
  rke_config {
    nodes {
      address = "XXXXXXXXXXXXXXXXXXX"
      user = "barkurus"
      role = ["controlplane",  "etcd", "worker"]
      ssh_key = "ssh-key"
      ssh_key_path = "/home/harsha/roche/git_repo/xxxx/scripts/rancher"
    }
  }
}
still in terraform.tfstate i am getting ssh_key as empty:
   "rke_config.0.nodes.0.hostname_override": "",
                            "rke_config.0.nodes.0.internal_address": "",
                            "rke_config.0.nodes.0.labels.%": "0",
                            "rke_config.0.nodes.0.node_id": "",
                            "rke_config.0.nodes.0.port": "22",
                            "rke_config.0.nodes.0.role.#": "3",
                            "rke_config.0.nodes.0.role.0": "controlplane",
                            "rke_config.0.nodes.0.role.1": "etcd",
                            "rke_config.0.nodes.0.role.2": "worker",
                            "rke_config.0.nodes.0.ssh_agent_auth": "false",
                            "rke_config.0.nodes.0.ssh_key": "", 

Even if i copy the private key content in ssh_key i can see the above empty field

**Comment by rawmind0** [comment]
@sriharsha99, are you trying to use an imported or a custom cluster?? None of these options support `nodes` info. [tf cluster examples](https://www.terraform.io/docs/providers/rancher2/r/cluster.html#example-usage)

For imported clusters you shouldn't specify any rke config, just the cluster name. It's supposed that k8s cluster is already up and running and you just need the command to be executed on k8s cluster to be managed by Rancher. Once the cluster is created with tf, you could get `command`, `insecure_command` and/or `manifest_url` from [tf attributes](https://www.terraform.io/docs/providers/rancher2/r/cluster.html#attributes)

For custom clusters, there are 2 options:
- nodes are deployed by yourself. Once the cluster is created you need [node_command](https://www.terraform.io/docs/providers/rancher2/r/cluster.html#node_command) that is generated as tf attributes, to be executed on your nodes.
- nodes are deployed by Rancher. You need to configure IaaS integration by using [rancher2_node_template](https://www.terraform.io/docs/providers/rancher2/r/nodeTemplate.html) and [rancher2_node_pool](https://www.terraform.io/docs/providers/rancher2/r/nodePool.html)

**Comment by sriharshabarkuru** [comment]
hi @rawmind0, i am not trying to import the cluster. i am trying to create the cluster from rancher2 provider. so i have given the nodes info in rke_config. above code is related to that.

**Comment by sriharshabarkuru** [comment]
i can see ssh-key i am passing is not sent properly.

**Comment by rawmind0** [comment]
Hi @sriharshabarkuru , as explained in previous comment, you shouldn't provide node info to rke config. Try using node_template and node_pools if rancher is deploying nodes

> For custom clusters, there are 2 options:
> * nodes are deployed by yourself. Once the cluster is created you need node_command that is generated as tf attributes, to be executed on your nodes.
> * nodes are deployed by Rancher. You need to configure IaaS integration by using rancher2_node_template and rancher2_node_pool

**Comment by sriharshabarkuru** [comment]
okay. so with rancher2_node_template & rancher2_node_pool i can bring up rke cluster on my onprem vms ?

**Comment by rawmind0** [comment]
Yep, you have a full example on [tf cluster examples](https://www.terraform.io/docs/providers/rancher2/r/cluster.html#example-usage) using node template and node pool

**Comment by sriharshabarkuru** [comment]
okay, In that cluster examples page i can see "rke_config" as one of the option for cluster. what is it used for ?

**Comment by rawmind0** [comment]
`rke_config` is used to create custom cluster on Rancher. Once the cluster is created you need to get `node_command`, that is saved as tf attribute, and execute it on your nodes.

**Comment by sriharshabarkuru** [comment]
"rke_config is used to create custom cluster on Rancher. Once the cluster is created you need to get node_command, that is saved as tf attribute, and execute it on your nodes."
     Regarding this, do i need to ssh into node manually & run the node_command. can't terraform-provider-rancher2 do it for me if i specify the ssh_key to it ?

**Comment by rawmind0** [comment]
Rancher2 provider can't do it for you. You need to do it manually.

**Comment by sriharshabarkuru** [comment]
okay. 
In https://www.terraform.io/docs/providers/rancher2/r/cluster.html#nodes-1
1. what are these **nodes**, where we will use this. 
2. what is the **ssh_key** represents in this nodes

**Comment by rawmind0** [comment]
Nodes information is computed once custom cluster is created. Node info on `rke_config` is not used to deploy the cluster.

**Comment by rawmind0** [comment]
Please, reopen issue if needed.
