### ISSUE TITLE
Move existing namespace to System project

### ISSUE THREAD

**Issue by fmunteanu** [rancher/terraform-provider-rancher2#193]
I'm trying to move an existing namespace to the Rancher system project. Because the namespace exists, running any of the commands will fail:

```
resource "rancher2_namespace" "istio-system" {
  depends_on = [module.istio]
  name       = "istio-system"
  project_id = data.rancher2_project.system.id
}

resource "kubernetes_namespace" "istio-system" {
  depends_on = [module.istio]

  metadata {
    annotations = {
      "field.cattle.io/projectId" = data.rancher2_project.system.id
    }
    name = "istio-system"
  }
}
```

Another solution is to run a `null_resource` and execute a command. However, this implies many manual annotations, which is simply unrealistic. What do you propose as solution?

**Comment by rawmind0** [comment]
Have you tried importing namespace?? https://www.terraform.io/docs/providers/rancher2/r/namespace.html#import

**Comment by fmunteanu** [comment]
@rawmind0, from experience, importing a resource is dangerous for terraform overall state. I really do not want to fiddle with an existing resource through import.

**Comment by fmunteanu** [comment]
I basically want to emulate the UI move of an existing namespace, from `All` to `System`.

**Comment by rawmind0** [comment]
may i misunderstood the issue. Is the namespace created with terraform rancher2 provider or the namespace was created on k8s without project assignment and you want to move it??

**Comment by fmunteanu** [comment]
The namespace was created a while ago with a Helm chart (not with `rancher2` provider). I automated the existing cluster import into Rancher, what is left is the assignment of existing namespaces from `All` to specific projects.

<img width="1257" alt="Screen Shot 2019-11-28 at 1 47 17 PM" src="https://user-images.githubusercontent.com/19806136/69827479-a4e6e600-11e5-11ea-924e-34ee1f8df8c6.png">

**Comment by fmunteanu** [comment]
The reason I need to automate the assignment of existing namespaces is because if I perform the change manually, every time the cluster is updated with a `terraform apply`, all annotations are removed.

**Comment by rawmind0** [comment]
If the namespace already exist and wasn't created with terraform, you'd need to import it before you can manage it from terraform.

The tf file you pasted would fails due to is trying to create a new namespace named `istio-system` that already exist on the k8s cluster

**Comment by fmunteanu** [comment]
In my case the projectid is `All`:
```
$ terraform import rancher2_namespace.foo <project_id>.<namespace_id>
```
How can I get the `<namespace_id>`, if it does not exist?

**Comment by fmunteanu** [comment]
The API output:
```
{
  "actions": {
    "move": "…/v3/cluster/c-f2nqk/namespaces/istio-system?action=move"
  },
  "annotations": {
    "cattle.io/status": "{\"Conditions\":[{\"Type\":\"ResourceQuotaInit\",\"Status\":\"True\",\"Message\":\"\",\"LastUpdateTime\":\"2019-11-09T00:04:16Z\"},{\"Type\":\"InitialRolesPopulated\",\"Status\":\"True\",\"Message\":\"\",\"LastUpdateTime\":\"2019-11-09T00:04:16Z\"}]}",
    "lifecycle.cattle.io/create.namespace-auth": "true"
  },
  "baseType": "namespace",
  "created": "2019-11-09T00:04:15Z",
  "createdTS": 1573257855000,
  "creatorId": null,
  "id": "istio-system",
  "labels": {
    "field.cattle.io/projectId": "p-hxhh5",
    "name": "istio-system"
  },
  "links": {
    "remove": "…/v3/cluster/c-f2nqk/namespaces/istio-system",
    "self": "…/v3/cluster/c-f2nqk/namespaces/istio-system",
    "update": "…/v3/cluster/c-f2nqk/namespaces/istio-system",
    "yaml": "…/v3/cluster/c-f2nqk/namespaces/istio-system/yaml"
  },
  "name": "istio-system",
  "projectId": null,
  "state": "active",
  "transitioning": "no",
  "transitioningMessage": "",
  "type": "namespace",
  "uuid": "77d38475-0284-11ea-9702-02911be2a4c6"
}
```

All I want is to update the `field.cattle.io/projectId` with Terraform.

**Comment by rawmind0** [comment]
`namespace_id` is the namespace id on Rancher. It should be same as namespace name, but you can check through Rancher API. 

BTW, `project_id` can't be "All", it should be on the form `c-xxxxx:p-xxxxx`. You can get project id from Rancher api or using [rancher2_project datasource](https://www.terraform.io/docs/providers/rancher2/d/project.html)

**Comment by fmunteanu** [comment]
@rawmind0 you mean the `namespace_id` is `"id": "istio-system"`?

**Comment by rawmind0** [comment]
> @rawmind0 you mean the namespace_id is "id": "istio-system"?

yes

**Comment by fmunteanu** [comment]
Great. Even if I do the import, how can I set the new label? Importing it will not let me set a new label.

**Comment by rawmind0** [comment]
If you mean label `field.cattle.io/projectId`, it will be updated when you import the namespace due to it's gonna be moved to project_id.

**Comment by fmunteanu** [comment]
The only way I see this happen is with a null_resource:
```
resource "null_resource" "rancher-label-namespace-istio-system" {
  depends_on = [module.istio]

  provisioner "local-exec" {
    command = format("kubectl label --overwrite namespace istio-system field.cattle.io/projectId=%s", data.rancher2_project.system.id)
  }
}
```

In real life, it will run a command similar to:
```
$ kubectl label --overwrite namespace istio-system field.cattle.io/projectId=c-f2nqk:p-pzp6n
error: at least one label update is required
```

It fails because the `:` in front of `p-pzp6n`. I tried everything, simple and double quotes.

**Comment by fmunteanu** [comment]
After further APi checking, while moving from a Project to another, it looks like the `field.cattle.io/projectId` is always in this format:
```
field.cattle.io/projectId=<project_id>
```
So, running the following command should move the namespace into System project:
```
$ kubectl label --overwrite namespace istio-system field.cattle.io/projectId=c-f2nqk:p-pzp6n
```

That is not the case. Before running the command:
```
$ kubectl describe namespace istio-system
Name:         istio-system
Labels:       field.cattle.io/projectId=p-hxhh5
              name=istio-system
Annotations:  cattle.io/status:
                {"Conditions":[{"Type":"ResourceQuotaInit","Status":"True","Message":"","LastUpdateTime":"2019-11-09T00:04:16Z"},{"Type":"InitialRolesPopu...
              field.cattle.io/projectId: c-f2nqk:p-hxhh5
              lifecycle.cattle.io/create.namespace-auth: true
Status:       Active

No resource quota.

No resource limits.

$ kubectl label --overwrite namespaces istio-system field.cattle.io/projectId=p-pzp6n
namespace/istio-system labeled
$ kubectl describe namespace istio-system
Name:         istio-system
Labels:       field.cattle.io/projectId=p-pzp6n
              name=istio-system
Annotations:  cattle.io/status:
                {"Conditions":[{"Type":"ResourceQuotaInit","Status":"True","Message":"","LastUpdateTime":"2019-11-09T00:04:16Z"},{"Type":"InitialRolesPopu...
              lifecycle.cattle.io/create.namespace-auth: true
Status:       Active

No resource quota.

No resource limits.
```

The namespace is still present into All.

<img width="1269" alt="Screen Shot 2019-11-28 at 4 04 17 PM" src="https://user-images.githubusercontent.com/19806136/69831748-d1582d80-11f8-11ea-990d-814b27555a0e.png">

**Comment by fmunteanu** [comment]
I determined how the namespace is moved to the correct project, by setting the `annotation`, `label`, as well the `Projectid`:
```
projectId": "c-f2nqk:p-pzp6n",
```

Namespace in `All`, with `"projectId": null`:
```
{
  "actions": {
    "move": "…/v3/cluster/c-f2nqk/namespaces/istio-system?action=move"
  },
  "annotations": {
    "cattle.io/status": "{\"Conditions\":[{\"Type\":\"ResourceQuotaInit\",\"Status\":\"True\",\"Message\":\"\",\"LastUpdateTime\":\"2019-11-09T00:04:16Z\"},{\"Type\":\"InitialRolesPopulated\",\"Status\":\"True\",\"Message\":\"\",\"LastUpdateTime\":\"2019-11-09T00:04:16Z\"}]}",
    "lifecycle.cattle.io/create.namespace-auth": "true"
  },
  "baseType": "namespace",
  "created": "2019-11-09T00:04:15Z",
  "createdTS": 1573257855000,
  "creatorId": null,
  "id": "istio-system",
  "labels": {
    "field.cattle.io/projectId": "p-pzp6n",
    "name": "istio-system"
  },
  "links": {
    "remove": "…/v3/cluster/c-f2nqk/namespaces/istio-system",
    "self": "…/v3/cluster/c-f2nqk/namespaces/istio-system",
    "update": "…/v3/cluster/c-f2nqk/namespaces/istio-system",
    "yaml": "…/v3/cluster/c-f2nqk/namespaces/istio-system/yaml"
  },
  "name": "istio-system",
  "projectId": null,
  "state": "active",
  "transitioning": "no",
  "transitioningMessage": "",
  "type": "namespace",
  "uuid": "77d38475-0284-11ea-9702-02911be2a4c6"
}
```

Namespace moved through UI, into System:
```
{
  "actions": {
    "move": "…/v3/cluster/c-f2nqk/namespaces/istio-system?action=move"
  },
  "annotations": {
    "cattle.io/status": "{\"Conditions\":[{\"Type\":\"ResourceQuotaInit\",\"Status\":\"True\",\"Message\":\"\",\"LastUpdateTime\":\"2019-11-09T00:04:16Z\"},{\"Type\":\"InitialRolesPopulated\",\"Status\":\"True\",\"Message\":\"\",\"LastUpdateTime\":\"2019-11-09T00:04:16Z\"}]}",
    "lifecycle.cattle.io/create.namespace-auth": "true"
  },
  "baseType": "namespace",
  "created": "2019-11-09T00:04:15Z",
  "createdTS": 1573257855000,
  "creatorId": null,
  "id": "istio-system",
  "labels": {
    "field.cattle.io/projectId": "p-pzp6n",
    "name": "istio-system"
  },
  "links": {
    "remove": "…/v3/cluster/c-f2nqk/namespaces/istio-system",
    "self": "…/v3/cluster/c-f2nqk/namespaces/istio-system",
    "update": "…/v3/cluster/c-f2nqk/namespaces/istio-system",
    "yaml": "…/v3/cluster/c-f2nqk/namespaces/istio-system/yaml"
  },
  "name": "istio-system",
  "projectId": "c-f2nqk:p-pzp6n",
  "state": "active",
  "transitioning": "no",
  "transitioningMessage": "",
  "type": "namespace",
  "uuid": "77d38475-0284-11ea-9702-02911be2a4c6"
}
```

**Comment by fmunteanu** [comment]
How do I set the `projectId` with kubectl? This is not a standard Kubernetes metadata.

**Comment by fmunteanu** [comment]
The  following code will properly migrate an existing namespace (e.g. `istio-system`) to a specific project (e.g. `System`):
```
data "rancher2_project" "system" {
  cluster_id = data.rancher2_cluster.default.id
  name       = "System"
}

resource "null_resource" "rancher-annotate-namespace-istio-system" {
  depends_on = [module.istio]
  triggers = {
    project_id = data.rancher2_project.system.id
  }

  provisioner "local-exec" {
    command = format("kubectl annotate --overwrite namespace istio-system field.cattle.io/projectId=%s", data.rancher2_project.system.id)
  }
}

resource "null_resource" "rancher-label-namespace-istio-system" {
  depends_on = [module.istio]
  triggers = {
    project_id = data.rancher2_project.system.id
  }

  provisioner "local-exec" {
    command = format("kubectl label --overwrite namespace istio-system field.cattle.io/projectId=%s", split(":", data.rancher2_project.system.id)[1])
  }
}
```

**Comment by rawmind0** [comment]
@fmunteanu have you tested the import method?? This is working just fine.

Namespace in `All` means namespace without project assigned, `projectId: null`
Just adding tf file like that
```
resource "rancher2_namespace" "test" {
  name = "test"
  project_id = "<project_id>"
}
```

Import with terraform,
```
terraform import rancher2_namespace.test <project_id>.test
```

The namespace gets imported into tfstate and moved to project_id

**Comment by fmunteanu** [comment]
The above code will work if you change the name, if you use an existing name (which I have to), it will not work.

**Comment by rawmind0** [comment]
You don't need to change the name, just import the namespace and it works fine. Test it.
