### ISSUE TITLE
Terraform provider release

### ISSUE THREAD

**Issue by cgriggs01** [rancher/terraform-provider-rancher2#2]
Hey @rawmind0,

We can use this issue as a thread for releasing this under the HashiCorp ecosystem. 

Are there anymore commits required for the release of this provider?

Thanks,
Chris

**Comment by rawmind0** [comment]
Hey @cgriggs01,

ok, good idea.

Commits are now in sync. No other commit is required.

LGTM

**Comment by cgriggs01** [comment]
@rawmind0,

One last item. For an initial release, it would be preferable if the release version is a full version. instead of a release candidate. I would suggest just v0.2.0 or making the first release be a v1.0.0

That should be the last change before we can build the binary. 

Thanks

**Comment by rawmind0** [comment]
Hey @cgriggs01,

Do you need we update CHANGELOG.md and build last binary with full version from rancher repo?? Do you have any preference on version number??

**Comment by cgriggs01** [comment]
I don't have a preference, I think the HashiCorp general suggestion is to release at 1.0.0. But it's up to you if you'd like to release at an earlier version. 

I can make the PR, just need to know what version number you would like.

**Comment by rawmind0** [comment]
If hashicorp general suggestion is to use v1.0.0, no problem we can follow it. v1.0.0 should be fine.

Thanks

**Comment by cgriggs01** [comment]
Kicking off the binary build now, thanks for your help with this process.

**Comment by cgriggs01** [comment]
Build successful and website documentation is now live. 

Great job! 

I'll now close this issue

**Comment by rawmind0** [comment]
Cool,thanks..
