### ISSUE TITLE
[Feature Request] VSphere - Support Datastore Cluster

### ISSUE THREAD

**Issue by amioranza** [rancher/terraform-provider-rancher2#20]
Hi,
I'm trying to create a new cluster on my VSphere environment and we have a datastore cluster but the node templates only support datastore not datastore cluster. Creating machines in this way we have to do storage migration after the machine was created to not left specific datastore with no free space.

**Comment by rawmind0** [comment]
Hi @amioranza, 

this issue has dependency with https://github.com/rancher/rancher/issues/19706 . Until this issue is not addressed, nothing could be done here.

**Comment by rawmind0** [comment]
Added datastore cluster on tf rpovider v1.7.1 and Rancher v2.3.3

Please, reopen issue if needed
