### ISSUE TITLE
Removing a member role from imported cluster?

### ISSUE THREAD

**Issue by fmunteanu** [rancher/terraform-provider-rancher2#200]
I would like to remove a specific member role, using the rancher2 provider. This is the API:
```
{
  "annotations": {
    "authz.management.cattle.io/creator-owner-binding": "true",
    "lifecycle.cattle.io/create.cluster-crtb-sync_c-d8bjr": "true",
    "lifecycle.cattle.io/create.mgmt-auth-crtb-controller": "true"
  },
  "baseType": "clusterRoleTemplateBinding",
  "clusterId": "c-d8bjr",
  "created": "2019-12-03T01:05:40Z",
  "createdTS": 1575335140000,
  "creatorId": null,
  "groupId": null,
  "groupPrincipalId": null,
  "id": "c-d8bjr:creator-cluster-owner",
  "labels": {
    "cattle.io/creator": "norman"
  },
  "links": {
    "remove": "…/v3/clusterRoleTemplateBindings/c-d8bjr:creator-cluster-owner",
    "self": "…/v3/clusterRoleTemplateBindings/c-d8bjr:creator-cluster-owner",
    "update": "…/v3/clusterRoleTemplateBindings/c-d8bjr:creator-cluster-owner"
  },
  "name": "creator-cluster-owner",
  "namespaceId": null,
  "roleTemplateId": "cluster-owner",
  "type": "clusterRoleTemplateBinding",
  "userId": "u-jgxhf",
  "userPrincipalId": "local://u-jgxhf",
  "uuid": "33911ef3-636d-4a2c-bc1f-fb3f9d91b8ae"
}
```

![User](https://user-images.githubusercontent.com/19806136/70161414-05fd3680-168a-11ea-8c0c-7777d1678fa2.png)

I looked at `rancher2_cluster_role_template_binding` but I cannot find any options to actually delete the member role from cluster.

**Comment by fmunteanu** [comment]
The actual goal is to replace the local `creator-cluster-owner` user with an AD group. I know how to add the AD group but I have difficulty removing the local user.

**Comment by rawmind0** [comment]
Is the `clusterRoleTemplateBinding` managed by terraform??  If yes, you just need remove `rancher2_cluster_role_template_binding` resource from your tf file.

If no, you need to import it first and then remove it.

**Comment by fmunteanu** [comment]
@rawmind0 Raul, I'm using the rancher provider to import an existing cluster. The `token_key` is attached to a local `user` which has very limited permissions:

![rancher-role-importer](https://user-images.githubusercontent.com/19806136/70167633-27afeb00-1695-11ea-8d59-cce36790e4db.png)

Once the cluster imported, `user` is attached as cluster owner. My goal is to replace `user` with an AD group allowing users to manage their imported cluster. So I bind the group with:
```
resource "rancher2_cluster_role_template_binding" "default" {
  depends_on         = [null_resource.rancher-import]
  cluster_id         = rancher2_cluster.default.id
  group_principal_id = format("activedirectory_group://CN=%s,%s", var.rancher_ad_group, var.rancher_ad_search_base[var.environment])
  name               = var.rancher_ad_group
  role_template_id   = "cluster-owner"
}
```

I have no idea how to remove the `user` binding.

**Comment by rawmind0** [comment]
You need to import the `rancher2_cluster_role_template_binding` resource https://www.terraform.io/docs/providers/rancher2/r/clusterRole.html#import

Then you can modify it adding proper `group_principal_id` and removing `user_id` if needed or you create define a new `rancher2_cluster_role_template_binding` resource and remove the old one.
