### ISSUE TITLE
Cannot set deleteNotReadyAfterSecs or "Auto Replace" value in Node Pool Resource

### ISSUE THREAD

**Issue by serverbaboon** [rancher/terraform-provider-rancher2#207]
In the Node Pool resource you are unable to set the "deleteNotReadyAfterSecs" value.

This value looks to be available in the api and is obviously available in the UI and would seem to be a useful item to set when you create a cluster as it effects your recoverability.

**Comment by rawmind0** [comment]
Added PR #208 to fix this issue.

**Comment by rawmind0** [comment]
PR merged into master. Please, reopen issue if needed.
