### ISSUE TITLE
rancher2_auth_config_activedirectory|rancher2_app idempotency problem

### ISSUE THREAD

**Issue by mc-meta** [rancher/terraform-provider-rancher2#210]
rancher2_auth_config_activedirectory is triggering at every run after introducing tls and CA certificates. At each run it tries to change certificate field:

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.rancher_core.rancher2_auth_config_activedirectory.mil will be updated in-place
  ~ resource "rancher2_auth_config_activedirectory" "xxx" {
        access_mode                     = "unrestricted"
        allowed_principal_ids           = [
            "local://user-5wv2h",
            "activedirectory_user://CN=XXXXX XXXXX,OU=XXXXX,OU=XXXX,OU=XX,DC=XX,DC=XXXXXX,DC=XXX",
        ]
        annotations                     = {}
      ~ certificate                     = (sensitive value)
        connection_timeout              = 5000
        default_login_domain            = "ad"
        enabled                         = true
        group_dn_attribute              = "distinguishedName"
        group_member_mapping_attribute  = "member"
        group_member_user_attribute     = "distinguishedName"
        group_name_attribute            = "name"
        group_object_class              = "group"
        group_search_attribute          = "sAMAccountName"
        group_search_base               = "OU=Groups,OU=XXXX,OU=XXXX,OU=XXXXX,DC=XXXX,DC=XXXXX,DC=XXX"
        id                              = "activedirectory"
        labels                          = {
            "cattle.io/creator" = "norman"
        }
        name                            = "activedirectory"
        nested_group_membership_enabled = false
        port                            = 636
        servers                         = [
            "xxx-xxxx-4.xx.xxxxxx.xxx",
        ]
        service_account_password        = (sensitive value)
        service_account_username        = (sensitive value)
        tls                             = true
        type                            = "activeDirectoryConfig"
        user_disabled_bit_mask          = 2
        user_enabled_attribute          = "userAccountControl"
        user_login_attribute            = "sAMAccountName"
        user_name_attribute             = "name"
        user_object_class               = "person"
        user_search_attribute           = "sAMAccountName|sn|givenName"
        user_search_base                = "OU=xx,DC=xx,DC=xxxxxx,DC=xxx"
    }
```

We are currently running a rancher 2.3.3 cluster automated with:

Terraform v0.12.18
+ provider.rancher2 v1.7.1

**Comment by mc-meta** [comment]
As a followup to my previous post, found a workaround to above mismatch, by simply trimming start/end spaces present in submitted certificate string:

```
diff --git a/modules/rancher_core/authentication.tf b/modules/rancher_core/authentication.tf
index bdc02a8..32a7add 100644
--- a/modules/rancher_core/authentication.tf
+++ b/modules/rancher_core/authentication.tf
@@ -12,7 +12,7 @@ resource "rancher2_auth_config_activedirectory" "mil" {
   group_search_base = "OU=Groups,OU=XXXX,OU=XXXXX,OU=XXXXX,DC=ad,DC=XXXX,DC=XXXX"
   port = 636
   tls = true
-  certificate = var.ad_certificate
+  certificate = trimspace(var.ad_certificate)
 
   allowed_principal_ids = data.rancher2_user.admin.principal_ids
```

Wonder if something similar should be managed by rancher2 provider to avoid submitting values that will not converge to what's stored in API objects.

A similar problem is present in `values_yaml` argument for`rancher2_app` resource (fixed as well by using trimspace()) and likely in other places as well. Would be great to possibly fix all discrepancies once and for all.

Thanks!

**Comment by rawmind0** [comment]
@mc-meta , it use to happens on multi line arguments, terraform adds a final `\n` on them. To address it, we've updated some arguments to be base64 encoded instead, but it seems we've missed some as `certificate` on `rancher2_auth_config_activedirectory`. I'll review multiline arguments and i'll add a PR updating them to be base64 encoded.

What i don't get is the issue with `values_yaml` argument for `rancher2_app` resource. It's already a base64 encoded argument, how are you filling it to get diffs?? Yaml content is ending with a `\n`?? In your solution, are you using trimspace() before base64 encoding??

**Comment by mc-meta** [comment]
Hello @rawmind0, content is currently filled with:

`values_yaml = base64encode(trimspace(data.template_file.helm_app_values.rendered))`

and original template currently ends with '\n', but IIRC even if removed was not making any difference, the only thing that worked was trimming spaces from rendered template.

I may privately provide  a testcase in case of need.

**Comment by rawmind0** [comment]
Submitted PR https://github.com/terraform-providers/terraform-provider-rancher2/pull/266 to address this issue.

**Comment by rawmind0** [comment]
Merger PR #266  to trim spaces by default  on multiline arguments. Please, reopen issue if needed

**Comment by mgamperl** [comment]
Hi, 

I am quite new to terraform so please forgive me if I have overlooked anything, but I'm using **no multiline arugments** and still the activedirectory config is **triggering in every run**. I have not found a way to find out why it is triggering, so if there is a way to do that, I'm happy to add some additional info.

```
resource "rancher2_auth_config_activedirectory" "activedirectory" {
  servers = ["xxx"]
  service_account_username = var.adUser
  service_account_password = var.adPassword
  user_search_base = "dc=xxx,dc=xxx"
  group_search_base = "dc=xxx,dc=xxx"
  group_search_filter = " xxx"
  nested_group_membership_enabled = true
  default_login_domain = "xxx"
  port = 389
  access_mode = "required"
  allowed_principal_ids = [
    "activedirectory_group://CN=xxx,OU=xxx,OU=xxx,DC=xxx,DC=xxx"
  ]  
}
```
I'am also using global_role_binding afterwards:
```
resource "rancher2_global_role_binding" "xxx" {
  name = "xxx"
  global_role_id = "admin"
  group_principal_id = "activedirectory_group://CN=xxx,OU=xxx,OU=xxx,DC=xxx,DC=xxx"
}
```
any help is highly appreciated!
thank you
