### ISSUE TITLE
Cannot add additional template revisions to assigned cluster template

### ISSUE THREAD

**Issue by HighwayofLife** [rancher/terraform-provider-rancher2#211]
When creating a custom cluster using Terraform, I'm unable to add additional template revisions once a cluster has been provisioned and assigned the cluster template.

First created the cluster template resource.
```
resource "rancher2_cluster_template" "demo" {
  name        = "customer-cluster-template-demo"
  description = "Azure Terraform Cluster Demo Template"
  template_revisions {
    name = "V1"
    default = true
    cluster_config {
      rke_config {
...
      }
    }
  }
}
```

After provisioning VM resources and assigning the cluster template to the cluster, I wanted to update that cluster with new rke configurations because the CNI plugin was crashing/failing, I tried to do this by adding a new template_revisions block, since it appears to be of attribute type list.
```diff
resource "rancher2_cluster_template" "demo" {
  name        = "customer-cluster-template-demo"
  description = "Azure Terraform Cluster Demo Template"
  template_revisions {
    name = "V1"
    default = true
    cluster_config {
      rke_config {
...
      }
    }
  }
+ template_revisions {
+   name = "V2"
+   default = false
+   cluster_config {
+     rke_config {
+...
+     }
+   }
+ }
}
```

On Terraform plan, it shows new block to be added and no other changes to the resource. However, upon apply, the following error is returned from the rancher server:
```
Error: Bad response statusCode [422]. Status [422 Unprocessable Entity]. Body: [baseType=error, code=InvalidAction, message=Cannot update the clusterTemplateRevision until Clusters are referring it] from [https://dashboard.<snip>.net/v3/clusterTemplateRevisions/cattle-global-data:ctr-7srn6]
  on cluster.tf line 1, in resource "rancher2_cluster_template" "demo":
   1: resource "rancher2_cluster_template" "demo" {
```

**Comment by bartlomiejjaroszewski** [comment]
@HighwayofLife, did you manage to resolve your issue?

**Comment by rawmind0** [comment]
Submitted PR #224 to address this issue.

**Comment by rawmind0** [comment]
Please, reopen issue if needed.
