### ISSUE TITLE
Unable to destroy cluster (AWS VPC), because of self-referencing Security Group

### ISSUE THREAD

**Issue by datosh** [rancher/terraform-provider-rancher2#212]
Hey, 

I have some trouble creating & destroying clusters in Rancher using Terraform, mainly because of AWS specific issues (I guess). Let me explain my setup:

I have a Rancher server running, and:
1. Use the aws provider to create a new AWS VPC, internet gateway & subnet per K8s cluster
1. Use the rancher2 provider to create cloud credentials, node template (here I leave the security groups empty for Rancher to create them), cluster & node pools

Standing this up works great! No problems here!

When trying to delete everything (simple `terraform destroy`), terraform eventually fails with
```
Error deleting VPC: DependencyViolation: The vpc 'vpc-xxxxxxxxxxxxx' has dependencies and cannot be deleted.
```

After some digging I found out that the Security Group `rancher-nodes` is the dependency that cannot be deleted. This is the one generated by Rancher for the node template. Since the security group references itself in the "Inbound Rules" section it cannot be deleted before all (self referencing) routes are deleted. Since this resource is generated by Rancher (not known to Terraform) it is not possible to clean this one up.

Possible solution I see:

* I explicitly create the security group (with routes) myself, so Terraform is aware of them, and therefore able to delete them. I don't like this approach, since now I am obligated to update the Rancher required rules, if there are changes in future patches.
* Somehow? AUTOMATICALLY import these rules / the security group (make Terraform aware of them), so they can be deleted.

**Comment by fabrinator** [comment]
Hi Datosh,

Did you try to use the meta-argument depends_on to mark explicitly the dependency?

Regards

**Comment by datosh** [comment]
I do use this in other places, but I cannot see how this would help in my situation, since I do not have the resources (Security Group & Routes created by Rancher) available in Terraform, and cannot "depend on" them.

What do you propose I use the `depends_on` on?

**Comment by fabrinator** [comment]
As I understood, your setup is using on the same definition the providers aws and rancher2.

With the aws you are creating the networking resources. So they exists on the tfstate file, as they are  being created by the terraform apply.

So when you are applying the destroy action, it appears that  its trying to delete those networking objects when stills exists some objects on aws. So first you have to put the depends_on on the required resources to delete with a properly order.

In another hand, be sure that you have not created objects attached to that vpc using another definition or using the console, as those objects are not being created with that run.

**Comment by datosh** [comment]
> In another hand, be sure that you have not created objects attached to that vpc using another definition or using the console, as those objects are not being created with that run.

That's exactly the problem, and I tried to explain this in my initial post:

> This is the one **generated by Rancher** for the node template.

Rancher creates AWS resources (AWS routing table routes) in order to allow communication between the Nodes. These are **not generated by Terraform**, and therefore Terraform is not able to remove those, since it does not know about them.

**Comment by rawmind0** [comment]
> I have a Rancher server running, and:
> 1. Use the aws provider to create a new AWS VPC, internet gateway & subnet per K8s cluster
> 1. Use the rancher2 provider to create cloud credentials, node template (here I leave the security groups empty for Rancher to create them), cluster & node pools
>
> Standing this up works great! No problems here!
>
> When trying to delete everything (simple `terraform destroy`), terraform eventually fails with
> ```
> Error deleting VPC: DependencyViolation: The vpc 'vpc-xxxxxxxxxxxxx' has dependencies and cannot be deleted.
> ```

@datosh , it seems that the error is caused due to tf eventually is trying to remove aws vpc before  removing its dependencies. I'm guessing that your tf definition with aws resources only is working fine creating and destroying. As @fabrinator  has commented, using the meta-argument `depends_on = aws_resources` on the `rancher2_node_template` and the `rancher2_cluster` resources should assure the deletion of them before delete aws vpc.

**Comment by iTaybb** [comment]
In my case, the problem was not a self-refering SG, but a LB that was stuck on deletion state (also because of some SG reference stuff). The default type of LB is Classic LB in AWS, so I switched to NLB and it solved my issue.

It might not be your case though.

**Comment by rawmind0** [comment]
Please, reopen issue if needed.
