### ISSUE TITLE
Allow DigitalOcean Cluster Creation 

### ISSUE THREAD

**Issue by zolty** [rancher/terraform-provider-rancher2#217]
rancher2_cluster seems to be missing support for digital ocean based droplets. It seems like adding support should be easier since the rancher2_node_template does contain undocumented support for do. 
https://github.com/terraform-providers/terraform-provider-rancher2/blob/master/rancher2/resource_rancher2_cluster.go

**Comment by rawmind0** [comment]
@zolty , may be i'm missing something, but i don't fully understand this issue. 

`rancher2_cluster` already supports cluster creation on Digital Ocean. It can be done using [digitalocean_config](https://www.terraform.io/docs/providers/rancher2/r/nodeTemplate.html#digitalocean_config-1) (already documented) on `rancher2_node_template` and `rancher2_node_pool`. 

Could you please clarify this??

**Comment by rawmind0** [comment]
Please reopen issue if needed.
