### ISSUE TITLE
rancher2 provider calls are async, but requesting a way to get the cluster status

### ISSUE THREAD

**Issue by bensonarokiadoss** [rancher/terraform-provider-rancher2#219]
rancher2 provider calls are async, but requesting a way to get the cluster status. so that we can run some post configuration once the cluster is up.

As the underlying infrastructure provision e.g: in AWS would take some time but the terraform calls are async and would return completed. Instead of hardcode wait time can i query for the cluster status and wait for success and then execute post configuration. Alternatively, any existing option solve the problem do let me know.

**Comment by rawmind0** [comment]
@bensonarokiadoss, please take a look to https://github.com/terraform-providers/terraform-provider-rancher2/issues/214#issuecomment-569134051

There is this resource:
https://github.com/terraform-providers/terraform-provider-rancher2/blob/3103513575036e41be3d1143ba192d9d9e22a903/website/docs/r/clusterSync.html.markdown

**Comment by bensonarokiadoss** [comment]
Thanks @rawmind0 that should solve my problem. I will go head and close this out.
