### ISSUE TITLE
Issues creating vsphere credentials

### ISSUE THREAD

**Issue by richardmosquera** [rancher/terraform-provider-rancher2#22]
Terraform v0.11.14
+ provider.rancher2 v1.1.0

I'm getting an error when trying to create vsphere credentials: 

> rancher2_cloud_credential.hkcreds: Creating...
>   driver:                                   "" => "<computed>"
>   labels.%:                                 "" => "<computed>"
>   name:                                     "" => "hkcreds"
>   vsphere_credential_config.#:              "0" => "1"
>   vsphere_credential_config.0.password:     "<sensitive>" => "<sensitive>"
>   vsphere_credential_config.0.username:     "" => "Administrator@vsphere.local"
>   vsphere_credential_config.0.vcenter:      "" => "vcenter.hostname"
>   vsphere_credential_config.0.vcenter_port: "" => "443"
> 
> Error: Error applying plan:
> 
> 1 error occurred:
>         * rancher2_cloud_credential.hkcreds: 1 error occurred:
>         * rancher2_cloud_credential.hkcreds: json: cannot unmarshal number into Go struct field vmwarevsphereCredentialConfig.vcenterPort of type string

The terraform config: 

```
resource "rancher2_cloud_credential" "hkcreds" {
  name = "hkcreds"
  vsphere_credential_config {
    username = "Administrator@vsphere.local"
    password = "<removed>"
    vcenter = "vcenter.hostname"
    vcenter_port = "443"
  }
} 
```

I've also tried removing the port from the terraform config but I get the same error.

**Comment by rawmind0** [comment]
What rancher version are you using??

**Comment by richardmosquera** [comment]
Rancher 2.2.0

**Comment by rawmind0** [comment]
@richardmosquera, are you sure about the rancher version?? It's weird seems a type mismatch. 

I just tested with tf 0.11 and 0.12 on rancher from v2.2.0 to v2.2.3 and works fine for me on all versions...

```
# tf file
resource "rancher2_cloud_credential" "tf-test" {
  name = "tf-test"
  vsphere_credential_config {
    username = "test@vsphere.local"
    password = "testOK"
    vcenter = "vcenter.hostname"
    vcenter_port = "443"
  }
} 

# applying plan
$ terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + rancher2_cloud_credential.tf-test
      id:                                       <computed>
      driver:                                   <computed>
      labels.%:                                 <computed>
      name:                                     "tf-test"
      vsphere_credential_config.#:              "1"
      vsphere_credential_config.0.password:     <sensitive>
      vsphere_credential_config.0.username:     "test@vsphere.local"
      vsphere_credential_config.0.vcenter:      "vcenter.hostname"
      vsphere_credential_config.0.vcenter_port: "443"


Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

rancher2_cloud_credential.tf-test: Creating...
  driver:                                   "" => "<computed>"
  labels.%:                                 "" => "<computed>"
  name:                                     "" => "tf-test"
  vsphere_credential_config.#:              "0" => "1"
  vsphere_credential_config.0.password:     "<sensitive>" => "<sensitive>"
  vsphere_credential_config.0.username:     "" => "test@vsphere.local"
  vsphere_credential_config.0.vcenter:      "" => "vcenter.hostname"
  vsphere_credential_config.0.vcenter_port: "" => "443"
rancher2_cloud_credential.tf-test: Creation complete after 2s (ID: cattle-global-data:tf-test)

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

**Comment by richardmosquera** [comment]
Definitely 2.2.0


Component | Version
-- | --
Cluster | v2.2.0
User Interface | v2.2.19
Helm | v2.10.0-rancher10
Machine | v0.15.0-rancher6-1



Getting the same error trying to apply your config. However, the credential DOES get created in the UI.

**Comment by richardmosquera** [comment]
This is the full rancher.tf file: 


```
provider "rancher2" {
  api_url   = "https://rancher.url.com/v3"
  token_key = "<token>"
}

resource "rancher2_cloud_credential" "tf-test" {
  name = "tf-test"
  vsphere_credential_config {
    username = "test@vsphere.local"
    password = "testOK"
    vcenter = "vcenter.hostname"
    vcenter_port = "443"
  }
}

```

**Comment by rawmind0** [comment]
It's weird, i couldn't reproduce your issue...

Could you please paste content of `https://rancher.url.com/v3/schemas/vmwarevspherecredentialconfig` ??

**Comment by richardmosquera** [comment]
```
{
"baseType": "schema",
"id": "vmwarevspherecredentialconfig",
"links": {
"self": "…/v3/schemas/vmwarevspherecredentialconfig"
},
"pluralName": "vmwarevspherecredentialconfigs",
"resourceFields": {
"password": {
"create": true,
"description": "vSphere password",
"dynamicField": true,
"required": true,
"type": "password",
"update": true
},
"username": {
"create": true,
"default": "",
"description": "vSphere username",
"dynamicField": true,
"required": true,
"type": "string",
"update": true
},
"vcenter": {
"create": true,
"default": "",
"description": "vSphere IP/hostname for vCenter",
"dynamicField": true,
"required": true,
"type": "string",
"update": true
},
"vcenterPort": {
"create": true,
"default": 443,
"description": "vSphere Port for vCenter",
"dynamicField": true,
"required": true,
"type": "int",
"update": true
}
},
"type": "schema",
"version": {
"group": "management.cattle.io",
"path": "/v3",
"version": "v3"
}
}
```

**Comment by richardmosquera** [comment]
Just deployed 2.2.3 on a single host and it worked fine, perhaps I should upgrade and try again with the existing cluster.

**Comment by rawmind0** [comment]
Yes, it seems a type mismatch on vcenterPort...It's weird due to it's working fine for me on v2.2.0..

```
"vcenterPort": {
  "create": true,
  "default": 443,
  "description": "vSphere Port for vCenter",
  "dynamicField": true,
  "required": true,
  "type": "int",
  "update": true
}
# Should be
vcenterPort": {
  "create": true,
  "default": "443",
  "description": "vSphere Port for vCenter",
  "dynamicField": true,
  "required": true,
  "type": "string",
  "update": true
}
```

Could you please update your rancher version to v2.2.3??

**Comment by dan-evolvere** [comment]
this is the same in 2.2.3, I'm using terraform 0.11 as 0.12 doesnt work with rancher2 provider and I also see this with vmwarevsphereConfig.cpuCount in a node template.
Note; the resources are actually being created (both the node template and the credential) but produce the error on the cli.

**Comment by dan-evolvere** [comment]
For completeness, rancher version info;

Component | Version
-- | --
Rancher | v2.2.3
User Interface | v2.2.41
Helm | v2.10.0-rancher10
Machine | v0.15.0-rancher6-1


also, see output below from schema endpoint;

{
"baseType": "schema",
"id": "vmwarevspherecredentialconfig",
"links": {
"self": "…/v3/schemas/vmwarevspherecredentialconfig"
},
"pluralName": "vmwarevspherecredentialconfigs",
"resourceFields": {
"password": {
"create": true,
"description": "vSphere password",
"dynamicField": true,
"required": true,
"type": "password",
"update": true
},
"username": {
"create": true,
"default": "",
"description": "vSphere username",
"dynamicField": true,
"required": true,
"type": "string",
"update": true
},
"vcenter": {
"create": true,
"default": "",
"description": "vSphere IP/hostname for vCenter",
"dynamicField": true,
"required": true,
"type": "string",
"update": true
},
"vcenterPort": {
"create": true,
"default": 443,
"description": "vSphere Port for vCenter",
"dynamicField": true,
"required": true,
"type": "int",
"update": true
}
},
"type": "schema",
"version": {
"group": "management.cattle.io",
"path": "/v3",
"version": "v3"
}
}

also, this is the schema for cpuCount on the vmwarevsphereconfig schema;

cpuCount": {
"create": true,
"default": 0,
"description": "vSphere CPU number for docker VM",
"dynamicField": true,
"type": "int",
"update": true
},

**Comment by rawmind0** [comment]
These fields should be string type. 
@dan-evolvere, @richardmosquera, Is your rancher v2.2.x a fresh install or an upgraded system?? If it's upgraded, from which version you upgraded it??

There was a type update at some node drivers and it seems there is an schema update issue if the system is updated, https://github.com/rancherlabs/rancher-security/issues/145 

@richardmosquera, have you already upgraded the system to v2.2.3?? If not, could you please disable vsphere driver before update??

**Comment by dan-evolvere** [comment]
This was an upgrade from 2.2.x, I can’t remember which right now.

**Comment by rawmind0** [comment]
Thanks @dan-evolvere ... Do you remember if it was an RC version??

**Comment by dan-evolvere** [comment]
There was an RC version in the upgrade path previously, but not most recently

**Comment by rawmind0** [comment]
That's what i guessed..thanks @dan-evolvere..

Fields should be string in all versions, it seems that issue is coming from rancher on upgrade path from some 2.2.x RC versions. Working to solve that.

**Comment by dan-evolvere** [comment]
Awesome, thanks

**Comment by richardmosquera** [comment]
Just to add, Ive tested on a newly installed 2.2.0 and it works as intended. 

On the 2.2.0 cluster where it doesn't work it was upgraded from the RC version.

**Comment by rawmind0** [comment]
Thanks @richardmosquera. The issue occurs if the system was updated from 2.2.x RC versions.
 
As workaround, to force schema update on node driver, you could delete vsphere driver from rancher UI "node-drivers" section and restart rancher server. The schema willl be updated, fields should be string type and provider should work as expected.

**Comment by dan-evolvere** [comment]
thanks @rawmind0 that did the trick! working perfectly now

**Comment by richardmosquera** [comment]
also worked for me @rawmind0. thanks!

**Comment by rawmind0** [comment]
Please reopen issue if needed.
