### ISSUE TITLE
Creating a cluster from custom nodes - lack of examples

### ISSUE THREAD

**Issue by justinhauer** [rancher/terraform-provider-rancher2#220]
## Description:
I cannot seem to find a good example that shows creating a cluster from custom nodes (nodes that already exist). I can do this through the UI and I get a shell script that I run on each individual node by SSH'ing to them and 'bootstrapping' them to the cluster.

### Not entirely relevant but worth mentioning: 
These are rancherOS vms created in Azure through terraform as well (This documentation is also lacking/could be more robust)

### My question:
In the following example, the[ documentation ](https://www.terraform.io/docs/providers/rancher2/r/cluster.html#nodes)states that the sub-attribute of RKE_CONFIG is a list (which makes sense, the list of vms you will boot strap with either master + etcd or worker roles)
If you look in the documentation on nodes, there are additional attributes. There is no example of this, but what should be listed in the nodes fields, is it a list of maps? (such as what I have listed below?)
```
resource "rancher2_cluster_template" "foo" {
  name = "foo"
  members {
    access_type = "owner"
    user_principal_id = "local://user-XXXXX"
  }
  template_revisions {
    name = "V1"
    cluster_config {
      rke_config {
        nodes{[{address = "1.2.3.4", other_thing = 23}, (address2 = "2.3.4.5", other_attribute = "another value"}]
        }

      }
    }
    default = true
  }
  description = "Test cluster template v2"
}
```

**Comment by rawmind0** [comment]
@justinhauer, create a cluster with custom nodes from terraform, works in the same way of doing it from the rancher UI, you don't need to fill `nodes` argument . 

Once you create an rke cluster from terraform, you get the [`node_command`](https://www.terraform.io/docs/providers/rancher2/r/cluster.html#node_command) attribute. You just need to get the `node_command`, add the roles `--etcd`, `--controlplane`and/or `--worker` and executed it on nodes to bootstrap the cluster. 

BTW, the example you pasted is a `rancher2_cluster_template` nor a `rancher2_cluster`. A cluster template is used to define rke cluster configurations and can be used to deploy clusters.

```
# Create a new rancher2 cluster template
resource "rancher2_cluster_template" "foo" {
  name = "foo"
  members {
    access_type = "owner"
    user_principal_id = "local://user-XXXXX"
  }
  template_revisions {
    name = "V1"
    cluster_config {
      rke_config {
        network {
          plugin = "canal"
        }
        services {
          etcd {
            creation = "6h"
            retention = "24h"
          }
        }
      }
    }
    default = true
  }
  description = "Test cluster template v2"
}
# Create a new rancher2 RKE Cluster from template
resource "rancher2_cluster" "foo" {
  name = "foo"
  cluster_template_id = "${rancher2_cluster_template.foo.id}"
  cluster_template_revision_id = "${rancher2_cluster_template.foo.default_revision_id}"
}
```

**Comment by rawmind0** [comment]
Please reopen issue if needed.
