### ISSUE TITLE
Docs for rancher2_node_template private_key_file are invalid for later versions of Rancher

### ISSUE THREAD

**Issue by kevinkjt2000** [rancher/terraform-provider-rancher2#222]
Thank goodness for https://github.com/rancher/rancher/issues/14330!
The terraform provider docs for rancher2 still mention that a filename is required instead of file contents (under openstack_config). I've been scratching my head for a few hours debugging ssh connections until I read that.

Using rancher/rancher:2.3.3, rancher2 provider version 1.7.1, and terraform 0.12.18.

**Comment by rawmind0** [comment]
Thanks for the feedback @kevinkjt2000 . We'll update doc properly.

**Comment by rawmind0** [comment]
Submitted Pr #265 to address this issue

**Comment by kevinkjt2000** [comment]
Thanks!
