### ISSUE TITLE
Support creation and management of config-maps

### ISSUE THREAD

**Issue by zonywhoop** [rancher/terraform-provider-rancher2#223]
Much like [the secrets resource](https://github.com/terraform-providers/terraform-provider-rancher2/blob/master/website/docs/r/secret.html.markdown), we need a mechanism for managing config-maps.

**Comment by rawmind0** [comment]
Hi @zonywhoop , using [terraform kubernetes provider](https://www.terraform.io/docs/providers/kubernetes/r/config_map.html) is not an option for you??

**Comment by zonywhoop** [comment]
the terraform kubernetes provider is how I'm handling it today, however, that then means that my terraform has 2 providers with 2 different sets of auth credentials.  One for Rancher and one for the k8s cluster directly.  It works but it's not "ideal".

**Comment by marcinbojko** [comment]
Agreed, using the same approach, which is not ideal and antipattern.

**Comment by david-maumenee** [comment]
In my team we want to create rolebinding in namespace just after it's created with rancher provider.
Every one can have specific needs and I think rancher provider's team can't provide all kubernetes provider feature.

The use of two differents provider seems to be mandatory.
But you can use Rancher credential to get your kubernetes cluster credential from a rancher datasource.

In this exemple we only need a rancher_token :

```yaml
provider "rancher2" {
  api_url = var.rancher_url
  token_key = var.rancher_token
}

data "rancher2_cluster" "cluster" {
  name = var.cluster_name
}

locals {
  cluster_config_yaml = yamldecode(data.rancher2_cluster.cluster.kube_config)
}
provider "kubernetes" {
  load_config_file = "false"

  host = local.cluster_config_yaml["clusters"][0]["cluster"]["server"]

  token = local.cluster_config_yaml["users"][0]["user"]["token"]
}```

**Comment by kkaempf** [comment]
closing stale issues.
If the problem still persists in Rancher v2.8.0 please reopen.
