### ISSUE TITLE
rancher2_project_role_template_binding errors on openldap user_principal_id

### ISSUE THREAD

**Issue by ajchiarello** [rancher/terraform-provider-rancher2#225]
When creating a project_role_template_binding, I get an error if I use an openldap user_principal_id. It is successful if I use a local user_principal_id or a user_id. Here's what I get when I apply:

> Terraform will perform the following actions:
> 
>   \# rancher2_project_role_template_binding.sandbox will be created
>   \+ resource "rancher2_project_role_template_binding" "sandbox" {
>       \+ annotations        = (known after apply)
>       \+ group_principal_id = (known after apply)
>       \+ id                 = (known after apply)
>       \+ labels             = (known after apply)
>       \+ name               = "project-owners"
>       \+ project_id         = "c-jj8lz:p-chl97"
>       \+ role_template_id   = "project-owner"
>       \+ user_principal_id  = "openldap_user://templeEduTUNIC=<redacted>,ou=people,dc=temple,dc=edu"
>     }
> 
> Plan: 1 to add, 0 to change, 0 to destroy.
> 
> Do you want to perform these actions?
>   Terraform will perform the actions described above.
>   Only 'yes' will be accepted to approve.
> 
>   Enter a value: yes
> 
> rancher2_project_role_template_binding.sandbox: Creating...
> 
> Error: Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [baseType=error, code=ServerError, message=user.management.cattle.io "templeEduTUNIC=<redacted>,ou=people,dc=temple,dc=edu" not found] from [https://rancher-np.k8s.temple.edu/v3/projectroletemplatebindings]
> 
>   on project.tf line 36, in resource "rancher2_project_role_template_binding" "sandbox":
>   36: resource "rancher2_project_role_template_binding" "sandbox" {
> 
> 
> [terragrunt] 2020/01/14 13:52:30 Hit multiple errors:
> exit status 1
> 

I'm using terraform version 0.12.19, and rancher2 v 1.7.1

**Comment by rawmind0** [comment]
@ajchiarello, it seems that the `user_principal_id` DN has a bad format. The username part doesn't have the field name. The error message is saying that the username is not found.

> user_principal_id = "openldap_user://templeEduTUNIC=,ou=people,dc=temple,dc=edu"

Please, check the `user_principal_id` DN, it should be something like,

```
user_principal_id = "openldap_user://CN=templeEduTUNIC,ou=people,dc=temple,dc=edu"
```

**Comment by ajchiarello** [comment]
@rawmind0 
I had removed the personally identifying info from the username - it is reported in the rancher API as openldap_user://templeEduTUNIC=PersonallyIdentifyingInfo,ou=people,dc=temple,dc=edu.

**Comment by mitchellmaler** [comment]
I am getting this issue as well.
If I create the project role template binding without the user_principal_id it will create fine but have no user linked to it. Now if I set the user_principal_id to what I tried to do on create it will then add it and compute the userid as well. Some reason I can add it afterwards without any changes to the user_principal_id but if I try adding it at the same time as create I get the 500 error.

**Comment by rawmind0** [comment]
@ajchiarello , @mitchellmaler I made some tests and not failing always.  Have the ldap user logged in Rancher before the role binding??

**Comment by ajchiarello** [comment]
@rawmind0 I've had failures with both scenarios. My default setting is "Allow members of Clusters, Projects, plus Authorized Users and Organizations", so they typically can't log in until they've been granted access to something.

**Comment by rawmind0** [comment]
@ajchiarello , not really. If you are using "Allow members of Clusters, Projects, plus Authorized Users and Organizations", users could log to the global section, before you grant access to any cluster or role. 

What i'm trying to figure out, if it's a kind of race condition where the binding is trying to apply before ldap auth is configured or if the user needs to login before can be assigned to a role template binding. Are you configuring ldap auth on the same tf apply?? If so, could you please add to role template binding a dependency on ldap auth ??

**Comment by ajchiarello** [comment]
@rawmind0 - That's not what we are seeing - If we haven't added a user to a cluster or project (or the authorized user list) explicitly, they cannot log in at all, which was our desired pattern. We are permitting login by adding them to the cluster or project they are going to have permissions for. The only time we've seen what you describe is when we allow any valid users to log in.

The ldap auth is not being configured in the same terraform script - it has been configured and running fine all along. Adding an openldap user via the GUI works as expected - it looks up the uid and adds the account to the global users list, after which the user can log in.  But even with users that already exist and have logged in, assigning them new permissions via user_principal_id fails.

**Comment by rawmind0** [comment]
@ajchiarello - what i mean is that if you add ldap user/group to a authorized user list, they can login without access to any clustet/project. 

Anyway, got it your answer, thanks. I'll continue testing it.

**Comment by nickngch** [comment]
I am getting this issue on AD user, and the user hasn't logon to the Rancher before

Terraform file
```
provider "rancher2" {
  api_url    = "https://xxxx.xxxxx.xxxxx.xxxxx"
  access_key = "token-xxxxx"
  secret_key = "xxxxxxxxxxxxxxxxxxxxxxxxxxx"
  insecure = true
}

resource "rancher2_project" "foo" {
  name = "foo"
  cluster_id = "local"
  resource_quota {
    project_limit {
      limits_cpu = "2000m"
      limits_memory = "2000Mi"
      requests_storage = "2Gi"
    }
    namespace_default_limit {
      limits_cpu = "2000m"
      limits_memory = "500Mi"
      requests_storage = "1Gi"
    }
  }
  container_resource_limit {
    limits_cpu = "20m"
    limits_memory = "20Mi"
    requests_cpu = "1m"
    requests_memory = "1Mi"
  }
}


resource "rancher2_project_role_template_binding" "foo" {
  name = "foo"
  project_id = "${rancher2_project.foo.id}"
  role_template_id = "project-owner"
  user_principal_id = "activedirectory_user://CN=adtest,CN=Users,DC=nick,DC=local"
}
```

Error message from terraform

> Error: Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [baseType=error, code=ServerError, message=SAML: Invalid principal type] from [https://nick.support.rancher.space/v3/projectroletemplatebindings]
> 
>   on rancher.tf line 32, in resource "rancher2_project_role_template_binding" "foo":
>   32: resource "rancher2_project_role_template_binding" "foo" {

The configuration seems legit if I compare with the request from browser

`{"type":"projectRoleTemplateBinding","projectId":"local:p-ntlxx","userPrincipalId":"activedirectory_user://CN=adtest,CN=Users,DC=nick,DC=local","roleTemplateId":"project-owner"}`

**Comment by nickngch** [comment]
So it was the token issue; I was using the token from a local user. Works perfectly fine on AD token, thanks @rawmind0

**Comment by lapfrank12** [comment]
This works fine with `group_principal_id` though. I use it to add AD-based groups without issues using the original admin token. Why can't we do the same thing with `user_principal_id`?

Thanks,

**Comment by azbpa** [comment]
Have a similar issue with `ActiveDirectory` and users that never have been logged in (but exsisting in AD):

```
resource "rancher2_cluster_role_template_binding" "cluster-admin-binding" {
  name = "cluster-admin-binding"
  cluster_id = rancher2_cluster.kubernetes_cluster.id
  role_template_id = data.rancher2_role_template.cluster-owner.id
  user_principal_id = "activedirectory_user://CN=User,OU=Generic,OU=Some,DC=test,DC=domain,DC=local"
}
```
Terraform error message:

```
Error: Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [baseType=error, code=ServerError, message=user.management.cattle.io "CN=User,OU=Generic,OU=Some,DC=test,DC=domain,DC=local] from [https://rancher-test.test.domain.local/v3/clusterroletemplatebindings]
```

**Comment by Kyrklund** [comment]
I have tested to add a user to a project with two different tokens in the rancher2 provider.
One from an AD user with admin permissions and the other with the local admin.

I get no error if I use the token from an AD user and the rancher2_project_role_template_binding gets applied as expected.

Could this be the same as that you can't look up users from AD when logged in with the local admin account?

Update:
Can also add that I see the exact same behavior as @mitchellmaler
If I do it in two steps, skipping `user_principal_id` on the first run, it goes through without issues.

my code:
```
resource "rancher2_project_role_template_binding" "owners" {
  name = "owners"
  project_id = rancher2_project.proj.id
  role_template_id = "project-owner"
  #user_principal_id = "activedirectory_user://CN=test-user,OU=Users,OU=Hosting,DC=example,DC=se"
}
```

Update 2:
Tested using a users local ID instead (ex. `user_id = "u-dxy3kmal8j"`) this works as expected, but demands that the users have logged in once.

Also tested adding a group instead, with `group_principal_id` and this also works.
So this is the way we will progress around the issue

**Comment by michalformanek** [comment]
Currently rancher2_project_role_template_binding requires either (user user_id | user_principal_id) or (group group_id | group_principal_id) to be defined. This makes suggested workarounds impossible, because you have to provide some value on the first run. Are there any other ways to create project role template bindings without using local user id?

**Comment by rawmind0** [comment]
> This works fine with group_principal_id though. I use it to add AD-based groups without issues using the original admin token. Why can't we do the same thing with user_principal_id?

@lapfrank12 , this behaviour is coming from Rancher. For security reasons, user_principal info is treated distinct than group principal info for auth providers.

> Could this be the same as that you can't look up users from AD when logged in with the local admin account?

@Kyrklund , yes it's the same. The reason is that local admin doesn't have any AD principal associated so can't access AD for query, just local users

> Tested using a users local ID instead (ex. user_id = "u-dxy3kmal8j") this works as expected, but demands that the users have logged in once.
>
> Also tested adding a group instead, with group_principal_id and this also works.
So this is the way we will progress around the issue

Yes to both. The use of `group_principal_id` is recommended and should work properly , but the use of `user_id` would require that the users have logged in Rancher before. 

> Currently rancher2_project_role_template_binding requires either (user user_id | user_principal_id) or (group group_id | group_principal_id) to be defined. This makes suggested workarounds impossible, because you have to provide some value on the first run. Are there any other ways to create project role template bindings without using local user id?

@michalformanek, the suggested workaround is possible. The way to create project role template bindings without using local `user_id` would be using `group_principal_id` instead

**Comment by kkaempf** [comment]
closing stale issues.
If the problem still persists in Rancher v2.8.0 please reopen.
