### ISSUE TITLE
Import a cluster from azure into rancher.

### ISSUE THREAD

**Issue by ronnie-webb** [rancher/terraform-provider-rancher2#227]
I want to import a cluster from azure via terraform into rancher. Can someone please inform me if this is all needed. This seems very vague. Is there any other config needed? 

```terraform
resource "rancher2_cluster" "foo-imported" {
  name = "foo-imported"
  description = "Foo rancher2 imported cluster"
}
```

**Comment by rawmind0** [comment]
@ronnie-webb , you need to create imported cluster and then execute the generated kubectl manifest on your working cluster. These are available as `command`, `insecure_command` or `manifest_url` [cluster attribute](https://www.terraform.io/docs/providers/rancher2/r/cluster.html#attributes) on tf state. 

Please, take a look to needed steps to import a k8s cluster into rancher, https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/imported-clusters/

**Comment by ronnie-webb** [comment]
@rawmind0 would you happen to know how to retrieve the yaml link from terraform tfstate. 

Thanks for you answer

**Comment by rawmind0** [comment]
Terraform output should do the work, https://www.terraform.io/docs/configuration/outputs.html

**Comment by ronnie-webb** [comment]
Thanks @rawmind0  the command is located here. 

```` terraform
output "command" {
    value = rancher2_cluster.imported-cluster.cluster_registration_token.0.command
} 
````

**Comment by rawmind0** [comment]
Please, reopen issue if needed.
