### ISSUE TITLE
Support GlobalDNS entries/providers

### ISSUE THREAD

**Issue by spencergilbert** [rancher/terraform-provider-rancher2#228]
Currently the provider doesn't have any resource concept of GlobalDNS, either the entries themselves or the providers.

This would dovetail nicely with the pre-existing management of multi-cluster apps

**Comment by rawmind0** [comment]
PR #253 is covering new feature request

**Comment by rawmind0** [comment]
This feature was already added with PR https://github.com/rancher/terraform-provider-rancher2/pull/551

Please, reopen issue if needed
