### ISSUE TITLE
Rancher 2 Cluster Resource - Support localClusterAuthEndpoint

### ISSUE THREAD

**Issue by vsabella** [rancher/terraform-provider-rancher2#23]
It is not possible to configure 
"localClusterAuthEndpoint": {
"enabled": true,
"type": "/v3/schemas/localClusterAuthEndpoint"
},

via the Terraform provider. It defaults to "False" when creating via the UI defaults to "true"

**Comment by rawmind0** [comment]
Added support on PR #28

**Comment by rawmind0** [comment]
PR #28  is included in new release [v1.2.0](https://github.com/terraform-providers/terraform-provider-rancher2/releases/tag/v1.2.0)

Please, reopen issue if needed.
