### ISSUE TITLE
Enable "Istio sidecar auto injection" via namespace resource

### ISSUE THREAD

**Issue by spencergilbert** [rancher/terraform-provider-rancher2#230]
As possible via the UI - it looks like the API call (at least shown in the rancher ui) includes the rancher project ID, however if you try and include just the label on the rancher2_namespace resource it will overwrite/remove the existing project id. Another solution I attempted was providing that label and leveraging the rancher2_project resource but the `id` attribute includes the full cluster:project id's which isn't desired either

`      ~ labels           = {
          - "field.cattle.io/projectId" = "p-bnnrc" -> null
          + "istio-injection"           = "enabled"
        }`

`          ~ "field.cattle.io/projectId" = "p-bnnrc" -> "c-mnhdj:p-bnnrc"
`

**Comment by serverbaboon** [comment]
Are you trying to update an existing namespace or when you create it. We create some default namespaces in our project as below which works, but notice we have to lifecycle ignore the labels...

resource "rancher2_namespace" "myproject_namspace" {

  count       = length(local.namespaces)
  name        = local.namespaces[count.index]
  project_id  = rancher2_project.myproject_project.id
  description = "${var.cluster_name} ${local.namespaces[count.index]} namespace"

  labels = {
    istio-injection = "enabled"
  }

  lifecycle {
    ignore_changes = [
      labels
    ]
  }
}

**Comment by spencergilbert** [comment]
Either to be honest. It would be nice to handle this natively, based on the capabilities in the UI I suspect there's an API endpoint for this

**Comment by rawmind0** [comment]
@spencergilbert , to update namespace project id, you should use `project_id` argument. Instead, namespace istio sidecar auto injection is not available on rancher AP. To enable it, add `istio-injection = "enabled"` and ignore the label is needed.

Thanks @serverbaboon for the attached example.

**Comment by rawmind0** [comment]
Please, reopen issue if needed
