### ISSUE TITLE
Let rancher create tags for subnets on cluster creation in AWS

### ISSUE THREAD

**Issue by ajfriesen** [rancher/terraform-provider-rancher2#232]
AWS still needs tags to be attached to the subnets, when using AWS ELB.
The tags needs to have the cluster id.

Let rancher on cluster creation create the proper tags for the subnet.
https://github.com/rancher/rancher/issues/21751#issuecomment-576734557

**What we do now:**
We are creating a basic vpc network via terraform.
After that we create a k8s cluster via rancher api and terraform.

This works like a charm.
The only problem we face is, that Rancher is not setting the proper tags for the AWS ELB.
We can not set the tag beforehand since the cluster-id is not known before cluster creation.
The tagging could be done on cluster creation since the subnets anyway need to be specified.

My workaround for this is a null resource with a local-exec which needs to be removed manually:

```
#TODO:
# Remove when this issue gets fixed:
# https://github.com/rancher/rancher/issues/21751
resource "null_resource" "resource_tagging" {
  count = var.cluster_az_count
  provisioner "local-exec" {
    command = <<EOF
    export AWS_PROFILE=${var.aws_role_profile}
    aws ec2 create-tags --region ${var.region} --resources ${var.cluster_private_subnets[count.index]} --tags 'Key=kubernetes.io/cluster/${rancher2_cluster.rancher_ec2_cluster.id},Value=owned'
    aws ec2 create-tags --region ${var.region} --resources ${var.cluster_public_subnets[count.index]} --tags 'Key=kubernetes.io/cluster/${rancher2_cluster.rancher_ec2_cluster.id},Value=owned'
    aws ec2 create-tags --region ${var.region} --resources ${aws_security_group.rancher_ec2_cluster_sg.id} --tags 'Key=kubernetes.io/cluster/${rancher2_cluster.rancher_ec2_cluster.id},Value=owned'
    unset AWS_PROFILE
    EOF
  }
}
```

**Comment by johnnymn** [comment]
+1
