### ISSUE TITLE
Logging Add Ability for Edit as File / customTargetConfig

### ISSUE THREAD

**Issue by toddexp** [rancher/terraform-provider-rancher2#235]
It would be great to have the ability to use the cluster logging resource with the "Edit as File" option that is provided in the Rancher ui. I believe in the Rancher api it is called `customTargetConfig`. This would allow additional configuration options to logging resource.

**Comment by johnnymn** [comment]
+1

**Comment by rawmind0** [comment]
Submitted PR #271  to add this feature

**Comment by rawmind0** [comment]
PR merged and will be included on next release. Please, reopen issue if needed.
