### ISSUE TITLE
rancher2_auth_config_openldap.certificate idempotency

### ISSUE THREAD

**Issue by rbq** [rancher/terraform-provider-rancher2#24]
I'm configuring `rancher2_auth_config_openldap` with a `certificate` read from a file (tried heredoc as well, same result) and can't figure out how to format it so that it doesn't get scheduled as changed over and over:

```
Terraform will perform the following actions:

  # rancher2_auth_config_openldap.openldap will be updated in-place
  ~ resource "rancher2_auth_config_openldap" "openldap" {
        access_mode                        = "unrestricted"
        allowed_principal_ids              = []
        annotations                        = {}
      ~ certificate                        = (sensitive value)
      [...]
```

I tried removing the trailing newline, removing line-breaks, putting `\n` in the file, etc., but couldn't find out how to work around whatever transformation is applied there. The fact that it only shows up as `(sensitive value)` isn't helping either.

**Comment by rbq** [comment]
I actually found a solution that works:

```terraform
resource "rancher2_auth_config_openldap" "openldap" {
  certificate = replace(file("./ldap.cert"), "/\\n/", "")
  [...]
}
```

I still think this should probably be handled by the provider?

**Comment by rawmind0** [comment]
Thanks for the feedback @rbq. It's a problem with multiline fields on terraform, that is doing some recoding on create. 

Agreed that this should be handled by the provider. I've submited PR #32 to use base64 encoding for this field. Terraform `filebase64(<FILE>)` could be used to specify file.

**Comment by rawmind0** [comment]
PR that fix this issue is merged. Please, reopen issue if needed.
