### ISSUE TITLE
Delete cluster?

### ISSUE THREAD

**Issue by fmunteanu** [rancher/terraform-provider-rancher2#245]
Hi,

I'm using Terraform to create an EKS cluster and imported into Rancher with the following code:
```
resource "rancher2_cluster" "default" {
  name = "alpha-cluster"
}

resource "null_resource" "cluster-import" {
  depends_on = [rancher2_cluster.default]
  triggers = {
    cluster_id = rancher2_cluster.default.id
  }

  provisioner "local-exec" {
    command = rancher2_cluster.default.cluster_registration_token.0.command
  }
}
```

If I decide to destroy the EKS cluster, how can I remove it from also from Rancher UI, using Terraform? Please write a code example.

**Comment by rawmind0** [comment]
Hi @fmunteanu , removing cluster definition from your tf file and applying plan, should be enough to remove the cluster from Rancher UI
