### ISSUE TITLE
Add mustChangePassword to user ressources

### ISSUE THREAD

**Issue by lucaspouzac** [rancher/terraform-provider-rancher2#247]
Hi, 

Currently, it is not possible to force a user to change his password the first time he connects. 

You should be able to add the `mustChangePassword = true` attribute to allow this.

Thanks.

**Comment by rawmind0** [comment]
Hi @lucaspouzac ,

`mustChangePassword` argument could be added, but if we add it as is, it would be saved at tfstate and  would generate a diff on terraform apply until you set it to false again. When the user changes the password, `mustChangePassword` is set to false in the rancher API but it would remain set to true in tfstate, generating diff on next terraform apply.

As workaround, may be we could add a way to force a user to change his password on first creation, but i don't think could be done on update.

**Comment by rawmind0** [comment]
Please, reopen issue if needed.
