### ISSUE TITLE
rancher2_cluster_logging: fluentd_config>fluent_servers parameter lacks support for multiple endpoints 

### ISSUE THREAD

**Issue by ghost** [rancher/terraform-provider-rancher2#252]
# SUMMARY

resource "**rancher2_cluster_logging**" > argument "**fluentd_config**" > nested argument "**fluent_servers**" is supposed to support a list (see [documentation](https://www.terraform.io/docs/providers/rancher2/r/clusterLogging.html#fluent_servers) ) of endpoints but only accept a map of strings

## ISSUE TYPE

    Bug Report

## VERSIONS

terraform: v0.12.18
rancher provider: 1.7.2

## STEPS TO REPRODUCE

terraform apply the following content:

```
# retrieve cluster ID from rancher
data "rancher2_cluster" "default" {
  name = "myclustername"
}

# Create a new Rancher2 Cluster Logging
resource "rancher2_cluster_logging" "fluentd" {
  name = "default"
  kind = "fluentd"
  cluster_id = data.rancher2_cluster.default.id
  output_flush_interval = 3
  output_tags = {}
  fluentd_config {
    fluent_servers = [
      {
        endpoint = "192.168.0.1:24224"
        hostname = "logs.mydomain.org"
        password = ""
        shared_key = ""
        standby = false
        username = ""
        weight = 100
      },
      {
        endpoint = "192.168.0.1:24225"
        hostname = "logs.mydomain.org"
        password = ""
        shared_key = ""
        standby = false
        username = ""
        weight = 100
      },
    ]
    enable_tls     = false
    certificate    = ""
    compress       = false
  }
}
```

## EXPECTED RESULTS

"terraform apply" command returns no error

## ACTUAL RESULTS

terraform apply returns the following error
```
Error: Unsupported argument

  on main.tf line 23, in resource "rancher2_cluster_logging" "fluentd":
  23:     fluent_servers = [

An argument named "fluent_servers" is not expected here. Did you mean to
define a block of type "fluent_servers"?
```

## COMMENTS

terraform apply the following content returns **NO** error:

```
data "rancher2_cluster" "default" {
  name = var.uks_cluster_name
}

# Create a new Rancher2 Cluster Logging
resource "rancher2_cluster_logging" "fluentd" {
  name = "default"
  kind = "fluentd"
  cluster_id = data.rancher2_cluster.default.id
  output_flush_interval = 3
  output_tags = {}
  fluentd_config {
    fluent_servers {
      endpoint = "192.168.0.1:24224"
      hostname = "logs.mydomain.org"
      password = ""
      shared_key = ""
      standby = false
      username = ""
      weight = 100
    }
    enable_tls     = false
    certificate    = ""
    compress       = false
  }
}
```

**Comment by rawmind0** [comment]
Have you tried??

```
# retrieve cluster ID from rancher
data "rancher2_cluster" "default" {
  name = "myclustername"
}

# Create a new Rancher2 Cluster Logging
resource "rancher2_cluster_logging" "fluentd" {
  name = "default"
  kind = "fluentd"
  cluster_id = data.rancher2_cluster.default.id
  output_flush_interval = 3
  output_tags = {}
  fluentd_config {
    fluent_servers {
        endpoint = "192.168.0.1:24224"
        hostname = "logs.mydomain.org"
        password = ""
        shared_key = ""
        standby = false
        username = ""
        weight = 100
    }
    fluent_servers {
        endpoint = "192.168.0.1:24225"
        hostname = "logs.mydomain.org"
        password = ""
        shared_key = ""
        standby = false
        username = ""
        weight = 100
    }
    enable_tls     = false
    certificate    = ""
    compress       = false
  }
}
```

**Comment by ghost** [comment]
> 
> 
> Have you tried??
> 
> ```
> # retrieve cluster ID from rancher
> data "rancher2_cluster" "default" {
>   name = "myclustername"
> }
> 
> # Create a new Rancher2 Cluster Logging
> resource "rancher2_cluster_logging" "fluentd" {
>   name = "default"
>   kind = "fluentd"
>   cluster_id = data.rancher2_cluster.default.id
>   output_flush_interval = 3
>   output_tags = {}
>   fluentd_config {
>     fluent_servers {
>         endpoint = "192.168.0.1:24224"
>         hostname = "logs.mydomain.org"
>         password = ""
>         shared_key = ""
>         standby = false
>         username = ""
>         weight = 100
>     }
>     fluent_servers {
>         endpoint = "192.168.0.1:24225"
>         hostname = "logs.mydomain.org"
>         password = ""
>         shared_key = ""
>         standby = false
>         username = ""
>         weight = 100
>     }
>     enable_tls     = false
>     certificate    = ""
>     compress       = false
>   }
> }
> ```

I've just tried and this syntax returns no errors, thanks for your help
