### ISSUE TITLE
[Feature request] Support new 2.3.x configurations

### ISSUE THREAD

**Issue by narfeta** [rancher/terraform-provider-rancher2#254]
There are some configurations that cannot be set using terraform

the two that we saw were

- network mtu 
- logging fluentd -> enable json parsing

**Comment by rawmind0** [comment]
2 features included at PR #276  and #271

**Comment by rawmind0** [comment]
PRs merged and will be included on next release. Please, reopen issue if needed.

**Comment by narfeta** [comment]
hi @rawmind0 sorry to bother you, but I'm not seeing how to enable json parsing at fluentd config it seems that the PR 271 only adds the custom_target_config

**Comment by rawmind0** [comment]
@narfeta , you are right, my fault. Submitted PR #282
