### ISSUE TITLE
Support rke_config defining no network CNI

### ISSUE THREAD

**Issue by DH-Rancher** [rancher/terraform-provider-rancher2#255]
Trying to recreate the "Disabling Deployment of a Network Plug-in step"s in https://rancher.com/docs/rke/latest/en/config-options/add-ons/network-plugins/ by implementing the following:
 ```
rke_config {
   network {
      plugin = "none"
   }
```
When applying the config  I get the following:

Error: expected rke_config.0.network.0.plugin to be one of [calico canal flannel weave], got none

if I omit the network part of the config it appears to default to canal.

It would be beneficial to implement this feature to have it in line with what RKE is documented to support.

**Comment by rawmind0** [comment]
PR #258 merged on master. Please reopen issue if needed.
