### ISSUE TITLE
API server does not start because of wrong audit log policy

### ISSUE THREAD

**Issue by czunker** [rancher/terraform-provider-rancher2#256]
Rancher Version: 2.3.5
terraform versions:
Terraform v0.12.20
+ provider.aws v2.48.0
+ provider.rancher2 v1.7.2
k8s version: 1.17.2

I tried to setup a cluster with audit logs enabled, but the api server didn't start.
I used the example provided with [docs](https://www.terraform.io/docs/providers/rancher2/r/cluster.html#example-usage):

    services {
      kube_api {
        audit_log {
          enabled = true
          configuration {
            max_age = 5
            max_backup = 5
            max_size = 100
            path = "-"
            format = "json"
            policy = jsonencode({"rules":[{"level": "Metadata"}]})
          }
        }
      }
    }

This results in the following error:

> I0212 12:31:11.888844    1 server.go:149] Version: v1.16.6
> 
> Error: loading audit policy file: unknown group version field audit.k8s.io/__internal, Kind=Policy in policy: from file /etc/kubernetes/audit-policy.yaml

The audit-policy.yaml looks like this:

    metadata:
      creationTimestamp: null
    rules:
    - level: Metadata

The missing pieces are:

    apiVersion: audit.k8s.io/v1
    kind: Policy

Adding this manually, the api server starts.
I also tried to add it in terraform:

    services {
          kube_api {
                audit_log {
                    enabled = true
                    configuration {
                        max_age = 5
                        max_backup = 5
                        max_size = 100
                        path = "-"
                        format = "json"
                        policy = jsonencode({"rules":[{"level": "Metadata"}], "apiVersion": "audit.k8s.io/v1", "kind": "Policy"})
                    }
                }
          }
    }

But it didn't get passed into the file.

Removing the line

    policy = jsonencode(....

The api server starts and the audit-policy.yaml is generated correctly:

    apiVersion: audit.k8s.io/v1
    kind: Policy
    metadata:
      creationTimestamp: null
    rules:
    - level: Metadata

**Comment by rawmind0** [comment]
Reproduced issue. Submitted PR #257 to fix it.

**Comment by rawmind0** [comment]
@czunker , finally `policy` has been implemented in yaml format. Take a look to example, https://github.com/terraform-providers/terraform-provider-rancher2/pull/257/files#diff-e06e84c47d0fb7fa4ee40b06919f98ecR28

**Comment by rawmind0** [comment]
PR merged and will be included on next release. Please, reopen issue if needed.
