### ISSUE TITLE
NodeTemplate vSphere  boot2dockerUrl argument unknown

### ISSUE THREAD

**Issue by vitalelect** [rancher/terraform-provider-rancher2#26]
Hi,

I seem to have encounter an issue using the rancher2 provider plugin (v1.0 & v1.1) with terraform v0.11.13, I am unable to set the boot2dockerUrl key to a defined string. 
![image](https://user-images.githubusercontent.com/43599833/58893675-e1330100-86f0-11e9-8dec-b73d3efc59a9.png)
I get this error in return
![image](https://user-images.githubusercontent.com/43599833/58893746-0162c000-86f1-11e9-9ce2-37e1a1f2c4f7.png)

If someone has any idea of why or if it's just not supported yet please let me know.
Thanks

**Comment by rawmind0** [comment]
Hi @wilegourd , it's a typo on the doc. Please, try using `boot2docker_url` instead.

**Comment by vitalelect** [comment]
Thanks @rawmind0!

**Comment by rawmind0** [comment]
Fixed on PR #28
