### ISSUE TITLE
[Feature request] Add option to specify default namespace's project in rancher2_cluster

### ISSUE THREAD

**Issue by iTaybb** [rancher/terraform-provider-rancher2#260]
At the moment it's not possible to control the default namespace project through rancher2.
My use case is to set the default namespace in the System project, so I'll have one monitoring instance that monitors everything in my application.

**Comment by rawmind0** [comment]
I think this feature is not available on Rancher. Can you do it from Rancher ui??

**Comment by iTaybb** [comment]
I just looked through the rancher UI & API and it looks like there's no such feature.
But there's a "move namespace's project" UI & API features. So perhaps it's possible to integrate it here.

**Comment by rawmind0** [comment]
@iTaybb , namespace moving is already integrated at the provider: 
- [Importing namespace](https://www.terraform.io/docs/providers/rancher2/r/namespace.html#import) 
- Updating [`project_id`](https://www.terraform.io/docs/providers/rancher2/r/namespace.html#project_id) namespace wiil be moved

**Comment by iTaybb** [comment]
But you need to import the namespace for that.
In case you want to make a one-stop terraform plan that creates a cluster from scratch - that is not possible.

**Comment by rawmind0** [comment]
As mentioned, you can import or create namespaces from terraform provider.  On both cases, namespaces can be moved between projects.

**Comment by iTaybb** [comment]
The problem is that "default" is a namespace that's coming natively with the `rancher2_cluster` object. You cannot create it afterwards as a new namespace, because it already exists

**Comment by rawmind0** [comment]
Yeah, already mentioned that this feature is not currently available on Rancher, not so much can be done here.

**Comment by iTaybb** [comment]
OK then. So not possible at the moment. Thank you very much for your help
