### ISSUE TITLE
rancher2_cluster eks_config not respecting associate_worker_node_public_ip

### ISSUE THREAD

**Issue by chrisreed87** [rancher/terraform-provider-rancher2#262]
Creating an eks cluster using `rancher2_cluster` resource, in the eks_config block, setting `associate_worker_node_public_ip` to `false` is not reflected in the cloudformation template after creating, still defaults to `true`. Have to edit the CF parameter after cluster creation

Provider "rancher2" (terraform-providers/rancher2) 1.7.2

**Comment by rawmind0** [comment]
Reproduced issue. Submited PR #278  to fix the issue.

**Comment by rawmind0** [comment]
PR merged and will be included on next release. Please, reopen issue if needed.
