### ISSUE TITLE
Deleting a cluster returns before cluster is actually deleted

### ISSUE THREAD

**Issue by iTaybb** [rancher/terraform-provider-rancher2#263]
I'm having a terraform script that installs rancher, configures it, and launches a new cluster within it (using cloud credentials).
When destroying the environment, everything gets destroyed in reversed order.
Since upgrading from rancher 2.3.2 to rancher 2.3.4, it seems like the deletion of the `rancher2_cluster` doesn't wait until the cluster is actually deleted. And then terraform goes directly to delete the next object in the queue, Rancher itself, and Rancher doesn't destroy the cluster on time.

In Rancher 2.3.2 it works fine.
In Rancher 2.3.4 and 2.3.5 the issue exists.
I'm using rancher2 provider v1.7.2.

This issue seems related: https://github.com/rancher/terraform-provider-rancher2/issues/44, though by what's written there it seems that the removal is an async operation. In that case, how can I wait gracefully before deleting Rancher itself?

Thanks

**Comment by iTaybb** [comment]
@rawmind0 sorry to bump this, but any idea where might be the issue? I might look into it myself and send a pull request, but I need a lead here

**Comment by rawmind0** [comment]
@iTaybb , i'm not quite sure it's related issue with #44. `clusterStateRefreshFunc` was already updated, it returns `removed` if cluster `IsNotFound` or `IsForbidden` https://github.com/terraform-providers/terraform-provider-rancher2/blob/master/rancher2/resource_rancher2_cluster.go#L313  Could your issue be related with `IsForbidden`??

**Comment by iTaybb** [comment]
After looking again, it seems like the problem is with the `rancher2_node_pool` resource. everytime it gets deletes, it's finishing within 1s (too soon to actually delete the nodes):
```
rancher2_node_pool.aws-controlplane-node[0]: Destroying... [id=c-rmrbx:aws-controlplane-node]
rancher2_node_pool.aws-all-media-node[0]: Destroying... [id=c-rmrbx:aws-all-media-node]
rancher2_node_pool.aws-worker-media-node[0]: Destroying... [id=c-rmrbx:aws-worker-media-node]
rancher2_node_pool.aws-worker-media-node[0]: Destruction complete after 1s
rancher2_node_template.aws-worker-media-node: Destroying... [id=cattle-global-nt:nt-8tsp2]
rancher2_node_pool.aws-all-media-node[0]: Destruction complete after 1s
rancher2_node_template.aws-all-media-node: Destroying... [id=cattle-global-nt:nt-9dmqj]
rancher2_node_pool.aws-controlplane-node[0]: Destruction complete after 1s
```

Is there a way to wait for the node_pool to be deleted before continuing?

**Comment by iTaybb** [comment]
Opened a new issue #275 to better express the issue due to new findings.
