### ISSUE TITLE
Changes to node count in rancher2_cluster aks_config are ignored after initial cluster deployment

### ISSUE THREAD

**Issue by brentwolfram** [rancher/terraform-provider-rancher2#267]
After successfully creating an AKS cluster using rancher2_cluster resource, subsequent changes to "count" in the aks_config block have no effect on cluster node count. The change is accepted during terraform apply with no errors, but actual node count in the cluster is never changed. Changing node count in Edit Cluster via Rancher UI has the desired effect, but the terraform apply with updated count in aks_config block is being ignored.

Provider "rancher2" (terraform-providers/rancher2) 1.7.2

**Comment by rawmind0** [comment]
Reproduced issue. Submited PR #278 to fix the issue.

**Comment by rawmind0** [comment]
PR merged and will be included on next release. Please, reopen issue if needed.
