### ISSUE TITLE
Error: [ERROR] No api_url provided

### ISSUE THREAD

**Issue by hetii** [rancher/terraform-provider-rancher2#268]
Hello I have just bootstrap like this:

    provider "rancher2" {
      alias   = "bootstrap"
      api_url = "https://192.168.80.200"
      bootstrap = true
      insecure  = true
     }

And resources like:

	# Create a new rancher2 Auth Config ActiveDirectory
	resource "rancher2_auth_config_activedirectory" "activedirectory" {
	  # provider                 = rancher2.bootstrap  <- when uncomment all is fine.
	  servers                  = var.ad_servers
	  service_account_username = var.ad_sa_username
	  service_account_password = var.ad_sa_password
	  user_search_base         = var.ad_search_base
	  default_login_domain     = var.ad_default_login_domain
	  depends_on = [
	    vsphere_virtual_machine.vm
	  ]
	}

When provider is not given the misleading error happen:

    2020-02-27T10:23:52.706+0100 [DEBUG] plugin: using plugin: version=5
    2020/02/27 10:23:52 [ERROR] <root>: eval: *terraform.EvalConfigProvider, err: [ERROR] No api_url provided

    Terraform v0.12.20:
    + provider.local v1.4.0
    + provider.null v2.1.2
    + provider.rancher2 v1.7.2
    + provider.tls v2.1.1
    + provider.vsphere v1.16.1

**Comment by fabrinator** [comment]
Did you try?
https://192.168.80.200/v3

Kind Regards

**Comment by rawmind0** [comment]
Hello @hetii , if you want to bootstrap and admin with same tf file, you need to specify 2 provider configurations as explained on [provider docs](https://www.terraform.io/docs/providers/rancher2/index.html#example-usage) 

```
provider "rancher2" {
  alias   = "bootstrap"
  api_url = "https://192.168.80.200"
  bootstrap = true
  insecure  = true
}

# Provider config for admin
provider "rancher2" {
  alias = "admin"
  api_url = "https://192.168.80.200"
  insecure  = true
}
```

And resources like:

```
# Create a new rancher2 Auth Config ActiveDirectory
resource "rancher2_auth_config_activedirectory" "activedirectory" {
  provider                 = rancher2.admin
  servers                  = var.ad_servers
  service_account_username = var.ad_sa_username
  service_account_password = var.ad_sa_password
  user_search_base         = var.ad_search_base
  default_login_domain     = var.ad_default_login_domain
  depends_on = [
    vsphere_virtual_machine.vm
  ]
}
```

**Comment by rawmind0** [comment]
Please, reopen issue if needed

**Comment by john-morsley** [comment]
I'm getting exactly the same thing!
