### ISSUE TITLE
Rancher internal annotations and labels should not be considered "changes"

### ISSUE THREAD

**Issue by pib** [rancher/terraform-provider-rancher2#27]
After creating a rancher2_namespace resource, when I go to apply again, it detects changes that were made by Rancher and wants to remove those changes:

``` Terraform will perform the following actions:
  ~ rancher2_namespace.cert_manager
      annotations.%:                                         "3" => "1"
      annotations.cattle.io/status:                          "{\"Conditions\":[{\"Type\":\"InitialRolesPopulated\",\"Status\":\"True\",\"Message\":\"\",\"LastUpdateTime\":\"2019-06-04T20:34:00Z\"},{\"Type\":\"ResourceQuotaInit\",\"Status\":\"True\",\"Message\":\"\",\"LastUpdateTime\":\"2019-06-04T20:33:59Z\"}]}" => ""
      annotations.lifecycle.cattle.io/create.namespace-auth: "true" => ""
      labels.%:                                              "3" => "1"
      labels.cattle.io/creator:                              "norman" => ""
      labels.field.cattle.io/projectId:                      "p-6js9c" => ""
```

The resource defintion:
```hcl
resource "rancher2_namespace" "cert_manager" {
  name       = "cert-manager"
  project_id = "${local.rancher_system_project}"

  annotations {
    "iam.amazonaws.com/permitted" = "${var.cluster}-cert-manager.*"
  }

  labels {
    "certmanager.k8s.io/disable-validation" = "true"
  }
}
```

**Comment by rbq** [comment]
Terraform's [`ignore_changes`](https://www.terraform.io/docs/configuration/resources.html#ignore_changes) might help as a workaround.

**Comment by pib** [comment]
> Terraform's [`ignore_changes`](https://www.terraform.io/docs/configuration/resources.html#ignore_changes) might help as a workaround.

Ah yes, that will help, though if I need to change one of the annotations or labels that isn't managed by Rancher, it will take some extra work to get Terraform to apply them...

**Comment by pib** [comment]
Actually, I was able to ignore specific attribute changes with:

```tf
  lifecycle {
    ignore_changes = [
      "annotations.%",
      "annotations.cattle.io/status",
      "annotations.lifecycle.cattle.io/create.namespace-auth",
      "labels.%",
      "labels.cattle.io/creator",
      "labels.field.cattle.io/projectId",
    ]
  }
```

Not the greatest solution since it feel pretty fragile and will break as soon as Rancher changes anything about the annotations and labels it uses for metadata, but it at least is a workaround.

**Comment by keymon** [comment]
Similar issue here for a EKS cluster

```
  ~ module.k8s-rancher-sz-1.rancher2_cluster.eks_cluster
      annotations.%:                                                                 "8" => "1"
      annotations.authz.management.cattle.io/creator-role-bindings:                  "{\"created\":[\"cluster-owner\"],\"required\":[\"cluster-owner\"]}" => ""
      annotations.clusterstatus.management.cattle.io/temporary-security-credentials: "true" => ""
      annotations.lifecycle.cattle.io/create.cluster-agent-controller-cleanup:       "true" => ""
      annotations.lifecycle.cattle.io/create.cluster-provisioner-controller:         "true" => ""
      annotations.lifecycle.cattle.io/create.cluster-scoped-gc:                      "true" => ""
      annotations.lifecycle.cattle.io/create.mgmt-cluster-rbac-remove:               "true" => ""
      annotations.provisioner.cattle.io/ke-driver-update:                            "updated" => ""
      labels.%:                                                                      "3" => "2"
      labels.cattle.io/creator:                                                      "norman" => ""
```

Ignored with:

```
  lifecycle {
    ignore_changes = [
      "annotations.authz.management.cattle.io/creator-role-bindings",
      "annotations.clusterstatus.management.cattle.io/temporary-security-credentials",
      "annotations.lifecycle.cattle.io/create.cluster-agent-controller-cleanup",
      "annotations.lifecycle.cattle.io/create.cluster-provisioner-controller",
      "annotations.lifecycle.cattle.io/create.cluster-scoped-gc",
      "annotations.lifecycle.cattle.io/create.mgmt-cluster-rbac-remove",
      "annotations.provisioner.cattle.io/ke-driver-update",
      "labels.cattle.io/creator",
    ]
  }

```

**Comment by keymon** [comment]
Same issue for GKE clusters: 
``` 
~ module.foo.rancher2_cluster.gke_cluster
      annotations.%:                                                           "7" => "1"
      annotations.authz.management.cattle.io/creator-role-bindings:            "{\"created\":[\"cluster-owner\"],\"required\":[\"cluster-owner\"]}" => ""
      annotations.lifecycle.cattle.io/create.cluster-agent-controller-cleanup: "true" => ""
      annotations.lifecycle.cattle.io/create.cluster-provisioner-controller:   "true" => ""
      annotations.lifecycle.cattle.io/create.cluster-scoped-gc:                "true" => ""
      annotations.lifecycle.cattle.io/create.mgmt-cluster-rbac-remove:         "true" => ""
      annotations.provisioner.cattle.io/ke-driver-update:                      "updated" => ""
      labels.%:                                                                "3" => "2"
      labels.cattle.io/creator:                                                "norman" => 
```

**Comment by erSitzt** [comment]
I had the same problem.
`ignore_changes` might help, but i think the provider should ignore all rancher managed annotations/labels

**Comment by erSitzt** [comment]
the above syntax for `ignore_changes` does not work for me with 
```
Terraform v0.12.24
+ provider.rancher2 v1.8.3
```

Does anyone know what the current syntax would look like ?

**Comment by spencergilbert** [comment]
It would be nice to have a built ignore ignore for the `cattle.io` labels/annotations

**Comment by patrickdappollonio** [comment]
Bumping this up, with Terraform 0.12 it's impossible / difficult to handle it, specially if you want to write your own annotations.

Looking at the code, it seems that while the object is defined as `Computed` and `Optional` but it might not be saving / merging the annotation keys when doing `resourceRancher2ClusterRead()`. We define our own custom annotations for other tools to pick up but then on changes, the other Rancher annotations (the `cattle.io` ones) conflict because they weren't declared by us.

`ignore_changes` might work for case scenarios where annotations aren't exposed / touched by devs but when you do, it's impossible to get a no-diff plan.

**Comment by jjno91** [comment]
Same issue here, I'm unable to ignore specific Rancher labels/annotations on Terraform 12.

You can only ignore all annotations and labels:

```
  lifecycle {
    ignore_changes = [
      metadata[0].annotations,
      metadata[0].labels
    ]
  }
```

**Comment by patrickdappollonio** [comment]
Absolutely, and an argument can be done towards not doing this, as stated before, we use annotations and / or labels to add our own information (maybe record keeping, maybe some sort of handling by third party tools), so lifecycle changes to those annotations added by us are important, while still hiding (ignoring?) Rancher standard ones. 

We tried adding ignore changes but it forced us to also declare those annotations in code, which then might not be in sync with what the API actually is supposed to have.

**Comment by rawmind0** [comment]
The issue is related to terraform v0.12.x and the "new" way to manage ignore_changes, https://github.com/hashicorp/terraform/issues/21433

annotations/labels are TypeMap arguments. Solution is not simple due to how terraform schema type map works. No way to set a wildcard to ignore all rancher managed annotations/labels due to map keys are not taken into account on TypeMap `DiffSuppressFunc`. We are working on a better way to manage this, adding a `DiffSuppressFunc` on annotations/labels arguments, limited to ignore changes on annotations/labels that had old value but new value is empty. Any comment, idea or proposal will be very welcomed on that.

In the meantime, there is a workaround to continue using [`ignore_changes`](https://www.terraform.io/docs/configuration/resources.html#ignore_changes) on arguments type map, 

> You can also ignore specific map elements by writing references like tags["Name"] in the ignore_changes list, though with an important caveat: the ignoring applies only to in-place updates to an existing key. Adding or removing a key is treated by Terraform as a change to the containing map itself rather than to the individual key, and so if you wish to ignore changes to a particular tag made by an external system you must ensure that the Terraform configuration creates a placeholder element for that tag name so that the external system changes will be understood as an in-place edit of that key:

That means that to successfully ignore a map element, it should be declared on tf file. The value could be whatever due to tf is going to ignore changes. 

This example should work

```
resource "rancher2_cluster" "cluster-test" {
  # ...
  annotations = {
    "lifecycle.cattle.io/create.cluster-agent-controller-cleanup" = "placeholder"
    "lifecycle.cattle.io/create.cluster-provisioner-controller" = "placeholder"
    "lifecycle.cattle.io/create.cluster-scoped-gc" = "placeholder"   
    "lifecycle.cattle.io/create.mgmt-cluster-rbac-remove" = "placeholder"
  }
  lifecycle {
    ignore_changes = [
      annotations["lifecycle.cattle.io/create.cluster-agent-controller-cleanup"],
      annotations["lifecycle.cattle.io/create.cluster-provisioner-controller"],
      annotations["lifecycle.cattle.io/create.cluster-scoped-gc"],
      annotations["lifecycle.cattle.io/create.mgmt-cluster-rbac-remove"],
    ]
  }
}
```

**Comment by rawmind0** [comment]
Digging a little bit more in the terraform `DiffSuppressFunc` function, i'd like to retract my previous comment ~~No way to set a wildcard to ignore all rancher managed annotations/labels due to map keys are not taken into account on TypeMap `DiffSuppressFunc`~~ It can be done. 

PR #373 is adding a `DiffSuppressFunc` function on annotations/labels arguments to suppress diff if annotations/labels name contains `cattle.io/` OR `rancher.io` AND has old value AND new value is empty. This should address the issue.

**Comment by rawmind0** [comment]
PR merged into master, it will be included on next provider release. Please, reopen issue if needed.

**Comment by gregsidelinger** [comment]
I'm seeing this behavior with terraform 0.13 and the 1.10.4 provider so it looks like this bug is back.

```
  # module.rancher[0].rancher2_project.cloud_platform must be replaced
-/+ resource "rancher2_project" "cloud_platform" {
      ~ annotations               = {
          - "authz.management.cattle.io/creator-role-bindings"                 = jsonencode(
                {
                  - created = null
                }
            )
          - "lifecycle.cattle.io/create.mgmt-project-rbac-remove"              = "true"
          - "lifecycle.cattle.io/create.project-namespace-auth_local"          = "true"
          - "lifecycle.cattle.io/create.project-precan-alert-controller_local" = "true"
        } -> (known after apply)
      ~ cluster_id                = "local" -> (known after apply) # forces replacement
        enable_project_monitoring = false
      ~ id                        = "local:p-bxxgw" -> (known after apply)
      ~ labels                    = {
          - "cattle.io/creator" = "norman"
        } -> (known after apply)
        name                      = "Cloud Platform"
        wait_for_cluster          = false
```

**Comment by rawmind0** [comment]
@gregsidelinger , seems that your resource replace is coming from `~ cluster_id                = "local" -> (known after apply) # forces replacement` not from annotations not labels. Rancher internal annotations and labels diffs are suppressed but they are showed if there is another change on the resource.  Are you computing  `cluster_id` argument value??
