### ISSUE TITLE
rke_config for ingress

### ISSUE THREAD

**Issue by spencergilbert** [rancher/terraform-provider-rancher2#273]
What's the proper formatting to pass the following nginx config into the ingress/options map. All things I've tried have either broken in TF or when rancher tries to install the nginx ingresses.

`log-format-upstream: '{"time": "$time_iso8601", "remote_addr": "$proxy_protocol_addr", "x-forward-for": "$proxy_add_x_forwarded_for", "request_id": "$req_id", "remote_user": "$remote_user", "bytes_sent": $bytes_sent, "request_time": $request_time, "status":$status, "vhost": "$host", "request_proto": "$server_protocol", "path": "$uri", "request_query": "$args", "request_length": $request_length, "duration": $request_time,"method": "$request_method", "http_referrer": "$http_referer", "http_user_agent": "$http_user_agent" }'`

**Comment by brentwolfram** [comment]
Have you tried passing in via [extra_args or options](https://rancher.com/docs/rke/latest/en/config-options/add-ons/ingress-controllers/)?

As an example, I use following to change default HTTP and HTTPS ports:

  ingress {
    provider = "nginx"
    extra_args = {
      http-port = 8080
      https-port = 8443
    }
  }

**Comment by spencergilbert** [comment]
`options       = map("log-format-upstream", "{\"time\": \"$time_iso8601\", \"remote_addr\": \"$proxy_protocol_addr\", \"x-forward-for\": \"$proxy_add_x_forwarded_for\", \"request_id\": \"$req_id\", \"remote_user\": \"$remote_user\", \"bytes_sent\": $bytes_sent, \"request_time\": $request_time, \"status\":$status, \"vhost\": \"$host\", \"request_proto\": \"$server_protocol\", \"path\": \"$uri\", \"request_query\": \"$args\", \"request_length\": $request_length, \"duration\": $request_time,\"method\": \"$request_method\", \"http_referrer\": \"$http_referer\", \"http_user_agent\": \"$http_user_agent\" }")

This has gotten me the closest but when this gets dumped into the nginx's configmap it's not valid

**Comment by rawmind0** [comment]
@spencergilbert, i guess that `log-format-upstream` nginx option is expecting json format. Have you tried, something like that??

```
ingress {
  provider = "nginx"
  options = {
    log-format-upstream = jsonencode({"time": "$time_iso8601", "remote_addr": "$proxy_protocol_addr", "x-forward-for": "$proxy_add_x_forwarded_for", "request_id": "$req_id", "remote_user": "$remote_user", "bytes_sent": $bytes_sent, "request_time": $request_time, "status":$status, "vhost": "$host", "request_proto": "$server_protocol", "path": "$uri", "request_query": "$args", "request_length": $request_length, "duration": $request_time,"method": "$request_method", "http_referrer": "$http_referer", "http_user_agent": "$http_user_agent" })
  }
}
```

**Comment by spencergilbert** [comment]
@rawmind0 doh, that's a great idea. It definitely looks like some quoting issue as it goes through, I'll give that a whirl.

**Comment by spencergilbert** [comment]
@rawmind0 that still seems to be breaking the rke-ingress-controller-deploy-job, i've attached the rke-ingress-controller configmap

the error in the job is still:

`error: error parsing /etc/config/rke-ingress-controller.yaml: error converting YAML to JSON: yaml: line 9: did not find expected key`

[rke-ingress-controller-cm.txt](https://github.com/terraform-providers/terraform-provider-rancher2/files/4377574/rke-ingress-controller-cm.txt)

**Comment by rawmind0** [comment]
@spencergilbert , i think this should be an error with the json format. I made test and is working fine, just check json validation

**Comment by spencergilbert** [comment]
@rawmind0 can you share the config of the test you used?

**Comment by rawmind0** [comment]
@spencergilbert , i used same config but with validated json.

```
ingress {
  provider = "nginx"
  options = {
    log-format-upstream = jsonencode({"time": "$time_iso8601", "remote_addr": "$proxy_protocol_addr", "x-forward-for": "$proxy_add_x_forwarded_for", "request_id": "$req_id", "remote_user": "$remote_user", "bytes_sent": "$bytes_sent", "request_time": "$request_time", "status": "$status", "vhost": "$host", "request_proto": "$server_protocol", "path": "$uri", "request_query": "$args", "request_length": "$request_length", "duration": "$request_time", "method": "$request_method", "http_referrer": "$http_referer", "http_user_agent": "$http_user_agent" })
  }
}
```

**Comment by spencergilbert** [comment]
I swear I tried this exact thing and it didn't work. I'm going to go back and look at it again, I feel like I'm losing my mind here.

**Comment by spencergilbert** [comment]
@rawmind0 could you share the ingress-controller configmap?

**Comment by rawmind0** [comment]
Sorry i tested and deleted the environment, but more or less like yours. I just validated and updated json.

**Comment by rawmind0** [comment]
Please reopen issue if needed
