### ISSUE TITLE
node_template might be deleted before node_pool is finished deletion

### ISSUE THREAD

**Issue by iTaybb** [rancher/terraform-provider-rancher2#275]
In my Terrafrom plan, when destroying, Terraform goes to delete `node_pool` and then deletes `node_template`.

It looks like the `node_pool` deletion returns immediately without waiting:

```
rancher2_node_pool.aws-all-media-node[0]: Destroying... [id=c-rmrbx:aws-all-media-node]
rancher2_node_pool.aws-all-media-node[0]: Destruction complete after 1s
rancher2_node_template.aws-all-media-node: Destroying... [id=cattle-global-nt:nt-9dmqj]
rancher2_node_template.aws-all-media-node: Destruction complete after 1s
```

Then the node pool object is stuck and cannot be deleted:
```
Unable to refresh config for node m-hskqx: nodetemplates.management.cattle.io "nt-9dmqj" not found; waiting on node-controller
```

This issue starting happening in v2.3.3/v2.3.4, so it might be casued by this merge request: https://github.com/rancher/rancher/pull/23718

**Comment by iTaybb** [comment]
As a workaround for the meantime, a sleep can be made after `rancher2_node_pool` removal and before `rancher2_node_template` removal.

Add this under all the `rancher2_node_template` resources:
```
provisioner "local-exec" {
    when    = destroy
    command = "echo Waiting a bit, for node_pool to be deleted properly && sleep 30"
  }
```

**Comment by rawmind0** [comment]
PR #283 should address your issue. Tested and worked fine for me.

**Comment by rawmind0** [comment]
Please, reopen issue if needed.

**Comment by iTaybb** [comment]
Thank you.

**Comment by iTaybb** [comment]
Looks like this still happens on provider v1.8.3 (on rancher v2.4.3). It might be a regression.
It looks like one of my `rancher2_node_template` objects is being deleted before its `rancher2_node_pool` is deleted.
