### ISSUE TITLE
Cannot create rancher2_app with catalog scoped at cluster or project level 

### ISSUE THREAD

**Issue by caiconkhicon** [rancher/terraform-provider-rancher2#281]
I face the exact same issue as #146,  but since it's closed, I create a new issue.

I tried rebuilding the provider locally from `master` but didn't help.
From my code below, you can see that both `template_name` and `catalog_name` have `-`. When I change to `scope = "global"`, it works.

```
resource "rancher2_catalog" "cert-manager" {
  name    = "cert-manager"
  url     = "https://charts.jetstack.io"
  refresh = true
  scope   = "cluster"
  cluster_id = rancher2_cluster.cluster.id
}

resource "rancher2_app" "cert-manager" {
  depends_on       = [rancher2_catalog.cert-manager]
  catalog_name     = rancher2_catalog.cert-manager.name
  name             = "cert-manager"
  description      = "cert-manager is a Kubernetes add-on to automate the management and issuance of TLS certificates from various issuing sources."
  project_id       = rancher2_cluster.cluster.default_project_id
  template_name    = "cert-manager"
  template_version = var.cert_manager_helm_chart_version
  target_namespace = "cert-manager"
  answers = {
    "global.leaderElection.namespace" = "cert-manager"
  }
}
```

**Comment by rawmind0** [comment]
I guess your catalog_name is wrong. It should have a prefix for cluster and project scope catalogs, https://www.terraform.io/docs/providers/rancher2/r/app.html#catalog_name

One of these should address your issue:
* add cluster ID or project ID before name, `c-XXXXX:`<name> or `p-XXXXX:`<name>
* set rancher2_app argument point to catalog id instead name, `catalog_name = rancher2_catalog.cert-manager.id`

**Comment by caiconkhicon** [comment]
@rawmind0 : you are right. Thank you for helping. I will close the issue.
