### ISSUE TITLE
Wait for Rancher API availability with rancher2_bootstrap

### ISSUE THREAD

**Issue by dkeightley** [rancher/terraform-provider-rancher2#284]
In a tightly coupled terraform configuration, resources that create the Rancher nodes and cluster may be followed closely with a `rancher2_bootstrap`.

In these cases, `rancher2_bootstrap` may fail when the Rancher API is still unavailable. To handle this gracefully with an argument or in the provider would some custom logic in between resources to test/sleep until the Rancher API is online.

**Comment by rawmind0** [comment]
This PR add this feature to the provider.

**Comment by rawmind0** [comment]
Please, reopen issue if needed
