### ISSUE TITLE
error addons_include

### ISSUE THREAD

**Issue by nickvth** [rancher/terraform-provider-rancher2#289]
[ERROR] cluster [c-2z7dz] provisioning: [addons] Unable to determine if ./cert-manager/cluster-issuer.yml is a file path or url, skipping

Can't find file to deploy, is local file working or is there only url based support (url is working)?

**Comment by rawmind0** [comment]
Both should work, https://rancher.com/docs/rke/latest/en/config-options/add-ons/user-defined-add-ons/#referencing-yaml-files-for-add-ons

**Comment by nickvth** [comment]
thanks!
