### ISSUE TITLE
rancher2_cluster data source as kubernetes provider input

### ISSUE THREAD

**Issue by iridian-ks** [rancher/terraform-provider-rancher2#290]
I believe this issue is related to this provider and not Terraform in general.

I was using the `terraform_remote_state` to grab the inputs for the `provider kubernetes {}` block. In particular, I was extracting the `host` and `token` attributes from a `data rancher2_cluster {}` block. I have since removed this code and am now, directly, grabbing outputs from `data.rancher2_cluster`.

On the *first* run everything works fine, but after any resources are created this functionality stops working. Here's an example:

```
data "rancher2_cluster" "primary" {
  name = "primary"
}

resource "rancher2_project" "example" {
  ...
}

locals {
  kubeconfig = yamldecode(rancher2_cluster.primary.kubeconfig)
  kube_host  = local.kubeconfig.clusters[0].host
  kube_token = local.kubeconfig.users[0].token
}

provider "kubernetes" {
  host = local.kube_host
  token = local.kube_token
  load_config_file = false
}

resource "kubernetes_deployment" "example" {
 ...
}
```

On the *first* `terraform apply` things go smoothly and the deployment is in the cluster. On a follow-up `destroy`, `plan` or `apply` we get an error on the `Refreshing...` stage.

If you look at the list of `refreshing` resources we see that `rancher2_cluster.primary` is _not_ in the list, which is odd. What's also odd is the `rancher2_project.example` resource *IS* in the `refreshing...` resources and there aren't any errors around that resource.

Again, I don't think this is entirely a Terraform problem as I was using data sources for provider configuration from a different provider and things worked. Even when using provider aliases, Terraform doesn't seem to wait for the data source to refresh. It should know to wait for that but maybe there's something in this provider that's causing it not to work?

I also don't think the issue is related to the yaml operations. If we were seeing this issue *and* seeing the `rancher2_cluster` data source in the refreshing phase then I could see it being related to that.

**Comment by rawmind0** [comment]
I've tested your pasted example.  I've needed to change few things to make it work, may be an error  pasting example??

>   kubeconfig = yamldecode(rancher2_cluster.primary.kubeconfig)

Here you are not referencing the datasource. Also, kubeconfig field should be called `kube_config`

>kube_host  = local.kubeconfig.clusters[0].host
  kube_token = local.kubeconfig.users[0].token

Here, fields are not defined properly by kubeconfig format.

This seems to work properly for me
```
...
data "rancher2_cluster" "primary" {
  name = "primary"
}
...
locals {
  kubeconfig = yamldecode(data.rancher2_cluster.primary.kube_config)
  kube_host  = local.kubeconfig.clusters[0].cluster.server
  kube_token = local.kubeconfig.users[0].user.token
}
...
```

**Comment by iridian-ks** [comment]
Hi @rawmind0 ,  thanks for the super quick response.

Sorry for the silly typos. The actual code is more in-depth and I quickly remade it in the Github ticket.

I did some actual testing in a single file and you're right that things look good. I'm using modules and outputs and depends_on. It looks like the issue is somehow related to a depends_on, but only in the context of a module. Definitely more of a Terraform issue not a provider issue.

I apologize for making the ticket prior to more in-depth testing. Here's the complete example and everything is working as expected.

```
#
# Parent module
#
variable "deps" {
  type    = list(string)
  default = []
}

#
# Rancher Module
#

resource "null_resource" "parent" {
  triggers = {
    depends = join(",", var.deps)
  }
}

variable "enabled" {
  type    = bool
  default = true
}

resource "null_resource" "depends_on" {
  triggers = {
    depends = join(",", [null_resource.parent.id])
  }
}

provider "rancher2" {
  api_url  = "<url>"
  insecure = true
}

data "rancher2_cluster" "primary" {
  count = var.enabled ? 1 : 0
  name  = "primary"
}

locals {
  cluster_id = data.rancher2_cluster.primary[0].id
  kubeconfig = yamldecode(data.rancher2_cluster.primary[0].kube_config)
  kube_host  = local.kubeconfig.clusters[0].cluster.server
  kube_token = local.kubeconfig.users[0].user.token
}

resource "rancher2_project" "example" {
  cluster_id  = local.cluster_id
  name        = "Example"

  depends_on = [null_resource.depends_on]
}

#
# Kubernetes module
#

provider "kubernetes" {
  host             = local.kube_host
  token            = local.kube_token
  insecure         = true
  load_config_file = false
}

resource "kubernetes_namespace" "example" {
  metadata {
    name = "examplespace"

    annotations = {
      "cattle.io/status" = "{}"
      "lifecycle.cattle.io/create.namespace-auth" = "nil"
    }
  }

  lifecycle {
    ignore_changes = [
      metadata[0].annotations["cattle.io/status"],
      metadata[0].annotations["lifecycle.cattle.io/create.namespace-auth"],
    ]
  }
}
```

**Comment by iridian-ks** [comment]
For now, I think things are working if I remove `depends_on`.

I'll reopen if I need to.
