### ISSUE TITLE
Bootstrapping provider results in a timeout error starting v1.8.0

### ISSUE THREAD

**Issue by iTaybb** [rancher/terraform-provider-rancher2#292]
Attempting to bootstrap a new rancher with a provider fails with `Error: Timeout, Rancher is not ready: <nil>` right at the terraform plan step (before applying) on a clean tfstate.
Example config:
```
provider "rancher2" {
  alias     = "bootstrap"

  api_url   = "https://${aws_instance.rancher.public_ip}/"
  bootstrap = true
  insecure  = true

  version   = ">= 1.8.0"
}
```

In 1.7.3 the same code block runs fine.

**Comment by rawmind0** [comment]
Is the https://${aws_instance.rancher.public_ip}/ available??  Working fine to me..

**Comment by rawmind0** [comment]
Have you tried to change `retries` argument value??

**Comment by iTaybb** [comment]
Not available yet. There is no state yet. This fails on the plan step, before any resources can get created.
Just to clarify - the `aws_instance.rancher` instance is being created in the same terraform plan.
It should not try to connect to it since it's not ready yet.

It worked fine in 1.7.3

**Comment by rawmind0** [comment]
yeah, i got that it was working on 1.7.3. On 1.8.0, there is an additional check on provider, to test if rancher is ready.  This check is managed by `retries` argument, to continue checking more or less retries. What is not clear is why is trying to connect, if dependent objects are not ready. May the check should be done if not bootstraping...

Have you tried to change retries argument value??

**Comment by iTaybb** [comment]
This is failing on `terraform plan` step. So retries won't make sense, even 50 retries won't be enough, since it's only the plan step and no resources are going to be created

**Comment by rawmind0** [comment]
Could you please test with PR #294??
 The issue is just happening when api_url is dependent of infra that is deployed at same tf apply

**Comment by iTaybb** [comment]
Looks great. 10x

**Comment by azelezni** [comment]
This still causes issues.
I have a TF module with optional `rancher2_cluster` (`count = 0`), when using the module without `rancher2_cluster` I will get the same error, just after the depended resources has been created.

The module creates K8S cluster with RKE, either with the Terraform provider or via `rancher2_cluster`, so in the case of RKE provider `rancher2_cluster` is not used, but I still have to configure the provider, but the URL will be available only after I install rancher on it, but to install rancher I need to module to finish creating the cluster.
