### ISSUE TITLE
Rancher v2.3+ Supports Linode Cloud. Support Still Hasn't Been Implemented In TF Provider

### ISSUE THREAD

**Issue by lots0logs** [rancher/terraform-provider-rancher2#293]
Rancher includes built-in support for Linode since version 2.3 but support is missing in the TF provider.  I'm not yet sure what all is missing in the terraform provider. I'll update the list as I discover them.

* rancher2_cloud_credential
* rancher2_node_template

**Comment by iTaybb** [comment]
I believe it's a question to rancher itself, and not to the terraform provider

**Comment by lots0logs** [comment]
How so? Rancher supports Linode AFAIK.

**Comment by rawmind0** [comment]
TF provider is not supporting linode yet. PR's are more than welcomed. :)

**Comment by lots0logs** [comment]
@rawmind0 Done :heavy_check_mark:

**Comment by rawmind0** [comment]
@lots0logs , thanks for submitting PR. Approved and merged into master.

Please, reopen issue if needed.
