### ISSUE TITLE
Wait for node pool to be deleted

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/terraform-provider-rancher2#297]
Currently there is some issues where a node pool is deleted and then it moves on to delete other dependent resources such as node templates. Could a wait be added for the node pool resource to block until it is cleaned up?

**Comment by rawmind0** [comment]
What issues are you having?? What provider version are you using??

PR https://github.com/terraform-providers/terraform-provider-rancher2/pull/283 should sync delete with API

**Comment by mitchellmaler** [comment]
One issue is we create folders in the vsphere environment which cannot be deleted until all nodes have been deleted. Even if the rancher node_pool resource has been deleted the nodecontroller is still doing work to clean up the nodes. There is no way to wait for all nodes to be completely deleted without running a sleep or something. It would be better if the resource has an opt in way to waitfor all nodes to be deleted on the rancher side.

I am using the latest provider, I will test the node_pool and node_template deletion again since that PR looks to have fixed it. It still doesn't solve for the above issue we are having though.

**Comment by mitchellmaler** [comment]
I just deleted nodes and all the workers did delete but it left the master nodes created even though if I go into rancher and the cluster is missing.
Looking in the logs I see this
```
rancher-5475f7c8f-k8hlx rancher 2020/04/01 18:35:54 [ERROR] NodeController c-dh47g/m-bxfc9 [node-controller] failed with : unable to refresh config for node m-bxfc9: nodetemplates.management.cattle.io "nt-fj9xl" not found
rancher-5475f7c8f-k8hlx rancher 2020/04/01 18:35:54 [ERROR] NodeController c-dh47g/m-kfsct [node-controller] failed with : unable to refresh config for node m-kfsct: nodetemplates.management.cattle.io "nt-fj9xl" not found
rancher-5475f7c8f-k8hlx rancher 2020/04/01 18:35:54 [ERROR] NodeController c-dh47g/m-ldfp6 [node-controller] failed with : unable to refresh config for node m-ldfp6: nodetemplates.management.cattle.io "nt-fj9xl" not found
rancher-5475f7c8f-k8hlx rancher 2020/04/01 18:36:16 [ERROR] NodeController c-dh47g/m-xsc2x [node-controller] failed with : unable to refresh config for node m-xsc2x: nodetemplates.management.cattle.io "nt-n7rlh" not found
```
So in the backend the nodes still exist and are having issues.

**Comment by mitchellmaler** [comment]
Yea the namespace is being terminated by the nodes still exist waiting on the node controller
```
$kubectl get namespace c-dh47g
NAME                 STATUS        AGE
c-dh47g              Terminating   53m
$ kubectl get nodes.management.cattle.io -n c-dh47g
NAME      AGE
m-bxfc9   53m
m-kfsct   53m
m-ldfp6   53m
m-xsc2x   53m

**Comment by mitchellmaler** [comment]
I had to manually remove the finializer on the node objects and then they deleted along with the namespcae. I then had to manually delete the VMs since rancher wont delete them anymore since they have been forced removed.

**Comment by rawmind0** [comment]
I can't reproduce the issue. Terraform destroy is working fine for me using node_pools and node_templates

```
...
Plan: 0 to add, 0 to change, 6 to destroy.

Do you really want to destroy all resources?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes

rancher2_node_pool.etcd: Destroying... [id=c-8qz2t:etcd]
rancher2_node_pool.wrkr: Destroying... [id=c-8qz2t:wrkr]
rancher2_node_pool.etcd: Destruction complete after 1s
rancher2_node_pool.wrkr: Destruction complete after 1s
rancher2_node_template.foo: Destroying... [id=cattle-global-nt:nt-user-m2tqz-nt-v6wrk]
rancher2_cluster.foo: Destroying... [id=c-8qz2t]
rancher2_node_template.foo: Destruction complete after 1s
rancher2_cloud_credential.foo: Destroying... [id=cattle-global-data:cc-sbpwr]
rancher2_cloud_credential.foo: Destruction complete after 1s
rancher2_cluster.foo: Still destroying... [id=c-8qz2t, 10s elapsed]
rancher2_cluster.foo: Still destroying... [id=c-8qz2t, 20s elapsed]
rancher2_cluster.foo: Still destroying... [id=c-8qz2t, 30s elapsed]
rancher2_cluster.foo: Still destroying... [id=c-8qz2t, 40s elapsed]
rancher2_cluster.foo: Destruction complete after 40s
rancher2_bootstrap.admin: Destroying... [id=user-m2tqz]
rancher2_bootstrap.admin: Destruction complete after 0s
```

**Comment by nickvth** [comment]
same issue here: worker nodes are deleted from vmware, but controlplane not. 
terraform say that destruction is complete, but controlplane node is still "powered on" on vmware

rancher log
`2020/04/02 08:20:49 [ERROR] NodeController c-744wb/m-hbp2q [node-controller] failed with : unable to refresh config for node m-hbp2q: nodetemplates.management.cattle.io "nt-wvcq8" not found`

**Comment by rawmind0** [comment]
What is the error on terraform??

**Comment by nickvth** [comment]
terraform gives no error.

terrraform say rancher2_node_pool.controlplane: Destruction complete, but controlplane vm still exists on vmware and in rancher the cluster state is updating.

**Comment by rawmind0** [comment]
Then, if the error is on rancher side, this issue should be opened on rancher/rancher repo

**Comment by nickvth** [comment]
When i remove the cluster from ui all nodes are succesfully deleted. So why is that working and not with terraform.

**Comment by rawmind0** [comment]
I guess that you are not doing the same process. Are you also removing node_template from ui?? Have you tried to just destroy the cluster and node_pools from terraform and let node_templates??

**Comment by mitchellmaler** [comment]
The main issue is Rancher allows you to remove node_templates before all related nodes are removed. I agree this should be looked at on the rancher side but that could end up with it just rejecting deletes of node_templates before all nodes are deleted which would break the terraform workflow.

Could this provider be enhanced to have a wait on the node_pool delete action to wait for all nodes to actually be removed? Even if deleting the node pool not all nodes are actually deleted yet since rancher is still processing them.

**Comment by rawmind0** [comment]
I think the issue is on node_template delete not in node_pool. Have you tested not deleting node_template?? Other think that could be tested is add a cluster dependency to node_templates, assuring that cluster is removed before node_template.

Issue should be addressed on Rancher side, managing delete dependencies properly and waiting for delete if needed. This shouldn't break tf due to provider is waiting for rancher API delete objects.

**Comment by nickvth** [comment]
Yes you are correct, node template was destroyed before cluster. I have solve this with the following order 
Delete node pool, delete cluster and then delete node template.

**Comment by rawmind0** [comment]
Cool. @nickvth , have you added a `depends_on = [<node_template>]` on the cluster??

**Comment by nickvth** [comment]
Yes that's correct @rawmind0 

```
resource "rancher2_cluster" "cluster" {
  depends_on = [rancher2_cloud_credential.vsphere_automation, rancher2_node_template.node_template]
  name                      = var.cluster_name
  description               = var.cluster_description

**Comment by mitchellmaler** [comment]
I logged this issue on the rancher side. I completely agree this isn't really an issue with this provider and was just coming up with way to get around the issue. Hopefully on the rancher side it can be resolved.
https://github.com/rancher/rancher/issues/26456

**Comment by angeloudy** [comment]
@nickvth I'm having the same issue. I tried adding `depends_on`, still doesn't work.

**Comment by nickvth** [comment]
@angeloudy can you share your code?
