### ISSUE TITLE
cluster monitoring broken

### ISSUE THREAD

**Issue by nickvth** [rancher/terraform-provider-rancher2#300]
when cluster monitoring enable: 

`Failed to install app cluster-monitoring. Error: Could not get apiVersions from Kubernetes: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request`

**Comment by rawmind0** [comment]
More detailed data about the issue is needed here. tf file, tf error,...

**Comment by nickvth** [comment]
i think this is a rancher issue not tf, broken after 2.4.2

**Comment by nickvth** [comment]
https://github.com/rancher/rancher/issues/26440
