### ISSUE TITLE
Cluster / Project Monitoring Version Upgrade

### ISSUE THREAD

**Issue by toddexp** [rancher/terraform-provider-rancher2#303]
It seems there is currently no way to upgrade the cluster or project monitoring from the Terraform provider. I don't see any version specified in the Terraform code. Reissuing the cluster or project monitoring code again doesn't upgrade it either.

It seems that the monitoring version is set by the helm template version that is deployed for the cluster / project monitoring.

Is there a way to upgrade the monitoring version via this Terraform code?

**Comment by rawmind0** [comment]
PR #306 will add this feature

**Comment by toddexp** [comment]
Thank you for addressing this so quickly. I took a quick look at the PR. It appears this will allow versioning for the cluster monitoring. Is it possible to also allow versioning for project monitoring as well? It's possible I missed this ability for the project monitoring when looking at the PR though.

**Comment by rawmind0** [comment]
Take a look now.

**Comment by toddexp** [comment]
Looks great. Thank you again for fixing this so quickly. Much appreciated.

**Comment by rawmind0** [comment]
PR merged. Fix will be included on v1.8.3. Please reopen issue if needed
