### ISSUE TITLE
Error Listing RKE K8s System Images: Unknown schema type

### ISSUE THREAD

**Issue by r0mk** [rancher/terraform-provider-rancher2#307]
Provider 1.8.2
Terraform v0.12.21
Rancher 2.2.8

[ERROR] Listing RKE K8s System Images: Unknown schema type [rkeK8sSystemImage]
on provider.tf line 1, in provider "rancher2":
1: provider "rancher2" {

Works fine with plugin 1.7

**Comment by rawmind0** [comment]
Fixed on PR #306

**Comment by rawmind0** [comment]
PR merged. Fix will be included on v1.8.3. Please reopen issue if needed
