### ISSUE TITLE
Unicity of rancher2_notifier by name in the same cluster

### ISSUE THREAD

**Issue by anouarchattouna** [rancher/terraform-provider-rancher2#308]
* Create two notifiers in the same cluster that have the same name (say `test-cluster-notifier`) (from the UI, or using the terraform resource `rancher2_notifier`)
* Use the terraform data source `rancher2_notifier` to retrieve information about a notifier:
```tf
data "rancher2_notifier" "foo" {
    name = "test-cluster-notifier"
    cluster_id = "c-bp5jp"
}
```
=>`Error: [ERROR] found 2 notifier with name "test-cluster-notifier" and cluster ID "c-bp5jp"`

* Shouldn't the notifier name be unique by cluster just like `user.username` or `project.name` ?

* Use case: get a notifier by name and set it in a cluster alert group recipients field.

**Comment by rawmind0** [comment]
> Create two notifiers in the same cluster that have the same name (say test-cluster-notifier) (from the UI, or using the terraform resource rancher2_notifier)

Why??  It doesn't seems a good practice if done on purpose. If both notifiers has same name, how to choose which is the correct one?? Anyway, if `rancher2_notifier` are created by tf provider, you wouldn't need to use datasource.

By the moment, datasource is responding error if more than one `rancher2_notifier` are found with same cluster_id and name. 

> Shouldn't the notifier name be unique by cluster just like user.username or project.name ?

Could be, but this issue should be opened at Rancher.

>  Use case: get a notifier by name and set it in a cluster alert group recipients field.

 This should work fine if using unique names.

**Comment by anouarchattouna** [comment]
Thanks
