### ISSUE TITLE
No left menu item for rancher2_project_alert_group & rancher2_project_alert_rule

### ISSUE THREAD

**Issue by anouarchattouna** [rancher/terraform-provider-rancher2#309]
There is no left menu items for the following data sources :

**[rancher2_project_alert_group](https://www.terraform.io/docs/providers/rancher2/d/projectAlertGroup.html)**
**[rancher2_project_alert_rule](https://www.terraform.io/docs/providers/rancher2/d/projectAlertRule.html)**

There is no left menu items for the following resources :

**[rancher2_project_alert_group](https://www.terraform.io/docs/providers/rancher2/r/projectAlertGroup.html)**
**[rancher2_project_alert_rule](https://www.terraform.io/docs/providers/rancher2/r/projectAlertRule.html)**

**Comment by rawmind0** [comment]
Fixed on PR #311

**Comment by rawmind0** [comment]
PR merged. Please reopen issue if needed.
