### ISSUE TITLE
terraform access keys should not be required when using iam profile (part 2/2)

### ISSUE THREAD

**Issue by patrick0057** [rancher/terraform-provider-rancher2#31]
Please see https://github.com/rancher/rancher/issues/20817 for part 1/2

**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Setup s3BackupConfig with instance that has an iam profile attached that allows s3 backups using Rancher terraform provider.  Do not use access key or secret key.

**Result:**
You are not allowed to do this as access key and secret key are required in terraform however you should be able to set this up if the instance has an iam profile attached.

**Comment by patrick0057** [comment]
Reason for two parts: https://github.com/rancher/rancher/issues/20817#issuecomment-501364055

**Comment by rawmind0** [comment]
This issue has dependency with https://github.com/rancher/rancher/issues/20817 . Until this issue is not addressed, nothing could be done here.

**Comment by rawmind0** [comment]
Submitted PR #103 to set `access_key` and `secret_key` arguments as optional on `s3_backup_config`

**Comment by rawmind0** [comment]
Merged PR. Please reopen issue if needed.
