### ISSUE TITLE
Set recipients for default Cluster Alert Group

### ISSUE THREAD

**Issue by anouarchattouna** [rancher/terraform-provider-rancher2#310]
I would like to attach a newly created notifier to the existing Cluster Alert Group that comes with a rancher cluster :
`A set of alerts for etcd`
`A set of alerts for kube components`
`A set of alerts when event happened`
`A set of alerts for node`
* I created the notifier
```tf
# Create a new rancher2 Notifier
resource "rancher2_notifier" "test" {
  name          = "test-cluster-notifier"
  cluster_id    = "c-bp5jp"
  description   = "test notifier"
  send_resolved = "true"
  webhook_config {
    url = "https://my-url.mydomain.com"
  }
}
```
* Then I cannot figure out how to set the recipients field of the already existing Cluster Alert Groups ? Is that achievable ?

**Comment by rawmind0** [comment]
To manage any existing resource from terraform, it should be imported first, https://www.terraform.io/docs/providers/rancher2/r/clusterAlertGroup.html#import

**Comment by anouarchattouna** [comment]
Well I already tried doing a manual `terrafrom import` first then managing the resource in my terraform code. But this not a good option knowing that we are looking to have some automation !

**Comment by rawmind0** [comment]
Terraform can't update any resource that is not managed by itself. 

May be you can think to do the import from an automation process, due to existing cluster alert groups have known ids, "<CLUSTER_ID>:etcd-alert", "<CLUSTER_ID>:kube-components-alert", ...
