### ISSUE TITLE
cluster_auth_endpoint Not Enabled by Default

### ISSUE THREAD

**Issue by toddexp** [rancher/terraform-provider-rancher2#313]
The [cluster_auth_endpoint](https://www.terraform.io/docs/providers/rancher2/r/cluster.html#cluster_auth_endpoint) is not enabled by default. The documentation states that it is enabled by default, but it is set to disabled by default.

I think the default setting should be enabled however if this is intentionally set to disabled the docs should reflect that.

**Comment by rawmind0** [comment]
@toddexp, this is not exactly like you are describing. I guess you are using Rancher v2.4.x, isn't it?? I'll try to clarify.

The documentation doesn't states that [`cluster_auth_endpoint`](https://www.terraform.io/docs/providers/rancher2/r/cluster.html#cluster_auth_endpoint) argument is enabled by default. It states that this argument is optional and computed on `rancher_cluster` resource, what in terraform means that if `cluster_auth_endpoint` argument is not defined, it gets default value from Rancher API. Default value of `Authorized Cluster Endpoint` at Rancher API:
* `enabled`, up to v2.3.x
* `disabled`, from v2.4.x

What is defined as `true` by default in the documentation, is the nested [`cluster_auth_endpoint.enabled`](https://www.terraform.io/docs/providers/rancher2/r/cluster.html#enabled-4) argument, what in terraform means, that `enabled = true` by default if `cluster_auth_endpoint` argument is defined, `cluster_auth_endpoint {}` is equal to `cluster_auth_endpoint { enabled = true }` 
```

**Comment by toddexp** [comment]
@rawmind0 Thank you for the clarification. I did just upgrade to Rancher 2.4 and that is when I noticed this change.

I didn't realize the the difference between leaving off the argument in Terraform vs specifying the argument and leaving it empty. I appreciate you explaining the difference.
