### ISSUE TITLE
[ERROR] No api_url provided when trying to use Rancher2 provider

### ISSUE THREAD

**Issue by john-morsley** [rancher/terraform-provider-rancher2#314]
I have just bootstrapped a Rancher installation. However, when I try and 'admin' the same installation, I get: 

```Error: [ERROR] No api_url provided```

Code:

```
provider "rancher2" {
  alias = "admin"
  api_url = local.admin_url
  token_key = data.aws_s3_bucket_object.admin-token.body
  insecure = true
}
```

Can anyone advise, please? Or is this a bug?

**Comment by rawmind0** [comment]
What is local.admin_url?? It seems is empty string..

**Comment by john-morsley** [comment]
Nope, it works out as ```rancher.morsley.io```, the same URL I used to bootstrap it with.

**Comment by rawmind0** [comment]
https://github.com/terraform-providers/terraform-provider-rancher2/blob/f65df9d14bcb9b0aed1426dcb35a886d13bfe941/rancher2/provider.go#L216

**Comment by john-morsley** [comment]
> https://github.com/terraform-providers/terraform-provider-rancher2/blob/f65df9d14bcb9b0aed1426dcb35a886d13bfe941/rancher2/provider.go#L216

Are you trying to tell me something?

**Comment by rawmind0** [comment]
Sure, that local.admin_url seems to be resolved as empty string..or may be there is another provider config where api_url is empty.. 

Pointing provider code, when this error is returned

**Comment by john-morsley** [comment]
Nope, as even when I try the following, same error:

```
provider "rancher2" {
  alias = "admin"
  api_url   = "https://rancher.morsley.io"
  token_key = data.aws_s3_bucket_object.admin-token.body
  insecure = true
}
```

And my entire Terraform script has only 1 "rancher2" provider.

**Comment by rawmind0** [comment]
The second option.. how looks like your resources?? Are using admin aliased provider??

**Comment by john-morsley** [comment]
Ah, didn't know you had to. Trying it now...

**Comment by rawmind0** [comment]
Take a look to the examples, https://www.terraform.io/docs/providers/rancher2/index.html#example-usage

`provider = "rancher2.admin"` should be added to resources

**Comment by john-morsley** [comment]
Thanks @rawmind0. I was trying to create an EKS cluster, and although that's failing, it is getting further now. You are a star!
