### ISSUE TITLE
[RFE] Resource to automate importing a existing cluster to Rancher 

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/terraform-provider-rancher2#318]
Currently you have to call out to the Rancher API to get the import manifest and then apply that to the cluster you want to import. Would it make sense to create a resource that can get this manifest and then applies that to the cluster in question? It isn't the best UX to have to call the API and then apply using cli commands.

**Comment by crsantini** [comment]
Found answer here https://github.com/terraform-providers/terraform-provider-rancher2/issues/227

**Comment by rawmind0** [comment]
As explained on issue referenced by @digitalassembly , you don't need to call the Rancher API to get the import manifest. It can be obtained from tfstate, once you've created an imported cluster.  https://github.com/terraform-providers/terraform-provider-rancher2/issues/227#issuecomment-574374552

**Comment by mitchellmaler** [comment]
Ah okay. It wasn’t obvious that’s how to import a cluster.
