### ISSUE TITLE
rancher2_cluster :: Custom Cloud Provider Does Not Work

### ISSUE THREAD

**Issue by lots0logs** [rancher/terraform-provider-rancher2#319]
Currently the schema for `custom_cloud_provider.name` forces the name to be one of the built-in provider names or `custom`. That makes cluster creation fail with the following error:
```
error building controller context: cloud provider could not be initialized: unknown cloud provider "custom"
```
~~In my case, the name is `digitalocean`~~ Actually looks like it must be set to `external` but Terraform won't allow me to use it because it doesn't pass the current schema validation. 

References: 
* https://github.com/rancher/terraform-provider-rke/issues/196
* https://rancher.com/docs/rke/latest/en/config-options/cloud-providers/custom/
* https://github.com/rancher/terraform-provider-rke/issues/21

**Comment by rawmind0** [comment]
Submitted PR #364 to address issue

**Comment by rawmind0** [comment]
PR merged into master. It will be included on next provider release. Please, reopen issue if needed.
