### ISSUE TITLE
rancher2_cluster  - extra_args not being removed on destroy

### ISSUE THREAD

**Issue by chrisreed87** [rancher/terraform-provider-rancher2#320]
Using kubelet as an example:

```
 resource "rancher2_cluster" "foo-custom" {
   name = "foo-custom"
   description = "Foo rancher2 custom cluster"
   rke_config {
     services {
       kubelet {
         extra_args = {
           read-only-port = "10255"
         }
       }
     }
   }
 }
```
Creates a cluster with those `extra_args`. Then removing, so the resource looks like this:
```
 resource "rancher2_cluster" "foo-custom" {
   name = "foo-custom"
   description = "Foo rancher2 custom cluster"
   rke_config {
     services {
       kubelet {
         extra_args = {
         }
       }
     }
   }
 }
```
Plan output shows that it will be removed:
```
              ~ kubelet {
                  ~ extra_args                   = {
                      - "read-only-port" = "10255" -> null
                    }
                    extra_binds                  = []
                    extra_env                    = []
                    fail_swap_on                 = false
                    generate_serving_certificate = false
                }
```
But extra arg is still present in RKE cluster.yml

**Comment by rawmind0** [comment]
@chrisreed87 , as [`ExtraArgs`](https://github.com/rancher/types/blob/master/client/management/v3/zz_generated_kubelet_service.go#L19) go struct is defined with  `json:"extraArgs,omitempty" yaml:"extraArgs,omitempty"` definiiton, an empty `extra_args` is omitted when json is marshalled. Could you please try setting `read-only-port = "0"` to disable it??

**Comment by wd** [comment]
I have the same problem. 
```
    ~ kubeproxy {
                   ~ extra_args  = {
                       - "hostname-override" = "hostname" -> null
                     }
```

The kube-proxy container still runs with the old args after apply the plan.

**Comment by rawmind0** [comment]
@wd , same comment for you. Could you please try setting `hostname-override = ""` to disable it??

**Comment by wd** [comment]
@rawmind0 No I can't. But I found that I can remove it from rancher UI by edit cluster in yaml.
