### ISSUE TITLE
Error when retry after error

### ISSUE THREAD

**Issue by narfeta** [rancher/terraform-provider-rancher2#321]
sometimes our terraform fails creating namespaces with the message 

```
Error: Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [baseType=error, code=ServerError, message=Post https://X.X.X.X:6443/api/v1/namespaces?timeout=30s: dial tcp 127.0.0.1:6443: connect: connection refused] from [https://xxxxxx/v3/cluster/c-qtvmt/namespaces]

on 02-rancher_cluster.tf line 31, in resource "rancher2_namespace" "add_redis":

31: resource "rancher2_namespace" "add_redis" {
```

now if I retry, I get 

```
Error: Bad response statusCode [409]. Status [409 Conflict]. Body: [baseType=error, code=AlreadyExists, message=namespaces "redis" already exists] from [https://xxxxxx/v3/cluster/c-qtvmt/namespaces]

on 02-rancher_cluster.tf line 31, in resource "rancher2_namespace" "add_redis":

31: resource "rancher2_namespace" "add_redis" {
```

Is there a way to workaround to this? or should I remove the namespace before retry? (that's what I'm actually doing) 

On other side I'm trying to figure it out why I'm getting 500 

Cheers

**Comment by rawmind0** [comment]
> Error: Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [baseType=error, code=ServerError, message=Post https://X.X.X.X:6443/api/v1/namespaces?timeout=30s: dial tcp 127.0.0.1:6443: connect: connection refused] from [https://xxxxxx/v3/cluster/c-qtvmt/namespaces]

It seems you are getting `500` errors due to Rancher to k8s cluster post is eventually failing with timeout. Are you k8s master services restarting or eventually failing or so busy?? 

Probably the k8s timeout error is coming once the namespace has been created, that's why you are getting `409` error on retry. 

It seems the issue is not related with the provider, moreover it seems related with the downstream k8s cluster connectivity issue. Please, reopen it if needed

**Comment by chad-barensfeld-exa** [comment]
@rawmind0 Are there any configurations that could help handle disconnections? We get the same issue when deploying to GKE clusters with our Terraform quite often. We've even added a 20 minutes cluster_sync to allow rancher to finish initial config after import.

**Comment by rawmind0** [comment]
@chad-barensfeld-exa could you please provide more context about your issue?? Is the issue occurring installing Rancher management server on GKE or adding GKE as downstream k8s cluster?? Is it occurring at initial GKE cluster deployment or eventually when you try to deploy something within the GKE cluster??
