### ISSUE TITLE
Documentation Inconsistency

### ISSUE THREAD

**Issue by ajchiarello** [rancher/terraform-provider-rancher2#322]
In the resource description for rancher2_node_template, under the vsphere_config, in the entry for clone_from, it says "If you choose creation type clone a name of what you want to clone is required."

However, under the entry for creation_type, clone is not a supported value ("Supported values: vm, template, library, legacy.") Looks like the text for clone_from was not updated when the creation types were.

**Comment by rawmind0** [comment]
Documentation fixed on PR #395
