### ISSUE TITLE
Cannot delete/add/modify clusterTemplateRevision when the clusterTemplate is in use

### ISSUE THREAD

**Issue by caiconkhicon** [rancher/terraform-provider-rancher2#323]
I want to delete a clusterTemplateRevision, so I remove that `template_revisions` block from the `rancher2_cluster_template` resource, then apply. The plan shows that `template_revisions` block will be removed:

> Plan: 0 to add, 1 to change, 0 to destroy.

However, when applying, it fails with the error: 

> Error: Bad response statusCode [422]. Status [422 Unprocessable Entity]. Body: [code=InvalidAction, message=Cannot update the clusterTemplateRevision until Clusters are referring it, baseType=error] from [https://my-rancher.com/v3/clusterTemplateRevisions/cattle-global-data:ctr-xxxx]

The revision is not in-use. I can delete it from the Rancher UI, and then when running `terraform apply` again, it shows that everything is up-to-date.

I believe there is a bug in the provider. Please a look at it.
Thank you.

**Comment by caiconkhicon** [comment]
I did more tests:

- A `rancher2_cluster_template` resource is created with 2 revisions, 1 is default and is used to created a K8S managed cluster. Then, I tried the following tests, all of them failed:
  - Modify the in-use revision
  - Add a new revision
  - Modify the unused revision - in fact it succeeded but the error was still returned
  - The errors are a same type: 
`Error: Bad response statusCode [422]. Status [422 Unprocessable Entity]. Body: [message=Cannot update the clusterTemplateRevision until Clusters are referring it, baseType=error, code=InvalidAction] from ...`

- A `rancher2_cluster_template` resource was created and unused. In this case, all delete/add/modify operations succeeded.

**Comment by Mike-Ling** [comment]
Hi caiconkhicon, 

I'm struggling to find an example that shows how to create a second template revision. Can you assist?

The docs say template_revisions is a list, but my cluster_config is about 100 lines of code? I can't work out how to structure template_revisions as a list.

Thanks in advance,

Mike

**Comment by caiconkhicon** [comment]
Hi @Mike-Ling,
yes, your `rancher2_cluster_template` will look very long because of `cluster_config`. The code structure looks like this:

```
resource "rancher2_cluster_template" "default" {
  name        = "default"
  members {
    access_type = "owner"
  }
  template_revisions {
    name    = "V1"
    default = true
    cluster_config {
    ....
    }
  }
  template_revisions {
    name    = "V2"
    default = false
    cluster_config {
    ....
    }
  }
}
```

**Comment by Mike-Ling** [comment]
Thanks @caiconkhicon for your help with the above... its easy once you know how; if only the official documentation was a little more detailed...

I've been doing a fair bit of testing with the cluster template resource over the last week or so and I've decided to abandon it and define the cluster config within the cluster resource. Having wrapped the cluster resource in a module that acts as a template and is more than adequate for our needs. Not having to add ~100 lines of code for each minor change will also be a relief.

I'm not sure if the cluster template resource was designed to exist in the same configuration as the cluster, but I could not reliably perform a run with both in the same config. When applying, I see the same error you mention above, even when nothing has changed.

Version 1.8.3 of the provider seems to interpret the private_registries password as a change:
```
~ private_registries {
                        is_default = true
                      + password   = (sensitive value)
                        url        = "xxxxxxxxx.azurecr.io"
                        user       = (sensitive value)
```
That results in the following error from Rancher server v2.4.3:
```
Error: Bad response statusCode [422]. Status [422 Unprocessable Entity]. Body: [baseType=error, code=InvalidAction, message=Cannot update the clusterTemplateRevision until Clusters are referring it] from [https://rancher.xxxxxx.dev/v3/clusterTemplateRevisions/cattle-global-data:ctr-24pll]
```
I thought RKE template revisions were supposed to be static/ read-only so it does not make sense why the provider would attempt to modify an existing template revision? Moving the template resource into its own config worked around the issue and allowed me to modify node pools etc. but at the expense of complexity and duplication.

Thanks again for your help.

Mike

**Comment by carlcauchi** [comment]
@Mike-Ling / @caiconkhicon - Just incase you might be able to help - I have raised a similar issue here: https://github.com/terraform-providers/terraform-provider-rancher2/issues/365

**Comment by rawmind0** [comment]
Thanks for the feedback @caiconkhicon  

Closing issue superseded by #365
