### ISSUE TITLE
Rancher 2.3.2 - Audit_log do not apply downstream

### ISSUE THREAD

**Issue by zaggash** [rancher/terraform-provider-rancher2#324]
Hi,
Using Rancher version 2.3.2.
I think there is an issue in regards to the `audit_log` argument.
Trying to apply the following, `terraform apply` says it is modified but nothing happen on the downstream cluster.
```
services {
      kube_api {
        audit_log {
          enabled = true
          configuration {
            max_age = 5
            max_backup = 5
            max_size = 100
            path = "-"
            format = "json"
            policy = file("auditlog_policy.yaml")
          }
        }
      }
    }
```

In order to make it work, I have to apply something like this, with the `autit.yaml` on the server beforehand:
```
rke_config {    
  services {
      kube_api {
        extra_args = {
          "audit-log-format" = "json"
          "audit-log-maxage" = "5"
          "audit-log-maxbackup" = "5"
          "audit-log-maxsize" = "100"
          "audit-log-path" = "/var/log/kube-audit/audit-log.json"
          "audit-policy-file" = "/etc/kubernetes/audit.yaml"
        }
        extra_binds = [
          "/var/log/kube-audit:/var/log/kube-audit"
        ]
      }
    }
  }
```

Is there a bug ? A minimum Rancher version to make it work ?

**Comment by zaggash** [comment]
https://github.com/rancher/rancher/issues/26713

**Comment by rawmind0** [comment]
Hey @zaggash , as explained on [RKE docs](https://rancher.com/docs/rke/latest/en/config-options/audit-log/#enabled-by-default), `audit_log` feature was added on RKE ~~v1.1.0~~ v1.0.0

[Rancher v2.3.2](https://github.com/rancher/rancher/blob/v2.3.2/go.mod#L81) is using RKE v0.3.2. RKE ~~v1.1.0~~ v1.0.0 was introduced on [Rancher ~~v2.4.0~~ v2.3.3](https://github.com/rancher/rancher/blob/v2.3.3/go.mod#L81)

To use `audit_log` argument, you need to use Rancher up to ~~v2.4.0~~ v2.3.3

**Comment by zaggash** [comment]
From what I understand, it is enabled by default starting with 1.1.0, doesn't mean it is not available before 🤔

**Comment by rawmind0** [comment]
Agreed that may be doc explanation is not pretty clear, but feature is not available at  Rancher v2.3.2 ([RKE v0.3.2](https://github.com/rancher/rke/blob/v0.3.2/vendor/github.com/rancher/types/apis/management.cattle.io/v3/rke_types.go#L263)). audit_log can be enabled on previous RKE versions but using `extra_args` and `extra_binds` like you are doing. 

Anyway, i made a mistake checking versions, sorry. `audit_log` argument is available at Rancher up to v2.3.3 ([RKE v1.0.0](https://github.com/rancher/rke/blob/v1.0.0/vendor/github.com/rancher/types/apis/management.cattle.io/v3/rke_types.go#L281))

**Comment by zaggash** [comment]
Okay make more sense and explain why it worked on v2.3.4 during the tests.
Thanks for the precision.

**Comment by bekakochauri** [comment]
rancher v2.4.4 version; kubernetes v17, but audit logging doesn't work. :|
--
