### ISSUE TITLE
Cluster cloud config for openstack load balancers lacks node_security_group parameter

### ISSUE THREAD

**Issue by dr4Ke** [rancher/terraform-provider-rancher2#328]
When configuring a cluster with load balancers on openstack, we should be able to specify the right security group to use for the load balancers rules management.

It's specified as mandatory (although it seems not) in [kubernetes documentation](https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/#load-balancer):

> `manage-security-groups` (Optional): Determines whether or not the load balancer should automatically manage the security group rules. Valid values are true and false. The default is `false`. **When true is specified `node-security-group` must also be supplied**.

**Comment by rawmind0** [comment]
@dr4Ke , i guess that this option is not supported by RKE, https://github.com/rancher/types/blob/master/apis/management.cattle.io/v3/rke_types.go#L635

I guess this issue should be opened on rke repo. Could you please, open the issue there, https://github.com/rancher/rke/issues

**Comment by dr4Ke** [comment]
As a matter of fact, it seems that this option is deprecated as the external cloud controller for openstack creates a new SG for that purpose. So I guess this won't be necessary after all. Sorry for the noise.
