### ISSUE TITLE
Node template error on delete in Terraform, but template is deleted in Rancher

### ISSUE THREAD

**Issue by patrickdappollonio** [rancher/terraform-provider-rancher2#329]
### What did you do?

Create a node template using the terraform provider 1.8.2 using the following code:

```
provider "rancher2" {
  api_url    = "https://rancher.example.com"
  access_key = ""
  secret_key = ""
}

terraform {
  required_version = ">= 0.12.0"
}

resource "rancher2_node_template" "master" {
  name = "patrick-testing-nodetemplate-delete"

  amazonec2_config {
    zone           = "abc"
    security_group = ["abc"]
    ami            = "abc"
    subnet_id      = "abc"
    vpc_id         = "abc"
    region         = "abc"
  }
}
```

Then proceed to create the node template and delete it right away using `terraform init && terraform apply -auto-approve && terraform destroy -auto-approve`

### What did you expect to see?

The node template created (showing up briefly in the UI before requesting deletion), then deleted right away.

### What did you see instead?

```
$ terraform apply -auto-approve
rancher2_node_template.master: Creating...
rancher2_node_template.master: Creation complete after 7s [id=cattle-global-nt:nt-42w4t]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

$ terraform destroy -auto-approve
rancher2_node_template.master: Refreshing state... [id=cattle-global-nt:nt-42w4t]
rancher2_node_template.master: Destroying... [id=cattle-global-nt:nt-42w4t]

Error: [ERROR] waiting for node template (cattle-global-nt:nt-42w4t) to be removed: Bad response statusCode [403]. Status [403 Forbidden]. Body: [code=Forbidden, message=nodetemplates.management.cattle.io "nt-42w4t" is forbidden: User "u-3mqsnaovmf" cannot get resource "nodetemplates" in API group "management.cattle.io" in the namespace "cattle-global-nt", baseType=error] from [https://rancher.example.com/v3/nodetemplates/cattle-global-nt:nt-42w4t]
```

### More information

It seems that the code from the previous node template management was left behind and now, node templates essentially are deleted right away upon request (returning a `204 no content`) rather than later on.

Due to this, the current Terraform provider in [this part of the code](https://github.com/terraform-providers/terraform-provider-rancher2/blob/v1.8.2/rancher2/resource_rancher2_node_template.go#L206-L218) seems to continue handling node templates the old fashion way.

Practically, our team was able to work around this by simply removing this piece of code but in practice, there should be a more concrete error handling where the status code comes into play. Digging down into the code, there is a part where the request is made then checked against statuses over or equal 300. Maybe a more fine grained approach could be exposing the status code or handling the resulting code differently.

**Comment by rawmind0** [comment]
PR #331  should address the issue

**Comment by rawmind0** [comment]
PR merged into master. Please, reopen issue if needed.
