### ISSUE TITLE
Default value for kubernetes_version in aks_config is no longer applicable

### ISSUE THREAD

**Issue by MattiasAng** [rancher/terraform-provider-rancher2#33]
The version for the default value of this parameter is no longer availble:

```
az aks get-versions -l eastus -o table
KubernetesVersion    Upgrades
-------------------  -----------------------
1.13.5               None available
1.12.8               1.13.5
1.12.7               1.12.8, 1.13.5
1.11.9               1.12.7, 1.12.8
1.11.8               1.11.9, 1.12.7, 1.12.8
1.10.13              1.11.8, 1.11.9
1.10.12              1.10.13, 1.11.8, 1.11.9`
```

Error in Rancher:
```
The value of parameter orchestratorProfile.OrchestratorVersion is invalid.
```
Solution is to change the defualt value in schema_cluster_aks_config.go but this will probably become an issue again. Parameter should either be required or default value should be routinely updated (will never work).

**Comment by rawmind0** [comment]
Thanks for the feedback @MattiasAng.

Submitted PR #56  to address it.

**Comment by rawmind0** [comment]
PR #56  is merged. Please, reopen issue if needed.
