### ISSUE TITLE
node template default ec2 encryption set to false

### ISSUE THREAD

**Issue by panho66** [rancher/terraform-provider-rancher2#330]
Node template in Rancher 2.3.x do not have encryption option . 
EC2 created with encrypted AMI is encrypted. You cannot create EC2 unencrypted from encrypted AMI

Rancher 2.4.x has encryption option but default to false. There is no option in rancher2_node_template to set encryption as a result create EC2 from encrypted AMI failed.

![image](https://user-images.githubusercontent.com/15118220/81521619-188f4080-938b-11ea-8384-77cc28d7aee6.png)

**Comment by rawmind0** [comment]
PR #331  should address the issue

**Comment by rawmind0** [comment]
PR merged into master. Please, reopen issue if needed.
