### ISSUE TITLE
rancher2_role_template - support view verb

### ISSUE THREAD

**Issue by chrisreed87** [rancher/terraform-provider-rancher2#332]
Creating or editing a role template, when adding the verb `view` provider returns this error:
```
   rules {
     api_groups = [
       "monitoring.cattle.io",
     ]
     non_resource_urls = []
     resource_names    = []
     resources = [
       "prometheus",
     ]
     verbs = [
       "view",
     ]
   }
```
```
Error: expected rules.23.verbs.0 to be one of [* create delete get list patch update watch], got view

  on main.tf line 280, in resource "rancher2_role_template" "project_owner":
 280: resource "rancher2_role_template" "project_owner" {
```

`view` is missing from this list in the docs here: https://www.terraform.io/docs/providers/rancher2/r/roleTemplate.html

**Comment by rawmind0** [comment]
`view` verb is not in the doc due to it's not supported here. Supported verbs are `create delete get list patch update watch`, actually like in the Rancher UI. 

Are you sure `view` is the verb you need??

**Comment by spencergilbert** [comment]
The API view for the default Project Owner contains the following spec...
```
{
    "apiGroups": [
        "monitoring.cattle.io"
    ],
    "resources": [
        "prometheus"
    ],
    "type": "/v3/schemas/policyRule",
    "verbs": [
        "view"
    ]
},
```

**Comment by chrisreed87** [comment]
@rawmind0 - yes, to @spencergilbert 's post above, the error is received when importing a role that already has `view` as an option (as above), edited for any additions, then re-applied to the cluster.

**Comment by rawmind0** [comment]
Got it, thanks for your comments.

I'll submit a PR adding it.

**Comment by spencergilbert** [comment]
Happy to open an issue against rancher directly if it should be updated to a GET or LIST as well. Thanks guys!

**Comment by rawmind0** [comment]
Submitted PR #344 to address the issue

**Comment by rawmind0** [comment]
PR #344 already merged to master. It will be included on next provider release. Please, reopne issue if needed.
