### ISSUE TITLE
403 when trying to access data rancher_cluster on RBAC enabled cluster

### ISSUE THREAD

**Issue by vCra** [rancher/terraform-provider-rancher2#333]
Currently using a multi-tenancy cluster, where access to certain resources (in this example cluster registration tokens) are not accessible to everyone (for obvious reasons). I only want to be able to access the things I have access to (e.g. the kube config and description), and for the objects that I don't have access to, to be ignored.

`Error: Bad response statusCode [403]. Status [403 Forbidden]. Body: [baseType=error, code=Forbidden, message=clusterregistrationtokens.management.cattle.io "system" is forbidden: User "u-uqa3abcdef" cannot get resource "clusterregistrationtokens" in API group "management.cattle.io" in the namespace "clu"] from [https://cluster.example.com/v3/clusterregistrationtokens/clu:system]`

This might mean having to hit some other endpoints to see what can be accessed by the current user, or maybe just defaulting to a blank value if we get an 403. Maybe a flag should be created to enforce "strict mode" where errors will always get thrown, and raise some warnings if not

**Comment by rawmind0** [comment]
@vCra , the issue has been reproduced. PR #409 should address it.

**Comment by rawmind0** [comment]
PR #409 is merged to master. Please reopen the issue if needed.
