### ISSUE TITLE
Rancher2_cluster AKS Config Tags not working

### ISSUE THREAD

**Issue by slessardjr** [rancher/terraform-provider-rancher2#335]
When I use the provider to create or update a cluster. I'm providing tags and they are not showing up in the ui, nor are the tags applied to the created AKS resource or virtual machines.

``` HCL
resource "rancher2_cluster" "aks_cluster" {
  name                      = format("aks-%s-%s", local.azure_subscription_name, terraform.workspace)
  enable_network_policy     = false
  enable_cluster_monitoring = true
  enable_cluster_istio      = true

  aks_config {
    admin_username                 = local.config.ssh.gecloud.username
    agent_os_disk_size             = local.config.aks.agent_os_disk_size
    agent_pool_name                = substr("rancher${terraform.workspace}", 0, 12)
    agent_vm_size                  = local.config.aks.agent_vm_size
    client_id                      = local.provider.azure.client_id
    client_secret                  = local.provider.azure.client_secret
    count                          = local.config.aks.agent_node_count
    docker_bridge_cidr             = "172.17.0.1/16"
    enable_monitoring              = local.config.aks.monitoring
    kubernetes_version             = local.config.aks.kubernetes_version
    master_dns_prefix              = "${terraform.workspace}-aks-master"
    network_plugin                 = "kubenet"
    pod_cidr                       = "172.33.0.0/16"
    resource_group                 = azurerm_resource_group.aks_rg.name
    service_cidr                   = "10.32.0.0/16"
    dns_service_ip                 = "10.32.0.2"
    ssh_public_key_contents        = local.config.ssh.public_key
    subnet                         = data.azurerm_subnet.aks_subnet.name
    subscription_id                = local.provider.azure.subscription_id
    tag                            = local.config.cloud_required_tags
    tenant_id                      = local.provider.azure.tenant_id
    virtual_network                = data.azurerm_virtual_network.vnet.name
    virtual_network_resource_group = data.azurerm_virtual_network.vnet.resource_group_name
  }
}
```
This creates successfully, but if I edit the cluster in the UI, none of the tags were added.

```
Terraform Version 0.12.24
Rancher2 Version 1.8.3
```

**Comment by slessardjr** [comment]
Looks like the problem is in the struct type. I think the input of a map is a good idea to ensure kv, but Rancher2 seems to expect them as an array of string

[snippit of output json from Rancher2_cluster]
```
{
  ...
  "azureKubernetesServiceConfig": {
    ...
    "tags": [
      "env=dev",
      "createdBy=terraform"            
  ],  
}
```
I'm still a beginner at go, but I think this line needs to change to []string
https://github.com/rancher/terraform-provider-rancher2/blob/33810e8edbdd7529239429bb11be37212f06f712/rancher2/schema_cluster_aks_config.go#L58

And also 
https://github.com/rancher/terraform-provider-rancher2/blob/33810e8edbdd7529239429bb11be37212f06f712/rancher2/schema_cluster_aks_config.go#L274

I'm not sure where converting from the terraform map to the string array would be. I'm assuming it would be here:
https://github.com/rancher/terraform-provider-rancher2/blob/33810e8edbdd7529239429bb11be37212f06f712/rancher2/structure_cluster_aks_config.go#L145

and/or here
https://github.com/rancher/terraform-provider-rancher2/blob/33810e8edbdd7529239429bb11be37212f06f712/rancher2/structure_cluster_aks_config.go#L309

Also the associated tests will need to be updated.

**Comment by rawmind0** [comment]
@slessardjr   , the tag argument is a terraform map, `map[string]interface{}`, the go field is a `map[string]string`, not a `[]string`. Conversions are done properly with `toMapInterface` and `toMapString`. How are you defining your tags?? Have you tried something like that??

```
  tag = {
    "env" = "dev"
    "createdBy" = "terraform"   
  }
```

**Comment by slessardjr** [comment]
> @slessardjr   , the tag argument is a terraform map, `map[string]interface{}`, the go field is a `map[string]string`, not a `[]string`. Conversions are done properly with `toMapInterface` and `toMapString`. How are you defining your tags?? Have you tried something like that??
> 
> 
> 
> ```
> 
>   tag = {
> 
>     "env" = "dev"
> 
>     "createdBy" = "terraform"   
> 
>   }
> 
> ```

That is exactly how I'm making my tags, but they are not in the UI of Rancher nor do they show up in Azure AKS. When I check the state I saw that the tags aren't maps by list of string in the state file. 

Is the conversion happening to []string that shows up in the state file?

**Comment by slessardjr** [comment]
@rawmind0  I'm not arguing that the conversions are improper. They are proper, what I 'm saying is that the values coming back from Azure is not a map, it's an array. so the parsing doesn't work.

**Comment by rawmind0** [comment]
> @rawmind0 I'm not arguing that the conversions are improper. They are proper, what I 'm saying is that the values coming back from Azure is not a map, it's an array. so the parsing doesn't work.

You were right @slessardjr . Submitted PR https://github.com/rancher/terraform-provider-rancher2/pull/660 to fix this issue. 

Deprecated `rancher2_cluster.aks_config.tag` argument due to it was not working properly. 
Created new `rancher2_cluster.aks_config.tags` argument to replace `tag`, with the proper `[]string` type to match Rancher API
