### ISSUE TITLE
terraform-rancher:CA: "terraform apply" is  updating the CA cert every time  with out any user changes

### ISSUE THREAD

**Issue by sadhugit** [rancher/terraform-provider-rancher2#337]
Steps:
1. Prepare the single node terraform rancher cluster.
2. Update the minio s3  config details  with certificate in the rancher resource file(rancher-common/rancher.tf).
eg:
`rke_config {
    kubernetes_version = var.workload_kubernetes_version
    services {
      etcd {
        backup_config {
          interval_hours = 24
          retention = 3
          s3_backup_config {
            access_key = var.backup_access_key
            secret_key = "IAMTHESECRETkey"
            bucket_name = "rancher-bucket"
            custom_ca = filebase64("/root/ca.pem")
            endpoint = "example.com:9004"
          }
        }
      }
    }
  }`
3. Perform the "terraform apply" and check the displayed output for CA.
4. Without any change again perform "terraform apply" and check for CA again.

Actual result:
With out any user changes its resending CA certs again .
The reason is its appending the few chars (may be newline) every  time  we perform  terraform apply then it thinking its a new CA cert and try to apply the same cert again and again.

Expected result:
It should not introduce special characters on existing certificate.
 
**Environment:**
Terraform version :   Terraform v0.12.24
Rancher version: Rancher -v2.3.5 ,Helm - v2.14.3-rancher1

**Comment by sadhugit** [comment]
Sample rancher Config File:
[rancher.tf](https://github.com/terraform-providers/terraform-provider-rancher2/files/4629657/rancher.tf.txt)

**Comment by rawmind0** [comment]
@sadhugit , triming spaces before base64 encode should help you. 
`custom_ca = base64encode(TrimSpace(file("/root/ca.pem")))`

**Comment by sadhugit** [comment]
Thanks alot @rawmind0  It fixed the issue.(Initially it updated and next time onwards its not updating while performing terraform apply).
 A small correction to the command i.e. it's "trimspace"
`custom_ca = base64encode(trimspace(file("/root/ca.pem")))`

**Comment by rawmind0** [comment]
@sadhugit , i'm glad it's fixed. Please, reopen issue if needed.
