### ISSUE TITLE
terraform-rancher2(RFE):Expose caCert in the rancher2_cluster data source

### ISSUE THREAD

**Issue by sadhugit** [rancher/terraform-provider-rancher2#339]
Details:
The rancher2 terraform provider does not expose the caCert in the attributes of either the rancher2_cluster resource, or more importantly, the rancher2_cluster data source. 

It may not make sense to add it to the resource, since it can take some time (1-2 minutes) for the value to appear. But it should exist in the data source.

The caCert value is available in the Rancher API when querying a cluster. That's the value that is needed. (This feature request would only need to apply to the terraform provider.)
FYI:
[https://www.terraform.io/docs/providers/rancher2/d/cluster.html](url)

**Comment by sadhugit** [comment]
Any updates on this RFE.

**Comment by HighwayofLife** [comment]
Following up on this RFE to check on the status.

**Comment by rawmind0** [comment]
Just curiosity, what is the use case?? K8s cluster cacert should be already included in the generated [kube_config](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/data-sources/cluster#kube_config)

**Comment by HighwayofLife** [comment]
We usually have to generate our own `kube_config` for downstream clusters for 2 primary reasons:
1. We front the Kube API with an Azure Load Balancer, and there isn't currently an option to specify this IP or hostname in RKE (that I'm aware of). An additional reason we front this with a load balancer (accepting traffice over 443 and routing traffic to all master/kube-api nodes on port 6443) is because the endpoint generated in the `kube_config` is the first master node IP on port 6443, which within a private corporate network is a blocked port.

2. We generate a kube config with a the azure auth provider configuration so that users can access the Kube API using their Azure AD credentials. I don't know of a way to configure this for RKE, so this is the second reason we generate our own `kube_config`.

**Comment by rawmind0** [comment]
> 1. We front the Kube API with an Azure Load Balancer, and there isn't currently an option to specify this IP or hostname in RKE (that I'm aware of). An additional reason we front this with a load balancer (accepting traffice over 443 and routing traffic to all master/kube-api nodes on port 6443) is because the endpoint generated in the `kube_config` is the first master node IP on port 6443, which within a private corporate network is a blocked port.

Are you using custom or imported RKE clusters?? RKE doesn't have the option but Rancher provide this option using [cluster_auth_endpoint](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster#cluster_auth_endpoint)

Cluster generated `kube_config` should add all k8s master nodes, rancher `system_url` and all configured `cluster_auth_endpoint` as kube context, not just first master node IP on port 6443

> 2. We generate a kube config with a the azure auth provider configuration so that users can access the Kube API using their Azure AD credentials. I don't know of a way to configure this for RKE, so this is the second reason we generate our own `kube_config`.

`kube_config` is generated with the terraform user credentials. RKE doesn't have the option of external auth but Rancher provide this option. If tf execution is done using an azure AD user, then kube_config will be generated with this credentials.

**Comment by HighwayofLife** [comment]
> Are you using custom or imported RKE clusters?? RKE doesn't have the option but Rancher provide this option using [cluster_auth_endpoint](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster#cluster_auth_endpoint)

We're using custom RKE generated clusters, (not imported). I think we do use the cluster with endpoint. I'll have to double check.

> Cluster generated `kube_config` should add all k8s master nodes, rancher `system_url` and all configured `cluster_auth_endpoint` as kube context, not just first master node IP on port 6443

I think this is the case when generating a cluster via Rancher, but an RKE generated cluster AFAIK requires the 6443 port on the first master node IP. 


> `kube_config` is generated with the terraform user credentials. RKE doesn't have the option of external auth but Rancher provide this option. If tf execution is done using an azure AD user, then kube_config will be generated with this credentials.

I'm uncertain I'm understanding this fully. RKE doesn't take Azure AD config, does it?

When generating clusters for customers, we want to use the config provided to the oidc provider, and then we produce a kind config based on their credentials, which are different from the Azure credentials used to configure the infrastructure, which is an SPN.

I'm not sure that I'm articulating this sufficiently, so I'll grab some TF code next week to demonstrate.

**Comment by rawmind0** [comment]
> We're using custom RKE generated clusters, (not imported). I think we do use the cluster with endpoint. I'll have to double check.

> I think this is the case when generating a cluster via Rancher, but an RKE generated cluster AFAIK requires the 6443 port on the first master node IP.

If you are using `cluster_auth_endpoint`, you shouldn't need to edit kube config server, and the k8s cluster should be available at `cluster_auth_endpoint`, not just at first master node IP:6443

> I'm uncertain I'm understanding this fully. RKE doesn't take Azure AD config, does it?

As mentioned, RKE doesn't take Azure AD config but Rancher does it. Generated cluster kube config should use same user used by tf provider. 

Anyway, PR #468 is adding new computed `ca_cert` to `rancher2_cluster` resource and datasource.

**Comment by HighwayofLife** [comment]
> As mentioned, RKE doesn't take Azure AD config but Rancher does it. Generated cluster kube config should use same user used by tf provider.

I'll check with our Rancher reps to get a bit more detail on this and make sure we're using this correctly. Rancher auths against Github Enterprise, but our Rancher provisioned clusters are setting up OIDC configuration to use Azure AD, so I don't know how that detail affects this configuration. 

> Anyway, PR #468 is adding new computed `ca_cert` to `rancher2_cluster` resource and datasource.

Awesome, thanks!! 👍
