### ISSUE TITLE
Support for encryptEbsVolume in node_template (amazonec2_config)

### ISSUE THREAD

**Issue by Israphel** [rancher/terraform-provider-rancher2#342]
### Terraform Version
Terraform v0.12.24
+ provider.aws v2.61.0
+ provider.rancher2 v1.8.3

### Affected Resource(s)
Please list the resources as a list, for example:
- node_template

### Expected Behavior
amazonec2_config doesn't have an entry for encryptEbsVolume (bool)

### Actual Behavior
You can only create node templates with encryptEbsVolume set to false. If you change it via rancher API, Terraform doesn't see the change.

### Steps to Reproduce
Create any node_template with amazonec2_config and the result will have encryptEbsVolume set to false.

**Comment by panho66** [comment]
@Israphel  https://github.com/terraform-providers/terraform-provider-rancher2/issues/330
