### ISSUE TITLE
create token for other users

### ISSUE THREAD

**Issue by panho66** [rancher/terraform-provider-rancher2#343]
Hi 
I have a need to create Rancher user using rancher2_user and retrieve user's token.
However, after user created, I couldn't find a way to create user token.  Rancher provider requires user's access, secret key or token and bootstrap only for admin. 

After rancher2_user created user, nothing I could use to login and create token.

Is it possible to extent rancher2_user to return token as well ?

**Comment by rawmind0** [comment]
Duplicated, please follow up #315
