### ISSUE TITLE
Data source with depends_on always forces a resource recreation

### ISSUE THREAD

**Issue by nathankodilla** [rancher/terraform-provider-rancher2#348]
I have the following code:

```hcl
resource "rancher2_bootstrap" "admin" {
  provider = rancher2.bootstrap
  password = var.rancher_password

  depends_on = [helm_release.rancher, aws_route53_record.rancher]
}

data "rancher2_cluster" "main" {
  name = "local"

  depends_on = [rancher2_bootstrap.admin]
}

data "rancher2_project" "system" {
  cluster_id = data.rancher2_cluster.main.id
  name = "System"
}

resource "rancher2_app" "kube2iam" {
  provider = rancher2
  name = "kube2iam"
  project_id = data.rancher2_project.system.id
  catalog_name = "helm"
  template_name = "kube2iam"
  template_version = var.kube2iam_version
  target_namespace = "kube-system"
  values_yaml = base64encode(templatefile("${path.module}/templates/kube2iam-values.yaml", { }))

  depends_on = [rancher2_catalog.main]
}
```

Every `apply` the `rancher2_app.kube2iam` resource thinks it needs to recreate itself. The plan shows a change of `~ project_id = "local:p-xxxxx" -> (known after apply) # forces replacement` but the project id is not changing between runs. If I remove the `depends_on` inside `rancher2_cluster.main` this will not happen. Unsure if this is an issue with the provider or terraform core.

**Comment by rawmind0** [comment]
`data.rancher2_project.system.id` is a computed argument, it is known after apply. For some reason, it seems terraform is detecting any change on rancher2_bootstrap.admin and  it's getting updated. 

Anyway, this dependency seems weird. I think better scope would be that the rancher2 provider depends on rancher2 bootstrap provider and remove this dependency on data source. Something like that.

```
provider "rancher2" {
  alias = "bootstrap"

  api_url   = "https://rancher.my-domain.com"
  bootstrap = true
}

# Create a new rancher2_bootstrap using bootstrap provider config
resource "rancher2_bootstrap" "admin" {
  provider = "rancher2.bootstrap"

  password = "blahblah"
  telemetry = true
}

# Provider config for admin
provider "rancher2" {
  alias = "admin"

  api_url = rancher2_bootstrap.admin.url
  token_key = rancher2_bootstrap.admin.token
  insecure = true
}
```

**Comment by nathankodilla** [comment]
This is what I have currently for providers (omitted it above) which is close to what you are recommending:

```hcl
provider "rancher2" {
  alias     = "bootstrap"
  api_url   = "https://${var.rancher_domain}"
  bootstrap = true

  version = "~> 1.8.3"
}

provider "rancher2" {
  api_url   = rancher2_bootstrap.admin.url
  token_key = rancher2_bootstrap.admin.token

  version = "~> 1.8.3"
}
```

I added the `depends_on = [rancher2_bootstrap.admin]` because I was experiencing an issue. I don't recall exactly what at this moment, but I believe it was that the data resource was being called before being bootstrapping occurred.

**Comment by rawmind0** [comment]
Got it. But seems weird, due to the dependency is implicit on the provider config. It depends of rancher2_bootstrap, data source dependency shouldn't be needed. Could you please try without dependency and confirm the issue??

Additionally, if you are using system project, you don't need project data source due to it can be also get from cluster data source https://www.terraform.io/docs/providers/rancher2/d/cluster.html#system_project_id
