### ISSUE TITLE
[amazonec2_config]Cannot add tags for existing nodes

### ISSUE THREAD

**Issue by angeloudy** [rancher/terraform-provider-rancher2#351]
I just tried adding some tags for my ec2 nodes.
And `terraform` apply succeeded, but no tags were added to my ec2 instances.
When add more nodes, it did add tags to the new ec2 instances.
I presume when I added tags to my `rancher2_node_template`, terraform only updates the template in rancher, and won't do anything to the ec2 instances.

Is this something that can be improved, either in rancher or in this provider?

**Comment by rawmind0** [comment]
That's the expected behaviour. Existing nodes will not get updated fields from `rancher2_node_template` until they will be redeployed. This is how node_templates works at Rancher.
