### ISSUE TITLE
`zone` shouldn't be a required argument for amazonec2_config

### ISSUE THREAD

**Issue by angeloudy** [rancher/terraform-provider-rancher2#352]
```
 amazonec2_config {
    ami =  "<AMI_ID>"
    region = "<REGION>"
    security_group = ["<AWS_SECURITY_GROUP>"]
    subnet_id = "<SUBNET_ID>"
    vpc_id = "<VPC_ID>"
    zone = "<ZONE>"
  }
```
It doesn't make sense to me that `zone` is a required argument in `amazonec2_config` because avalability zone can is already determined by the `subnet_id`.
Same with `vpc_id`.

When you create an EC2 instance with terraform, you don't need to specify either `vpc_id` or `availability_zone`, then we need them here? unless they also serve some other purposes.

Another weird thing with this `zone` config is that it only accepts `a, b, c, d`; it's neither `availability_zone` or `availability_zone_id`, which forced me to use the following ugly line to get the value
```
zone = substr(data.aws_subnet.rancher-subnet[count.index].availability_zone, length(data.aws_subnet.rancher-subnet[count.index].availability_zone) -1, -1)
```
Is this something that can be improved or I am understanding it wrong?

**Comment by rawmind0** [comment]
`zone` values are not limited to `a,b,c,d` as you mentioned. What value do you need on it?? Have you check some value and got refused?? 

On Rancher, it's set by default as `a` as you can check on Rancher API, https://<RANCHER>/v3/schemas/amazonec2config

**Comment by angeloudy** [comment]
@rawmind0 
My point is that `zone` shouldn't be needed here at all. But it's a required argument.

**Comment by rawmind0** [comment]
As mentioned, `zone` value is required by Rancher API, setting `a` as default value.

**Comment by rawmind0** [comment]
Please, reopen issue if needed.
