### ISSUE TITLE
Can't create a node with `node_taints`

### ISSUE THREAD

**Issue by nikita-voronoy** [rancher/terraform-provider-rancher2#353]
After adding a nested block with node_taints, I got an error from terraform:

```bash
An argument named "node_taints" is not expected here. Did you mean to define a
block of type "node_taints"?
```

Terraform version = Terraform v0.12.25
Rancher2 provider = v1.8.3

```bash
resource "rancher2_node_pool" "worker" {
  for_each = local.subnet_for_az
  cluster_id       = rancher2_cluster.test.id
  name             = "worker-${each.key}"
  hostname_prefix  = "worker-${each.key}"
  node_template_id = rancher2_node_template.worker[each.key].id
  quantity         = var.worker_pool_count_per_az
  control_plane    = false
  etcd             = false
  worker           = true
  node_taints = []
}
```

UP: Same for `delete_not_ready_after_secs`

**Comment by rawmind0** [comment]
`node_taints` is a list not and array, bad notation on your resource definition. Also, it has a couple of required arguments, https://www.terraform.io/docs/providers/rancher2/r/nodePool.html#node_taints-1

Could you try with something like that 

```
  node_taints {
    key = "KEY"
    value = "VALUE"
  }
```

**Comment by nikita-voronoy** [comment]
@rawmind0 thank you,

  node_taints {
    key = "Key"
    value = "Value"
    effect = "NoSchedule"
  }
Works for me!

**Comment by rawmind0** [comment]
Please, reopen issue if needed.
