### ISSUE TITLE
rancher2_cluster_logging - fluentd_config - compress boolean is ignored

### ISSUE THREAD

**Issue by chrisreed87** [rancher/terraform-provider-rancher2#356]
Setup a basic rancher2_cluster logging resource, with `compress=false`

```
 resource "rancher2_cluster_logging" "test" {
   cluster_id = <cluster_id>
   name = "test"
   kind = "fluentd"
   output_flush_interval = 60
   enable_json_parsing = true
   fluentd_config {
     fluent_servers {
       endpoint = "fluentd-aggregator.fluentd-aggregator.svc.cluster.local:80"
     }
     compress = false
   }
 }
```

Terraform applies successfully, but compress is still set to true (the default). Subsequent re-applies will always show a change being made.

**Comment by rawmind0** [comment]
Known issue that will be addressed on next provider release, once PR https://github.com/rancher/types/pull/1083 is included on Rancher

**Comment by rawmind0** [comment]
PR #362 already merged on master to address this issue. Please reopen issue if needed.
