### ISSUE TITLE
Update project

### ISSUE THREAD

**Issue by hyunsun** [rancher/terraform-provider-rancher2#357]
How can we update the existing project?
Rancher seems to create another project with duplicate name instead of updating the existing project.

**Comment by rawmind0** [comment]
Was the project created by terraform or manually?? If manually, you should import it first, https://www.terraform.io/docs/providers/rancher2/r/project.html#import

**Comment by hyunsun** [comment]
Thanks, I confirmed that the project created by Terraform can be updated.
