### ISSUE TITLE
timeout waiting for app state to become active

### ISSUE THREAD

**Issue by angeloudy** [rancher/terraform-provider-rancher2#359]
I got the following error when I was using `rancher2_app` to deploy my application because some of my pods failed to start.
```
Error: [ERROR] waiting for app (p-wr9zv:demo-qa) to be created: timeout while waiting for state to become 'active' (last state: 'installing', timeout: 10m0s)
```
First of all, I wonder if we can add an option to disable the waiting. In my case, the failure of the pods are expected, but I still want terraform to return success. 

Second, this error also cause other problems.
I found when I tried to deploy it again, terraform would complain that the app already exists
```
Error: Bad response statusCode [409]. Status [409 Conflict]. Body: [baseType=error, code=AlreadyExists, message=apps.project.cattle.io "demo-qa" already exists] from [https://rancher.xxx.xxx/v3/project/c-rqqbn:p-wr9zv/apps]
```

Then I tried to import the app into terraform, but I got the error `Error: Resource already managed by Terraform`

**Comment by rawmind0** [comment]
Submitted PR #381 adding `wait` argument (default true) to `rancher2_app` resource and saving app state before wait

**Comment by rawmind0** [comment]
Pr #381 is merged on master. Please, reopen issue if needed
