### ISSUE TITLE
Is there a "local user" resource?

### ISSUE THREAD

**Issue by jgreat** [rancher/terraform-provider-rancher2#36]
Is there a way to create local users?

Need a way to create local "API" users for automation. These should not be tied to any external auth provider.

**Comment by rawmind0** [comment]
Not yet. This feature is on the way.

**Comment by headcr4sh** [comment]
The (now unmaintained / deprecated) Rancher2 provider plugin that I was using before this official provider plugin was born, has the functionality to manage local Rancher2 users.

Maybe it can be of use (e.g. copying the functionality over should be quite easy):
https://github.com/iplabs/terraform-provider-rancher2/blob/master/rancher2/resource_user.go

Without a corresponding "Token" local users are probably not very useful, so we should also add this functionality:
https://github.com/iplabs/terraform-provider-rancher2/blob/master/rancher2/resource_token.go

**Comment by rawmind0** [comment]
Issue fixed with PR #61 .

Please, reopen issue if needed.
