### ISSUE TITLE
Application deployed by terraform cannot be upgrade from UI

### ISSUE THREAD

**Issue by angeloudy** [rancher/terraform-provider-rancher2#360]
I have just tried using `rancher2_app` to deploy some applications on rancher, and I found that apps deployed by terraform cannot be upgraded from the UI.
When I clicked the three dot --> Upgrade, nothing happens.
If I deploy my application by hand from UI, I have no problem upgrading it.
Is this expected behavior?

**Comment by rawmind0** [comment]
Apps deployed by terraform can be upgrade from UI as well. Just tested and it's working in the same way that is working if app is deployed from the UI. 

Once app is deployed using terraform, i can update it to next version 1.9.2

```
resource "rancher2_app" "foo" {
  catalog_name = "library"
  name = "foo"
  description = "Terraform app test"
  project_id = "project_id"
  template_name = "docker-registry"
  template_version = "1.8.1"
  target_namespace = "namespace"
  answers = {
    "ingress_host" = "test.xip.io"
  }
}
```

What is the app you are getting this issue?? Could you please provide more detailed info to be able to reproduce the issue??

**Comment by angeloudy** [comment]
I found it is quite inconsistent, even with the apps deployed by hand.
I guess it has nothing to do with this terraform provider. Closing it
