### ISSUE TITLE
Add refresh to rancher2_app

### ISSUE THREAD

**Issue by angeloudy** [rancher/terraform-provider-rancher2#368]
If I deploy app from rancher UI, there's button I can click to refresh the catalog.
Can we have the same option in `rancher2_app`?
I have integrated terraform with our CICD pipeline. The pipeline often fails because template version not found error.

I did find a refresh option in `rancher2_catalog`, but that is not gonna work for me because the catalog is not managed by terraform.

**Comment by rawmind0** [comment]
Have you consider to import catalog to be managed by terraform and refresh it??  Or include a Rancher API call  on your pipeline to refresh used catalog?? `rancher2_app` doesn't implement refresh action on Rancher API.
