### ISSUE TITLE
Ability to define global scope roles in rancher2_role_template

### ISSUE THREAD

**Issue by axeal** [rancher/terraform-provider-rancher2#370]
As custom global role creation was introduced in Rancher v2.4.0, support for this should be added in the rancher2 rancher2_role_template resource https://www.terraform.io/docs/providers/rancher2/r/roleTemplate.html

gz#10716

gz#13391

**Comment by rawmind0** [comment]
This feature will be added soon to the provider

**Comment by gregsidelinger** [comment]
Any ETA on when this will be added?

**Comment by m4ce** [comment]
@rawmind0 - any chance we could have this feature in the next release?

**Comment by ernst-at-tv2** [comment]
what's the status?

**Comment by rawmind0** [comment]
The feature is already merged and will be included in the next provider release.
