### ISSUE TITLE
Add GCE rancher2_node_template

### ISSUE THREAD

**Issue by kubaracek** [rancher/terraform-provider-rancher2#372]
GCE seems not to be supported yet

**Comment by fabrinator** [comment]
AFAIK this is not avaiable on rancher right now..
https://github.com/rancher/rancher/issues/23218
So on the rancher provider, it wont be.

**Comment by rawmind0** [comment]
@kubaracek, as @fabrinator mentioned GCE is not supported by Rancher. Take a look, https://github.com/rancher/rancher/issues/4711
