### ISSUE TITLE
terraform import  rancher2_namespace mutates cluster id to some other id

### ISSUE THREAD

**Issue by haisumb** [rancher/terraform-provider-rancher2#377]
This is really weird one but I am running this on command line:

```
terraform import rancher2_namespace.ou-support-redis c-vnttw.redis
```

and it fails with this error:
```
Error: Bad response statusCode [404]. Status [404 Not Found]. Body: 
[message=clusters.management.cattle.io "c-wl7f8" not found, baseType=error, code=NotFound] from [https://rancher.org.com/v3/clusters/c-wl7f8]
```

What is  **c-wl7f8**? I checked on Rancher UI, there's no cluster with id c-wl7f8.

Attached are trace logs.

[rancher_import.txt](https://github.com/terraform-providers/terraform-provider-rancher2/files/4837911/rancher_import.txt)

**Comment by rawmind0** [comment]
Yeah, it's weird. Taking a look to the logs, I'm guessing that may be the error is coming from the tf file. How looks like the `rancher2_namespace.ou-support-redis` definition on your tf file?? `project_id` value??

**Comment by haisumb** [comment]
@rawmind0 Sorry for late reply. Here are relevant Terraform resources:

```hcl
resource "rancher2_cluster" "ou-support" {
  name        = "ou-support"
  description = "ou-support cluster"
}

resource "rancher2_project" "ou-support-Filestreamer" {
  name       = "Filestreamer"
  cluster_id = rancher2_cluster.ou-support.id
}

resource "rancher2_namespace" "ou-support-redis" {
  name       = "redis"
  project_id = rancher2_project.ou-support-Filestreamer.id
}
```
Interestingly, I deleted ou-support cluster from Rancher UI. Re-imported it. Then everything worked as expected and I was able to import namespace with new cluster id.

**Comment by rawmind0** [comment]
I guess it was some inconsistency on tf and tfstate files. Please, reopen issue if needed.
