### ISSUE TITLE
Error: Rancher is not ready: Doing get: Get https://<my.rancher.host>/ping: net/http: request canceled while waiting for connection

### ISSUE THREAD

**Issue by mihard** [rancher/terraform-provider-rancher2#378]
Hi

I encountered rather a stupid issue after I moved my terraform project to a new machine. (Ubuntu 20.04) 

```
Error: Rancher is not ready: Doing get: Get https://<my.rancher.host>/ping: net/http: request canceled while waiting for connection

on init.tf line 37, in data "rancher2_namespace" "fe-ns":
  37: data "rancher2_namespace" "fe-ns" {
```

With the same code on a nearby desktop in the same LAN - I have no problems at all, everything works well. 
I just run out of ideas about what can be the reason and how to investigate the issue. 
The URL is accessible, I can get the response in the same terminal with `curl`

Terraform versions: 0.12.25 and 0.12.28 - same behavior 
the plugin - 1.8.3

**Comment by fabrinator** [comment]
Maybe on that terminal where you are lunching the curl is using a proxy that has access to rancher. Otherwise, talk with you networking team. But, I do not think that this is a issue related with the provider...
