### ISSUE TITLE
[Suggestion] New acceptance test mode that uses a cluster member token

### ISSUE THREAD

**Issue by armsnyder** [rancher/terraform-provider-rancher2#391]
My team uses Rancher primarily for its control plane multi-tenancy features. We give everyone the builtin "Cluster Member" role, so they may create a project and stay mostly isolated. Recently we tried using this Terraform provider as Cluster Member and ran into some issues (#388, #389, #390). I expect that we're going to encounter more.

Firstly, I was wondering if perhaps we are not using this provider as intended. Can someone more familiar with this project comment on whether Cluster Members should be able to use the provider?

I looked at the acceptance tests and it seems like all run using admin credentials. What do you think about adding a new test mode that uses a Cluster Member token? We can run the same acceptance tests twice, with different tokens, and include a way for tests to opt out of being run with the Cluster Member token. Maybe something like:

```go
func TestAccRancher2Bootsrap_basic(t *testing.T) {
	testAccSkipClusterMember(t)
	resource.Test(t, resource.TestCase{ ...
```

I'm interested in hearing your thoughts. Thanks!

**Comment by rawmind0** [comment]
@armsnyder, we had issues with non admin roles, but they seems addressed. The provider can be used with any access role level, but obviously some tasks will not be allowed based on access role.

At the moment, not easy to implement and i don't see much value on running provider acceptance test with distinct access roles.
