### ISSUE TITLE
Cannot change default revision for rancher2_cluster_template

### ISSUE THREAD

**Issue by caiconkhicon** [rancher/terraform-provider-rancher2#393]
I have a `rancher2_cluster_template` resource with 2 revisions, one of them has `default = true`. One revision (doesn't matter which one) is used to create a managed cluster.
Now I want to swap the default revision, so I set one revision to `default = false` and vice versa for the other. Terraform apply fails with the error:
```
message=Cannot update the clusterTemplateRevision until Clusters are referring it]
```

No config is changed for both revisions. Meanwhile, I can change the default revision on the Rancher UI (https://rancher.com/docs/rancher/v2.x/en/admin-settings/rke-templates/creating-and-revising/#setting-a-template-revision-as-default). Thus, I think that this is not a limitation of Rancher, but a bug in the Rancher2 provider.

Please check it. Thanks a lot.

**Comment by caiconkhicon** [comment]
Another test I did is:

- Create a template with one revision as default
- Use the revision to create a managed cluster
- Add a new revision and apply using Terraform
- On Rancher UI, change the new revision to be default
- Change Terraform code to reflect the change above (new revision is default, old one is not)
- Apply Terraform -> Terraform wants to update the "default" value of both revisions even though in fact they are updated via Rancher UI already -> Confirm apply: fails with the same above error

**Comment by rawmind0** [comment]
@caiconkhicon , the issue has been reproduced. Submitted PR #395 to address it

**Comment by caiconkhicon** [comment]
@rawmind0 : thanks a lot for your quick fix. I confirm that it works. I close this issue.

**Comment by abhi1693** [comment]
@rawmind0 I am facing this exact same issue with `v1.10.3`. In my case, I only have a single default template. I'm trying to creating a newer one with slightly different configuration changes. If I give a new name, I get `Cannot update the clusterTemplateRevision until Clusters are referring it`. If I do not make changes to the name, as per terraform the update is a success however there is no change on Rancher. If you need me to provide more information, let me know.

**Comment by rawmind0** [comment]
@abhi1693 , not fully understand what are you trying to do. If you can provide the intial cluster_template definition and the updated definition, it would be useful
