### ISSUE TITLE
Cannot move existing namespace to a project

### ISSUE THREAD

**Issue by dhiman-halder** [rancher/terraform-provider-rancher2#394]
There seems to be no way to move a namespace pre-created using kubectl (and unassigned to any project) to a project within the cluster. Is there an equivalent to the cli ./rancher namespace move command in terraform?

**Comment by spencergilbert** [comment]
you can use the `terraform import` command to do so, as seen in https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/namespace#import

**Comment by rawmind0** [comment]
@dhiman-halder , as @spencergilbert mentioned, if resource is not created with terraform, you should import it first, before you can manage it from terraform. Please, reopen issue if needed.
