### ISSUE TITLE
[Docs] Registry sidebar uses camel-cased resource names

### ISSUE THREAD

**Issue by nikkelma** [rancher/terraform-provider-rancher2#396]
Sidebar on <https://registry.terraform.io/providers/rancher/rancher2> uses for example `rancher2_cloudCredential` instead of `rancher2_cloud_credential`.

Image for reference:
![Screen Shot 2020-07-26 at 13 39 30](https://user-images.githubusercontent.com/16194510/88485650-715f8580-cf45-11ea-88e3-6c20e33bf62c.png)

**Comment by nikkelma** [comment]
Took a look at the docs code and only saw `rancher2.erb` that specifies underscore-delimited names, so I'm guessing these sidebar entries are auto-generated. I'm unfamiliar with that system, happy to investigate and make a PR when I get the time but figured I'd at least document this for anyone interested.

**Comment by rawmind0** [comment]
Issue is related to the new terraform registry doc format, https://www.terraform.io/docs/registry/providers/docs.html
PR #395 is updating docs format. Please reopen issue if needed.
