### ISSUE TITLE
rancher2_token does not apply labels

### ISSUE THREAD

**Issue by Fresa** [rancher/terraform-provider-rancher2#398]
The documentation indicates that labels can be defined as arguments.
https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/token

When defining labels, they are identified in the plan but they never get applied onto the token resource in kubernetes,.

```
resource "rancher2_bootstrap" "admin" {
  provider = rancher2.bootstrap
  password = "admin"
}

resource "rancher2_token" "test" {
  provider = rancher2.admin
  cluster_id = "local"
  labels = {
    "foo" = "bar"
  }
}
```

![image](https://user-images.githubusercontent.com/1190300/88539666-f617d580-d011-11ea-83c4-5a7593e4a6eb.png)

`$ kubectl get token/token-g6gkp -o yaml:`
![image](https://user-images.githubusercontent.com/1190300/88539421-80ac0500-d011-11ea-8cac-d2723b2c2c4a.png)

I have tried setting labels on the rancher2_namespace resource, and that works as expected.

Versions
======
```
$ terraform version
Terraform v0.12.29
+ provider.rancher2 v1.9.0
```
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

```
```
$ docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:46 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by rawmind0** [comment]
@Fresa , we can reproduce your issue with token labels. However, it seems to be an issue on Rancher API, due to same behaviour using Rancher API directly. This issue should be opened on Rancher repo. In the meanwhile, we'll update the docs to set token labels as attribute instead of argument.

**Comment by rawmind0** [comment]
PR #409 is updating `rancher2_token` docs. Please reopen the issue if needed.
