### ISSUE TITLE
rancher2_cluster_sync errors if cluster deleted out of band

### ISSUE THREAD

**Issue by armsnyder** [rancher/terraform-provider-rancher2#401]
**Bug Description**

Terraform fails while reading initial state (as part of running apply or destroy) if the Terraform configuration includes a `rancher2_cluster_sync` resource for a cluster that was deleted out of band (not using Terraform). This contradicts expected Terraform provider behavior, where a resource not existing should silently remove that resource from Terraform state, without erroring.

**Reproduce Steps**

Declare a `rancher2_cluster_sync` for an existing cluster.

```hcl
resource "rancher2_cluster_sync" "this" {
  cluster_id = "c-xxxxx"
}
```

Run `terraform apply`

Delete the cluster in the Rancher UI

Run `terraform destroy`

Error:

```sh
rancher2_cluster.this: Refreshing state... [id=c-xxxxx]
rancher2_cluster_sync.this: Refreshing state... [id=c-xxxxx]

Error: Bad response statusCode [404]. Status [404 Not Found]. Body: [baseType=error, code=NotFound, message=clusters.management.cattle.io "c-xxxxx" not found] from [https://example.com/v3/clusters/c-xxxxx]
```

**Provider version**
rancher2 v1.7.1

**Comment by armsnyder** [comment]
By the way this is true for other resources too, like `rancher2_namespace`. Not sure if it should be considered the same bug or a different bug.

```sh
rancher2_cluster.this: Refreshing state... [id=c-xxxxx]
rancher2_namespace.istio_system: Refreshing state... [id=istio-system]

Error: Bad response statusCode [404]. Status [404 Not Found]. Body: [code=NotFound, message=clusters.management.cattle.io "c-xxxxx" not found, baseType=error] from [https://example.com/v3/clusters/c-xxxxx]
```

**Comment by rawmind0** [comment]
@armsnyder , issue has been reproduced. PR #408 should address it.

**Comment by rawmind0** [comment]
@armsnyder PR is merged to master. Please, reopen issue if needed.
