### ISSUE TITLE
Documentation about cluster template revision questions is ambiguous

### ISSUE THREAD

**Issue by gladavius** [rancher/terraform-provider-rancher2#403]
**Terraform Version**
Terraform v0.12.28

**ProviderVersion**
provider.rancher2 1.9.0

**Affected Resource(s)**
rancher2_cluster_template

**Problem**
As per the documentation : 
```questions - (Optional) Cluster template questions (list)```

So my first thought was to do something like this : 
```
questions = [
  {
    default = ""
    variable = "rancherKubernetesEngineConfig.cloudProvider.azureCloudProvider.aadClientId"
  },
  {
    default = ""
    variable = "rancherKubernetesEngineConfig.cloudProvider.azureCloudProvider.aadClientSecret"
  }
]
```

But it appears that questions have to be declared this way : 
```
questions {
    default = ""
    variable = "rancherKubernetesEngineConfig.cloudProvider.azureCloudProvider.aadClientId"
 }
 questions {
    default = ""
    variable = "rancherKubernetesEngineConfig.cloudProvider.azureCloudProvider.aadClientSecret"
  }
```

**Request**
Documentation should be modified to avoid ambiguity, maybe with an example snippet

**Comment by rawmind0** [comment]
@gladavius thanks for your feedback on this. 

I don't think this is ambiguous, documentation is specifying the terraform type used on every argument. The way that you mention works for defining `questions` argument, is the only way to define [typelist](https://www.terraform.io/docs/extend/schemas/schema-types.html#typelist) and [typeset](https://www.terraform.io/docs/extend/schemas/schema-types.html#typeset) with not [primitive-types](https://www.terraform.io/docs/extend/schemas/schema-types.html#primitive-types) elements on terraform. Just on `rancher2_cluster_template` resource, same notation is needed for `members`, `template_revisions`, `cluster_config.cluster_auth_endpoint`,...

Others list examples are available on the documentation, take a look to `targets` and `answers` arguments on [rancher2_multi_cluster_app example](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/multi_cluster_app#example-usage)
