### ISSUE TITLE
addons_include doesn't work using local file path

### ISSUE THREAD

**Issue by chrisreed87** [rancher/terraform-provider-rancher2#406]
Tried a few iterations to use an addons_include manifest locally, in the cluster_template resource:

```
      rke_config {
        addons_include = [
          "./config-map.yml"
        ]
```
```
      rke_config {
        addons_include = [
          file("config-map.yml")
        ]
```
Both error in the `rke-user-includes-addons-pod`:
```
error: no objects passed to apply
```

Using a gist or URL will still work however.

**Comment by rawmind0** [comment]
This is the expected behaviour, rke cluster can't access local files, but yes gist or URL. Local files should work fine if you use [`addons`](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster#addons) instead, due to is copying the file content

**Comment by rawmind0** [comment]
Please, reopen issue if needed.
