### ISSUE TITLE
Project Monitoring doesnt upgrade

### ISSUE THREAD

**Issue by Arola1982** [rancher/terraform-provider-rancher2#407]
When changing versions of the monitoring terraform shows it modifying the project resource, but in actual fact the resource in rancher stays on the current version.

Shouldnt this trigger a redeploy of the later version?

**Comment by armsnyder** [comment]
Possible duplicate of #376?

**Comment by rawmind0** [comment]
PR #409 is merged to master and should address this issue. Please reopen it if needed.
