### ISSUE TITLE
Setting ignore_docker_version to false is not applied to cluster

### ISSUE THREAD

**Issue by jwwaltoncredera** [rancher/terraform-provider-rancher2#41]
**Terraform Versions**
Terraform v0.11.13
rancher2 v1.2.0

**Terraform Configuration File**
```
resource "rancher2_cluster" "rancher2-cluster" {
  name        = "${var.rancher_cluster_name}"

  cluster_auth_endpoint {
    enabled = true
  }

  rke_config {
    ignore_docker_version = false
    kubernetes_version    = "${var.kubernetes_version}"

    authentication {
      strategy = "x509|webhook"
    }

    ingress {
      provider = "nginx"
    }

    monitoring {
      provider = "metrics-server"
    }

    network {
      plugin = "canal"

      options {
        flannel_backend_type = "vxlan"
      }
    }

    services {
      etcd {
        backup_config {
          enabled        = true
          interval_hours = 12
          retention      = 6
        }

        creation  = "12h"
        retention = "72h"
        snapshot  = false

        extra_args {
          election-timeout   = "5000"
          heartbeat-interval = "500"
        }
      }

      kube_api {
        pod_security_policy     = false
        service_node_port_range = "30000-32767"
      }

      kubelet {
        fail_swap_on = false
      }
    }
  }
}
```

**Expected Behavior**
`ignore_docker_version` to be set to false

**Actual Behavior**
`ignore_docker_version` is set to true
The initial plan has `false` for the `ignore_docker_version`
And subsequent plans indicate the needed change `rke_config.0.ignore_docker_version:         "true" => "false"` and the apply indicates a successful change.  But checking the config in Rancher still has `ignore_docker_version: true`.

**Additional Context**
Rancher - v2.2.4
Kubernetes - v1.13.5-rancher1-2

**Comment by rawmind0** [comment]
@jwwaltoncredera, you are right. Golang `Marshal` function from `encoding/json` omits false bool if `omitempty` is set, https://github.com/golang/go/issues/13284#issuecomment-157288425

It's a bug on rancher API definition. Thanks for the feedback, i'll submit a PR on rancher types repo to address it.

**Comment by ajfriesen** [comment]
Just ran into this today.

Is there already an issue in rancher which will track this?

**Comment by rawmind0** [comment]
PR #362 already merged on master to address this issue. Please reopen issue if needed.
