### ISSUE TITLE
Rancher cluster cluster_template_questions questions is ambiguous

### ISSUE THREAD

**Issue by ashokf458** [rancher/terraform-provider-rancher2#411]
Terraform Version
Terraform v0.12.29

ProviderVersion
provider.rancher2 1.0.0

Affected Resource(s)
rancher2_cluster

Problem
As per the documentation :
cluster_template_questions - (Optional) Cluster template questions. Just for Rancher v2.3.x and above (list)

So my run was something like below:
```
cluster_template_questions = [
  {
    default = "<azureClientId value>"
    variable = "rancherKubernetesEngineConfig.cloudProvider.azureCloudProvider.aadClientId"
  },
  {
    default = "<azureClientSecret value>"
    variable = "rancherKubernetesEngineConfig.cloudProvider.azureCloudProvider.aadClientSecret"
  }
]
```

Error: 
```
Error: Unsupported argument

  on main.tf line 18, in resource "rancher2_cluster" "cluster_az":
  18:   cluster_template_questions = [

An argument named "cluster_template_questions" is not expected here. Did you
mean to define a block of type "cluster_template_questions"?
```

According to explanation in #403, refering the example of `targets` and `answers` in [multi_cluster_app](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/multi_cluster_app#example-usage) :

I also tried the following:
```
cluster_template_questions = {
    default = "<azureClientId value>"
    variable = "rancherKubernetesEngineConfig.cloudProvider.azureCloudProvider.aadClientId"
 }
 cluster_template_questions = {
    default = "<azureClientsecret value>"
    variable = "rancherKubernetesEngineConfig.cloudProvider.azureCloudProvider.aadClientSecret"
  }
```

Error: 
```
Error: Attribute redefined

  on main.tf line 22, in resource "rancher2_cluster" "cluster_az":
  22:   cluster_template_questions = {

The argument "cluster_template_questions" was already set at main.tf:18,3-29.
Each argument may be set only once.
```

I think it is best to give an example as to how to get this to work in case of multiple questions in the RKE template defined in Rancher server. Ideally, list should be as should be expected, a list. But multiple declarations is also fine so long as they are not considered as redefinition as can be seen above.

**Comment by rawmind0** [comment]
> According to explanation in #403, refering the example of `targets` and `answers` in [multi_cluster_app](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/multi_cluster_app#example-usage) :
>
> I also tried the following:
> ```
> cluster_template_questions = {
>    default = "<azureClientId value>"
>    variable = "rancherKubernetesEngineConfig.cloudProvider.azureCloudProvider.aadClientId"
> }
> cluster_template_questions = {
>    default = "<azureClientsecret value>"
>    variable = "rancherKubernetesEngineConfig.cloudProvider.azureCloudProvider.aadClientSecret"
>  }
> ```

@ashokf458 , It seems you are adding an extra `=` in your cluster_template_questions definition, may be that's why they are considered as redefinition.

accorddingly  to #403 
```
questions {
    default = ""
    variable = "rancherKubernetesEngineConfig.cloudProvider.azureCloudProvider.aadClientId"
 }
 questions {
    default = ""
    variable = "rancherKubernetesEngineConfig.cloudProvider.azureCloudProvider.aadClientSecret"
 }
```
accorddingly to `targets` example at [multi_cluster_app](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/multi_cluster_app#example-usage), 

```
  targets {
    project_id = "<project_id1>"
  }
  targets {
    project_id = "<project_id2>"
  }
```

> I think it is best to give an example as to how to get this to work in case of multiple questions in the RKE template defined in Rancher server. Ideally, list should be as should be expected, a list. But multiple declarations is also fine so long as they are not considered as redefinition as can be seen above.

A list at terraform is what it is, the documentation is not ambiguous. I mean, this is the expectable from a list using terraform configuration language. There are few examples about how to express a list on the docs, as referred at https://github.com/rancher/terraform-provider-rancher2/issues/403#issuecomment-666522771 . Anyway, we are more than happy to accept PR to improve the provider.

Closing this issue due to it's duplicated. Please continue this thread at https://github.com/rancher/terraform-provider-rancher2/issues/403
