### ISSUE TITLE
Does  Rancher Terraform provider support KMS key in EC2 node template introduce in Rancher 2.4.6 ?

### ISSUE THREAD

**Issue by panho66** [rancher/terraform-provider-rancher2#413]
Does  Rancher Terraform provider support KMS key in EC2 node template introduce in Rancher 2.4.6 ?

https://github.com/rancher/rancher/issues/27015

**Comment by rawmind0** [comment]
KMS key will be supported by the provider once Rancher 2.4.6 is released.

**Comment by rawmind0** [comment]
PR #415 added this feature. It's included on provider v1.10.1 Please, reopen issue if needed.
