### ISSUE TITLE
Rancher2 terraform failed to set up Rancher monitoring correctly. Behaviour different to UI

### ISSUE THREAD

**Issue by panho66** [rancher/terraform-provider-rancher2#414]
Rancer2 terraform provider 1.9

Set up monitoring via UI with additional 3 name/values pairs
alertmanager.enabled = true
alertmanager.replicaCount = 2
operator.alertmanager.enabled = true

 Notices there is no alert set up yet only default alerts but not notifier set up
![image](https://user-images.githubusercontent.com/15118220/89723390-de404880-da38-11ea-8e44-f22c987e4516.png)

Alertmanager comes up to 2 instances
![image](https://user-images.githubusercontent.com/15118220/89723822-9c1a0580-da3e-11ea-8439-4c422411da11.png)

Set up monitoring with terraform

  cluster_monitoring_input {
    answers = {
      "exporter-kubelets.https" = true
      "exporter-node.enabled" = true
      "exporter-node.ports.metrics.port" = 9796
      "exporter-node.resources.limits.cpu" = "500m"
      "exporter-node.resources.limits.memory" = "512Mi"
      "grafana.persistence.enabled" = false
      "grafana.persistence.size" = "10Gi"
      "grafana.persistence.storageClass" = "default"
      "operator.resources.limits.memory" = "500Mi"
      "prometheus.persistence.enabled" = "false"
      "prometheus.persistence.size" = "50Gi"
      "prometheus.persistence.storageClass" = "default"
      "prometheus.persistent.useReleaseName" = "true"
      "prometheus.resources.core.limits.cpu" = "1500m",
      "prometheus.resources.core.limits.memory" = "1758Mi"
      "prometheus.resources.core.requests.cpu" = "1000m"
      "prometheus.resources.core.requests.memory" = "1256Mi"
      "prometheus.retention" = "72h"
      "alertmanager.enabled"  = "true"
      "alertmanager.replicaCount" = "2"
      "operator.alertmanager.enabled" = "true"
    }
    version = "0.1.1"
  }

**Altermanager comes up with 2 instances but then destroy automatically.** 

There is no way to set up 2 instances of alertmanager automatically without manual fix after monitoring enable. It is kind of defect of the whole automation and causing Rancher monitoring single point of failure. 
https://github.com/rancher/rancher/issues/28308

**Comment by rawmind0** [comment]
PR #409 is fixing cluster and project monitoring config and upgrade. It should address your issue. Please reopen it if needed.
