### ISSUE TITLE
Failed to install provider in 0.13

### ISSUE THREAD

**Issue by ghost** [rancher/terraform-provider-rancher2#417]
hi, 

i just upgraded my terraform client from 0.12.28 to 0.13. 

i'm using a versions.tf file in a module and copy paste the example from https://registry.terraform.io/providers/rancher/rancher2/latest.

versions.tf
`terraform {
  required_providers {
    rancher2 = {
      source = "rancher/rancher2"
      version = "1.10.0"
    }
  }
}`

when i run `terraform init` i get following output ...

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/rancher2...
- Finding hashicorp/kubernetes versions matching "1.12.0"...
- Finding hashicorp/helm versions matching "1.2.4"...
- Finding latest version of -/helm...
- Finding latest version of -/kubernetes...
- Finding latest version of -/rancher2...
- Finding rancher/rancher2 versions matching "1.10.0"...
- Installing hashicorp/helm v1.2.4...
- Installed hashicorp/helm v1.2.4 (signed by HashiCorp)
- Installing -/helm v1.2.4...
- Installed -/helm v1.2.4 (signed by HashiCorp)
- Installing -/kubernetes v1.12.0...
- Installed -/kubernetes v1.12.0 (signed by HashiCorp)
- Installing -/rancher2 v1.10.0...
- Installed -/rancher2 v1.10.0 (signed by HashiCorp)
- Installing rancher/rancher2 v1.10.0...
- Installed rancher/rancher2 v1.10.0 (signed by a HashiCorp partner, key ID 2EEB0F9AD44A135C)
- Installing hashicorp/kubernetes v1.12.0...
- Installed hashicorp/kubernetes v1.12.0 (signed by HashiCorp)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/plugins/signing.html

Warning: Additional provider information from registry

The remote registry returned warnings for registry.terraform.io/-/rancher2:
- For users on Terraform 0.13 or greater, this provider has moved to
rancher/rancher2. Please update your source in required_providers.

Error: Failed to install providers

Could not find required providers, but found possible alternatives:

  hashicorp/rancher2 -> terraform-providers/rancher2

If these suggestions look correct, upgrade your configuration with the
following command:
    terraform 0.13upgrade .

am i doing something wrong? thanks for the help

**Comment by amnk** [comment]
We got behind this by doing 0.13upgrade, but it still fails with 
```

 Error: [ERROR] No api_url provided
 
  on <empty> line 0:

   (source code not available)
```

**Comment by bartlomiejjaroszewski** [comment]
@rawmind0 is there any chance you could take a look into this issue? If needed I can provide debug log as well.

**Comment by kcraley** [comment]
@amnk, I originally had the same error return on a plan/apply however, I was providing a "bootstrap" alias for the provider similar to the documentation.

```
# Configure the Rancher2 provider to bootstrap and admin
# Provider config for bootstrap
provider "rancher2" {
  alias = "bootstrap"

  api_url   = "https://rancher.my-domain.com"
  bootstrap = true
}

# Create a new rancher2_bootstrap using bootstrap provider config
resource "rancher2_bootstrap" "admin" {
  provider = "rancher2.bootstrap"

  password = "blahblah"
  telemetry = true
}
```

After removing the `alias` on the provider and the `provider` on the resource, everything planned/applied properly.

**Comment by mo-moneyy** [comment]
I am getting the same error as OP. Worked fine on Terraform 0.12.26... upgraded to 0.13 and get the error

With the provider at the root module level, the following error is received:

`Error: Failed to install providers`

`Could not find required providers, but found possible alternatives:`

 `hashicorp/rancher2 -> terraform-providers/rancher2`

It then says to run ` terraform 0.13upgrade ../../` to fix the issue. I run it, it puts the provider at the **child module** level which is obviously problematic, especially with 0.13.

**Comment by mo-moneyy** [comment]
> We got behind this by doing 0.13upgrade, but it still fails with
> 
> ```
> 
>  Error: [ERROR] No api_url provided
>  
>   on <empty> line 0:
> 
>    (source code not available)
> ```

@amnk This is most likely because your rancher provider config... ie:
`provider "rancher2" {`
`  api_url    = "https://rancher.my-domain.com"`
`  access_key = var.rancher2_access_key`
`  secret_key = var.rancher2_secret_key`
`}`
 is at the root module level, but the required providers block with rancher2 is at the child level. I ran into this when I ran their recommended command to fix it.

**Comment by ranchersvet** [comment]
I will attach it to support request gz#11920

**Comment by rawmind0** [comment]
Hi, we've tested the upgrade process and should work fine, just defining `version.tf` like that

```
terraform {
  required_providers {
    rancher2 = {
      source = "rancher/rancher2"
      version = "1.10.0"
    }
  }
}
```

I'm guessing this issue may be related to something specific at your installations. 

The `Could not find required providers` issue that you are having is mentioned at [terraform upgrade guide](https://www.terraform.io/upgrade-guides/0-13.html#explicit-provider-source-locations) , 
> `If you are using providers that now require an explicit source location to be specified, terraform init will produce an error like the following:`  

Updating version.tf to proper definition should address the `Could not find required providers` error. 

Multiple dirs installations are not directly supported by, [`terraform 0.13upgrade`](https://www.terraform.io/docs/commands/0.13upgrade.html#batch-usage), there is `batch-usage` but in dev mode. Please, check and review If `terraform 0.13upgrade` is moving or creating new `version.tf` files on proper folders. I'm guessing this may be the reason about  `No api_url provided` error, Ex: provider configuration at root folder but provider explicit definition at child folder. Reallocating provider explicit definition at root level should fix it.

More info at [terraform upgrade guides](https://www.terraform.io/upgrade-guides/0-13.html)

**Comment by mo-moneyy** [comment]
> Hi, we've tested the upgrade process and should work fine, just defining `version.tf` like that
> 
> ```
> terraform {
>   required_providers {
>     rancher2 = {
>       source = "rancher/rancher2"
>       version = "1.10.0"
>     }
>   }
> }
> ```
> 
> I'm guessing this issue may be related to something specific at your installations.
> 
> The `Could not find required providers` issue that you are having is mentioned at [terraform upgrade guide](https://www.terraform.io/upgrade-guides/0-13.html#explicit-provider-source-locations) ,
> 
> > `If you are using providers that now require an explicit source location to be specified, terraform init will produce an error like the following:`
> 
> Updating version.tf to proper definition should address the `Could not find required providers` error.
> 
> Multiple dirs installations are not directly supported by, [`terraform 0.13upgrade`](https://www.terraform.io/docs/commands/0.13upgrade.html#batch-usage), there is `batch-usage` but in dev mode. Please, check and review If `terraform 0.13upgrade` is moving or creating new `version.tf` files on proper folders. I'm guessing this may be the reason about `No api_url provided` error, Ex: provider configuration at root folder but provider explicit definition at child folder. Reallocating provider explicit definition at root level should fix it.
> 
> More info at [terraform upgrade guides](https://www.terraform.io/upgrade-guides/0-13.html)

@rawmind0 Thanks for looking into this. Though even following the instructions for upgrading Terraform 0.13, you are always prompted to run a Terraform upgrade. 

With this setup below at the **root** level, you will still be prompted to run a Terraform upgrade. With a root module calling a child module config, Terraform will refuse to initialize unless the Rancher2 provider resides at the child level. 
```terraform {
  required_providers {
    rancher2 = {
      source = "rancher/rancher2"
      version = "1.10.0"
    }
  }
}
provider "rancher2" {
api_url = "https://rancher.my-domain.com"
access_key = var.rancher2_access_key
secret_key = var.rancher2_secret_key
}
```

If you run that terraform upgrade, a version.tf will get created at the child level with the explicit providers block changing from `source = "rancher/rancher2"` to `source="terraform-providers/rancher2"`.

The provider will not let you run a Terraform apply unless that version.tf with `source="terraform-providers/rancher2"` is at the child level. And then once you do run that, Terraform 0.13 will error saying that all providers need to be at the root level.

**Comment by rawmind0** [comment]
@tigerkeeper5 , if you are using tf modules, they should updated them one by one. Every single tf module should have its own `version.tf` file with 0.13 notation with all required providers.

Provider upgrade on tf modules has been also successfully tested, as example take a look at [tf-module-rke-cluster](https://github.com/rawmind0/tf-module-rke-cluster) . This tf module  is working fine on tf 0.13 and 0.12 (just showing a warning)

> If you run that terraform upgrade, a version.tf will get created at the child level with the explicit providers block changing from source = "rancher/rancher2" to source="terraform-providers/rancher2".

If `terraform 0.13upgrade` is making that change, then something is going wrong.  As mentioned, source should be `source = "rancher/rancher2"` . It should be defined in every single `version.tf` that load the provider, child and/or root. BTW `terraform 0.13upgrade` execution is not mandatory, `version.tf` files can be updated manually instead of it.

Please, review your tf module structure and your `version.tf` files. 

It seems the issue is not related with the provider upgrade, rather with the way terraform is upgrading modules at some circumstances. I think the issue should be also opened at [new terraform issue](https://github.com/hashicorp/terraform/issues/new/choose)

**Comment by Jasper-Ben** [comment]
> We got behind this by doing 0.13upgrade, but it still fails with
> 
> ```
> 
>  Error: [ERROR] No api_url provided
>  
>   on <empty> line 0:
> 
>    (source code not available)
> ```

I ran into a similar issue. In my case it seems that trying to hand over the api_url etc. to the child module broke things.

Before:
```
module "foo" {
  source            = "bar"
  api_url            = var.rancher_api_url
  token_key       = var.rancher_token_key
}
```
After: 
```
module "foo" {
  source = "bar"
}
```

**Comment by rawmind0** [comment]
@Jasper-Ben , as mentioned, if `terraform 0.13upgrade` is doing these changes, something is wrong with it. Have you tried adding module vars again?? Module vars should be in the same place than before, adding `version.tf` with required providers on all modules (root and child)

**Comment by Jasper-Ben** [comment]
> @Jasper-Ben , as mentioned, if `terraform 0.13upgrade` is doing these changes, something is wrong with it. Have you tried adding module vars again?? Module vars should be in the same place than before, adding `version.tf` with required providers on all modules (root and child)

As mentioned in my last comment, I resolved it, seemingly by removing the variables from the modules. The whole transition was kinda messy though, so I am not sure that's what did the trick in the end. But it works for us now.

**Comment by rawmind0** [comment]
Agreed, tf upgrade is being messy. It seems `terraform 0.13upgrade` is not working fine when applied on nested modules.

Please, reopen issue if needed.

**Comment by nitingadekar** [comment]
> verything planned/applied properly.

This worked for me, Thanks for the solution

**Comment by iTaybb** [comment]
I second @kcraley 's fix. Removing the alias on the provider and the provider on the resource fixes the issue.
The documentation is broken for tf>=0.13

**Comment by m-uwh** [comment]
Hello,

I've got the same Issue. Removing the alias fixed it for me. How to update the documentation?
https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/bootstrap

**Comment by jrodonnell** [comment]
Adding another workaround for now, tested using terraform 1.2.5. Add this into a `version.tf` file in the root directory of the project:

```
terraform {
  required_providers {
    rancher2 = {
      source = "rancher/rancher2"
      version = "1.24.0"
    }
  }
}
```

If you have child modules in the repo also using the `rancher2` provider, add identical `version.tf`s into each of their folders as well.

I'm not sure whether the issue is on Hashicorp's side or Rancher's, but it seems like the terraform cli just can't find the rancher2 provider by default.
