### ISSUE TITLE
Openstack node template does not support application credentials.

### ISSUE THREAD

**Issue by vasiczech** [rancher/terraform-provider-rancher2#418]
Rancher v2.4.5 
Terraform v0.12.24, provider.rancher2 v1.9.0

```
source "rancher2_node_template" "openstack-cloud" {
  name = "opnestack-cloud"  openstack_config {
    application_credential_id = "abc..."
    application_credential_name = "credname"
    application_credential_secret = "xyz..."
    auth_url = "https://..."
    # no username 
    # no password
    ...
  }
}
```
Attributes `application_credential_*` are not supported. However, Rancher can use this method of logging in to Openstack instead of a username / password.

**Comment by rawmind0** [comment]
Yeah, these features are not supported yet. These will be implemented on next provider releases.
