### ISSUE TITLE
Breaking change to rancher2_cluster_sync ID in v1.11 pre-release

### ISSUE THREAD

**Issue by armsnyder** [rancher/terraform-provider-rancher2#419]
Hi,

I noticed a potentially breaking change to the `rancher2_cluster_sync` resource was merged recently: https://github.com/rancher/terraform-provider-rancher2/commit/5d652277e405504308a84f39efe9afaef16bc9fe#diff-64cfe614b85a1d9a4b7f52aeb31a308eR79

Changing the ID format is listed as a potentially breaking change in [Hashicorrp's versioning best practices](https://www.terraform.io/docs/extend/best-practices/versioning.html#example-major-number-increments):

> Increasing the MAJOR number is intended to signify potentially breaking changes.
> Within Terraform provider development, some examples include:
> * Changing resource ID format

If we can revert the ID format change prior to the next release, that would be great.

**Comment by rawmind0** [comment]
Hi @armsnyder , thanks for reporting that. 

It's not a real breaking change due to `rancher2_cluster_sync` resource just exist on tf state. Anyway, the change was introduced trying to solve other issue but not really needed anymore. Change reverted.

**Comment by armsnyder** [comment]
It broke my TF because I had a reference to `id` elsewhere in my TF module. ;)
