### ISSUE TITLE
terraform resource to assign membership to a cluster.

### ISSUE THREAD

**Issue by annerajb** [rancher/terraform-provider-rancher2#42]
I been looking but I don't this this exists today.

Is there a way for me from a terraform to a assign member users / ldap/azure ad groups to a cluster?
It seems I have to create the clusters using terraform and then go to the website to manually add the correct membership.

**Comment by rawmind0** [comment]
@annerajb, you can use [rancher2_cluster_role_template_binding](https://www.terraform.io/docs/providers/rancher2/r/clusterRole.html) and/or  [rancher2_project_role_template_binding](https://www.terraform.io/docs/providers/rancher2/r/projectRole.html) to assign rancher users/groups to a cluster or a project respectively.

**Comment by rawmind0** [comment]
Please, reopen issue if needed.

**Comment by annerajb** [comment]
If I assign a member to a cluster as read only is it suppose to grant him access to all other clusters or projects?
I am using the AzureAD provider with the setting for allowing access to rancher2 of authorized users and group members.
But it seems that either AzureAD setting grants global access or this binding membership is not working and it just sets global permissions.

**Comment by rawmind0** [comment]
What kind of bindings are you using for your users/groups?? There are 3 bindings, global (for global permissions), cluster (for cluster permissions) and project (for project permissions). https://rancher.com/docs/rancher/v2.x/en/admin-settings/rbac/

**Comment by annerajb** [comment]
in this case I am trying to configure azuread global binding to that all users of a group are made global admin of the rancher install.

```
resource "rancher2_cluster_role_template_binding" "admins-global" {
  name = "admins"
  cluster_id = rancher2_cluster.new-cluster.id
  role_template_id = "admin"
  group_principal_id = "azuread_group://admin_group_id"
}
```
