### ISSUE TITLE
Creating a rancher2_registry results in runtime error.

### ISSUE THREAD

**Issue by MG2R** [rancher/terraform-provider-rancher2#427]
When creating a couple rancher2_registry resources, I got a couple errors (one for each resource) like these:

```
24-Aug-2020 13:38:52 | module.rancher_cluster.module.k8s_workspace[<wsname>].rancher2_registry.registry_credentials[<rcname>]: Creation complete after 0s [id=<wsname>:<rcname>]
-- | --
24-Aug-2020 13:38:52 |  
24-Aug-2020 13:38:52 | Error: Provider produced inconsistent result after apply
24-Aug-2020 13:38:52 |  
24-Aug-2020 13:38:52 | When applying changes to
24-Aug-2020 13:38:52 | module.rancher_cluster.module.k8s_workspace[<wsname>].rancher2_registry.registry_credentials[<rcname>],
24-Aug-2020 13:38:52 | provider "registry.terraform.io/rancher/rancher2" produced an unexpected new
24-Aug-2020 13:38:52 | value: Root resource was present, but now absent.
24-Aug-2020 13:38:52 |  
24-Aug-2020 13:38:52 | This is a bug in the provider, which should be reported in the provider's own
24-Aug-2020 13:38:52 | issue tracker.
24-Aug-2020 13:38:52 |  
24-Aug-2020 13:38:52 | make: *** [apply-plan] Error 1
```

The resources in question were actually successfully created in Rancher.
Manually re-applying fixed one of the error, another required me to remove the created Registry Credentials. The code that makes these resources looks like:

```terraform
resource "rancher2_registry" "registry_credentials" {
  for_each = var.registry_credentials

  name = each.key

  project_id = rancher2_project.project.id
  namespace_id = rancher2_namespace.namespace.id

  registries {
    address = each.value.address
    username = each.value.username
    password = each.value.password
  }
}
```

The weird thing is that ever since that first batch which resulted in errors, I've been able to destroy and create registry credentials without any issues whatsoever. I haven't been able to reproduce the error consistently.

Creating a bug report in case anyone else runs into this. If I see it popping up again, I'll try to get more useful reproduction steps.

**Comment by rawmind0** [comment]
It seems a race condition, tf file content has been modified during apply execution. I'm guesssing due to `var.registry_credentials` value. When apply started the plan was create a new resource that is not there when apply finished. How are you updating these values??

**Comment by MG2R** [comment]
My Terraform runs are performed by a CI/CD pipeline which decrypts secrets, runs a `terraform plan` against the code in question, and saves that plan. After verification of the plan output, a go is given and the pipeline then runs `terraform apply` against the previously-made plan.

I was the only one using the pipeline at the time, and all configuration (including encrypted secret values) are committed in the repository. The pipeline runs all steps for a given commit, so as far as I can tell it's pretty much impossible the input variables for terraform changed during the run.

**Comment by matttrach** [comment]
The last comment on this issue was 4 years ago, but I will say that I have encountered things like this when dynamically generating sets that are used in for_each loops. While the data may be the same, sometimes converting an unordered list to a set or working with a list of objects can result in Terraform getting confused. Once it interacts with the set it will cache it in state and this won't be an issue, so generally I only see this on new deployments. That said, I am going to close this as stale, please open a new issue if you are still having issues with this and we will work on a solution together.
