### ISSUE TITLE
Manual LDAP service account credential entry is still required when using rancher2_auth_config_activedirectory resource

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/terraform-provider-rancher2#429]
When using the rancher2_auth_config_activedirectory resource in the Rancher2 terraform provider, after the initial deployment it is still required to log in with the local admin and re-input the LDAP service account credentials before it works.  It would be great if this step was no longer needed.

Screenshot below is the rancher2_auth_config_activedirectory configuration:

![image](https://user-images.githubusercontent.com/55704795/91064178-f0a3b000-e5fc-11ea-8580-ee5e07123b49.png)

gz#11487

**Comment by ajureeruja** [comment]
I'm also experiencing this problem.

**Comment by david-maumenee** [comment]
Be aware that if you re-input the LDAP service account credentials in the UI into "Your Username" and "Your Password" after log in with the local admin, **this service account become the rancher admin**.

https://github.com/rancher/rancher/issues/27620

The Rancher API that perform this is https://my-rancher-dns-name/v3/activeDirectoryConfigs/activedirectory?action=testAndApply
It takes 4 parameters :
- activeDirectoryConfig
- enabled (boolean)
- password
- username

To improve the terraform provider, consider to add two new parameters : the rancher admin ldap username and password

**Comment by rawmind0** [comment]
Issue reproduced, working on fix.

**Comment by rawmind0** [comment]
Submitted PR https://github.com/rancher/terraform-provider-rancher2/pull/481 to fix this issue

**Comment by rawmind0** [comment]
PR #481 merged.
