### ISSUE TITLE
Support labels and taints for rke_config

### ISSUE THREAD

**Issue by luhahn** [rancher/terraform-provider-rancher2#430]
Hi I've just seen, that rke supports labels and taints for the nodes to be set. Would it be possible to include these settings into rancher2_cluster.rke_config? Just saw that only gke_config supports this.

**Comment by rawmind0** [comment]
Hi @luhahn , Rancher2 doesn't manage the nodes for rke clusters. The way to add nodes into a cluster is executing on them the `node_command` generated when the cluster is created. https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/custom-nodes/

The provider works on the same way, when a cluster is created, `node_command` is generated.  You should execute it on rke nodes adding rke roles and labels and taints are already supported. You just should concat something like `--label <name>=<value> --taints <name>=<value>:<action>` with the `node_command`

**Comment by luhahn** [comment]
Hi thank you for clarifying that :) I think i missunderstood the way rke_config was meant to work.

However i now ended up using the rke provider to configure my nodes and importing them in the rancher2 provider by using .cluster_registration_token[0].insecure_command and my generated kubeconfig from the rke provider with a local-exec.
