### ISSUE TITLE
GlobalDNS Provider and entries

### ISSUE THREAD

**Issue by abhi1693** [rancher/terraform-provider-rancher2#439]
I have been using this provider pretty much since it was released. And, I have been waiting for several months for [PR #253](https://github.com/rancher/terraform-provider-rancher2/pull/253) to be merged and released. Is there a plan on doing so?

**Comment by rawmind0** [comment]
Waiting for PR #253

**Comment by rawmind0** [comment]
PR #253 has been superseded by PR #551
