### ISSUE TITLE
Unable to disable node draining in rancher2_cluster

### ISSUE THREAD

**Issue by ryanelliottsmith** [rancher/terraform-provider-rancher2#440]
**Steps to reproduce** 

1. Apply TF code to create node_pool, node_template and cluster with drain enabled:
```
provider "rancher2" {
  api_url    = "https://xxxxx"
  token_key = "xxxxx"
}

resource "rancher2_cluster" "custom" {
  name = "custom-rke"
  description = "custom cluster"
  rke_config {
    network {
      plugin = "canal"
    }
    upgrade_strategy {
      drain = true
    }    
  }
}
resource "rancher2_node_template" "aws" {
  name = "aws-nt"
  description = "test"
  amazonec2_config {
    access_key = "XXXX"
    secret_key = "XXXX"
    ami =  "XXXX"
    instance_type = "XXXX"
    region = "XXXX"
    security_group = ["XXXX"]
    subnet_id = "XXXX"
    vpc_id = "XXXX"
    zone = "a"
  }
}
resource "rancher2_node_pool" "aws-np" {
  cluster_id =  rancher2_cluster.custom.id
  name = "aws-np"
  hostname_prefix =  "tf-"
  node_template_id = rancher2_node_template.aws.id
  quantity = 3
  control_plane = true
  etcd = true
  worker = true
}
```
2.  Wait for Rancher to create and reconcile cluster
3. Confirm that `drain nodes` is "true" from within Rancher
4. Modify TF code to set drain=false within the upgrade_strategy and apply with `terraform apply`
```
      rke_config {
        upgrade_strategy {
          drain = false
        }
```
5. Note that `drain nodes` is still "true"

**Versions**
Rancher - v2.4.5
Terraform - v0.12.20
rancher2 provider - v1.10.1

gz#12021

**Comment by rawmind0** [comment]
@ryanelliottsmith , as [`upgrade_strategy.drain`](https://github.com/rancher/types/blob/release/v2.4/client/management/v3/zz_generated_node_upgrade_strategy.go#L12) go struct is defined as bool with json:"drain,omitempty" yaml:"drain,omitempty" on Rancher API, `drain = false` is treated as empty value and it's omitted on API request when json is marshalled. This issue should be open on [Rancher](https://github.com/rancher/rancher) to update `bool` field to `*bool` or to avoid `omitempty` on bool definition on the Rancher API.
