### ISSUE TITLE
Unable to register nodes for custom on premise cluster

### ISSUE THREAD

**Issue by lucasdrai** [rancher/terraform-provider-rancher2#442]
Hello,

When I try to create a custom cluster from existing nodes, I cannot achieve to have my nodes registered by Terraform, I need to use Ansible or to do it manually to execute the "node_command" on each node. 

**What I did:** 
I use the rancher2_cluster resource and fill up the "nodes" part in "rke_config" with the IP nodes, roles, ssh keys, etc. I execute the terraform code and it goes well: no error appears. But the result is that I still have an empty cluster with no nodes registered.

**What I expect:**
I'm expecting an error to tell me that my nodes can't be registered, whatever the reason is OR I expect to see my nodes registered (it would be the best :) ).

So I was wondering if I'm too dumb to use this module or if something is not working properly for this one. 

For information, my nodes are reachable from the server where I execute the terraform code, ssh keys are working and I can make it work without terraform, just by using SSH from my terraform server. 

Thanks in advance for your help.
Regards.

**Comment by rawmind0** [comment]
@lucasdrai , rancher2 provider can manage node-templates and node-pools to deploy vm's and build the k8s cluster from rancher. But it doesn't support ssh access to vm to execute node_command. You could get node_command from rancher2_cluster and use another tf provider to execute node_command on vm's

**Comment by ppiccolo** [comment]
Hello I'm in the same exact situation, now I understand, but please take in consideration this usecase and add the capability to this provider to add nodes too.

**Comment by lucasdrai** [comment]
@rawmind0 Thanks for the quick answer, it confirms what I thought. If it could be an improvement for the future it would be great, especially that the terraform-provider-rke (https://github.com/rancher/terraform-provider-rke) is doing it so the mechanism seems to be there already.
Anyway, thanks again for the quick reply, I'll keep an eye on the evolutions.

Regards.

**Comment by rawmind0** [comment]
@lucasdrai , terraform-provider-rke is doing it due rke is doing it, but Rancher2 is not doing it, due to is the node who connects to Rancher. The provider is working at the same way Rancher2 works. 

We are considering add nodes to the provider, but not a priority at the moment. Anyway, there are some options to do it with terraform: adding `node_command` to vm's cloud_init, using remote provisioner to execute the `node_command`,...

**Comment by ppiccolo** [comment]
I've solved in this way 

```hcl
resource "null_resource" "nodes" {
  for_each = var.vms

  provisioner "remote-exec" {
    connection {
      host = each.value["networks"][0]["ip"]
      user = each.value["user"]
      password = each.value["password"]
    }

    inline = [
      format("%s %s",
        rancher2_cluster.cluster.cluster_registration_token[0]["node_command"],
        join(" ", formatlist("--%s", split(",", each.value["roles"])))
      )
    ]
  }
}

```

**Comment by rawmind0** [comment]
Please, reopen issue if needed.

**Comment by frouzbeh** [comment]
@ppiccolo Hi, I’m doing the same way for rke2 custom cluster. But I’m having trouble to find a way making sure the nodes are active. Something similar to cluster_sync but for nodes. Do you happen to have any suggestions? Thanks

**Comment by Ehsaan-Azizi** [comment]
> I've solved in this way
> 
> ```terraform
> resource "null_resource" "nodes" {
>   for_each = var.vms
> 
>   provisioner "remote-exec" {
>     connection {
>       host = each.value["networks"][0]["ip"]
>       user = each.value["user"]
>       password = each.value["password"]
>     }
> 
>     inline = [
>       format("%s %s",
>         rancher2_cluster.cluster.cluster_registration_token[0]["node_command"],
>         join(" ", formatlist("--%s", split(",", each.value["roles"])))
>       )
>     ]
>   }
> }
> ```

hi @ppiccolo! can you please share more on how you are setting VMs in your var.tf file and passing IP and password? Thanks!
