### ISSUE TITLE
Setting for services.kubeproxy.image  not working

### ISSUE THREAD

**Issue by wd** [rancher/terraform-provider-rancher2#446]
I create a image based on rancher hyperkube image, but seems the settings in this section not working, the kubeproxy container still create from the rancher/hyperkube:v1.17.4-rancher1 image.
```
               ~ kubeproxy {
                     extra_binds = []
                     extra_env   = []
                   + image       = "myimg:v1.17.4"
                 }
```

**Comment by wd** [comment]
I found this comment: https://github.com/rancher/rke/blob/41706a06805559b335fc722f22954c2db7ce5b5a/cluster/defaults.go#L257

So rke don't accept custom images for services now?

**Comment by rawmind0** [comment]
No RKE doesn't accept custom images by service. It's using `SystemImages.Kubernetes` for all services but etcd. `SystemImages.Kubernetes` can be customized at rke, but this provider is not supporting it by the moment.
