### ISSUE TITLE
[Feature Request] Support node templates for custom providers/node drivers

### ISSUE THREAD

**Issue by Dids** [rancher/terraform-provider-rancher2#448]
I use Hetzner Cloud as my primary cloud provider, which has a lot of official support for Kubernetes, as well as community support for Rancher UI/node drivers for template creation.

While I can create custom node templates through Rancher itself, I cannot do it through Terraform, as the Rancher Terraform provider only supports specific cloud providers when creating node templates.

Would it be possible to allow for fully custom/dynamic node templates? Since custom templates are still available through the Rancher API, it should be possible and relatively trivial, at least from a technical perspective.

Right now I'm doing this with just Terraform and RKE (no Rancher), manually creating and configuring my nodes, which works well enough, but I'd definitely appreciate having everything Rancher brings to the table as well.

Lastly, I couldn't figure out if there's a way to import an RKE cluster to Rancher in Terraform, as automating the infrastructure is number one priority right now.

While I did discover [this discussion](https://github.com/rancher/terraform-provider-rancher2/issues/220), and while I'm sure it would help me combine my existing RKE code with Rancher, it still doesn't solve the problem of not being able to utilize custom node templates.

**Comment by rawmind0** [comment]
This topics was previously discussed at #105 . There is no technical problem here, but every single node driver uses its own config, then every single node driver should be coded on the provider. It's a question of hands and priorities.

We are more than happy to collaborate and accept PR adding or improving features. In fact, Hetzner Cloud support was proposed in this PR #216 but unfortunately the author didn't have time to finish it. May be it could be got from there and finished.
