### ISSUE TITLE
Fails convert AzureKubernetesServiceConfig.tags of type map[string]string

### ISSUE THREAD

**Issue by ivanov-aleksander** [rancher/terraform-provider-rancher2#449]
Rancher version: 2.3.5
terraform provider version: 1.10.2

I am trying to use data resource for getting information about AKS `cluster.`

```hcl
data "rancher2_cluster" "cluster" {
  name = var.cluster_name
}
```

Terraform plan and apply fails with error:

```bash
Error: Failed to parse: ...
...
json: cannot unmarshal array into Go struct field AzureKubernetesServiceConfig.tags of type map[string]string
```

Related to Rancher API schema v3/schemas/azureKubernetesServiceConfig :

```
"tags": {

    "create": true,
    "description": "Tags for Kubernetes cluster. For example, foo=bar.",
    "dynamicField": true,
    "type": "array[string]",
    "update": true

}
```

Currenly cluster that i want to use in data resource has such AzureKubernetesServiceConfig.tags
```json
        "tags": [
            "Application_ID=TST-CLUSTER",
            "Business_Unit_Name=Unit_Name",
            "Playbook_Version=1.0.0",
            "Environment=Test",
            "Live=Yes",
            "Application_Name=app TST"
        ]
```

gz#16860

**Comment by ivanov-aleksander** [comment]
If i set empty array in tags terraform will work correctly.
But if i set simple string in tags
```json
        "tags": [
            "Environment=Test"
        ]
```
terraform will fails with error

```bash
json: cannot unmarshal array into Go struct field AzureKubernetesServiceConfig.azureKubernetesServiceConfig.tags of type map[string]string
```

**Comment by ivanov-aleksander** [comment]
It is strange because cluster has the same tags in appliedSpec.genericEngineConfig.tags and rancher provider converts this tags correctly

**Comment by rawmind0** [comment]
@ivanov-aleksander , it seems tags definition is not done fine in your tf file. The tag field is a terraform map `map[string]interface{}` not a []string. Have you tried to define tags like??

```
  tags = {
    "Environment" = "Test"
  }
```

**Comment by ivanov-aleksander** [comment]
@rawmind0  cluster was created from Rancher API and I only want get info from terraform.
Related to Rancher API schema v3/schemas/azureKubernetesServiceConfig  tags are "array[string]" :

```json
"tags": {

    "create": true,
    "description": "Tags for Kubernetes cluster. For example, foo=bar.",
    "dynamicField": true,
    "type": "array[string]",
    "update": true

}
```

**Comment by ivanov-aleksander** [comment]
@rawmind0  i use data resource. There is no tags in it

```hcl
data "rancher2_cluster" "cluster" {
  name = var.cluster_name
}
 ```

**Comment by slessardjr** [comment]
I outlined where I think the problem is in #335 that I reported back in May.
Azure is storing each tag as a string in an array.  You cannot unmarshal that with JSON which is what the provider is trying to do.  I highlighted in my issue what I think needs to be fixed 
@rawmind0 @ivanov-aleksander

**Comment by rawmind0** [comment]
Submitted PR https://github.com/rancher/terraform-provider-rancher2/pull/660 to fix this issue. 

Deprecated `rancher2_cluster.aks_config.tag` argument due to it was not working properly. 
Created new `rancher2_cluster.aks_config.tags` argument to replace `tag`, with the proper `[]string` type to match Rancher API
