### ISSUE TITLE
Allow configuring a CA for etcd S3 backup to a private S3 server

### ISSUE THREAD

**Issue by avthart** [rancher/terraform-provider-rancher2#45]
Will be supported within Rancher 2.2.5 and 2.3.x

See related issues in Rancher and RKE:
https://github.com/rancher/rancher/issues/19222
https://github.com/rancher/rke/issues/1316

**Comment by rawmind0** [comment]
Added support on PR #76

**Comment by avthart** [comment]
thanks @rawmind0

**Comment by rawmind0** [comment]
Merged PR #76. Please, reopen issue if needed.
