### ISSUE TITLE
Monitoring-operator app not upgraded when version is set to new value

### ISSUE THREAD

**Issue by dnoland1** [rancher/terraform-provider-rancher2#450]
To reproduce:
1. On Rancher v2.4.8 with terraform-provider-rancher2 v1.10.2, enable cluster monitoring when deploying a cluster. Use version 0.1.1. Example:
```terraform
resource "rancher2_cluster" "my-cluster" {
  name                      = "mycluster"
  provider                  = rancher2.admin
  description               = "my cluster to test monitoring"
  enable_cluster_monitoring = true
  cluster_monitoring_input {
    answers = {
      "exporter-node.enabled"                   = true
      "exporter-node.resources.limits.memory"   = "400Mi"
      "exporter-node.ports.metrics.port"        = 9796
      "operator.resources.limits.memory"        = "1000Mi"
      "grafana.persistence.enabled"             = false
      "prometheus.resources.core.limits.memory" = "2000Mi"
      "prometheus.persistence.enabled"          = false
      "prometheus.retention"                    = "720h"
    }
    version = "0.1.1"
  }
  enable_cluster_alerting = true
}
```
2. Run `terraform apply`, note older version of monitoring is available and Rancher UI shows that an update is available.
3. Change `version = "0.1.2"` and then `terraform apply`

Go to System project, Apps. Note that `cluster-monitoring` app shows version 0.1.2, but `monitoring-operator` app shows version 0.1.1. Both of these apps should have been upgraded. When doing a monitoring upgrade directly on the UI (Tools -> Monitoring), both apps are upgraded.

Checked networking browser tools, and see two PUT requests when updating version in UI:

PUT | https://redacted.rancher.space/v3/project/c-dw9ls:p-fsjmj/apps/p-fsjmj:cluster-monitoring
PUT | https://redacted.rancher.space/v3/project/c-dw9ls:p-fsjmj/apps/p-fsjmj:monitoring-operator

Is rancher2 terraform provider not calling the PUT for monitoring-operator when the version has changed?

gz#12219

gz#14797

**Comment by rawmind0** [comment]
The provider is using Rancher go api client, in that case, calling the cluster monitoring functions, [`ActionDisableMonitoring`, `ActionEditMonitoring` and/or `ActionEnableMonitoring`](https://github.com/rancher/types/blob/release/v2.4/client/management/v3/zz_generated_cluster.go#L150) , [resource_rancher2_cluster](https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/resource_rancher2_cluster.go#L290

`cluster-monitoring` and `monitoring-operator` charts have the proper dependency defined??

**Comment by fad3t** [comment]
Same issue here, running Rancher 2.4.6 - with Rancher provider 1.10.0 and Terraform 0.13.2.

**Comment by rawmind0** [comment]
Rancher2 provider v1.10.0 is not upgrading monitoring properly. PR [409](https://github.com/rancher/terraform-provider-rancher2/pull/409/commits/7ea4e0df1a9e61914ee439e6f4815a320f1dee00) should address the issue, provider up to v1.10.1, v1.10.2 if Rancher v2.4.8

**Comment by dnoland1** [comment]
Re-tested this on rancher2 terraform provider 1.10.6. Set version = "0.1.1" then changed it to version = "0.1.2". Same result, cluster-monitoring app upgraded:
<img width="615" alt="image" src="https://user-images.githubusercontent.com/468462/99015682-6b001400-250a-11eb-8c08-3f6233157d63.png">
monitoring-operating app not upgraded:
<img width="618" alt="image" src="https://user-images.githubusercontent.com/468462/99015745-79e6c680-250a-11eb-8d4c-e319fcf6aaa4.png">

**Comment by rawmind0** [comment]
The fix is already merged and will be included in the next provider release.

**Comment by jiaqiluo** [comment]
The bug is reproduced on Rancher `v2.4.8` and Terraform rancher2 `v1.11.0`. 

As the screenshot shows, only the upgrade of app `cluster-monitoring` is triggered.

<img width="1118" alt="Screen Shot 2021-02-25 at 8 11 41 PM" src="https://user-images.githubusercontent.com/6218999/109254481-512fc780-77af-11eb-80fd-41c73898cdcd.png">


The bugfix is validated with the self-built provider binary. 

As the screenshot shows, both apps are upgraded to 0.1.2

<img width="1316" alt="Screen Shot 2021-02-25 at 9 05 06 PM" src="https://user-images.githubusercontent.com/6218999/109254599-93f19f80-77af-11eb-9e61-4dac9a2830a5.png">

![image](https://user-images.githubusercontent.com/6218999/109254675-c00d2080-77af-11eb-800b-cbae361f21b4.png)
