### ISSUE TITLE
rancher2_role_template global context

### ISSUE THREAD

**Issue by m4ce** [rancher/terraform-provider-rancher2#451]
Is it possible to add support for the `global` context in `rancher2_role_template`?

When using `rancher2_global_role_binding`, one is unable to use custom global roles templates.

**Comment by rawmind0** [comment]
@m4ce this issue is duplicated by #370 . Please, use #370 for your comments about this topic.

**Comment by m4ce** [comment]
thanks @rawmind0 and sorry for the dup.
