### ISSUE TITLE
Set PodSecurityPolicy for System Project with terraform

### ISSUE THREAD

**Issue by hijmen** [rancher/terraform-provider-rancher2#452]
We are using Terraform to rollout Istio in the System project. We have restrictive PodSecurityPolicies enabled in our cluster. According to this page we need an 'unrestricted' podsecuritypolicy for the System project: https://rancher.com/docs/rancher/v2.x/en/cluster-admin/tools/istio/setup/enable-istio-in-cluster/enable-istio-with-psp/
Am I missing something, or is this not possible with the current Rancher2 Terraform provider?

**Comment by rawmind0** [comment]
You'd need to [import the system project](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/project#import) and set proper [pod_security_policy_template_id](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/project#pod_security_policy_template_id)

**Comment by hijmen** [comment]
We spin up entire clusters (including istio) all the time with a single comand, so an import would require a manual action. 

We fixed the issue by adding an extra rolebinding with an 'unrestricted' podsecuritypolicy to the serviceaccounts in the istio-system namespace on top of the restricted policy using the kubernetes provider:

```
resource "rancher2_namespace" "istio-system" {
  name = "istio-system"
  project_id = var.rancher_system_project_id
  description = "Istio Namespace"
}

resource "kubernetes_role_binding" "istio-unrestricted-rolebinding" {
  metadata {
    name      = "istio-unrestricted-rolebinding"
    namespace = rancher2_namespace.istio-system.name
  }
  role_ref {
    api_group = "rbac.authorization.k8s.io"
    kind      = "ClusterRole"
    name      = "unrestricted-clusterrole"
  }
  subject {
    kind      = "ServiceAccount"
    name      = "default"
    namespace = "istio-system"
  }
  subject {
    ...
  }
}
```
