### ISSUE TITLE
CoreDNS configuration

### ISSUE THREAD

**Issue by m4ce** [rancher/terraform-provider-rancher2#454]
I am trying to figure out how to add stubdomains to coredns. I could use `kubernetes_config_map` resource but the issue is that the configmap itself already exists and would need to be imported first, which sucks.

Is there any way one can configure stubdomains in coredns via this provider?

**Comment by spencergilbert** [comment]
https://rancher.com/docs/rke/latest/en/config-options/add-ons/dns/  has some information on for the RKE configuration around dns - but the provider is fairly limited: https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster#dns

**Comment by m4ce** [comment]
@spencergilbert - I've created a feature request with them, see https://github.com/rancher/rke/issues/2236.

**Comment by matttrach** [comment]
The last comment on this issue was 4 years ago and this question appears to be focused on rke1 which is EOL. I am going to close this issue as stale, but please feel free to open a new issue if this is still a concern.
