### ISSUE TITLE
AKS defaults to AvailabilitySet 

### ISSUE THREAD

**Issue by ams0** [rancher/terraform-provider-rancher2#457]
AKS clusters default to `AvailabilitySet` instead of the more modern `VirtualMachineScaleSets`. I can see that the request sent to Azure doesn't even contain the appropriate key

```
sanitized request body: {"location":"West Europe","tags":{"displayName":"aks"},"properties":{"kubernetesVersion":"1.17.9","dnsPrefix":"aksrancher","agentPoolProfiles":[{"name":"rancher","count":2,"vmSize":"Standard_B4ms","osDiskSizeGB":30,"storageProfile":"ManagedDisks","vnetSubnetID":"/subscriptions/12c7e9d6-967e-40c8-8b3e-4659a4ada3ef/resourceGroups/rancheraks/providers/Microsoft.Network/virtualNetworks/ranchervnet/subnets/ranchersubet","maxPods":110,"osType":"Linux"}],"linuxProfile":{"adminUsername":"rancher","ssh":{"publicKeys":[{"keyData":"ssh-rsa AAAAB3Nza"}]}},"servicePrincipalProfile":{"clientId":"cca39846-4dd8-4a83-a575-753451183da9","secret":"REDACTED"},"addonProfiles":{"httpApplicationRouting":{"enabled":false,"config":null},"omsagent":{"enabled":false,"config":null}},"enableRBAC":true,"networkProfile":{"networkPlugin":"kubenet","podCidr":"172.244.0.0/16","serviceCidr":"10.0.0.0/16","dnsServiceIP":"10.0.0.10","dockerBridgeCidr":"172.17.0.1/16"}}}
```

There should be a `type` for the `AgentPoolType` (https://docs.microsoft.com/en-us/rest/api/aks/agentpools/createorupdate#agentpooltype) property in the agentpool profile.

**Comment by rawmind0** [comment]
The provider is not doing Azure request, it's done by rancher. Have you tested this config using Rancher UI?? Is working on it?? I'm guessing that the issue should be opened on [Rancher](https://github.com/rancher/rancher)

**Comment by ams0** [comment]
Ah! Makes sense now, afaict, rancher still doesn’t do VMSS. Thanks, I’m wrapping my head around rancher+AKS, lots to learn still.

—-
Live long and prosper
________________________________

**Comment by rawmind0** [comment]
Please, reopen issue if needed.
