### ISSUE TITLE
Suggestion: rancher2_app should be deleted if the installation fails

### ISSUE THREAD

**Issue by tibuntu** [rancher/terraform-provider-rancher2#464]
When a rancher2_app resource is applied for the first time, but the installation fails within the default 10 minute timeout, the rancher2 provider throws an error like this:

`Error: [ERROR] waiting for app (p-7sxs7:someapp) to be created: timeout while waiting for state to become 'active' (last state: 'installing', timeout: 10m0s)`

Now after fixing the actual cause (E.g. a faulty docker image tag in the values.yaml) and when re-running the deployment, the subsequent run will fail with the following error:

`Error: Bad response statusCode [409]. Status [409 Conflict]. Body: [message=apps.project.cattle.io "someapp" already exists, baseType=error, code=AlreadyExists] from [https://rancher-url.foo/v3/project/c-5spdc:p-7sxs7/apps]`

It would be awesome to have an argument for the resource like _delete_on_failure_ = true|false or just taint the terraform resource so that it will be deleted before the next run.

**Comment by caiconkhicon** [comment]
I have a same problem.
I would expect it to behave like the "default" behaviour of Terraform: when a resource is created unsuccessfully, it is still a part of the TF state, and marked as "tainted". Thus, when we run TF the next time, the resource would be recreated.

**Comment by rawmind0** [comment]
What provider version are you using??  Provider should save and taint tf state with created app before wait for installed, https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/resource_rancher2_app.go#L64

**Comment by rawmind0** [comment]
Suggestion accepted and included on PR #468

**Comment by caiconkhicon** [comment]
Thanks. I will test the latest version and give feedback asap
