### ISSUE TITLE
Suggestion: Automatically encode to base64 values for secret

### ISSUE THREAD

**Issue by ppiccolo** [rancher/terraform-provider-rancher2#466]
Hi, 

I think that will be useful to automatically encode values of secret passed to data property of rancher2_secret resource.

Take in consideration the following resource creation, where ` each.value["values"]` is a map

```
resource "rancher2_secret" "secret" {
  depends_on = [
    data.rancher2_cluster.cluster,
  ]

  for_each = local.workload_secret_map
  name = each.value["name"]
  data = each.value["values"]
  project_id = rancher2_project.project[each.value["project"]].id
}

```

**Comment by rawmind0** [comment]
Hi, have you tried using terraform `base64encode()` function on each.value on your resource definition??

```
resource "rancher2_secret" "secret" {
  depends_on = [
    data.rancher2_cluster.cluster,
  ]

  for_each = local.workload_secret_map
  name = each.value["name"]
  data = base64encode(each.value["values"])
  project_id = rancher2_project.project[each.value["project"]].id
}
```

**Comment by ppiccolo** [comment]
Hi,

I think that this will not work because in my case `each.value["values"]` is a map like : `{key1: "value1", key2: "value2" }` and if I apply `base64encode`on it, I'll get the whole map (key and value) encoded.


https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/secret

**Comment by rawmind0** [comment]
The change you are suggesting is a breaking change, requiring a resource schema update. 

If `each.value["values"]` is  a map, for sure you could iterate over it using terraform configuration lang and get key/value pairs.
