### ISSUE TITLE
rancher2_app with version specified results in error to create

### ISSUE THREAD

**Issue by MG2R** [rancher/terraform-provider-rancher2#469]
I'm trying to deploy filebeat from the elastic Helm v3 repo. The relevant Terraform code is:

```Terraform
resource "rancher2_catalog" "elastic" {
  name       = "elastic"
  url        = "https://helm.elastic.co"
  branch     = "master"
  scope      = "cluster"
  version    = "helm_v3"
  cluster_id = rancher2_cluster.cluster.id
}

resource "rancher2_app" "stdout_aggregator" {
  name        = "stdout-aggregator"
  description = "Takes logs from stdout and ships them to ELK."

  catalog_name  = rancher2_catalog.elastic.id
  template_name = "filebeat"
  template_version = "7.9.2"

  project_id       = rancher2_project.log_aggregation.id
  target_namespace = rancher2_namespace.log_aggregation.id

  values_yaml = base64encode(templatefile(
    "${path.module}/filebeat_config.yml.tpl",
    {
      logstash_hosts = var.logstash_hosts,
      cluster_name   = rancher2_cluster.cluster.name
    }
  ))
}
```

If this is the first time the app is deployed (i.e. the app is created, not upgraded), I can't specify the `template_version`. If I do specify it, I get the following error during `terraform apply`:

```
Error: Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [message=catalogtemplateversions.management.cattle.io "elastic-filebeat-7.9.2" not found, baseType=error, code=ServerError] from [https://rancher.domain.net/v3/project/c-wbxnd:p-cmrcm/apps]
```

If I don't specify `template_version`, the creation works perfectly. Once the app is created, I can specify the `template_version without issue. This is annoying because I can't reuse this bit of code when rolling out a new cluster. I need to do two runs simply to roll this out. 

Is there a way to fix this? Googling the error got me nowhere.

**Comment by MG2R** [comment]
Further usage/testing seems to suggest that it's because I'm creating the app in the same run where I add the catalog. This means the catalog has not yet been synced by Rancher by the time Terraform tries to start the app. Is there a way to add a delay there?

**Comment by rawmind0** [comment]
Using rancher2_catalog `refresh` argument should force the catalog refresh and should address this, https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/catalog#refresh

**Comment by MG2R** [comment]
Doh, looked over that option. Sorry
