### ISSUE TITLE
Rancher Cluster delivering outdated kube_config

### ISSUE THREAD

**Issue by ajchiarello** [rancher/terraform-provider-rancher2#47]
When creating a new cluster resource, and setting the cluster_auth_endpoint to enabled = true, the kube_config generated doesn't reflect the authorized endpoints immediately. Instead, I have to refresh the resource in order to get the expanded kube_config that includes the endpoints.

**Comment by rawmind0** [comment]
@ajchiarello, the kube_config that includes the endpoint is generated once the cluster is `active`, isn't it?? Are you specifying `cluster_auth_endpoint`-`fqdn` as is recommended on [docs page](https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/options/#local-cluster-auth-endpoint) ??

**Comment by ajchiarello** [comment]
@rawmind0 When I create the cluster, I save the kubeconfig to a Vault secret. The first time I run my terraform script, I don't get the correct kubeconfig - I have to run the script a second time, which refreshes the content of my secret. I'm not specifying a cluster_auth_endpoint; I'm just enabling the feature and using the connection to the controlplane nodes.

**Comment by rawmind0** [comment]
@ajchiarello, the kube_config that already includes the endpoint is generated once the cluster is active?? The second time you run terraform, is the cluster `active`??

**Comment by ajchiarello** [comment]
Yes, the second time I run terraform, the cluster is active.

**Comment by rawmind0** [comment]
@ajchiarello, due to k8s cluster has to be installed and activated, `cluster_auth_endpoint` is not available until k8s cluster is active. 

We are working to add a dummy resource just to wait for a k8s cluster is active.

**Comment by ajchiarello** [comment]
@rawmind0 Thanks. For now, I've worked around my need; since I can now use the cluster as a datasource, I don't need to cache the kubeconfig in Vault. I just pull it from the cluster as needed.

**Comment by rawmind0** [comment]
Nice, datasources are indeed for thinks like that. :)

Closing issue, please reopen it if needed.
