### ISSUE TITLE
Cannot specify SSL certificate bundle for rancher2

### ISSUE THREAD

**Issue by supercoolgreatcoder** [rancher/terraform-provider-rancher2#470]
It's not possible to specify ssl certificate bundle when configuring rancher2. I was able to specify those successfully using the following command:
`docker run -d -p 80:80 -p 443:443 -v $SSL/cacerts.pem:/etc/rancher/ssl/cacerts.pem -v $SSL/private.key.pem:/etc/rancher/ssl/key.pem -v $SSL/domain.cert.pem:/etc/rancher/ssl/cert.pem rancher/rancher:latest`
Is there anything similar in terraform configuration?
I tried specifying `ca_certs` directory, but it crashes terraform:
```
provider "rancher2" {
  alias = "bootstrap"

  api_url  = "https://${var.rancher_server_dns}"
  insecure = false
  ca_certs  = var.ssl_certs_dir  
  bootstrap = true
}
```

**Comment by rawmind0** [comment]
> It's not possible to specify ssl certificate bundle when configuring rancher2. I was able to specify those successfully using the following command:
`docker run -d -p 80:80 -p 443:443 -v $SSL/cacerts.pem:/etc/rancher/ssl/cacerts.pem -v $SSL/private.key.pem:/etc/rancher/ssl/key.pem -v $SSL/domain.cert.pem:/etc/rancher/ssl/cert.pem rancher/rancher:latest`
Is there anything similar in terraform configuration?

Rancher tls config should be specified on [Rancher installation](https://rancher.com/docs/rancher/v2.x/en/installation/). This provider is not installing Rancher. Rancher should be up and running (with the proper tls config) before the provider can be used to bootstrap and/or manage the system.

> I tried specifying ca_certs directory, but it crashes terraform:

As explained in the provider docs, [`ca_certs`](https://registry.terraform.io/providers/rancher/rancher2/latest/docs#ca_certs) is expecting `CA certificates used to sign Rancher server tls certificates` not a cert directory. If Rancher2 tls certificates were signed with a self signed CA, then the provider should be configured providing `ca_certs` or setting [`insecure`](https://registry.terraform.io/providers/rancher/rancher2/latest/docs#insecure) argument to true to be able to connect to the Rancher API.
