### ISSUE TITLE
external_urls for etcd not working

### ISSUE THREAD

**Issue by wd** [rancher/terraform-provider-rancher2#472]
I'm trying to setup a cluster with external etcd cluster, and create a cluster with configs bellow
```
external_urls = 
ca_cert = 
cert = 
key = 
path =
```

then run the register command on a node
```
sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.3.5 --server https://my-server --token my-token --controlplane --worker
```

I'll get this error

```
time="2020-09-29T09:46:36Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering or etcd and controlplane node have to be registered first"
```

Does the `rancher2_cluster` support `external_etcd`?

**Comment by wd** [comment]
If I register a node with `-etcd` argument in the register command, i'll get this error ```Cluster can't have both internal and external etcd```.

**Comment by rawmind0** [comment]
The provider should work fine with `external_etcd`. May be a config issue. Same config is working fine if you create the cluster from the ui?? Is controlplane connecting fine with the external etcd??

**Comment by wd** [comment]
It seems the provider successfully and correctly submitted the settings for the cluster. I think it's just because the rancher server didn't support it? I see [this code](https://github.com/rancher/rancher/blob/master/pkg/controllers/management/clusterprovisioner/provisioner.go#L894) will check if there is any machine has the etcd role, when we use external etcd, there will no machine has that role.

**Comment by rawmind0** [comment]
@wd i guess this config should be supported at Rancher but not pretty sure on that. If provider is submitting settings properly, try opening the issue at rancher/rancher to check if this config is supported
