### ISSUE TITLE
Allow creation of new Microsoft Teams notifier

### ISSUE THREAD

**Issue by Caspila** [rancher/terraform-provider-rancher2#474]
Hello,

I was looking forward to the fix provided in Rancher v2.4 to have a built-in notifier that works with Microsoft Teams (https://github.com/rancher/rancher/issues/15802)

However, it doesn't seem to be possible to create this new notifier via Terraform. Following what seems to be the standard, {type}_config, I tried using both `teams_config` and `msteams_config` within a `rancher2_notifier` scope and neither of them is valid.

Let me know if you need any more information.

Thank you

**Comment by rawmind0** [comment]
Hello @Caspila , no, this config is not valid since MS teams notifier is not yet supported by this provider, https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/notifier 

Working to support it soon.

**Comment by grok-rv** [comment]
Hopefully it will be rolled out soon, as we are trying to use the same from rancher2_notifier for MS teams.

**Comment by rawmind0** [comment]
PR #483 add this feature
