### ISSUE TITLE
Can't enable cloud_provider

### ISSUE THREAD

**Issue by angeloudy** [rancher/terraform-provider-rancher2#475]
I was trying to get persistent volume working on my kubernetes cluster made the following update to my terraform template:
```
rke_config {
    ...
    cloud_provider {
      aws_cloud_provider {}
    }
  }
```

After I ran terraform apply, it tried to upgrade the first controller node and failed and stuck there and the whole cluster became unavailable. Is this something I can update or has to be set on first deploy?

**Comment by rawmind0** [comment]
Cloud provider is something that you can update, but some preparations should be done at the provider before, https://rancher.com/docs/rke/latest/en/config-options/cloud-providers/aws/ https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/cloud-providers/amazon/

Also, cloud provider config seems incorrect, you should define name argument and avoid `aws_cloud_provider` if it's empty. For amazon should be something like,
```
...
    cloud_provider {
      name = "aws"
    }
...
```

**Comment by angeloudy** [comment]
@rawmind0 I think your syntax is for `rke up`, while my one is for terraform template, according to https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster#cloud_provider

**Comment by rawmind0** [comment]
The syntax is the same. The cloud_provider link you attached, shows that `cloud_provider` has the `name` argument. 

```
  rke_config {
    ...
    cloud_provider {
      name = "aws"
    }
  }
```

**Comment by rawmind0** [comment]
Please, reopen issue if needed
