### ISSUE TITLE
Active Directory provider requires local login to function

### ISSUE THREAD

**Issue by David-VTUK** [rancher/terraform-provider-rancher2#476]
# Problem Description

When leveraging the `"rancher2_auth_config_activedirectory" "activedirectory"` resource, local login to re-apply the configured settings is required for AD authentication to work

# Steps to recreate

## Create a AD auth config resource:

```
# Create a new rancher2 Auth Config ActiveDirectory
resource "rancher2_auth_config_activedirectory" "activedirectory" {
  servers = ["myserver"]
  default_login_domain = "mydomain"
  service_account_username = "myuser"
  service_account_password = "mypassword"
  user_search_base = "mybase
  port = 389
}
```

## Apply the configuration

```
rancher2_auth_config_activedirectory.activedirectory: Refreshing state... [id=activedirectory]
rancher2_auth_config_activedirectory.activedirectory: Modifying... [id=activedirectory]
rancher2_auth_config_activedirectory.activedirectory: Modifications complete after 0s [id=activedirectory]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

## Refresh the Rancher login page, logging in via AD is now presented as an option:

![image](https://user-images.githubusercontent.com/5892615/95561336-81e6ae80-0a12-11eb-8d8d-7abc172ccc44.png)

## Attempt to login with an AD user

![image](https://user-images.githubusercontent.com/5892615/95561784-29fc7780-0a13-11eb-9956-f8cbfce190b0.png)

## Log back in as a local user 

Go to security > authentication > click "Save" (without changing any settings)

Re-attempt AD login, after which it will succeed. 

## Example

![login](https://user-images.githubusercontent.com/5892615/95562501-25848e80-0a14-11eb-8e2b-7aa0b436d8c3.gif)

**Comment by mcmcghee** [comment]
Also reported in #429

**Comment by rawmind0** [comment]
@mcmcghee thanks for reporting. This issue is duplicated. 

Already working on a fix for it. Please, follow issue #429
