### ISSUE TITLE
How to wait for cluster to be active

### ISSUE THREAD

**Issue by angeloudy** [rancher/terraform-provider-rancher2#478]
I use rancher2 provider to create my kubernetes clusters.
I also would like to install some application after the cluster is created.
But I always get errors like this ```Error: [ERROR] Creating Namespace: Cluster ID c-9dmf5 is not active```
Is it possible to wait for the cluster to be active before I install anything?

**Comment by rawmind0** [comment]
There are 2 options to do that, that are explained at provider documentation:
- using `rancher2_namespace` [wait_for_cluster](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/namespace#wait_for_cluster) argument
- using [`rancher2_cluster_sync`](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster_sync)
