### ISSUE TITLE
is_default not being honored for private_registries resource

### ISSUE THREAD

**Issue by oxr463** [rancher/terraform-provider-rancher2#485]
Despite `is_default` being set to false, the newly created cluster still attempted to access the private registry when attempting to download system images, causing a failure since the private registry only contains customer application images.

```hcl
rke_config {
  private_registries {
    is_default: false
  }
|
```

versions:
  - terraform: 0.12.24
  - rancher2-terraform-provider: 1.10.3

gz#12537

**Comment by rawmind0** [comment]
[`is_default`](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster#is_default) is false by default and should work fine. Is the provider applying the config properly, have you checked if same cluster config at Rancher UI?? May be docker daemon at k8s nodes configured with a private registry??

**Comment by oxr463** [comment]
> [`is_default`](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster#is_default) is false by default and should work fine. Is the provider applying the config properly, have you checked if same cluster config at Rancher UI?? May be docker daemon at k8s nodes configured with a private registry??

When the new cluster is launched, it never becomes available because it can't find all the images it needs to create the cluster.

**Comment by rawmind0** [comment]
You are not answering any of my questions

**Comment by rawmind0** [comment]
It seems the issue was related to the template config and not the provider. Please reopen if needed
