### ISSUE TITLE
rancher2_cluster_role_template_binding is not working with global admin token for user_id

### ISSUE THREAD

**Issue by ritheshgm** [rancher/terraform-provider-rancher2#488]
Hello Team, 

We were trying to provide the cluster access for the user from AD, We were using global admin_token to perform this task. But it not working and getting below error 

Error: Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [baseType=error, code=ServerError, message=user.management.cattle.io "CN=XXXX,OU=1234,OU=Remote Sites,DC=XXX,DC=com" not found] from [https://rancher-sandbox.com/v3/clusterroletemplatebindings]

But with the same admin token we can able to perform the rolebinding for AD groups. 

main.tf 

resource "rancher2_cluster_role_template_binding" "user_permission" {
  name = "role-bind"
  cluster_id = data.rancher2_cluster.cluster.id
  role_template_id = "projects-view"
  user_principal_id = "activedirectory_user://CN=XXXX,OU=1234,OU=Remote Sites,DC=XXX,DC=com"
}

provider.tf

provider "rancher2" {
  version = "1.10.3"
  api_url   = "https://rancher-sandbox.com/v3/"
  token_key = "admin_token"
  insecure   = true
}

It works when we use other user tokens.

**Comment by rawmind0** [comment]
Hi @ritheshgm , not fully understanding the issue. could you please provide tf file with what is working and what no??

May be this is related to https://github.com/rancher/terraform-provider-rancher2/issues/429 that has been fixed on PR #481 .

**Comment by ritheshgm** [comment]
We are trying to create rancher2_cluster_role_template_binding by providing user_principal_id, 

Main tf : 

resource "rancher2_cluster_role_template_binding" "user_permission" {
name = "role-bind"
cluster_id = data.rancher2_cluster.cluster.id
role_template_id = "projects-view"
user_principal_id = "activedirectory_user://CN=XXXX,OU=1234,OU=Remote Sites,DC=XXX,DC=com"
}

provider.tf

provider "rancher2" {
version = "1.10.3"
api_url = "https://rancher-sandbox.com/v3/"
token_key = "admin_token"
insecure = true
}

By using above configuration we trying to create cluster_role_binding for ldap user, We are getting below error : 

Error: Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [baseType=error, code=ServerError, message=user.management.cattle.io "CN=XXXX,OU=1234,OU=Remote Sites,DC=XXX,DC=com" not found] from [https://rancher-sandbox.com/v3/clusterroletemplatebindings]

Note : For Rancher authentication we are using admin token key. Which is not working.

**Comment by rawmind0** [comment]
> By using above configuration we trying to create cluster_role_binding for ldap user, We are getting below error :
>
>  Error: Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [baseType=error, code=ServerError, message=user.management.cattle.io "CN=XXXX,OU=1234,OU=Remote Sites,DC=XXX,DC=com" not found] from [https://rancher-sandbox.com/v3/clusterroletemplatebindings]

This may be this is related to #429 that has been fixed on PR #481 . Could you please build the provider from master and try if it fix the issue??

> Note : For Rancher authentication we are using admin token key. Which is not working.

Don't understand what that means. Admin user token is not working to authenticate with Rancher or it's not finding ldap user??

**Comment by ritheshgm** [comment]
Admin user token is not able to find ldap user. But it can able to search Ldap groups. 

Working with admin token : 
resource "rancher2_cluster_role_template_binding" "group_permission" {
  name = "role-binding-groups
  cluster_id = data.rancher2_cluster.cluster.id
  role_template_id = "projects-view"
  group_principal_id ="activedirectory_group://CN=X,OU=1234,OU=Messaging,OU=DirectoryApps,DC=XXX,DC=com"
}


Not working with admin token : 
resource "rancher2_cluster_role_template_binding" "user_permission" {
name = "role-bind"
cluster_id = data.rancher2_cluster.cluster.id
role_template_id = "projects-view"
user_principal_id = "activedirectory_user://CN=XXXX,OU=1234,OU=Remote Sites,DC=XXX,DC=com"
}

**Comment by rawmind0** [comment]
Thanks for the clarification @ritheshgm . 

The issue seems related to #429 , next provider release 1.10.4 includes a patch for it.
