### ISSUE TITLE
How to enable monitoring for default/system project

### ISSUE THREAD

**Issue by angeloudy** [rancher/terraform-provider-rancher2#489]
When I create a project with `rancher2_project`, I can enable monitoring for that project by setting `enable_project_monitoring`.
Question is, how do I enable monitoring for the default or system project?

**Comment by rawmind0** [comment]
The projects that hasn't been created with terraform, should be imported into it first

**Comment by angeloudy** [comment]
@rawmind0 The default & system project are created by rancher itself.
My goal is to have everything built from scratch when I run `terraform apply` with all the kubernetes clusters created, all the monitoring enabled, all the apps installed. If I have to manually import the default project, it won't work next time, because terraform will complain that the project already exists

**Comment by rawmind0** [comment]
@angeloudy , i already know that default & system project are created by rancher. I understand your point, but it is what it is at the moment. To manage any resource from terraform you should import it first. Import can be done manually or automated, but for sure should be done just once.
