### ISSUE TITLE
Add support to install Apps from catalog.cattle.io.clusterrepos

### ISSUE THREAD

**Issue by gregsidelinger** [rancher/terraform-provider-rancher2#491]
rancher2_app does not appear to be able to install apps from catalog.cattle.io.clusterrepos in Rancher 2.5.

**Comment by rawmind0** [comment]
No, it's not. `rancher2_app_v2` and `rancher2_catalog_v2` resources will provide Rancher 2.5 support , PR https://github.com/rancher/terraform-provider-rancher2/pull/473

**Comment by gregsidelinger** [comment]
Sorry missed that there was an existing PR, I only looked for open issues.  Now I can't want for the next release.
