### ISSUE TITLE
[Documentation Bug] Formatting issues on the apps and marketplace guide examples

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/terraform-provider-rancher2#492]
While looking at the new documentation guide for the apps and marketplace I noticed the examples are not formatted correctly.

https://registry.terraform.io/providers/rancher/rancher2/latest/docs/guides/apps_marketplace

![Screen Shot 2020-10-29 at 4 55 57 PM](https://user-images.githubusercontent.com/4107699/97636889-bfce6580-1a07-11eb-901b-3ee6bb88547b.png)

**Comment by rawmind0** [comment]
Thanks for the advice @mitchellmaler . Working to address it
