### ISSUE TITLE
rancher2_project wait_for_cluster not working 

### ISSUE THREAD

**Issue by mikekuzak** [rancher/terraform-provider-rancher2#495]
Hi, 

Terraform 0.13.5
I have provisioned a cluster, and trying to create a project via TF. 

The Cluster is created in a module, the rancher2 provider is in the parent main.tf. Also in that parent main.tf I'm trying to create the project using the wait_for_cluster attribute. 

```
resource "rancher2_project" "my-services" {
  provider   = rancher2.admin
  name       = "My Services"
  cluster_id = module.k8s_cluster.cluster_id
  wait_for_cluster = true
}
```

Output:
```
rancher2_project.my-services: Still creating... [10s elapsed]

Error: [ERROR] waiting for cluster ID (c-vhzrj) to be active: Get "https://sbox-k8s:9443/v3/clusters/c-vhzrj": dial tcp 10.132.194.37:9443: connect: connection refused

  on main.tf line 132, in resource "rancher2_project" "my-services":
 132: resource "rancher2_project" "my-services" {
```

**Comment by rawmind0** [comment]
Hi @mikekuzak , it seems your module is unable to connect to rancher API, `Get "https://sbox-k8s:9443/v3/clusters/c-vhzrj: dial tcp 10.132.194.37:9443: connect: connection refused"`
