### ISSUE TITLE
Feature Request: rancher2_app_v2 - set_sensitive (Security information leakage)

### ISSUE THREAD

**Issue by ghost** [rancher/terraform-provider-rancher2#499]
Hello,

at the moment im terraforming the new rancher 2.5 rancher-monitoring.
Sensitive information is leaked via the provider and there is no ability to fix that.

My Setup:
- Rancher 2.5
- rke Kubernetes created via the rancher ui with 1.18.10 k8s

Terraform:
```hcl
resource "rancher2_app_v2" "rancher-monitoring" {
  cluster_id = var.rancher_cluster_id
  name = "rancher-monitoring"
  namespace = "cattle-monitoring-system"
  repo_name = "rancher-charts"
  chart_name = "rancher-monitoring"
  chart_version = "9.4.200"
  values = templatefile("${path.module}/templates/rancher-monitoring.values.yml", {})
}
```
rancher-monitoring.values.yml
```hcl
grafana:
  adminPassword: testpassword
```

When ever i change this password this is shown in the terraform output. I'm missing the feature "set_sensitive" from helm:
https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release

Can you please add this feature :)

Best regards 

Stefan

**Comment by ghost** [comment]
@rawmind0 when i understand your pr right everything from values is now sensitive right?

**Comment by rawmind0** [comment]
> @rawmind0 when i understand your pr right everything from values is now sensitive right?

@oed-mertenss , yes. `values` is a string argument, and with PR is sensitive

**Comment by ghost** [comment]
Thanks that was :rocket: fast :+1:
