### ISSUE TITLE
terraform destroy eks fails with Status [403 Forbidden]

### ISSUE THREAD

**Issue by nkk1** [rancher/terraform-provider-rancher2#50]
when we delete an EKS cluster, the cluster actually gets deleted in the Rancher UI, but terraform does not know that the cluster got deleted in Rancher and it still tries to destroy every 10s. Rancher responds with a "403 Forbidden" error

```
module.k8s-rancher-sz-1.rancher2_cluster.eks_cluster: Destroying... (ID: c-qphhb)
module.k8s-rancher-sz-1.rancher2_cluster.eks_cluster: Still destroying... (ID: c-qphhb, 10s elapsed)
module.k8s-rancher-sz-1.rancher2_cluster.eks_cluster: Still destroying... (ID: c-qphhb, 20s elapsed)
module.k8s-rancher-sz-1.rancher2_cluster.eks_cluster: Still destroying... (ID: c-qphhb, 30s elapsed)
Releasing state lock. This may take a few moments...

Error: Error applying plan:

1 error(s) occurred:

* module.k8s-rancher-sz-1.rancher2_cluster.eks_cluster (destroy): 1 error(s) occurred:

* rancher2_cluster.eks_cluster: [ERROR] waiting for cluster (c-qphhb) to be removed: Bad response statusCode [403]. Status [403 Forbidden]. Body: [baseType=error, code=Forbidden, message=clusters.management.cattle.io "c-qphhb" is forbidden: User "u-67xj8" cannot get resource "clusters" in API group "management.cattle.io" at the cluster scope] from [https://rancher.infra.xxxxx.xxxxxxxx/v3/clusters/c-qphhb]
```

**Comment by rawmind0** [comment]
TF is just checking the state of the cluster every 10s not trying to destroy it again. 

It's weird this result. It seems that your tf user, loose access to the rancher API in the meanwhile the cluster is being removed, `...User "u-67xj8" cannot get resource "clusters" in API group "management.cattle.io" at the cluster scope...` Are tf user permissions modified during the tf execution?? 

Could you please paste your tf file??

**Comment by rawmind0** [comment]
PR #80 fixes this issue

**Comment by rawmind0** [comment]
Please, reopen issue if needed.
