### ISSUE TITLE
auth_config_openldap: Difference between test_username and service_account_distinguished_name

### ISSUE THREAD

**Issue by sbirl** [rancher/terraform-provider-rancher2#501]
I noticed today that a new (to me) argument is required for `auth_config_openldap`: `test_username`.
I assigned it the same variable used to populate `service_account_distinguished_name`, but received a 401 Unauthorized from my LDAP server when executing the code.  I am hoping to understand why this occurred so that I can talk to my LDAP admins to see if permissions are lacking, but Im not sure what the difference between these two arguments are.

**Comment by rawmind0** [comment]
`test_username` and `test_password` are new arguments for openldap auth. They are used by Rancher to test openldap auth. You just need to provide a valid openldap user and password to test the user login to the auth provider. `service_account_distinguished_name` is the service account DN to do the openldap bind, not a username to test the login

**Comment by sbirl** [comment]
Is there a recommended workaround for this?  Or how do I disable this?  We don't do application-specific test user accounts in our environment.

**Comment by rawmind0** [comment]
@sbirl, you just need to provide a valid user/password like is done at [Rancher UI](https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/openldap/#test-authentication) when you configure openldap auth. It's a requirement, due to Rancher is executing `testAndApply` function to test openldap config and login before apply. https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/openldap/

**Comment by MG2R** [comment]
Did Rancher Server change something then? This wasn't the case previously when going through the API.

I'm reluctant to provide a "test user" as when you do this through the UI, the account principal of the test user and that of the built-in admin account get linked and all of a sudden the "test user" is the admin account.

**Comment by SinisterMinister** [comment]
This wasn't the case originally as my module was working correctly with `v1.10.3`. Why is this different now and why is it a **breaking change** with a **patch** increment?

**Comment by sbirl** [comment]
I have to agree with Sinister Minister, here.  I closed this out because I decided to just use local accounts for the time being (in a test environment so I dont care), but Im more than happy/willing to re-open this issue for further evaluation.
