### ISSUE TITLE
unable to use annotations in configuring alerts

### ISSUE THREAD

**Issue by Hkavya1215** [rancher/terraform-provider-rancher2#504]
My code is like below:
I have added the annotations but the message does not showup in slack notifier

resource "rancher2_cluster_alert_rule" "LowDiskSpace" {
  cluster_id = rancher2_cluster_alert_group.default.cluster_id
  group_id = rancher2_cluster_alert_group.default.id
  name = "LowDiskSpace"
  metric_rule {
    expression = <<EOF
      (node_filesystem_free_bytes{fstype=~"ext4|xfs"} / node_filesystem_size_bytes{fstype=~"ext4|xfs"})
    EOF
    duration = "1m"
    comparison = "less-than"
    threshold_value = 20
  }
  severity = "warning"
  labels = {
    test-alert = "true"
  }
  annotations = {
      title = "Low free space on {{ $labels.instance }}"
      description = "On {{ $labels.instance }} device {{ $labels.device }} mounted on {{ $labels.mountpoint }} has low free space of {{ $value }}%"
  }
}

**Comment by rawmind0** [comment]
Using similar code, annotations are set properly at `rancher2_cluster_alert_rule` 

```
resource "rancher2_cluster_alert_rule" "LowDiskSpace" {
  cluster_id = <CLUSTER_ID>
  group_id = <GROUP_ID>
  name = "LowDiskSpace"
  metric_rule {
    expression = <<EOF
(node_filesystem_free_bytes{fstype="ext4|xfs"} / node_filesystem_size_bytes{fstype="ext4|xfs"})
EOF
    duration = "1m"
    comparison = "less-than"
    threshold_value = 20
  }
  severity = "warning"
  labels = {
    test-alert = "true"
  }
  annotations = {
    title = "Low free space on"
    description = "On device mounted on has low free space of"
  }
}
```

Once it's created, i can see annotations set properly from Rancher API

```
{
...
"annotations": {
    "description": "On device mounted on has low free space of",
    "title": "Low free space on"
},
...
}
```

**Comment by Hkavya1215** [comment]
When i run this, i am unable to see it in my notifier (slack) it does not take the annotation value, it displays the default value 

![image](https://user-images.githubusercontent.com/9451731/98338026-83b28a80-202f-11eb-8f63-163963dd4138.png)

**Comment by Hkavya1215** [comment]
I want to pint the message like below in slack.

[FIRING:1] LowDiskSpace @
On abc device /dev/sdb2 mounted on / has low free space of 0.17552972404475542%

**Comment by rawmind0** [comment]
@Hkavya1215 , provider is setting annotations properly at Rancher API. Have you tested if same config is working from Rancher API?? 

The issue seems related with slack configuration at Rancher. It should be opened at rancher/rancher repo.
