### ISSUE TITLE
secret alertmanager config gets overwritten

### ISSUE THREAD

**Issue by Hkavya1215** [rancher/terraform-provider-rancher2#510]
I have enabled monitoring in rancher and trying to set alerts. I have configured alert group and alerts and i have also modified the Secret: alertmanager-cluster-alerting, but this config file always gets overwritten if there is any change in alerts. Please suggest

**Comment by rawmind0** [comment]
If you are using a file to provide secret, try using https://www.terraform.io/docs/configuration/functions/trimspace.html
