### ISSUE TITLE
Rancher 2.5.1 rancher2_app_v2 install of rancher-istio succeeds but returns unexpected value.

### ISSUE THREAD

**Issue by mchnwzrd** [rancher/terraform-provider-rancher2#512]
Hi!  Wanted to share an issue we are seeing when setting up internal Rancher apps via rancher2_app_v2.  Example code:

 

```
# Install new 2.5x Rancher Istio.
resource "rancher2_app_v2" "rancher-istio" {
  count = var.istio_enable ? 1 : 0
  cluster_id    = data.rancher2_cluster.this.id
  name          = "istio-system"
  namespace     = "istio-system"
  project_id    = data.rancher2_project.this.id
  repo_name     = "rancher-charts"
  chart_name    = "rancher-istio"
  chart_version = "1.7.100"

  depends_on = [rancher2_app_v2.rancher-monitoring]
}
```

The install works but this error is returned failing our orchestration:

Provider produced inconsistent result after apply.

`When applying changes to rancher2_app_v2.rancher-istio[0], provider "registry.terraform.io/rancher/rancher2" produced an unexpected new value: Root resource was present, but now absent.  This is a bug in the provider, which should be reported in the provider's own issue tracker.`

Trying to determine if it's something we should move to our own API calls vs Terraform if it's an actual bug.  Thanks!

**Comment by rawmind0** [comment]
Hi @mchnwzrd , when terraform shows errors like  `...produced an unexpected new value..` `...produced inconsistent plan..`, most of the times use to be related to modules sync or vars sync. I guess the issue may be related with `count = var.istio_enable ? 1 : 0`.  Terraform seems updating resource data in the meanwhile is applying. Error is saying that `rancher2_app_v2.rancher-istio` tf definition was there to apply, but it isn't anymore when applied.
