### ISSUE TITLE
v1.10.5 invalid checksum

### ISSUE THREAD

**Issue by jacobwgillespie** [rancher/terraform-provider-rancher2#516]
It appears that the checksum hash may be invalid for the v1.10.5 release - this message is from CI, which is a `linux_amd64` environment:

```
Error: Failed to install provider

Error while installing rancher/rancher2 v1.10.5: checksum list has unexpected
SHA-256 hash 484edfa558f922db9f2534210c3563d908a07021900b8a4e042345f8d360cf96
(expected 68be53c138a9ab4dcc1420eb399d2af90a4e28ad08e7f6363886d2b90729a5a6)
```

The correct hash `484edfa558f922db9f2534210c3563d908a07021900b8a4e042345f8d360cf96` is present in the `SHA256SUMS` file [here](https://github.com/rancher/terraform-provider-rancher2/releases/tag/v1.10.5), but not on the Terraform Registry.

You can see the invalid hash in the registry API response here: https://registry.terraform.io/v1/providers/rancher/rancher2/1.10.5/download/linux/amd64

**Comment by daanemanz** [comment]
I'm getting the same error when using the `rancher/rancher2` provider in one of our repos. Pinning to v1.10.4 works.

**Comment by rawmind0** [comment]
It's an issue on tf registry that is not updating tags properly. Cutting new release v1.10.6

**Comment by rogersd** [comment]
Fantastic, thank you!

**Comment by rawmind0** [comment]
Just as curiosity, setting old source path `source = "terraform-providers/rancher2"` at version.tf, terraform apply gets the binary properly

```
Initializing the backend...

Initializing provider plugins...
- Finding terraform-providers/rancher2 versions matching "1.10.5"...
- Installing terraform-providers/rancher2 v1.10.5...
- Installed terraform-providers/rancher2 v1.10.5 (signed by HashiCorp)


Warning: Additional provider information from registry

The remote registry returned warnings for
registry.terraform.io/terraform-providers/rancher2:
- For users on Terraform 0.13 or greater, this provider has moved to
rancher/rancher2. Please update your source in required_providers.

Terraform has been successfully initialized!
```

Anyway, provider v1.10.6 is already published, and it should be downloaded fine as it was.

Please, reopen issue if needed.

**Comment by mikekuzak** [comment]
@rawmind0 Is this just me ? 

```
Error while installing rancher/rancher2 v1.10.6: provider
registry.terraform.io/rancher/rancher2 1.10.6 is not available for linux_amd64
```

**Comment by rogersd** [comment]
@mikekuzak Nope, I'm getting that too.

**Comment by jacobwgillespie** [comment]
@mikekuzak it's not just you, but it looks like a cache issue, the CDN must have cached the 404. Appending a query parameter, like https://registry.terraform.io/v1/providers/rancher/rancher2/1.10.6/download/linux/amd64?a=b, does return the release. Not sure what can be done about it though, or if the cache will eventually expire.

**Comment by jacobwgillespie** [comment]
I opened an issue related to the cached 404 here: https://github.com/hashicorp/terraform/issues/26890

**Comment by rawmind0** [comment]
Thanks @jacobwgillespie  

Reopening issue

**Comment by rawmind0** [comment]
Hashicorp registry cache has been refreshed and rancher2 provider v1.10.6 should work properly on all archs. Tested on darwin and linux.

Please reopen issue if needed.

**Comment by rogersd** [comment]
Looks good now, thanks!
