### ISSUE TITLE
1.10.6 release missing linux_amd64? 

### ISSUE THREAD

**Issue by jgreat** [rancher/terraform-provider-rancher2#517]
Not sure if this is a terraform registry issue or something that can be fixed on this side, but my `terraform init` is failing with the 1.10.6.

1.10.6 output:

```
Terraform v0.13.3
Configuring remote state backend...
Initializing Terraform configuration...

Setup failed: Failed terraform init (exit 1): <nil>

Output:
Initializing modules...
Initializing the backend...

Successfully configured the backend "remote"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding hashicorp/kubernetes versions matching "~> 1.13.2"...
- Finding rancher/rancher2 versions matching "~> 1.10.3"...
- Installing hashicorp/kubernetes v1.13.3...
- Installed hashicorp/kubernetes v1.13.3 (signed by HashiCorp)

Error: Failed to install provider

Error while installing rancher/rancher2 v1.10.6: provider
registry.terraform.io/rancher/rancher2 1.10.6 is not available for linux_amd64
```

**Comment by rawmind0** [comment]
it seems a registry issue. It has been reported to hashicorp, binary seems not available for all archs, depending on provider source path working fine with "source = terraform-providers/rancher2” but failing for "source = rancher/rancher2” 

https://github.com/rancher/terraform-provider-rancher2/issues/516#issuecomment-725663934

**Comment by rawmind0** [comment]
It seems related to #516 . Please follow thread there.
