### ISSUE TITLE
How to deal with clusters not active during initial roll-out?

### ISSUE THREAD

**Issue by MG2R** [rancher/terraform-provider-rancher2#520]
I have a codebase to set up k8s clusters for different development environments with Rancher. This means I just need to provide the data of each environment to my own "rancher_cluster" module and Terraform will create clusters, projects, namespaces, rolebindings, etc... I'm using a Terraform output to get the token needed to join nodes to the cluster using the Docker command (I'm using custom node clusters). When I originally set this up the idea was that I would create the cluster in Rancher using Terraform, copy the token I get from Terraform and feed that into Puppet which actually configures the nodes themselves.

However, I´ve come into a bit of peculiar situation while trying to roll out new environments: I'm user custom nodes. That means that when Terraform rolls everything out, I don't have the cluster key needed to enroll nodes to the cluster. Terraform then times out on the run, because the cluster isn't active and it can't and it can't add the necessary resources. Because Terraform times out on those resources, the run is considered a failure and it doesn't print the token.

This leaves me with nothing but to log in on the Rancher UI, retrieve the token that way, provision the nodes, then run Terraform again. Until I have done so, Terraform sits in a broken state and cannot be used for anything else.

Is there a solution to this problem? Would it be possible to recognize that the cluster is inactive, yet make the resources in Rancher anyway, so they are available when the nodes register? I mean, from a Terraform perspective, the application is successful as soon as Rancher has the configuration. It is then Rancher's job to apply the necessary changes to the k8s clusters.

**Comment by rawmind0** [comment]
Have you consider using [tf operating timeout](https://www.terraform.io/docs/configuration/resources.html#operation-timeouts) on resources?? From terraform perspective, the application is successfully when the resource has the same state that you define at tf file. How do you expect that Rancher apply necessary changes to a Rancher cluster that is not active?? I mean, how a namespaces can be created when the k8s cluster is not active??

**Comment by MG2R** [comment]
> Have you consider using tf operating timeout on resources??

As far I know, that wouldn't change the behavior here. Only make the time it takes to get Terraform to fail to be longer or shorter. 

> How do you expect that Rancher apply necessary changes to a Rancher cluster that is not active??

The way I see it, Terraform isn't responsible for creating a namespace in the k8s clusters. Terraform is responsible for setting up Rancher with a desired state. Rancher then goes and enforces that desired state on k8s clusters.

It would be nice if we could simply apply a desired state to a cluster which is not yet active, so that it can be applied to the cluster as soon as it does become active. This wouldn't be any different from Rancher being disconnected from a cluster due to a network outage, and then reconnecting later. If, for example, a PSP on Rancher's global settings has changed during the disconnect, Rancher can't instruct the cluster to change it, but that doesn't stop me from applying the change in Rancher in the mean time.

It's quite possible the lacking functionality I describe in the OP is a limitation of Rancher, not Terraform. If that's the case I'll create an issue for the Rancher Server project.

**Comment by rawmind0** [comment]
> As far I know, that wouldn't change the behavior here. Only make the time it takes to get Terraform to fail to be longer or shorter.

When a custom cluster is created using the provider, it lets the cluster in `provisioning` state, not waiting for `active`. In that point, `cluster_registration_token` command can be obtained and be run on nodes in the meanwhile. If you are getting timeout on tf resources in the meanwhile nodes are getting up, afaik, setting a bigger timeout on tf resource would help on that. The behaviour would be the same, for custom cluster creation the provider is NOT waiting until `active`. On cluster update, the provider is waiting for the same state that the cluster was before update.

> The way I see it, Terraform isn't responsible for creating a namespace in the k8s clusters. Terraform is responsible for setting up Rancher with a desired state. Rancher then goes and enforces that desired state on k8s clusters.

Terraform is responsible to create a namespaces if your are using `rancher2_namespace` resource. Terraform is responsible to create and check that the desired and the real state are the same, trying to reconcile if there are diffs.

> It would be nice if we could simply apply a desired state to a cluster which is not yet active, so that it can be applied to the cluster as soon as it does become active. This wouldn't be any different from Rancher being disconnected from a cluster due to a network outage, and then reconnecting later. If, for example, a PSP on Rancher's global settings has changed during the disconnect, Rancher can't instruct the cluster to change it, but that doesn't stop me from applying the change in Rancher in the mean time.

Custom cluster config can be set without the need to wait for `active`. For update, i can be done, but the cluster will wait until the cluster is again in the same state it was before update.

**Comment by MG2R** [comment]
> Terraform is responsible to create a namespaces if your are using rancher2_namespace resource. Terraform is responsible to create and check that the desired and the real state are the same, trying to reconcile if there are diffs.

This was a complete misunderstanding from my end. Just tried deleting a namespace with kubectl and indeed it also gets removed in rancher, so I rancher does not enforce a desired state. Can't believe I didn't know this before. Sorry.

So indeed, I'll have to roll out the nodes on-the-fly during the Terraform run. That's going to require some workflow changes.

It seems I was just misunderstanding how things are managed by Rancher. I'll get to work with you suggestions and take it from there. Thank you!
