### ISSUE TITLE
Ability to add/edit/delete configmap

### ISSUE THREAD

**Issue by abhi1693** [rancher/terraform-provider-rancher2#521]
I have a requirement of updating `tcp-services` under namespace `ingress-nginx`. I could not find any resource or data source to make this happen.

Interacting directly with config maps is something I believe most of us do on rancher and doing it with terraform would be a great addition to the platform.

**Comment by alexzimmer96** [comment]
Is there any reason you don't use the [kubernetes provider](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/config_map)? As far as i understand, this provider is made to interact with rancher(2) and its API and not with the managed kubernetes clusters themselves.

**Comment by abhi1693** [comment]
@alexzimmer96 I only asked because rancher v3 APIs does interact with the config maps as I've used it via Python. In order to use the kubernetes provider, I need to add another provider out of my workflow. There is dependency of configuring the config map and it would be difficult to do it as the code will leave rancher and will have to come back here.

Your statement is contradictory to me as  rancher does have [secrets resource](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/secret). This can also be managed by kubernetes secret resource so why add this into rancher?

Now, I understand if this wouldn't be added however rancher APIs does have ability to configure config maps, secrets etc.

**Comment by alexzimmer96** [comment]
You're right. There is an API to manage ConfigMaps on Rancher Project level, like you can do with secrets. Under this circumstances, from my point of view, implementing the ConfigMaps as well makes sense.

**Comment by abhi1693** [comment]
@alexzimmer96 Would this be implemented or should I simply go for Kubernetes provider as you suggested?

**Comment by rawmind0** [comment]
Rancher API has de ability to deal with k8s resources as configMap, secret, etc within projects, https://<RANCHER_IP>/v3/projects . BTM, this is not implemented at the provider due there is more priority work to do at the provider (like issues, bugs, new features,..), and there is an option to get this feature working, using [tf k8s provider](https://github.com/rancher/terraform-provider-rancher2/issues/223#issuecomment-698361419)

Anyway, we are more than happy to accept contributions and PR that improve the provider. :)

Duplicated issue, please follow this thread at #223
