### ISSUE TITLE
rancher2_cluster_template tries to delete revision when changing configuration

### ISSUE THREAD

**Issue by abhi1693** [rancher/terraform-provider-rancher2#523]
I have written a very simple code to create `rancher2_cluster_template` revision. When I update the revision code along with its name, terraform tries to delete the existing resource. This always fails as there are clusters using the previous revision as it first tries to remove them before creating a newer revision.

Now, this functionality does not work as to how a user would do the same from Rancher UI. The UI gives an option to clone the revision into a newer version with new changes without having to delete the existing ones.

There should be a similar functionality using terraform. I should be able to clone from an existing resource or make a new revision without deleting any old ones. I do not want to keep adding multiple revisions to my terraform module just to add a newer revision. At the moment our code has become 1600 lines because of this and is completely unmanageable.

**Comment by rawmind0** [comment]
You can't update cluster_template_revision that is already in use by any cluster, tf is doing what you are telling it to do at tf file. The provider is working exactly same way as the UI is doing. UI clone is actually creating a new cluster_template_revision with new values, same that you can do at tf file. You should always add a new cluster_template_revision or you could modify  cluster_template revision just if it's NOT used by any cluster.
