### ISSUE TITLE
RFE:VMware:VMTagging: request to add VM tagging at “Add Node Pool” level

### ISSUE THREAD

**Issue by sadhugit** [rancher/terraform-provider-rancher2#526]
Right now, we are giving the option to add existing tags while creating the NodeTemplate. We can add prefixes to the node, but there is no option to tag the set of nodes (VM) while defining the NodePool. This will be useful to tag the set of Nodes while adding the NodePool (i.e., tagging VMS at the vcenter level)
https://github.com/rancher/rancher/issues/30231

**Comment by rawmind0** [comment]
May be i'm missing something, but i think this feature is not available at Rancher api, is it?? I think this RFE should be opened at rancher/rancher

**Comment by matttrach** [comment]
This feature would be dependent on https://github.com/rancher/rancher/issues/30231 which has been closed as stale. 
This request is 4 years old, so I am going to close it as stale as well. Please feel free to open a new issue if this feature is still required.
