### ISSUE TITLE
rancher2_catalog docs: repo url is not required, but error message says otherwise

### ISSUE THREAD

**Issue by scaleoutsean** [rancher/terraform-provider-rancher2#528]
I'm working with v2.5.2 to provision a Management Cluster.

According to the [docs](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/catalog_v2), `git_repo` should be enough and in that case `url` would be optional. The docs offer an example (below, [1]).

But if I specify git_repo and git_branch, TF errs and says that `url` is required. Why is that?

```
Error: Missing required argument

  on terraform/modules/kubernetes/rancher/bootstrap.tf line 138, in resource "rancher2_catalog" "trident":
 138: resource "rancher2_catalog" "trident" {

The argument "url" is required, but no definition was found.
```

Everything works fine with a `url` (no git_* vars), but I'm curious is this a documentation bug or am I looking at the wrong document?

Even when a `url` is provided, `git_*` vars must be removed because they are not supported (An argument named "git_repo" is not expected here.)

[1] Example:

```yaml
resource "rancher2_catalog_v2" "foo" {
  cluster_id = <CLUSTER_ID>
  name = "foo"
  git_repo = "<GIT_REPO_URL>"
  git_branch = "<GIT_BRANCH>"
}
```

[2] My config:

```yaml
resource "rancher2_catalog" "trident" {
  count    = var.rancher_create_trident_catalog ? 1 : 0
  provider = rancher2.admin
  name    = "netapp-trident"
  git_repo = "https://github.com/NetApp/ez-rancher-trident-installer"
  git_branch = "master"
}
```

**Comment by rawmind0** [comment]
It seems you are defining wrong resource type:
* Example, `rancher2_catalog_v2` [doc](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/catalog_v2) 
* your config, `rancher2_catalog` [doc](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/catalog)

**Comment by scaleoutsean** [comment]
LOL, that is hilarious. Now I see they next to each other on the docs site. I did look very carefully at the docs, but not at the script. Mystery solved!
