### ISSUE TITLE
Error: "template_revisions.0.cluster_config": required field is not set

### ISSUE THREAD

**Issue by oxr463** [rancher/terraform-provider-rancher2#530]
Per the docs, `cluster_config` is optional:

> cluster_config - (Optional) Cluster configuration (list maxitem: 1)

However, terraform is complaining that it is a required field:

```sh
terraform -v
Terraform v0.13.5
+ provider registry.terraform.io/rancher/rancher2 v1.10.4

terraform plan
Error: "template_revisions.0.cluster_config": required field is not set

  on main.tf line 74, in resource "rancher2_cluster_template" "foo":
  74: resource "rancher2_cluster_template" "foo" {
```

Here is the example code:

```terraform
resource "rancher2_cluster_template" "foo" {
  name = "foo"

  template_revisions {
    name = "bar"
  }
}
```

See: https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster_template#nested-blocks

**Comment by rawmind0** [comment]
`cluster_config` is a required argument. The error is on doc definition.

**Comment by oxr463** [comment]
Also, in my testing, `rke_config` was also required.

This snippet actually passed the `terraform plan` stage:

```terraform
resource "rancher2_cluster_template" "foo" {
  name = "foo"

  template_revisions {
    default = true
    enabled = true
    name    = "bar"

    cluster_config {
      rke_config {}
    }
  }
}
```
