### ISSUE TITLE
Failure connecting to API - 401 Unauthorized or ping/pong connection refused

### ISSUE THREAD

**Issue by eliz-ol** [rancher/terraform-provider-rancher2#531]
I'm just starting to use Terraform to manage our lab Rancher. I am almost certainly doing something wrong, but I don't know what:

When I use the below TF module (with a couple variants), I get one of two errors:
`Error: Bad response statusCode [401]. Status [401 Unauthorized]. Body: [message=Unauthorized 401: must authenticate] from [https://rancher.contoso.com/v3]` or 
`Error: Rancher is not ready: Doing get: Get "http://rancher.contoso.com/ping": dial tcp 10.10.10.5:80: connectex: No connection could be made because the target machine actively refused it.`

I've copied the ca_cert directly out of the Rancher WebUI (`Settings | show cacerts`), and used terraform console to validate that it is formatted (at least superficially) correctly.

The **only** time I can get to the ping/pong error is when I use `api_url="http://..."` and `insecure="true"`. Every other variant (`insecure="false"`, `api_url="https://..."`, `ca_certs` commented out) in every other combination I can test gets the 401 error.

I can obviously connect to the API endpoint over http, because it gets past the 401 but then fails trying to hit the ping endpoint over http - when I `curl https://rancher.contoso.com/ping` I get a `pong` response. I believe I have two independent problems, at least one of which is caused by a misconfiguration in my system but possibly both:

1) It seems to me that there's something inside rancher that only wants the ping/pong to be https, even when `insecure=true` is set
2) Some part of my configuration isn't reading the ca_cert or I've entered the wrong cert data or something.

I'm pretty new at this and not sure how to get any further on my own.
```
provider "rancher2" {
  api_url    = "https://rancher.contoso.com/v3"
  token_key = "token-foo:longstring"
  insecure = "false"
  ca_certs = var.ca_cert
  version = "~> 1.10.6"
}

variable "ca_cert" {
    type = string
    default = <<-EOF
        -----BEGIN CERTIFICATE-----
        MIIDszCCApugAwIBAgIQeJqBWnyng4RNNrvvD1/pyzANBgkqhkiG9w0BAQsFADBg
        MRMwEQYKCZImiZPyLGQBGRYDY29tMRowGAYKCZImiZPyLGQBGRYKb3JiaXRsb2dp
        YzESMBAGCgmSJomT8ixkARkWAmhxMRkwFwYDVQQDExBocS1PTFNFUlYtQUQxLUNB
        MB4XDTIwMDIxMTEzMjg0OFoXDTI1MDIxMTEzMzg0N1owYDETMBEGCgmSJomT8ixk
        ARkWA2NvbTEaMBgGCgmSJomT8ixkARkWCm9yYml0bG9naWMxEjAQBgoJkiaJk/Is
        ZAEZFgJocTEZMBcGA1UEAxMQaHEtT0xTRVJWLUFEMS1DQTCCASIwDQYJKoZIhvcN
        AQEBBQADggEPADCCAQoCggEBAK08jQYqC4WtMxgxWLoQTAEUcG3sMk5KIaDdHU3s
        xwPU1sWHzayym+nPZR4FcpMDKZmS0CQMTGDV5CJIyKaA+Jorv9X/Z996gX7y9g7O
        7ImeHigFWjfiup+j0+F05UmuCqdFp0kh1NQOKcqt74IuFgSzBwht3sJHoJhcyBqW
        vqfY1AZw8HGuwzgbJKvzw3kRm64B+fhxN8xPw4gaDpvrAUd9GKitw8bgN2+GnfpT
        yOR8MXQZIuYDfUfVE0Q47Knc49TOqW0meUL4Q5ascWsxn36vjAZFABacHrIv3CZM
        7DqxULzDAodtJiGnz7b+LQ4uaehwugW8AWUt0/uO1dkSxukCAwEAAaNpMGcwEwYJ
        KwYBBAGCNxQCBAYeBABDAEEwDgYDVR0PAQH/BAQDAgGGMA8GA1UdEwEB/wQFMAMB
        Af8wHQYDVR0OBBYEFK7HCdHK5fRlw9/DLgnauB2cLWKFMBAGCSsGAQQBgjcVAQQD
        AgEAMA0GCSqGSIb3DQEBCwUAA4IBAQAnsUsNzV//Y51KqGWQJGcEAYzuW04ahh1j
        nGoU9L4IiS6pPN/yqdKnd7BYzy6AdcQLh06jctfpC/aB2A4e30foauH7E626fOBP
        ZiugguVOWKRgyt5MwIRF7AdTXHHeLQN4JehnI3oU0KB+X8ZFblKfYey2lONQ+p9K
        knQH8VeSLboDyFTNEC3c1vxV5P/uxfG9d2sIBsmiZORQG6XPZnFzz2EjwqhFBRze
        qujkI+5KOyo7Q17UMWWhixl5gH4QbLr95+jbTL3EOdZB3fdF7V2ZC40RbGMFLB8U
        wZLKjepgrMjclVh2CfzH/ZNlxmDto6HK9AMo77ukZVCjksxtDohW
        -----END CERTIFICATE-----
        EOF
}
resource "rancher2_cloud_credential" "vsphere-terraform" {
  name = "vcenter-terraform"
  description = "Terraform Credentials"
  vsphere_credential_config {
    username = var.vcenter_user
    password = var.vcenter_pass
    vcenter = "https://vcenter.contoso.com"
  }
}
```

**Comment by rawmind0** [comment]
Rancher api connection is always done using https.`insecure` argument is used just to allow https connection using non trusted certificates (self signed). `ca_certs` argument is used to provide non trusted CA certificates used to sign Rancher server tls certificates (self signed). If you are using self signed certificates on Rancher api, you can use one of both options, enable `insecure` or provide `ca_certs`

**Comment by eliz-ol** [comment]
It turns out this is a restatement of [rancher #29943](https://github.com/rancher/rancher/issues/29943) / [rancher #18639](https://github.com/rancher/rancher/issues/18639)

I didn't realize I had created a cluster scoped API Key. After creating a non-scoped key, it works.
