### ISSUE TITLE
How to set Project when installing a rancher2_app_v2 ?

### ISSUE THREAD

**Issue by mikekuzak** [rancher/terraform-provider-rancher2#532]
Hi,

When I look at the TF definition I don't see the possibility to configure the Project I want the namespace to be created. 

namespace - (Required/ForceNew) The namespace of the app v2 (string)
ForceNew ..ok but in which Project if I have network isolation enabled I might want to install this in multiple Projects right ? 

```
resource "rancher2_app_v2" "foo" {
  cluster_id = "<CLUSTER_ID>"
  name = "rancher-monitoring"
  namespace = "cattle-monitoring-system"
  repo_name = "rancher-charts"
  chart_name = "rancher-monitoring"
  chart_version = "9.4.200"
  values = file("values.yaml")
}
```

The UI of Cluster Explorer has an option: Install into Project:
![image](https://user-images.githubusercontent.com/18675587/100021410-56a8fa80-2dd9-11eb-9a5b-cf63d0822f9d.png)

I guess the only option is:
 - First create a project, create a namespace, install app into existing namespace which is attached to the project. 
Unless I'm missing something here ? 

Thanks

**Comment by rawmind0** [comment]
Hi @mikekuzak , have you tried using [project_id](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/app_v2#project_id) argument??

**Comment by mikekuzak** [comment]
Ugh .. sorry mate for waiting your time, my bad.
