### ISSUE TITLE
rancher2_app_v2 requires chart_version 

### ISSUE THREAD

**Issue by enrico9034** [rancher/terraform-provider-rancher2#535]
Hi everyone, 
Looking at the [documentation](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/app_v2#chart_version) the **chart_version** variable is optional but when I try to install a chart without passing the variable it fails with **"Catalog V2 id, chart name and chart version should be provided"**, also from the code [here](https://github.com/rancher/terraform-provider-rancher2/blob/34a9e52634ed75ed1769c07d8bceda550f076148/rancher2/config.go#L803) the variable seems to be required with resource **rancher2_app_v2** this was a very good feature available in the previous resource **rancher2_app** where it could be skipped.

Thanks in advance.

**Comment by rawmind0** [comment]
Hi @enrico9034 , you are right, btm `chart_version` is required. It seems there is a docs issue defining it but we are working to solve it and provide the latest default `chart_version` as provided at `rancher2_app`

**Comment by rawmind0** [comment]
Docs fixed and new feature added at PR #538
