### ISSUE TITLE
Support PersistentVolumes and claims

### ISSUE THREAD

**Issue by MG2R** [rancher/terraform-provider-rancher2#544]
Rancher has support for adding persistent volumes and persistent volume claims. I can't find these resources in the provider. Am I missing something? Are there plans to support these?

**Comment by rawmind0** [comment]
By the moment, no plans to support PersitentVolumes and PersitentVolumeClaims resources. They are supported by kubernetes tf provider, is this not an option for you??.

**Comment by MG2R** [comment]
I know they exist, but that would require management of an admin token for Terraform in each Kubernetes cluster. With the Rancher Provider, I get all of that for free.

No worries though, I'll figure it out. Just wanted to make sure I wasn't missing anything.

Thanks a lot for your all of you work on this provider, really appreciated!
