### ISSUE TITLE
Latest RKE in rancher2 provider does not support k8s 1.19 or newer

### ISSUE THREAD

**Issue by HighwayofLife** [rancher/terraform-provider-rancher2#547]
The latest version RKE supported by the Rancher2 Terraform provider does not support a Kubernetes version newer than v1.18.12-rancher1-1. It doesn't appear that the Rancher2 provider has updated to RKE v1.2.3

**Comment by rawmind0** [comment]
This provider has not direct dependency with RKE. The supported RKE version is determined by the Rancher server version used. 

A k8s cluster `v1.19.4-rancher1-1` can be deployed fine with this provider and Rancher v2.5.3

**Comment by rawmind0** [comment]
Please, reopen issue if needed
