### ISSUE TITLE
[rancher2_cluster/gke_config] enable_master_authorized_network missing from documentation.

### ISSUE THREAD

**Issue by keisari-ch** [rancher/terraform-provider-rancher2#548]
Hi guys,

For a **GKE Private cluster**, the master_authorized_network_cidr_blocks parameter is not set.
Hence the cluster is unreachable after deployment.

Sample code used : rancher/rancher#30442

**Comment by keisari-ch** [comment]
The enable_master_authorized_network parameter is not documented but needs to be used explicitly with the master_authorized_network_cidr_blocks parameter.
I mistakenly thought it was enabled if master_authorized_network_cidr_blocks was not null.
Found it there : https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/structure_cluster_gke_config.go#L51

I guess https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster needs an update in the gke_config section.

- [ ] update https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster  with #548

**Comment by rawmind0** [comment]
Hi @p4ranoidandro1d , thanks for the feedback. Submitted PR https://github.com/rancher/terraform-provider-rancher2/pull/550 to fix the docs
