### ISSUE TITLE
Cannot create EKS cluster with different subnets to the node group

### ISSUE THREAD

**Issue by ghost** [rancher/terraform-provider-rancher2#549]
I want to create an EKS cluster that has both public and private subnets, but a node group that has instances only in the private subnet.

It looks like the `subnets` parameter of the `eks_config` is used for both the cluster and for the `node_group`, which means that some nodes are exposed to the public.

Would it be possible to add an optional parameter to the `node_group` to configure the subnets, with the default being the same as `eks_config.subnets`?

**Comment by rawmind0** [comment]
The feature was added with PR https://github.com/rancher/terraform-provider-rancher2/pull/608
