### ISSUE TITLE
rancher2_app_v2 installation is a success but still treated as ERROR 

### ISSUE THREAD

**Issue by wilderbridge** [rancher/terraform-provider-rancher2#554]
When installing the logging app via `rancher2_app_v2`

```
 resource "rancher2_app_v2" "banzai" {
   name = "banzai"
   cluster_id = "${rancher2_cluster.rancher-cluster.id}"
   depends_on = [kubernetes_namespace.logging]
   namespace = "cattle-logging-system" 
   repo_name = "rancher-charts"
   chart_name = "rancher-logging"
   cleanup_on_fail = true
   chart_version = "3.8.201"
   values = file("banzai_values.yaml")
 }
```

It gives error, even if there isn't any. The first error is about installing the required CRD and the second about the CRD missing. I would assume that the installation proceeds without any errors. Right now I have to manually import the succesfully installed application to state.

```
 Error: Provider produced inconsistent result after apply
 
 Error: [ERROR] installing App V2: helm upgrade --install=true --namespace=cattle-logging-system --timeout=10m0s --values=/home/shell/helm/values-rancher-logging-crd-3.6.001.yaml --version=3.6.001 rancher-logging-crd /home/shell/helm/rancher-logging-crd-3.6.001.tgz
 Release "rancher-logging-crd" does not exist. Installing it now.
 
 Error: execution error at (rancher-logging/templates/validate-install-crd.yaml:15:7): Required CRDs are missing. Please install the rancher-logging-crd chart before installing this chart.
```

**Comment by rawmind0** [comment]
Take a look to https://github.com/rancher/terraform-provider-rancher2/blob/master/docs/guides/apps_marketplace.md#examples-1 first note.

Try with

```
resource "rancher2_app_v2" "rancher-logging" {  
  name = "rancher-logging"
  cluster_id = rancher2_cluster.rancher-cluster.id
  namespace = "cattle-logging-system"
  repo_name = "rancher-charts"
  chart_name = "rancher-logging"
  chart_version = "3.8.201"
  values = file("banzai_values.yaml")
  wait = true
}
```

**Comment by kingnarmer** [comment]
I am having slightly different issue. I get the logging operator and crd installed but they don't pick clusterFlows/clusterOuputs from value.yaml file. Not sure how to successfully pass those config on install time in terraform. 

`resource "rancher2_app_v2" "logging" {
  cluster_id    = data.rancher2_cluster.cluster.id
  name          = "rancher-logging"
  namespace     = rancher2_namespace.logging.name
  repo_name     = "rancher-charts"
  chart_name    = "rancher-logging"
  values        = file("${path.module}/logging_values.yaml")
  wait          = true
}


logging_values.yaml file 

controlNamespace: "cattle-logging-system"
clusterFlows:
  - name: cluster-wide-logs-to-kafka
    spec:
      globalOutputRefs:
        - kafka
clusterOutputs:
  - name: cluster-wide-logs-to-kafka
    spec:
      kafka:
        brokers: 10.10.1.20:9294
        format:
          type: json
        default_topic: topicname`

**Comment by wilderbridge** [comment]
Thanks @rawmind0 that did it. 

@true64gurus I'm doing it like this:

```
resource "rancher2_app_v2" "banzai" {
  name = "rancher-logging"
  cluster_id = "${rancher2_cluster.rancher-cluster.id}"
  depends_on = [kubernetes_namespace.logging]
...
}
resource "kubernetes_namespace" "logging" {
   depends_on = [rancher2_cluster_sync.cluster]
   metadata {
     name = "cattle-logging-system"
   }
...
}
```
```
