### ISSUE TITLE
Add rancher2_feature resource to control Rancher feature flags

### ISSUE THREAD

**Issue by axeal** [rancher/terraform-provider-rancher2#556]
Feature request from the user is for a `rancher2_feature` resource, similar to the `rancher2_setting` resource to enable configuration of Rancher feature flags via the Terraform provider.

gz#14330

**Comment by rawmind0** [comment]
Submitted PR #565

**Comment by rawmind0** [comment]
The feature is already merged and will be included in the next provider release.

**Comment by slickwarren** [comment]
Tested on rancher 2.5-head (a85f4d1f87feea0083ebf8ae517a140f39de7fbd) and terraform latest (built locally on 2/22/21):
* update a feature -- PASS
```
rancher2_feature.disable-dashboard: Destruction complete after 0s
rancher2_feature.test2: Destruction complete after 0s
rancher2_feature.enable-fleet: Creating...
rancher2_feature.disable-ustorage-drivers: Creating...
rancher2_feature.disable-ustorage-drivers: Creation complete after 3s [id=unsupported-storage-drivers]
rancher2_feature.enable-fleet: Creation complete after 3s [id=fleet]

Apply complete! Resources: 2 added, 0 changed, 2 destroyed.
```
* update multiple features at once -- PASS
* update feature to same status -- PASS
* update feature that requires restart -- FAIL (reports failure, but feature was modified) 
  * if other features are listed for modification **after** the feature that requires a restart, they will also report an error but NOT be modified
  * if other features are listed for modification **before** the feature that requires a restart, they are modified normally
```
Error: [ERROR] waiting for feature (fleet) to be updated: Get "https://173.230.156.234/v3/features/fleet": dial tcp 173.230.156.234:443: connect: connection refused
```

**Comment by slickwarren** [comment]
retested all of the above tests with the above PR. Here was the diff of results: 
* update feature that requires restart -- PASS
* changing multiple features, NONE of which require rancher restart -- PASS
* changing multiple features ANY of which require rancher restart -- Expected to fail (concurrency issue with terraform, not resolvable at this time)

will close once PR merges

**Comment by slickwarren** [comment]
retested the above after the merge to master (and rebuilt locally on commit 43e57199ac06047f583b1ad58caca31d2915edb7) 
* update feature that requires restart -- PASS
* update a feature that does not require restart -- PASS
* run tf script that has entries for features that match the existing state -- PASS
* update multiple features, NONE of which require rancher restart -- PASS
* changing multiple features ANY of which require rancher restart -- Expected to fail (concurrency issue with terraform, not resolvable at this time)
