### ISSUE TITLE
Rancher2_cluster with rke_config doesn't provision node

### ISSUE THREAD

**Issue by jehutyy** [rancher/terraform-provider-rancher2#559]
As I understand the following snippet is expected to: 
- create a new rke cluster 
- add it to rancher ui 
- provision node via ssh

The first two item are true but the provisionning of configured node doesn't seem to work.

```
resource "rancher2_cluster" "ad" {
  provider = rancher2.admin
  name = "ad"
  description = "admin cluster"
  rke_config {
    nodes {
        role = ["controlplane", "worker", "etcd"]
        address = "50.0.0.120"
        user = "root"
    }
    private_registries {
      url = "50.0.0.1:5000"
      is_default = true
    }
  }
}
```

**Comment by rawmind0** [comment]
@jehutyy , your assumption is not completely right. Rancher2 provider is not doing ssh to vm's, you should get [`node_command`](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster#node_command) from `rancher2_cluster` and use another tf provider/provisioner to execute node_command with proper roles on vm's. The provider is working at the same way Rancher2 works.

Duplicated with #442. for more info, take a look to https://github.com/rancher/terraform-provider-rancher2/issues/442#issuecomment-685773446
