### ISSUE TITLE
node_command attribute contain partially correct  command

### ISSUE THREAD

**Issue by jehutyy** [rancher/terraform-provider-rancher2#560]
Terraform provider doesn't print appropriate `node_command`. 

When adding a node that hold all three roles from rancher UI here the command I get : 
`
sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run 50.0.0.2:5000/rancher/rancher-agent:v2.5.5 --server https://localhost --token xwbx8w2qrhknnjmjds6c6vvvxjzp72z4k4djtgdgx757w26z4vwxdr --ca-checksum f89ad735bc7d61561ba143cb3b84df4f3ca7d87c9593a3c3d0e18b2e7a6c91a5 --etcd --controlplane --worker`
`

While with `rancher2` provider it prints the following : 
`
command = "sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run 50.0.0.2:5000/rancher/rancher-agent:v2.5.5 --server https://localhost --token xwbx8w2qrhknnjmjds6c6vvvxjzp72z4k4djtgdgx757w26z4vwxdr --ca-checksum f89ad735bc7d61561ba143cb3b84df4f3ca7d87c9593a3c3d0e18b2e7a6c91a5"
`

Thing that jumps out is missing `--etcd --controlplane --worker` flags, but there's more than that, I tried to add `internal_address` in terraform manifest which doesn't appear either in `node_command`

Here my manifest terraform if anyone would try to reproduce.

```
resource "rancher2_cluster" "ad" {
  provider = rancher2.admin
  name = "ad"
  description = "admin cluster"
  rke_config {
    nodes {
        role = ["controlplane", "worker", "etcd"]
        address = "50.0.0.120"
        user = "root"
        internal_address = "1.2.3.4"
    }
    private_registries {
      url = "50.0.0.2:5000"
      is_default = true
    }
  }
}
 
output "command" {
  value = rancher2_cluster.ad.cluster_registration_token[0].node_command
}      
```

**Comment by rawmind0** [comment]
@jehutyy , the node_command provided by the tf provider is correct. As mentioned [here](https://github.com/rancher/terraform-provider-rancher2/issues/559#issuecomment-763602093), `--etcd --controlplane --worker` parameters are the rke roles for the node. You should add all or a subset of them depending your nodes.

The `rke_config.nodes` shouldn't be provided. It has no effect on rke cluster, you should add your nodes executing the node_command (adding the rke roles) on every single node. If you need to specify address and/or internal address you should add params to the node_command `--address X.X.X.X --internal-address Y.Y.Y.Y`. Take a look to edit cluster, `Customize Node Run Command`-`Show advance options` on Rancher ui.

**Comment by jehutyy** [comment]
First of all, thank you very much for all your answers in my today ticket.

I would like to better understand underlying mechanism : what's the point of specifying bunch of options in terraform manifest?

Like if, at the end, I have to concatenate appropriate flags to match wanted configuration why is there so much options?

Are they placeholder or something?

________________________________

**Comment by rawmind0** [comment]
You don't need options on terraform manifest, but if you need specific options on nodes, you need to tune the node_command, as it's presented as standard command, where you add node roles or specific [rancher agent options](https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/custom-nodes/agent-options/). The way of working is the same than using rancher ui https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/custom-nodes/

**Comment by rawmind0** [comment]
Please, reopen issue if needed
