### ISSUE TITLE
dial tcp [IP]:8443: connect: connection refused` on Rancher server-provided cacerts

### ISSUE THREAD

**Issue by fschueller** [rancher/terraform-provider-rancher2#563]
Hi everyone,

I have installed Rancher server via [RancherD](https://rancher.com/docs/rancher/v2.x/en/installation/install-rancher-on-linux/#part-i-installing-rancher) and am now trying to connect with the rancher2 provider.
RancherD installs the Rancher server on a single-node RKE2 cluster and exposes it on port 8443.

Running the plain install as documented, I have not used any custom certs. The ca-cert provided comes from the Rancher server install itself ( `Settings > cacerts`). I'm using a non-scoped token.

`main.tf`:

```
terraform {
  required_version = "0.14.5"
  required_providers {
    rancher2 = {
      source  = "rancher/rancher2"
      version = "1.11.0"
    }
  }
}

provider "rancher2" {
  api_url   = var.api_url
  token_key = var.api_token
  insecure = false
  ca_certs = <<-EOF
  -----BEGIN CERTIFICATE-----
SERVER-CERT HERE
  -----END CERTIFICATE-----
  EOF
}

resource "rancher2_user" "foo" {
  name = "Foo user"
  username = "foo"
  password = "changeme"
  enabled = true
}
```

`vars.tf`:
```
api_url = "https://SERVER.com:8443/v3"
api_token = "token-f8llm:[token-string]"
```

Error:

```
Error: Rancher is not ready: Doing get: Get "https://SERVER.com:8443/ping": dial tcp [IP]:8443: connect: connection refused

  on main.tf line 38, in resource "rancher2_user" "foo":
  38: resource "rancher2_user" "foo" {
```

I assumed some kind of SSL error. However, when I import the Rancher-provided ca-cert into my browser it gets accepted. Same when providing cURL with it.

I have also tried `insecure = true` option, but same error. I saw https://github.com/rancher/terraform-provider-rancher2/issues/531 but for me it didn't solve it. Any ideas?

Thank you for your help!

**Comment by rawmind0** [comment]
Hi @fschueller , it seems that the tf provider can't connect to your service `Get "https://SERVER.com:8443/ping": dial tcp [IP]:8443: connect: connection refused` . Is the rancher service running?? Is running in same ip:port?? Doesn't seems a provider issue.

**Comment by fschueller** [comment]
Hi @rawmind0, yes the server is running on the specified port. I can connect to the UI and API via browser and cURL all fine and without CA/cert errors.

```
>> curl --cacert ~/certs/rancher-101-ca.pem https://rancher-101.com:8443/ping
pong
```

I thought at first it's an issue of the RKE2 cluster underneath but I couldn't really verify that up to now. I'll have a look again, but it's weird since it's working for everything else.

**Comment by fschueller** [comment]
Forgive me the hassle. It's a DNS problem. Obviously. Thanks for your patience.
