### ISSUE TITLE
Add launch template support to eks_config_v2

### ISSUE THREAD

**Issue by axeal** [rancher/terraform-provider-rancher2#572]
With the [introduction of the EKS launch template support in the upcoming v2.5.6 release](https://github.com/rancher/rancher/issues/28803) the user request is to make this configurable via the eks_config_v2 resource

gz#14485

**Comment by rawmind0** [comment]
The feature was added with PR https://github.com/rancher/terraform-provider-rancher2/pull/608, included at provider v1.13.0

Please, reopen issue if required
