### ISSUE TITLE
can rancher2_node_pool wait until machines are up?

### ISSUE THREAD

**Issue by ajchiarello** [rancher/terraform-provider-rancher2#573]
I was wondering if there was any way to have the rancher2_node_pool not consider itself complete until the nodes in the pool have finished deploying. I'm testing a cluster repaving process using the create_before_destroy lifecycle argument, and while it is successfully replacing a node pool before destroying the old one, not having the new nodes in place is problematic.

**Comment by rawmind0** [comment]
Have you consider to use [cluster_sync](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster_sync) resource??

**Comment by ajchiarello** [comment]
Yes, but it didn't wait for the nodepools during the destroy/recreate - would I need to taint that resource as well in order to force it to wait again?

**Comment by rawmind0** [comment]
The cluster_sync should wait until cluster state is `active`. Once you added a new node_pool to a cluster, the cluster state is updated, coming back to `active` when the new node_pool has finished. At this point, you could destroy old node_pool.
