### ISSUE TITLE
Add http_port, https_port and network_mode to ingress

### ISSUE THREAD

**Issue by axeal** [rancher/terraform-provider-rancher2#575]
http_port, https_port and network_mode were added to the ingress config api type per https://github.com/rancher/types/pull/1184/files but are not yet configurable within an rke_config via the Rancher2 provider, user request is to add these

gz#14878

**Comment by rawmind0** [comment]
Submitted PR https://github.com/rancher/terraform-provider-rancher2/pull/636 adding requested arguments
