### ISSUE TITLE
Support for aks_config to allow setting the loadbalancer sku

### ISSUE THREAD

**Issue by slessardjr** [rancher/terraform-provider-rancher2#580]
Rancher UI supports setting the LoadBalancer SKU https://github.com/rancher/rancher/issues/23715
Can the provider be updated so the aks_config can set this value?

**Comment by rawmind0** [comment]
Submitted PR to add the feature, https://github.com/rancher/terraform-provider-rancher2/pull/581

**Comment by rawmind0** [comment]
PR https://github.com/rancher/terraform-provider-rancher2/pull/581 has been merged. The feature will be available at next provider release.

**Comment by rawmind0** [comment]
Please reopen issue if needed
