### ISSUE TITLE
Support labels and annotations for rancher2_cluster

### ISSUE THREAD

**Issue by dkeightley** [rancher/terraform-provider-rancher2#582]
Currently labels can be applied for nodes/nodegroups, in some use cases (for eg, fleet) adding this metadata for a cluster in a programmatic way is ideal in the same way it can be managed in the UI/API.

gz#14923

**Comment by rawmind0** [comment]
@dkeightley , may be i'm missing something, but labels and annotations are already supported for rancher2_cluster resource, https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster#annotations . Not clear what is requested here, could you please clarify??

**Comment by dkeightley** [comment]
Thanks @rawmind0, the label/annotations in `rancher2_cluster` are applied to a nodepool, or am I mistaken? The intention here is to label the cluster for use with Fleet.

edit: Tested and this works as desired, it appears the documentation may be a copy/paste typo from `rancher2_node_pool`, shall we update it?

**Comment by rawmind0** [comment]
@dkeightley , i'm glad it's working as desired. 

For sure, if you found out a typo in the docs, it should be fixed. Could you please open a PR fixing the docs typo or be more explicit where the typo is to be fixed??

**Comment by rawmind0** [comment]
Fix included on new provider release v1.12.0

Please, reopen issue if needed
