### ISSUE TITLE
Support node_taints on rancher2_node_template

### ISSUE THREAD

**Issue by MG2R** [rancher/terraform-provider-rancher2#584]
When I create a node template through the UI, I can add node taints to the template, which will then be applied to any node started from that template. A template made that way will show this in the API:

```json
nodeTaints": [
    {
        "effect": "PreferNoSchedule",
        "key": "myorg.net/specialnode",
        "type": "/v3/schemas/taint",
        "value": "true"
    }
],
```

With the Terraform provider, it seems there is no way to add this, if I'm reading the docs correctly. Would it be possible to add support for that? Right now I need to add node labels in the Template and node taints in the Node Pool. I'd like to add them both through the template.

Thank you!

**Comment by rawmind0** [comment]
Both features should be available. Docs reference:
* https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/node_template#labels
* https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/node_pool#node_taints

**Comment by MG2R** [comment]
I'm trying to add node_taints on `rancher2_node_template`s, though. It's possible in the UI and the API, but not in the Terraform provider.

**Comment by rawmind0** [comment]
Ok got it.  Adding new feature on PR https://github.com/rancher/terraform-provider-rancher2/pull/585
