### ISSUE TITLE
Rename/Duplicate nodetemplate labels property to be node_labels so it is in line with the node_taints var

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/terraform-provider-rancher2#596]
With PR https://github.com/rancher/terraform-provider-rancher2/pull/585 it will add a node_taints property to the node template resource. This makes it confusing to know that node_taints are added to nodes and labels are as well. I recommend duplicating the labels property to be named node_labels and then deprecate the generic labels property that way they are aligned and users will know these are added to the nodes of this template.

**Comment by rawmind0** [comment]
`labels` and `node_taints` argument names are aligned with its Rancher API field names, https://github.com/rancher/rancher/blob/master/pkg/client/generated/management/v3/zz_generated_node_template.go#L56 .  I don't think renaming `labels` is something to be done, moreover being a breaking change. May clarify it adding some comment on the docs??

**Comment by mitchellmaler** [comment]
Ah yea if the rancher api has it that way then just clarifying it in the docs is probably the best.

**Comment by rawmind0** [comment]
Updated PR #585 adding a doc note to clarify  it.

Please, reopen if needed
