### ISSUE TITLE
rancher2_cluster doesn't allow to set annotation for rke_config nodes

### ISSUE THREAD

**Issue by raelix** [rancher/terraform-provider-rancher2#599]
Hello everyone,

I'm trying to add annotation on rancher2_cluster nodes (rke_config) but there is no way to do that. I see just taint and labels but not annotation.

Do you have any suggestion?

**Comment by rawmind0** [comment]
Hi @raelix , `rancher2_cluster` is not managing nodes if set as `custom` or `imported` k8s cluster. Using `custom` cluster, as you mentioned, labels and taints can be added on the node_command, but i guess annotations are not supported at Rancher side, as you can also check from ui.

The only way to do it is using [`rancher2_node_pool`](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/node_pool#argument-reference) and [`rancher2_node_template`](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/node_template#argument-reference)

**Comment by raelix** [comment]
Hi @rawmind0  thanks for the quick answer. I'm using rancher2_cluster as custom and as you mentioned there is no way to add annotation (only labels and tains) and it's not possible use rancher2_node_pool and rancher2_node_templates for custom nodes (bare-metal installation). 
My problem is that longhorn needs annotations on the nodes to create custom tags disks/nodes, do you have any suggestions on how to that with rancher provider who is the only one that manage the nodes?

**Comment by rawmind0** [comment]
> My problem is that longhorn needs annotations on the nodes to create custom tags disks/nodes, do you have any suggestions on how to that with rancher provider who is the only one that manage the nodes?

May be i'm missing something, but does Longhorn require annotations in the nodes?? Afaik, node toleration/taints can be used to set node groups,  https://longhorn.io/docs/1.1.0/advanced-resources/deploy/taint-toleration/ .
