### ISSUE TITLE
Creation of EKS cluster with rancher 2.5.6 does not work.

### ISSUE THREAD

**Issue by wojtasool** [rancher/terraform-provider-rancher2#601]
After rancher server upgrade from 2.5.5 to 2.5.6 creation of EKS clusters does not work anymore.
Tried plugin rancher2 with version 1.12.0 but no sucess.
It complaints about launchTemplate beeing nil and also about ResourceTags being nil for node group.
Example:
"Field [resourceTags] cannot be nil for nodegroup [harbor_node_group] in non-nil cluster [c-8pl69]"

Such fields can not be specified with there versions of terraform module.
I'm using eks_config_v2 configuration parameter.

gz#15934

**Comment by wojtasool** [comment]
| Field [launchTemplate.ID] cannot be nil for nodegroup [test-node_group] in non-nil cluster [c-5mj79]
-- | --

**Comment by carlcauchi** [comment]
**[ BLOCKING ISSUE ]**

I have managed to replicate the same issue using Rancher v2.5.7 using Rancher2 provider v1.12.0:
When creating an EKS Cluster, its errors out on:

**`Field [launchTemplate.ID] cannot be nil for nodegroup [xxxxNodeGroupNamexxxx] in non-nil cluster [c-b69l4]`**

@rawmind0

**Comment by rawmind0** [comment]
Fix included at new Rancher2 tfp release v1.13.0
