### ISSUE TITLE
Import rke2 clusters

### ISSUE THREAD

**Issue by ron1** [rancher/terraform-provider-rancher2#603]
Provider should deliver the same level of support to rke2 clusters as it does to k3s clusters. At a minimum, the importation of rke2 clusters should be supported.

**Comment by rawmind0** [comment]
PR https://github.com/rancher/terraform-provider-rancher2/pull/626 has been tested and merged. The feaure will be availbale on next tfp release.

Please, reopen issue if needed

**Comment by ron1** [comment]
@rawmind0 Since this is a significant, customer-facing capability, would it be possible to cut a new tfp release soon that includes this feature?
