### ISSUE TITLE
Support configuration of environment variables for RKE clusters

### ISSUE THREAD

**Issue by fad3t** [rancher/terraform-provider-rancher2#604]
Since Rancher 2.5.6, it is possible to set environment variables for the rancher-agent (see [doc](https://rancher.com/docs/rancher/v2.5/en/cluster-provisioning/rke-clusters/options/#agent-environment-variables) or [github](https://github.com/rancher/rancher/issues/31370)).
It would be nice to be able to configure them through the rancher2_cluster resource.

**Comment by Edge94** [comment]
Hello, any update on this request?
