### ISSUE TITLE
[hetzner] wrong type of networks in rancher2_node_template

### ISSUE THREAD

**Issue by Jasstkn** [rancher/terraform-provider-rancher2#607]
Hi.
According to the docs networks should be comma-separated list of networks, but as I can see in source [code](https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/schema_node_template_hetzner.go) it's a string. 

I'm also wonder why networks passed as null? 

```
resource "rancher2_node_template" "hetzner_node_template" {
  for_each = toset(var.node_template_name)
  name     = "${var.node_template_prefix}_${each.key}"

  description        = "Template to create ${var.node_template_prefix} ${each.key} nodes"
  driver_id          = var.hetzner_driver_id
  engine_install_url = var.engine_install_url
  hetzner_config {
    api_token       = var.hcloud_token
    image           = var.node_image
    server_type     = var.node_type
    server_location = var.node_location
    networks        = var.private_network_name
  }
}
```

Compare manually created and via terraform - networks, imageid are different:
```json
hetznerConfig": {
  "additionalKey": [ ],
  "apiToken": "XXXXX",
  "existingKeyId": "0",
  "existingKeyPath": "",
  "image": "ubuntu-20.04",
  "imageId": "15512617",
  "networks": [ ],
  "serverLabel": [
  "cattle.io/creator=norman"
  ],
  "serverLocation": "nbg1",
  "serverType": "cx21",
  "usePrivateNetwork": false,
  "userData": ""
 }
```

```json
hetznerConfig": {
  "apiToken": "XXXXXX",
  "existingKeyId": "0",
  "existingKeyPath": "",
  "image": "ubuntu-20.04",
  "imageId": "0",
  "networks": null,
  "serverLocation": "nbg1",
  "serverType": "cx21",
  "usePrivateNetwork": false,
  "userData": ""
}
```

If I change node template via UI and run terraform plan I've got:
```
: json: cannot unmarshal array into Go struct field hetznerConfig.hetznerConfig.networks of type string
```

Maybe it comes from this [line](https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/schema_node_template_hetzner.go#L53).

... And if I try to provision cluster from this template, I've got:
```
Error setting machine configuration from flags provided: --hetzner-image and --hetzner-image-id are mutually exclusive;
```

**Comment by Jasstkn** [comment]
@alexzimmer96 Hi. maybe you have some info regarding this issue? I've forked your module so maybe you have some answers :)

**Comment by rawmind0** [comment]
Hi @Jasstkn , PR https://github.com/rancher/terraform-provider-rancher2/pull/570 containing a patch to fix this issue has been merged. 

Please, reopen the issue if needed

**Comment by Jasstkn** [comment]
> Hi @Jasstkn , PR https://github.com/rancher/terraform-provider-rancher2/pull/570 containing a patch to fix this issue has been merged. 
> 
> 
> 
> Please, reopen the issue if needed

Great news! Many thanks! I'm gonna test that.

**Comment by Jasstkn** [comment]
@rawmind0 Hello. I'm just wondering when release will be cut?

**Comment by Jasstkn** [comment]
@rawmind0 hi! Sorry for disturbing you.. But maybe you can cut the release?
