### ISSUE TITLE
Disabling monitoring v1 requires false

### ISSUE THREAD

**Issue by dkeightley** [rancher/terraform-provider-rancher2#610]
rancher2 provider: v0.12.0 (v0.11.0 also tested)
Rancher: v2.5.6
Terraform: v0.14.4

After enabling monitoring (`enable_cluster_monitoring = true`) on a `rancher2_cluster`, a typical workflow of removing the `enable_cluster_monitoring` argument will not detect any change for the `rancher2_cluster` resource.

Explicitly setting `false` is required to disable monitoring.

This may be working as expected, if so this might be a documentation update.

**Comment by rawmind0** [comment]
This is the expected behaviour, due to [`rancher2_cluster.enable_cluster_monitoring`](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster#enable_cluster_monitoring) is a terraform computed argument. If it's not defined, getting the value from Rancher API (doesn't set a default value `false`).

**Comment by dkeightley** [comment]
@rawmind0 would this be worthwhile documenting in the `rancher2_cluster` resource page? It seems to be adding some confusion recently.

I'd be happy to draft this, but I'm not sure exactly where or the most appropriate wording.

**Comment by rawmind0** [comment]
@dkeightley , sure, would be useful to add some docs notes about this, if it's adding confusion. The provider docs are under the folder, https://github.com/rancher/terraform-provider-rancher2/tree/master/docs, it would be so useful if you could submit a PR adding some explanations about it.

**Comment by rawmind0** [comment]
Added a note at the docs at PR #681  https://github.com/rancher/terraform-provider-rancher2/pull/681/files#diff-ea87985827a5e33692d9699416d9144971b191e9688a542125e8f31b5133adbdR11
