### ISSUE TITLE
Rancher plugin for OKE  new feature- Customer controlled Kubernetes API Server Endpoint

### ISSUE THREAD

**Issue by rishgh** [rancher/terraform-provider-rancher2#612]
New OKE clusters now allow users to manage the Kubernetes API Server endpoint. Need to add this in the racnher plugin for OKE cluster creation - https://docs.oracle.com/en-us/iaas/releasenotes/changes/09d90926-eac8-491f-954e-d7347b40aded/

**Comment by jlamillan** [comment]
See also: https://github.com/rancher-plugins/kontainer-engine-driver-oke/issues/26

**Comment by rawmind0** [comment]
This feature is not available at Rancher side yet. It has dependencies with https://github.com/rancher-plugins/kontainer-engine-driver-oke/issues/26

**Comment by jlamillan** [comment]
Server side support for this feature is complete: https://github.com/rancher/rancher/commit/b0b0ff38d727d8287ae2b5bfee47ce3457d45539
