### ISSUE TITLE
Creating project with empty namespace quotas fails

### ISSUE THREAD

**Issue by sveba** [rancher/terraform-provider-rancher2#613]
Rancher 2.5.5
I'm trying to create a project without default namespace limits

```
resource "rancher2_project" "foo" {
  name = "foo"
  cluster_id = data.rancher2_cluster.foo.id
  resource_quota {
    project_limit {
      limits_cpu = "25000m"
      limits_memory = "500Gi"
    }
    namespace_default_limit {}
  }
}
```

Result:
```
Error: Bad response statusCode [422]. Status [422 Unprocessable Entity]. Body: [code=MissingRequired, fieldName=namespaceDefaultResourceQuota, message=does not have all fields defined on a resourceQuota, baseTyp
from [https://rancher-thf.idst.ibaintern.de/v3/projects]

  on ocp-system.tf line 1, in resource "rancher2_project" "foo":
   1: resource "rancher2_project" "foo" {
```

**Comment by rawmind0** [comment]
[`namespace_default_limit`](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/project#namespace_default_limit) argument is required if `resource_quota` is defined

**Comment by sveba** [comment]
@rawmind0 you are right. But all arguments are optional. So I guess an empty object should be OK?

**Comment by rawmind0** [comment]
Yes, you are right. The doc explanation could be improved, but basically they are all optional due to just limits that are defined at `project_limit` could be defined at `namespace_default_limit`. 

```
resource "rancher2_project" "foo" {
  name = "foo"
  cluster_id = data.rancher2_cluster.foo.id
  resource_quota {
    project_limit {
      limits_cpu = "25000m"
      limits_memory = "500Gi"
    }
    namespace_default_limit {
      limits_cpu = "5000m"
      limits_memory = "100Gi"
    }
  }
}
```

**Comment by sveba** [comment]
> limits that are defined at `project_limit` could be defined at `namespace_default_limit`.

This would be great to find in the documentation. Thank you for clearing this for me
