### ISSUE TITLE
Add possibility to create private AKS cluster

### ISSUE THREAD

**Issue by wojtasool** [rancher/terraform-provider-rancher2#619]
In Azure portal there is possibility to create private AKS cluster.
We would like to have same option in rancher2 provider.

Regards

**Comment by rawmind0** [comment]
Is this feature available at Rancher2??

**Comment by wojtasool** [comment]
It is not present there either.

**Comment by rawmind0** [comment]
@wojtasool , if the feature is not available at Rancher, this issue should be first opened at https://github.com/rancher/rancher repo.

**Comment by wojtasool** [comment]
Ale rady present in 1.20.0
