### ISSUE TITLE
Feature request: Add support for node pool node labels and annotations

### ISSUE THREAD

**Issue by rodcloutier** [rancher/terraform-provider-rancher2#620]
The Rancher api allows to set the labels and annotations on nodes through the node pool resource. 
The `nodeTaints` is already supported but `nodeAnnotations` and `nodeLabels` are not. 

```
{
    "annotations": {
        "lifecycle.cattle.io/create.nodepool-provisioner": "true",
    },
    "baseType": "nodePool",
    "clusterId": "c-7lrvt",
    "controlPlane": true,
    "created": "2021-04-07T17:03:16Z",
    "createdTS": 1617814996000,
    "creatorId": "u-r4zs2fm23u",
    "deleteNotReadyAfterSecs": 0,
    "displayName": "",
    "driver": "internal",
    "etcd": false,
    "hostnamePrefix": "cluster-master",
    "id": "c-7lrvt:cluster-master",
    "labels": {
        "cattle.io/creator": "norman",
    },
    "links": {
        "nodes": "…/v3/nodes?nodePoolId=c-7lrvt%3Acluster-master",
        "remove": "…/v3/nodePools/c-7lrvt:cluster-master",
        "self": "…/v3/nodePools/c-7lrvt:cluster-master",
        "update": "…/v3/nodePools/c-7lrvt:cluster-master"
    },
    "name": "cluster-master",
    "namespaceId": null,
    "nodeAnnotations": null,
    "nodeLabels": null,
    "nodeTaints": [
    ],
    "nodeTemplateId": "cattle-global-nt:nt-4pr48",
    "quantity": 1,
    "state": "active",
    "status": {
        "conditions": [
            {
                "lastUpdateTime": "2021-04-07T17:03:20Z",
                "status": "True",
                "type": "Updated"
            }
        ],
        "type": "/v3/schemas/nodePoolStatus"
    },
    "transitioning": "no",
    "transitioningMessage": "",
    "type": "nodePool",
    "uuid": "2a344a9b-ec01-4799-a056-22a974c23b48",
    "worker": false
}
```

**Comment by mitchellmaler** [comment]
This can be done using the NodeTemplate resources labels and annotations fields.

Unfortunately to add labels and annotations to NodePools (which are applied to the downstream nodes) would require a Rancher Server change allowing the capability first before it can be added to tf provider.

**Comment by rodcloutier** [comment]
Thanks for the hint. I will use that instead. 

Just a question then, what are those fields purpose?

**Comment by mitchellmaler** [comment]
annotations. labels, and note_taints on the NodeTemplate resource.
https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/node_template#annotations

**Comment by rodcloutier** [comment]
Well the whole thing seems to be somewhat messy. 

The documentation on the provider states that the annotations and labels are for the `NodeTemplate` resource not the nodes.
https://github.com/rancher/terraform-provider-rancher2/blame/master/docs/resources/node_template.md#L110

But... the `labels` from the node template are applied to the node as seen here:
https://github.com/rancher/rancher/blob/master/pkg/controllers/management/node/controller.go#L652

Taints can be applied with `nodeTaints` from either the `NodePool` or `NodeTemplate` resources...
https://github.com/rancher/rancher/blob/master/pkg/controllers/management/node/controller.go#L665

Annotations are never applied.

**Comment by rawmind0** [comment]
> The documentation on the provider states that the annotations and labels are for the NodeTemplate resource not the nodes.
https://github.com/rancher/terraform-provider-rancher2/blame/master/docs/resources/node_template.md#L110
>
> But... the `labels` from the node template are applied to the node as seen here:
https://github.com/rancher/rancher/blob/master/pkg/controllers/management/node/controller.go#L652

True, but there is a [note]((https://github.com/rancher/terraform-provider-rancher2/blame/master/docs/resources/node_template.md#L113)) in the nodeTemplate documentation saying `**Note** `annotations`, `labels` and `node_taints` will be applied to nodes deployed using the Node Template`

> Taints can be applied with `nodeTaints` from either the `NodePool` or `NodeTemplate` resources...
https://github.com/rancher/rancher/blob/master/pkg/controllers/management/node/controller.go#L665
>
> Annotations are never applied.

True. Updating nodeTemplate documentation [note](https://github.com/rancher/terraform-provider-rancher2/pull/695/files#diff-39a66052d7b00293a89409c0ba1034281488acf7b0b5301ca2d400811b9f582eR113) to clarify this at PR https://github.com/rancher/terraform-provider-rancher2/pull/695

Please, reopen issue if required
