### ISSUE TITLE
Inconsistent status after applying name to existing node pool

### ISSUE THREAD

**Issue by Jasstkn** [rancher/terraform-provider-rancher2#622]
Expected behaviour: new name applied (id in unchanged)
Current behaviour: 
```
  # module.rancher_sandbox_cluster_init.rancher2_node_pool.node_pool["controlplane"] will be updated in-place
  ~ resource "rancher2_node_pool" "node_pool" {
        id                          = "c-XXXXX:np-XXXXX"
      ~ name                        = "np-XXXXX" -> "sandbox-controlplane"
        # (10 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```

**Comment by rawmind0** [comment]
Not clear what the question is here. The tf diff seems that `rancher2_node_pool`  name is going to be updated. Could you please clarify??

**Comment by Jasstkn** [comment]
> Not clear what the question is here. The tf diff seems that `rancher2_node_pool` name is going to be updated. Could you please clarify??

I imported already existing node pool with name np-XXXXX, then I've changed name to sandbox-controlplane, but seems that this change was ignored by API. And now I have inconsistent state because of that.

**Comment by rawmind0** [comment]
Terraform imports resources as they are (import is not updating the resource). I mean, you can't import and update a resource in a row, it's a 2 steps process: first import the resource and second apply changes on it, if required. This is the expected behaviour.

**Comment by Jasstkn** [comment]
> Terraform imports resources as they are (import is not updating the resource). I mean, you can't import and update a resource in a row, it's a 2 steps process: first import the resource and second apply changes on it, if required. This is the expected behaviour.

I did that. After I applied new name I see output from the description. That name of the template wasn't changed.

**Comment by rawmind0** [comment]
Oh, got it. The node_pool name can't be updated from Rancher2 API.  Take a look to https://RANCHER_URL/v3/schemas/nodePool
```
...
"name": {

    "create": true,
    "nullable": true,
    "type": "dnsLabel",
    "update": false

},
...
```
The provider should force a new node_pool resource if the name is updated. We'll submit a PR to address that.

**Comment by Jasstkn** [comment]
> Oh, got it. The node_pool name can't be updated from Rancher2 API. Take a look to https://RANCHER_URL/v3/schemas/nodePool
> 
> ```
> ...
> "name": {
> 
>     "create": true,
>     "nullable": true,
>     "type": "dnsLabel",
>     "update": false
> 
> },
> ...
> ```
> 
> The provider should force a new node_pool resource if the name is updated. We'll submit a PR to address that.

Will it trigger recreation of node pools which are already existing?

**Comment by rawmind0** [comment]
> Will it trigger recreation of node pools which are already existing?

Yes, due to node_pool name can't be updated.

**Comment by rawmind0** [comment]
Submitted PR https://github.com/rancher/terraform-provider-rancher2/pull/625  to address this issue
