### ISSUE TITLE
Specify project registry credentials via terraform

### ISSUE THREAD

**Issue by Jasstkn** [rancher/terraform-provider-rancher2#624]
Hi!

Is it possible to specify project registry credentials via terraform? I didn't find a mention in the documentation.

**Comment by rawmind0** [comment]
Hi @Jasstkn , as shown in the documentation, it's possible to specify username and password in the registry definition,  https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/registry .

**Comment by Jasstkn** [comment]
> Hi @Jasstkn , as shown in the documentation, it's possible to specify username and password in the registry definition, https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/registry .

Ahh, I got it.
I thought it was about internal registry created by Rancher because of this description:
> This can be used to create docker registries for Rancher v2 environments and retrieve their information.
