### ISSUE TITLE
Generating a Kubeconfig for a single user

### ISSUE THREAD

**Issue by TristanAllaire** [rancher/terraform-provider-rancher2#628]
Hello !
With its API, Rancher offers the possibility to generate a Kubeconfig for a single user (with a user-scope).
The URI ends with "generatekubeconfig" and it needs a user auth token to be used.

My plan would be to create an user -> generate a kubeconfig for this user in terraform -> populating a var from another resource with this kubeconfig

Is there an implementation of this function in the provider or is it planned?

Thank you for your answers

**Comment by rawmind0** [comment]
Hi @TristanAllaire,

the `rancher2_cluster` resource/datasource is already [generating a kubeconfig](https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/resource_rancher2_cluster.go#L221), saving it as [tf `kube_config` attribute](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster#kube_config) 

The generated kubeconfig is generated for the user used at tf provider. For the use case you mention, if the user is not the cluster owner, using [`rancher2_cluster` datasource](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/data-sources/cluster), with the proper user token, it should generate a kube_config attribute for this user.
