### ISSUE TITLE
enable_cluster_monitoring: true

### ISSUE THREAD

**Issue by ajchiarello** [rancher/terraform-provider-rancher2#63]
Is there any way to set the enable_cluster_monitoring setting to true in an RKE cluster with the provider? I see the monitoring section in the RKE config, but that deals with the metrics-server and doesn't look like it enables the Prometheus integration that this setting does.

**Comment by rawmind0** [comment]
@ajchiarello , feature added on PR #66

**Comment by rawmind0** [comment]
Merged PR. Please, reopen issue if needed.
