### ISSUE TITLE
enabling metric alerts fails despite wait_monitoring enabled

### ISSUE THREAD

**Issue by sayshh** [rancher/terraform-provider-rancher2#630]
### Issue:

Enabling of metric alerts with `rancher2_cluster_alert_rule` fails even when `wait_monitoring` is set to true in `rancher2_cluster_sync`. Error as below:

```
Error: Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [baseType=error, code=ServerError, message=if you want to use metric alert, need to enable monitoring for cluster c-np89w] from [https://rancher-demo/v3/clusteralertrules]
```

### Setup:

**Terraform version;** 

```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/rancher/rancher2 v1.12.0
```

### Code:

```hcl
resource "rancher2_cluster" "k8s_cluster" {
  name = "foo-cluster"
  enable_cluster_monitoring = true
  enable_cluster_alerting   = true

  rke_config {
    network {
      plugin = "canal"
    }
  }
}

# resources for rancher2_node_pool omitted

resource "rancher2_cluster_sync" "k8s_cluster" {
  cluster_id      = rancher2_cluster.k8s_cluster.id
  wait_monitoring = rancher2_cluster.k8s_cluster.enable_cluster_monitoring
  node_pool_ids   = [
    rancher2_node_pool.k8s_masters.id,
    rancher2_node_pool.k8s_workers.id
  ]
}

# resource rancher2_cluster_alert_group omitted

resource "rancher2_cluster_alert_rule" "k8s_node_disk_alert" {
  cluster_id  = rancher2_cluster.k8s_cluster.id
  group_id    = rancher2_cluster_alert_group.k8s_cluster_alert_group.id
  name        = "Node disk is running full within 24 hours"
  severity    = "warning"

  metric_rule {
    comparison      = "has-value"
    duration        = "10m"
    expression      = "predict_linear(node_filesystem_free_bytes{mountpoint!~\"^/etc/(?:resolv.conf|hosts|hostname)$\"}[6h], 3600 * 24) < 0"
    threshold_value = 0
  }
}
```

### Expected behaviour:

`rancher2_cluster_sync` resource waits for monitoring to be enabled, then creates `rancher2_cluster_alert_rule`.

### Actual behaviour: 

`rancher2_cluster_sync` resource waits for monitoring to be enabled, and it tries to create the metric rule but fails with the error mentioned above.

**Note**: If I wait for 10 minutes and then run `terraform apply` again then the rule gets created.

**Comment by rawmind0** [comment]
The `rancher2_cluster_alert_rule` tf definition is not using `rancher2_cluster_sync`, so not waiting for the cluster. Could you please try using `cluster_id  = rancher2_cluster_sync.k8s_cluster.cluster_id` instead??

```
resource "rancher2_cluster_alert_rule" "k8s_node_disk_alert" {
  cluster_id  = rancher2_cluster_sync.k8s_cluster.cluster_id
  group_id    = rancher2_cluster_alert_group.k8s_cluster_alert_group.id
  name        = "Node disk is running full within 24 hours"
  severity    = "warning"

  metric_rule {
    comparison      = "has-value"
    duration        = "10m"
    expression      = "predict_linear(node_filesystem_free_bytes{mountpoint!~\"^/etc/(?:resolv.conf|hosts|hostname)$\"}[6h], 3600 * 24) < 0"
    threshold_value = 0
  }
}
```

**Comment by sayshh** [comment]
Ok, so using the `id` attribute from `rancher2_cluster_sync` resource made sure that the alert got created as expected. Thanks for that!

I also have a bunch of other resources and outputs that depend on the cluster ID, should they all reference the `id` from `rancher2_cluster_sync`? 

I wish the documentation was clearer about the use of attributes from `rancher2_cluster` and `rancher2_cluster_sync` resources.

The other question that arises in my mind is, why have a separate resource to "sync", can it not be a parameter of `rancher2_cluster` resource itself?

Like so:

```hcl
resource "rancher2_cluster" "k8s_cluster" {
  name = "foo-cluster"
  enable_sync = true

  rke_config {
    network {
      plugin = "canal"
    }
  }
}
```

**Comment by rawmind0** [comment]
> Ok, so using the id attribute from rancher2_cluster_sync resource made sure that the alert got created as expected. Thanks for that!

Glad to hear that. The dependency was not properly defined.

> I also have a bunch of other resources and outputs that depend on the cluster ID, should they all reference the id from rancher2_cluster_sync?
>
> I wish the documentation was clearer about the use of attributes from rancher2_cluster and rancher2_cluster_sync resources.

It depends if the resources need that the cluster is active or not. The [rancher2_cluster_sync](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster_sync
) was just created to manage sync/dependencies between resources. 

The docs are explaining what a `rancher2_cluster_sync` is:
`This dummy resource doesn't create anything at Rancher side. It's used to sync terraform resources that depends of Rancher v2 Cluster resource in active state. This resource will wait until cluster_id is active on terraform apply. It also helps to sync terraform destroy dependencies, specially useful if cluster is using node pools.`

If the explanation is not fully clear, more than happy to accept a PR with a clearer explanation.

> The other question that arises in my mind is, why have a separate resource to "sync", can it not be a parameter of rancher2_cluster resource itself?

Because the expected cluster state depends on the kind of the cluster. For example, if you are creating a custom cluster, you need to create it, get the node_command and execute it before the cluster is active. Both resources are required

**Comment by sayshh** [comment]
I've seen the documentation, but not sure how to know which resources require the cluster to be in active state? For e.g. `rancher2_cluster_logging`  works as well with the `id` from either of the resources. Pretty much every resource can wait for the cluster to be active I guess. :)

> It's used to sync terraform resources that depends of Rancher v2 Cluster resource in active state

Anyway, I'm not sure how the documentation can be improved.
