### ISSUE TITLE
Issue with Hetzner node tamplate (options use_private_network = true doesn't work)

### ISSUE THREAD

**Issue by denismatiu** [rancher/terraform-provider-rancher2#631]
If options `use_private_network = true`
```
# Create a new rancher2 Node Template
resource "rancher2_node_template" "hetzner-template" {
  name        = "hetzner-template"
  description = "Default template to acquire Hetzner Cloud Nodes"
  driver_id   = var.hetzner_driver_id
  engine_install_url = "https://releases.rancher.com/install-docker/19.03.sh"
  hetzner_config {
    api_token       = var.hcloud_token
    image           = "ubuntu-20.04"
    server_type     = var.server_type
    server_location = "hel1"
    use_private_network = true
    networks        = var.private_network_name
  }
}
```
then after` terraform apply` - in node tamplate I see
"usePrivateNetwork": false,
````
...
"creatorId": "user-cgw65",
"description": "Default template to acquire Hetzner Cloud Nodes",
"driver": "hetzner",
"engineInstallURL": "https://releases.rancher.com/install-docker/19.03.sh",
"hetznerConfig": {
"apiToken": "HWxsfy1DSFozHr77TE3b************************************",
"existingKeyId": "0",
"existingKeyPath": "",
"image": "ubuntu-20.04",
"imageId": "0",
"networks": [
"kubernetes-internal"
],
"serverLocation": "hel1",
"serverType": "cx11",
"usePrivateNetwork": false,
"userData": ""
},
"id": "cattle-global-nt:nt-xslvc",
"labels": {
"cattle.io/creator": "norman"
},
"links": {
...
````

**Comment by aleksmova** [comment]
I have the same issue. Are there any solutions?

**Comment by rawmind0** [comment]
It seems json tag is not properly set at Hetzner node template schema,
https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/schema_node_template_hetzner.go#L19

I guess it should be:
```
	UsePrivateNetwork bool     `json:"usePrivateNetwork,omitempty" yaml:"usePrivateNetwork,omitempty"`
``` 

cc: @alexzimmer96

**Comment by rawmind0** [comment]
Submitted PR https://github.com/rancher/terraform-provider-rancher2/pull/661 to fix this issue

**Comment by aleksmova** [comment]
Could you please reopen this issue, seems that issue wasn't fixed.

**Comment by rawmind0** [comment]
Have you built the provider and test it??

**Comment by aleksmova** [comment]
Exactly. I have updated the provider for all templates and modules to the 0.14.0 version and built a new cluster from scratch.

**Comment by rawmind0** [comment]
The patch to this issue is not included on the provider v0.14.0. Still not released, to test the provider should be built from repo

**Comment by aleksmova** [comment]
Got it. Thanks

**Comment by denismatiu** [comment]
@rawmind0  I checked, everything works great. 👍  Thank you guys. Could you tell me when you are planning the next release?
