### ISSUE TITLE
Use cluster_yaml for rke_config?

### ISSUE THREAD

**Issue by jmatsushita** [rancher/terraform-provider-rancher2#639]
Hello,

Is it possible to use the rke `cluster.yml` configuration file either as a `rancher_cluster_template` or `rancher_cluster` in the way the `rancher/rke` terraform module allows with [`cluster_yaml`](https://registry.terraform.io/providers/rancher/rke/latest/docs/resources/cluster#cluster_yaml) ?

**Comment by rawmind0** [comment]
Hi @jmatsushita , no it's not possible on this provider

**Comment by jmatsushita** [comment]
Something you'd consider a PR for? Or do you have other plans? I'm interested in the `rke2` yaml config too in [this PR](https://github.com/rancher/terraform-provider-rancher2/pull/626).

**Comment by rawmind0** [comment]
The use of `cluster.yml` is not supported at Rancher, so btm there isn't plans to include it into the provider. The rke2 support is prepared, just waiting for review and be included in next provider release.
