### ISSUE TITLE
Create user with permissions & scopes

### ISSUE THREAD

**Issue by ronny35** [rancher/terraform-provider-rancher2#641]
Hi,

Is it possible to create user permissions & scopes ?

Thanks in advance for your work.

**Comment by rawmind0** [comment]
Hi @ronny35 , yes you can. Please, take a look to the [provider documentation](https://registry.terraform.io/providers/rancher/rancher2/latest/docs):
- [user](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/user)
- Roles by scope:
  - [global_role](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/global_role)
  - [cluster/project](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/role_template) 
- Role bindings by scope:
  - [global_role_binding](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/global_role_binding) 
  - [cluster_role_binding](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster_role_template_binding) 
  - [project_role_binding](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/project_role_template_binding)
