### ISSUE TITLE
rancher resources are deleted, vsphere nodes still existing

### ISSUE THREAD

**Issue by dcardellino** [rancher/terraform-provider-rancher2#642]
Hey there,

I'm using the terraform-provider-rancher2 to provision clusters in vmware vsphere 6.7u3l.
I wrote a little module to create my resources 

- rancher2_cloud_credential
- rancher2_node_template
- rancher2_cluster
- rancher2_cluster_sync
- rancher2_node_pool

The creation/deletion of those resources are all successful. But when i want to delete a cluster, the virtual machines in vSphere are still existing. I already tried to manage dependencies like mentioned in rancher/terraform-provider-rancher2#297 but had no success.

Are there some known issues, when delete a cluster you will have to manually delete the virtual machines in vsphere?

Terraform Version: 0.14.5
Provider Version: 1.13.0
vSphere Version: 6.7U3L

**Comment by rawmind0** [comment]
Hi @dcardellino , what Rancher version are you using?? There is a know issue on v2.5.6 and v2.5.7, where node pools vm's are not properly removed https://github.com/rancher/rancher/issues/31765. It will be addressed on Rancher v2.5.8

**Comment by dcardellino** [comment]
@rawmind0 

I knew there was one thing missing :-) I'm using Rancher v2.5.7, so there is a known issue. I will close this issue and wait for 2.5.8. 

Thanks 👍
