### ISSUE TITLE
Delete rancher2_node_pool should wait until node controller deletes nodes

### ISSUE THREAD

**Issue by ekristen** [rancher/terraform-provider-rancher2#643]
If a node pool is created by the terraform provider, the deletion shouldn't be considered successful until all the underlying nodes are cleaned up.

**Comment by rawmind0** [comment]
Yes, it should wait but it's a Rancher issue at concrete versions. Please take a look to https://github.com/rancher/terraform-provider-rancher2/issues/642#issuecomment-827547674

**Comment by ekristen** [comment]
So with 2.5.8 the terraform provider will work properly? No changes needed on the terraform side?

**Comment by rawmind0** [comment]
As mentioned, the issue seems to be at rancher side.  Once addressed, should work properly

**Comment by ekristen** [comment]
@rawmind0 thanks, but it seems premature to close the issues if it hasn't been verified as working properly. 2.5.8-rc12 is out, can we test and verify the fix there at the very minimum?

**Comment by rawmind0** [comment]
It was already tested at 2.5.8-rc1 https://github.com/rancher/rancher/issues/31765
