### ISSUE TITLE
Rancher2 Terraform EKSv2.0 import does not import cluster as is 

### ISSUE THREAD

**Issue by sogajeffrey** [rancher/terraform-provider-rancher2#648]
**What kind of request is this (question/bug/enhancement/feature request):**
BUG: When using the terraform rancher2 provider rancher_cluster resource to import an existing EKS cluster. it sets the EKS cluster access back to the default of public access and disables private access. If I set private_access to true and public_access to false it assumes I'm creating a new cluster and asks for kubernetes_version and node_groups. 

**Steps to reproduce (least amount of steps as possible):**
1. Create EKS cluster outside of rancher (using terraform) and set only private access 
2. Import using below terraform code
```
resource "rancher2_cluster" "eks_import" {
  name                  = var.cluster_id
  description           = var.cluster_id
  eks_config_v2 {
    cloud_credential_id = var.rancher_cloud_credential
    name                = var.cluster_id
    region              = data.aws_region.current.name
    imported            = true
  }
}
```

**Result:**
1. Rancher will import the EKS cluster and modify the EKS cluster to enable public access and disable private access

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.3
- Installation option (single install/HA): HA on top of EKS

**Comment by rawmind0** [comment]
@cbron , fix is merged and we are gonna release a new tfp after 2.5.8. 

@aaronRancher attaching tfp custom binaries with patch applied,  to be tested:

* [terraform-provider-rancher2_linux_amd64.gz](https://github.com/rancher/terraform-provider-rancher2/files/6422057/terraform-provider-rancher2_linux_amd64.gz)
* [terraform-provider-rancher2_windows_amd64.exe.gz](https://github.com/rancher/terraform-provider-rancher2/files/6422058/terraform-provider-rancher2_windows_amd64.exe.gz)
* [terraform-provider-rancher2_darwin_amd64.gz](https://github.com/rancher/terraform-provider-rancher2/files/6422054/terraform-provider-rancher2_darwin_amd64.gz)

To use custom binary, download proper architecture archive, decompress it and use it to overwrite tf provider binary.

**Comment by cbron** [comment]
@rawmind0 can you make sure its fixed in both gke and eks

**Comment by rawmind0** [comment]
@cbron just fixed on EKS, GKE feature is not yet merged at tfp

**Comment by cbron** [comment]
Ok can you make sure its fixed when its added in https://github.com/rancher/terraform-provider-rancher2/issues/647

**Comment by rawmind0** [comment]
@cbron @aaronRancher , last patched tfp binaries, fixing GKE and EKS imported cluster can be found here https://github.com/rancher/terraform-provider-rancher2/pull/621#issuecomment-833806210

**Comment by aaronyeeski** [comment]
Tested on Rancher `master-head` `version 70ba0d5` with these tf binaries https://github.com/rancher/terraform-provider-rancher2/pull/621#issuecomment-833806210.

Imported a private GKE cluster with the following tf code:
```
resource "rancher2_cluster" "aaron-import-private" {
  name = "aaron-import-private"
  description = "Foo rancher2 imported GKE cluster"
  gke_config_v2 {
    name = "aaron-import-private"
    google_credential_secret = "cattle-global-data:----"
    zone = "us-central1-c"
    project_id = "---"
    imported = true
  }
```
Cluster nodes remain private in GKE upstream spec:
```
rivateClusterConfig": {
"enablePrivateEndpoint": false,
"enablePrivateNodes": true,
"masterIpv4CidrBlock": "10.00.0.0/28",
"type": "/v3/schemas/gkePrivateClusterConfig"
},
```

Imported a private EKS cluster with the following tf code:
```
resource "rancher2_cluster" "aaron-private2" {
  name = "aaron-private2"
  description = "Foo rancher2 imported eks cluster"
  eks_config_v2 {
    name = "aaron-private2"
    cloud_credential_id = "cattle-global-data:---"
    region = "us-east-2"
    imported = true
  }
```
EKS cluster remains private in upstream spec:
```
privateAccess": true,
"publicAccess": false,
"publicAccessSources": [ ],
"region": "us-east-2",
"secretsEncryption": false,
"securityGroups": null,
"serviceRole": null,
"subnets": null,
"tags": { },
"type": "/v3/schemas/eksClusterConfigSpec"
```
