### ISSUE TITLE
xip.io is down so things like rancher2_bootstrap doesn't work

### ISSUE THREAD

**Issue by SebTardif** [rancher/terraform-provider-rancher2#649]
Could we rewrite the logic to not rely to a public internet web site that is fragile.

Also, if I want to use that 'airgap' / detached from Internet. How can I replace the logic of xip.io ?

**Comment by rawmind0** [comment]
What do you mean?? `rancher2_bootstrap` nor any other provider resource is based xip.io

**Comment by SebTardif** [comment]
@rawmind0 I was surprised like you, see https://github.com/rancher/terraform-provider-rancher2/blob/8a9c0e4022f659b823fb076a1cf0ae2325208fa3/scripts/start_rancher.sh

**Comment by rawmind0** [comment]
@SebTardif That's not a surprise to me, this is known. The file you mention is just a script to build acceptance test env, nothing related with the use of the tf provider nor its resources. These scripts are just intended to run automated ci and acceptance tests, they are not part of the provider code nor functionality. Are you having any issue with any provider resource??
