### ISSUE TITLE
Add support for specifying enableProjectMonitoring while creating project resource

### ISSUE THREAD

**Issue by ishantanu** [rancher/terraform-provider-rancher2#65]
Hi,

Currently, I am not sure if it's possible to enable project-level monitoring while creating `rancher2_project` resource. Yes, it was disabled in 2.2.2 because of some issues but it's back in 2.2.4.

**Comment by rawmind0** [comment]
@ishantanu, feature added on PR #66

**Comment by rawmind0** [comment]
Merged PR. Please, reopen issue if needed.
