### ISSUE TITLE
Filter `pull_request` build events to run on `drone-pr.rancher.io`

### ISSUE THREAD

**Issue by paraglade** [rancher/terraform-provider-rancher2#652]
Pull requests should be targeted to `drone-pr.rancher.io` as this environment is more suitable for validating code pull requests. This will require repo activation on `drone-pr.rancher.io` and modification to `.drone.yml` to filter this event and target `drone-pr.rancher.io`

**Comment by rawmind0** [comment]
@paraglade thanks for the advice. The config changes has been done configuring drone webhook. The `.drone.yml` update is not required.
