### ISSUE TITLE
rke_config in rancher2_cluster resource for custom provider seems useless

### ISSUE THREAD

**Issue by rule88** [rancher/terraform-provider-rancher2#655]
It is hard to figure out that apparently rancher2_cluster does not provision hosts when using the "custom" provider, despite configurations imply it will.

Documentation is also not clear about this. Especially arguments like `bastion_host` and `ssh_agent_auth` do suggest provisioning nodes with RKE (as what RKE is built for) is possible.

**Comment by rule88** [comment]
To elaborate, we would like to provision new `child` clusters on top of `custom` machines. We assumed it would be possible to use the `rke_config` attribute in the `rancher2_cluster` resource for this as the `parent` cluster is also provisioned with rke (using tf module rancher/rke).

Is there any automation in this case possible other than fetching a token from the `rancher2_cluster` resource and fiddling around with executors?

**Comment by rawmind0** [comment]
Custom `rancher2_cluster` is not deploying any node nor imply it, same behaviour as got from Rancher UI. [Rancher doc custom nodes](https://rancher.com/docs/rancher/v2.0-v2.4/en/cluster-provisioning/rke-clusters/custom-nodes/) is also explaining it. Custom cluster is assuming nodes are already deployed, so once the cluster is created, [`node_command`](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster#node_command) is generated and it's needed to be executed at nodes, with proper k8s roles.

If you want to deploy a cluster (including the infrastructure deployment), you should use `rancher2_node_template` and `rancher2_node_pools`. You can find an example in the [Rancher2 tf provider docs](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster#creating-rancher-v2-rke-cluster-assigning-a-node-pool-overlapped-planes)

**Comment by rule88** [comment]
It does imply deploying k8s using RKE. The confusion is RKE itself, as with RKE you normally deploy RKE on existing machines (machines are ready and only awaiting the initial docker command).

Using the RKE TF module (also provided by rancher), the same attributes are accepted and this module **does** deploy k8s to the provided list of hosts.

**Comment by rawmind0** [comment]
Rancher2 and RKE works different at this point, so the tf providers are working different. RKE is connecting by ssh to nodes to run the needed components, Rancher2 instead is just providing the command and you need to execute it in yous nodes and they will connect to Rancher.

**Comment by rule88** [comment]
How would you advice to, idempotent, use rancher2 (as we would like to have the cluster managed with Rancher) and have the ability to create `custom` clusters?

**Comment by rawmind0** [comment]
@rule88, don't fully understanding the question . The use of the `rancher2_cluster` is idempotent, and the ability to create `custom` clusters is already there as mentioned before. 

> Custom cluster is assuming nodes are already deployed, so once the cluster is created, [`node_command`](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster#node_command) is generated and it's needed to be executed at nodes, with proper k8s roles.

So, create `rancher2_cluster` with custom config (rke_config), once cluster is created (provisioning state) get the `rancher2_cluster.cluster_registration_token.0.node_command` and execute it on nodes, adding proper k8s roles.

**Comment by rule88** [comment]
> So, create rancher2_cluster with custom config (rke_config), once cluster is created (provisioning state) get the rancher2_cluster.cluster_registration_token.0.node_command and execute it on nodes, adding proper k8s roles.

This is where my concern is regarding idempotent provisioning/deploying, who or what knows the actual state of that machine? Terraform will either always run that command on the host or only once when the resource is created. Both approaches have no guarantee that the node _is_ successfully registered in the end.

**Comment by rule88** [comment]
It just would be a very nice feature if the rancher2_cluster, with it's rke_config, had the ability to ssh to the host and provision the host, as only the rancher2_cluster is aware of machine's state in rancher.

**Comment by rawmind0** [comment]
@rule88 Rancher2 is NOT going to ssh any node if using custom config, this is the same behaviour as at Rancher UI. The ssh and the execution of the node_command has to be done "outside" this tf provider, manual or automated. Custom cluster is not taking care of the nodes provision/config, it's assuming nodes are already deployed/maintained outside .

> It just would be a very nice feature if the rancher2_cluster, with it's rke_config, had the ability to ssh to the host and provision the host, as only the rancher2_cluster is aware of machine's state in rancher.

As mentioned, this can be done using node_templates and node_pools, so rancher would take care of the nodes deployment/config.

**Comment by rule88** [comment]
@rawmind0 I understand it won't be Rancher2 itself that should loginover ssh itself, it must be terraform that should be doing this. The references in the [doc's](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster#rke_config) regarding ssh (e.g. [bastion_host](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster#bastion_host), [ssh_agent_auth](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster#ssh_agent_auth) ) do suggest to me that the rancher2-terraform module uses this to deploy provision the nodes for you (using rke and/or ssh)

**Comment by rawmind0** [comment]
May be docs could be more clear on that, but again, custom clusters are not taking into account `nodes`, `bastion_host`, `ssh_agent_auth`, etc... The behaviour is the same than in Rancher2 ui, where you can't neither provide these parameters. You may ssh/config host using other terraform providers/modules if you prefer, but the Rancher2 tf provider is not doing it, as custom clusters are not getting nodes list. 

Another option may be, use RKE tf provider to create the cluster and then use Rancher2 tf provider to import the cluster into Rancher.

**Comment by rawmind0** [comment]
This was also discussed at https://github.com/rancher/terraform-provider-rancher2/issues/442#issuecomment-685773446

**Comment by rule88** [comment]
Hi @rawmind0 ,

the suggested solution is what we indeed came up with yesterday and it is working as expected. I think indeed that docs could be more clear on this, the misconception to me was the term `rke_config`. To me it seemed that the config was used by Terraform and on its turn somehow uses RKE to create the desired nodes. 

Might it be an idea, as it seems we are not alone on this topic, that docs are enhanced (some warning or remark )?

**Comment by rawmind0** [comment]
Hi @rule88 ,

for sure we might improve the docs, if something seems not clear to users. I understand the misconception, but this is a Rancher2 provider and is having same behaviour as Rancher2 has. Could you please help on this, proposing a PR with some warning or remark on docs that would help to clarify the misconception??

**Comment by rule88** [comment]
@rawmind0 - https://github.com/rancher/terraform-provider-rancher2/pull/659

**Comment by rawmind0** [comment]
@rule88 , Thanks for the PR. It's already merged. 

Please, reopen issue if required.
