### ISSUE TITLE
[hetzner] rancher2_node_template ignores "networks"

### ISSUE THREAD

**Issue by Jasstkn** [rancher/terraform-provider-rancher2#656]
Hi!

I've noticed that if I pass "networks" as string value to rancher2_node_template, it's ignored. 

I'm not sure but maybe problem is in the mismatch of types [here](https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/schema_node_template_hetzner.go#L18)([]string) and [here](https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/schema_node_template_hetzner.go#L53)(string)

**Comment by rawmind0** [comment]
> I'm not sure but maybe problem is in the mismatch of types [here](https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/schema_node_template_hetzner.go#L18)([]string) and [here](https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/schema_node_template_hetzner.go#L53)(string)

This shouldn't be an issue, it's properly adapted in the [expander](https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/structure_node_template_hetzner.go#L72) and the [flatten](https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/structure_node_template_hetzner.go#L30)

cc: @alexzimmer96

**Comment by rawmind0** [comment]
The issue seems to be at hetzner docker machine driver. `networks` field is not set as "public" at golang struct, https://github.com/JonasProgrammer/docker-machine-driver-hetzner/blob/master/driver.go#L42, so json marshal/unmarshall is just ignoring it.

@alexzimmer96 , could you please take a look on this??

**Comment by process0** [comment]
@Jasstkn I've tried to reproduce this but I cannot. I believe https://github.com/JonasProgrammer/docker-machine-driver-hetzner/issues/64 has solved this.
