### ISSUE TITLE
darwin/arm64 builds

### ISSUE THREAD

**Issue by lewispeckover** [rancher/terraform-provider-rancher2#664]
Publishing darwin/arm64 (Apple Silicon) builds would be good.

Building locally (go 1.16.3 and `make build`) gave me some weirdness when I tried using it:

> The provider provider.rancher2 does not support resource type "rancher2_catalog_v2".

Maybe there's a bug there, or maybe just an issue with my build environment.

I hacked around the problem by downloading the published darwin/amd64 build into ~/.terraform.d/plugins/registry.terraform.io/rancher/rancher2/1.14.0/darwin_arm64/terraform-provider-rancher2. This ends up running via Rosetta, which works for now.

**Comment by rawmind0** [comment]
Added darwin/arm64 builds at PR https://github.com/rancher/terraform-provider-rancher2/pull/692/files#diff-95ebf75ba399b4aa1a30237d0c3bc80ca817f1a086508979786c5a78e96ae352R14

**Comment by rawmind0** [comment]
Next release 1.16.0, will build darwin/arm64 binaries. Please reopen issue if required

**Comment by dewnull** [comment]
I am getting `Provider registry.terraform.io/rancher/rancher2 v1.15.1 does not have a package available for your current platform, darwin_arm64`
