### ISSUE TITLE
rancher2_app_v2 module seems to assume a non-null system-default-registry setting

### ISSUE THREAD

**Issue by tulanian** [rancher/terraform-provider-rancher2#666]
### Versions
Terraform v0.15.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/rancher/rancher2 v1.14.0

rancher v2.5.8

### Problem
Trying to install an app into a cluster or import an app already installed I get the following error:

` Error: Bad response statusCode [404]. Status [404 Not Found]. Body: [code=NotFound, message=settings.management.cattle.io "system-default-registry" not found] from [https://rancher-server/k8s/clusters/c-8pjl6/v1/management.cattle.io.settings/system-default-registry]`

system-default-registry in the rancher instance is null. Is the module assuming it should be set?

**Comment by rawmind0** [comment]
Related to https://github.com/rancher/rancher/issues/32642 
Submitted fix for this https://github.com/rancher/terraform-provider-rancher2/pull/663

**Comment by rawmind0** [comment]
PR merged, it will be available at Rancher2 provider v1.15.0
