### ISSUE TITLE
gke_config_v2.cluster_addons field is optional but if not defined, i get an error

### ISSUE THREAD

**Issue by azacchino** [rancher/terraform-provider-rancher2#671]
cluster_addons is [optional](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster#gke_config_v2) but if not defined, i get this error "cannot be nil for non-import cluster"

``` yaml
rancher2_cluster {
  ...
  gke_config_v2 {
    cluster_addons {
     # This block
    }
  }
  ...
}
```
I think it's possibly missing initialize the slice

**Comment by rawmind0** [comment]
Reproduced issue, fix included at PR https://github.com/rancher/terraform-provider-rancher2/pull/678

**Comment by rawmind0** [comment]
PR https://github.com/rancher/terraform-provider-rancher2/pull/678 merged. Fix will be included on next tf provider release

Please, reopen issue if needed
