### ISSUE TITLE
Resource "rancher2_auth_config_keycloak" not supporting optional "Entity ID Field"

### ISSUE THREAD

**Issue by rule88** [rancher/terraform-provider-rancher2#674]
An alternative `Client ID` in Keycloak than the default described in the [Rancher documentation](https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/keycloak/) is not possible as the `rancher2_auth_config_keycloak` resource does not provide a way to override the default.

**Comment by rule88** [comment]
PR: https://github.com/rancher/terraform-provider-rancher2/pull/675

**Comment by rule88** [comment]
I have to admit that this PR is not tested yet.

**Comment by rawmind0** [comment]
The PR #675 doesn't pass CI pipeline, https://github.com/rancher/terraform-provider-rancher2/pull/675#issuecomment-851399232

**Comment by hnc-yusop** [comment]
Is there any progress for this issue???

**Comment by rule88** [comment]
@hnc-yusop 

code is updated and merged in master, now it is waiting for next release which will contain this feature.

**Comment by rawmind0** [comment]
PR #675 id already merged. Feature will be available at next tf provider release. 

Please, reopen issue if needed.
