### ISSUE TITLE
Activedirectory fails to configure access_mode required

### ISSUE THREAD

**Issue by bemeyert** [rancher/terraform-provider-rancher2#676]
Hi all,

We want to configure AD with `access_mode = required`. But we always get a 403 code.
Example code:
```
resource "rancher2_auth_config_activedirectory" "activedirectory" {
  servers = ["ad.server.com"]
  service_account_username = var.svc_ad_username
  service_account_password = var.svc_ad_password
  certificate              = file(var.svc_ad_cert)
  port                     = 636
  user_search_base     = "OU=user,DC=domain,DC=server.com,DC=com"
  group_search_base    = "OU=group,DC=domain,DC=server.com,DC=com"
  default_login_domain = "domain"
  access_mode = "required"
  allowed_principal_ids = [
    "activedirectory_group://CN=Rancher-Admins,OU=Security Groups,DC=domain,DC=server.com,DC=com",
    "local://${var.admin_principalid}"
  ]
  tls           = "true"
  test_username = var.test_username
  test_password = var.test_password
}
```
Applied to a cluster with only local users this gives the following error:
```
Error: Bad response statusCode [403]. Status [403 Forbidden]. Body: [baseType=error, code=PermissionDenied, message=Permission denied] from [https://rancher.server.com/v3/activeDirectoryConfigs/activedirectory?action=testAndApply]

  on modules/rancher-settings/auth.tf line 1, in resource "rancher2_auth_config_activedirectory" "activedirectory":
   1: resource "rancher2_auth_config_activedirectory" "activedirectory" {
```
But when I run this code first with `access_mode` set to `unrestricted` and after that again with `access_mode` set to `required` it works.
My guess is that the principal IDs aren't yet configured when the access mode is set to required.

I tried this with the currently most recent version 1.15.1.

**Comment by rawmind0** [comment]
Hi @bemeyert , is `test_username` part of the defined `allowed_principal_ids` groups??

**Comment by bemeyert** [comment]
@rawmind0 No, it isn't. The docs aren't very clear about that... 
Hmm, I'll try that one tomorrow. Keep you posted. Ta!

**Comment by bemeyert** [comment]
@rawmind0 Well, that did the trick. So it seems that one has to add the local admin and the test user to principal IDs. Is that correct? If so I would like to create a PR adding this to the documentation.

**Comment by bemeyert** [comment]
Just created the PR  #683

**Comment by rawmind0** [comment]
PR https://github.com/rancher/terraform-provider-rancher2/pull/683 is already merged. Fix will be included in next tf provider release.

Please, reopen issue if required.
