### ISSUE TITLE
Activate an existing/builtin node driver

### ISSUE THREAD

**Issue by ba-work** [rancher/terraform-provider-rancher2#677]
I want to activate the included OpenStack node driver as part of my deployment.

If I attempt to do this via Terraform like this:
```tf
resource "rancher2_node_driver" "openstack {
  active  = true
  builtin = true
  name    = "openstack"
  url     = "local://"
}
```
I get this in the UI `/n/drivers/node`:
![image](https://user-images.githubusercontent.com/61976254/120020934-6851a180-bfb8-11eb-971a-1ac21fe2e906.png)

Additionally, this causes some weird behavior because it somehow _does_ enable it for use in node templates: 
1. `/g/clusters/add/select`
![image](https://user-images.githubusercontent.com/61976254/120021079-9800a980-bfb8-11eb-8c66-e47816cf4541.png)
2. `/g/clusters/add/launch/openstack`
![image](https://user-images.githubusercontent.com/61976254/120021216-c41c2a80-bfb8-11eb-83aa-1394c835fe09.png)

Even if you don't want to support this and want to (justifiably) claim it should be imported, this is some weird behavior.

**Comment by rawmind0** [comment]
To manage built in node drivers from terraform, they should imported first, https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/node_driver#import

> If I attempt to do this via Terraform like this:
> ```tf
> resource "rancher2_node_driver" "openstack {
>  active  = true
>  builtin = true
>  name    = "openstack"
>  url     = "local://"
>}
>```

Doing this, the provider is creating another node driver called `openstack` (Rancher is not checking unique name) , but with distinct `id` as you can check in the attached screenshot. As mentioned,  to manage built in node drivers from terraform, you should import them first
