### ISSUE TITLE
Can't add EKS spot node group add to the existing cluster

### ISSUE THREAD

**Issue by vkwiley** [rancher/terraform-provider-rancher2#680]
Rancher doesn't add a new node group to existing cluster

Steps to reproduce:
1) Create an AWS EKS cluster via rancher2 tf provider with a node group with a custom Launch Template
2) Add TF config for a second node group with same or another LT and spot type

The cluster then hangs in "Updating" state, in AWS console the cluster is Active and nothing changes.

Then i go to Rancher GUI to edit the cluster and see that my new node group is present there but without chosen LT. I choose the LT, click Save, after that the new spot node group is created

**Comment by rawmind0** [comment]
The use of  EKS `launch_template` is not working properly. Working on a fix, https://github.com/rancher/terraform-provider-rancher2/issues/693#issuecomment-872423764

**Comment by rawmind0** [comment]
Please follow up the issue at https://github.com/rancher/terraform-provider-rancher2/issues/693
