### ISSUE TITLE
[Feature request] Add ability to specify list of value files in rancher2_app_v2

### ISSUE THREAD

**Issue by jbapu** [rancher/terraform-provider-rancher2#684]
The current API for rancher2_app_v2 resource has
`values - (Optional/Sensitive) The app v2 values yaml. Yaml format is required (string)`
This does not allow multiple value files to be specified.

In contrast, the helm_release resource has
`values - (Optional) List of values in raw yaml to pass to helm. Values will be merged, in order, as Helm does with multiple -f options.`

Not being able to specify a list of value files makes the value files not DRY.

**Comment by rawmind0** [comment]
> The current API for rancher2_app_v2 resource hasvalues - (Optional/Sensitive) The app v2 values yaml. Yaml format is required (string)This does not allow multiple value files to be specified.

True, but this is how it's defined at Rancher API, https://github.com/rancher/rancher/blob/master/pkg/apis/catalog.cattle.io/v1/helm.go#L40 map[string]interface to unmarshal yaml content. `values` is not saving a file, but yaml content. Have you consider to use tf [`join`](https://www.terraform.io/docs/language/functions/join.html) to concat the content of multiple files??

> In contrast, the helm_release resource has
values - (Optional) List of values in raw yaml to pass to helm. Values will be merged, in order, as Helm does with multiple -f options.
>
> Not being able to specify a list of value files makes the value files not DRY.

Not so clear what you mean, could you please explain a use case example for this??

**Comment by jbapu** [comment]
@rawmind0  Thanks for responding!

I don't think the join function would work here. Helm allows multiple value files to be supplied using its `-f` / `--values` option. From the [doc ](https://helm.sh/docs/helm/helm_install/) here,
> You can specify the '--values'/'-f' flag multiple times. The priority will be given to the last (right-most) file specified.

The Helm provider's [helm_release](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release#values) resource also allows this merging of multiple value files, according to Helm it says. Meaning, I can do something like this:
```
values = [
  "${file("values1.yaml")}",
  "${file("values2.yaml")}",
]
```
and I could have the same key-value defined in both and the value in values2.yaml would have precedence.

Maybe I don't understand how the `values` is used internally in the rancher2_app_v2 resource, but if I used `join()` to combine the yaml contents of two files, would I get the same behavior?

**Comment by rawmind0** [comment]
@jbapu, thanks for the clarification, i see what you mean now. I don't think using `join()`  is gonna work for this use case. 

By the moment, we are not considering add this feature at the provider. `yq` may help you to get same behaviour https://mikefarah.gitbook.io/yq/v/v2.x/merge#overwrite-values
