### ISSUE TITLE
StorageClass

### ISSUE THREAD

**Issue by ayushmehrotra12** [rancher/terraform-provider-rancher2#686]
Hello. I have a rancher cluster hosted on AWS EKS and I am using rancher2 to create more clusters. I need to add storage class via rancher2. I haven't seen any option in terraform to add storage class. Can anyone provide me some insight how can I achieve that Storageclass with rancher2. 

I am able to add it manually but not via rancher2.

I am using eks_config_v2 to create the clusters from rancher cluster.

I have successfully added the storageclass in rancher main cluster via kubernetes_storage_class but not in the cluster created by rancher.

Every cluster is in the AWS EKS Platform.

**Comment by rawmind0** [comment]
Hello @ayush121195 , by the moment, Rancher2 tf provider is not supporting StorageClass management. To do it, the recommendation is to use the  kubernetes tf provider.

**Comment by rawmind0** [comment]
Storage class has been added at PR https://github.com/rancher/terraform-provider-rancher2/pull/716, already merged. The new resource and dataosurce will be available at next tfp release, v1.17.0

Please, reopen issue if required
