### ISSUE TITLE
Add ability to provision applications within a project

### ISSUE THREAD

**Issue by SinisterMinister** [rancher/terraform-provider-rancher2#69]
Provisioning apps from Rancher or Helm charts would be super useful. In my case, I'm setting up our CI/CD environment and need to deploy the Jenkins helm chart within a project.

I can try to tackle this if it's a feature that's desired. If there's a workaround instead, I'll take that as well.

**Comment by rawmind0** [comment]
Submitted PR #125 to provide rancher app support.

**Comment by rawmind0** [comment]
Merged PR to address this issue. Please, reopen it if needed.
