### ISSUE TITLE
rancher2_app_v2 not terminating on error

### ISSUE THREAD

**Issue by jabbrwcky** [rancher/terraform-provider-rancher2#697]
When deploying the rancher-monitoring app (v4.9.202) using the terraform provider v0.15.1 the resource does not abort on helm errors, e.g.:

```
helm upgrade --install=true --namespace=cattle-monitoring-system --timeout=15m0s --values=/home/shell/helm/values-rancher-monitoring-9.4.202.yaml --version=9.4.202 --wait=true rancher-monitoring /home/shell/helm/rancher-monitoring-9.4.202.tgz
coalesce.go:199: warning: destination for metricRelabelings is a table. Ignoring non-table value []
coalesce.go:199: warning: destination for metricRelabelings is a table. Ignoring non-table value []
Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(ServiceMonitor.spec.endpoints[0]): unknown field "regex" in com.coreos.monitoring.v1.ServiceMonitor.spec.endpoints, ValidationError(ServiceMonitor.spec.endpoints[0]): unknown field "sourceLabels" in com.coreos.monitoring.v1.ServiceMonitor.spec.endpoints]
```

 or a different error:

```
helm upgrade --install=true --namespace=cattle-monitoring-system --timeout=15m0s --values=/home/shell/helm/values-rancher-monitoring-9.4.202.yaml --version=9.4.202 --wait=true rancher-monitoring /home/shell/helm/rancher-monitoring-9.4.202.tgz
Error: UPGRADE FAILED: "rancher-monitoring" has no deployed releases
```

The terraform process keps chugging on happily, ignoring any configured timeouts until the AWS token becomes invalid (which also results in a failure to persist the TF state to S3).

IMO the resource should terminate as soon as helm exits with an error.

**Comment by rawmind0** [comment]
Is this just happening to you with rancher-monitoring v9.4.202?? The provider should return error if the `appV2OperationWait` is returning error, https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/resource_rancher2_app_v2.go#L68

**Comment by jabbrwcky** [comment]
I am not quite sure if an error is returned at all, even when fixing the helm error it still hangs. Helm reports sucess for both the installation of the CRDs and the monitoring infrastructure but I get the alertmanager and prometheus in `cattle-monitoring-system` caught in a Terminationg state constantly (still investigating what is going on there).

Apparently the app install waits for alertmanager/prometheus to be running?

Regardless of the reason the app install seems to be hanging the configured timeout should pull the plug on the resource after the configured timeouts.

Here is the code used to install the app:

```hcl
resource "rancher2_app_v2" "monitoring" {
  cluster_id      = var.cluster_id
  name            = "rancher-monitoring"
  namespace       = var.rancher_monitoring_namespace
  repo_name       = "rancher-charts"
  project_id      = var.project_id
  chart_name      = "rancher-monitoring"
  chart_version   = var.chart_version
  values          = var.values
  cleanup_on_fail    = true
  force_upgrade      = true
  chart_version      = "9.4.202"
  timeouts {
    create = "15m"
    update = "15m"
    delete = "15m"
  }
}
```

**Comment by jabbrwcky** [comment]
Ok, so I found the cause of my problems: I tried to install the App on an Kubernetes 1.20 cluster running Rancher 2.5.5, which does not support K8S 1.20 yet, causing resources bein stuck in an `Unknown` state (so the error is independent of the application version).

Reverting the cluster to 1.19 resolved the issue. 

Apparently the terraform provider (or rancher API client?) uses a blocking call that undermines the timeout configuration.

**Comment by rawmind0** [comment]
Thanks for your feedback @jabbrwcky , i'm glad your issue is resolved

There is no blocking call, just waiting until app V2 operation finish, https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/resource_rancher2_app_v2.go#L223 . If it was stuck in `Unknown` state that was the reason.

Please, reopen the issue if required
