### ISSUE TITLE
Is it possible to import AKS cluster via  terraform-provider-rancher2 ?

### ISSUE THREAD

**Issue by PrakashFromBunnings** [rancher/terraform-provider-rancher2#698]
Hello Team ,

We are planning to put CI/CD pipelines for all things we do for Rancher like importing AKS cluster , assigning global group  rule etc. 

I am wondering if we can use terraform-provider-rancher2 to do above work ?

**Comment by rawmind0** [comment]
Hi @PrakashFromBunnings , this feature is not yet available at Rancher, it will be at Rancher 2.6. This provider is gonna support it when available, https://github.com/rancher/terraform-provider-rancher2/pull/711

**Comment by PrakashFromBunnings** [comment]
@rawmind0 , not sure if my question was clear or not to you.

Currently we do import AKS clusters in rancher , but we are doing that manually . 

And wanted to know if we can do this by terraform module in this repo ?

**Comment by rawmind0** [comment]
@prabalsharma may be your question was not completely clear. I was talking about the specific integration with aks to import clusters, like new integrations added to [eks_config_v2](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster#eks_config_v2) and [gke_config_v2](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster#gke_config_v2)

With this provider you can import whatever k8s cluster using docs example [creating-rancher-v2-imported-cluster](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster#creating-rancher-v2-imported-cluster) and then getting getting [command](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster#command) or [insecure_command](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster#insecure_command) to be executed at the cluster to be imported

**Comment by rawmind0** [comment]
Please, reopen the issue the issue if you have more questions about it
