### ISSUE TITLE
cluster_auth_endpoint not default true

### ISSUE THREAD

**Issue by janlauber** [rancher/terraform-provider-rancher2#699]
When I create a rancher2 cluster with the terraform provide and doesn't mention the cluster_auth_endpoint the created cluster doesn't have authorized endpoints.
In the documentation you can see the following:
- enabled - (Optional) Enable the authorized cluster endpoint. Default true (bool)

**Comment by rawmind0** [comment]
cluster_auth_endpoint is not enabled by default, the argument is optional/computed, as it's specified at docs.

```
cluster_auth_endpoint - (Optional/Computed) Enabling the local cluster authorized endpoint allows direct communication with the cluster, bypassing the Rancher API proxy. (list maxitems:1
```

The `cluster_auth_endpoint.enabled` is a nested argument that it's true by default just if cluster_auth_endpoint is set

**Comment by janlauber** [comment]
Okey thanks for the information.
have a nice day!
