### ISSUE TITLE
How to set the retention and schedule for  "rancher2_app_v2" "rancher-backup"

### ISSUE THREAD

**Issue by mikekuzak** [rancher/terraform-provider-rancher2#700]
The snipped below doesn't document how to set the retention and schedule. 
If there any specific syntax for that ? 

Thanks

```
resource "rancher2_app_v2" "rancher-backup" {  
  cluster_id = "<CLUSTER_ID>"
  name = "rancher-backup"
  namespace = "cattle-resources-system"
  repo_name = "rancher-charts"
  chart_name = "rancher-backup"
  chart_version = "1.0.200"
  values = <<EOF
persistence:
  enabled: false
  size: 2Gi
  storageClass: '-'
  volumeName: ""
s3:
  bucketName: ""
  credentialSecretName: ""
  credentialSecretNamespace: ""
  enabled: false
  endpoint: ""
  endpointCA: ""
  folder: ""
  insecureTLSSkipVerify: false
  region: ""
EOF
}
```

**Comment by rawmind0** [comment]
Not sure what you mean with rentention and schedule, but here you can find all values that you may use for rancher-backup app https://github.com/rancher/charts/blob/release-v2.5/charts/rancher-backup/rancher-backup/1.0.400/README.md#configuration

**Comment by mikekuzak** [comment]
@rawmind0 

![image](https://user-images.githubusercontent.com/18675587/125652582-a9e6a0c3-6bef-4874-894d-eaad5b59991c.png)

**Comment by rawmind0** [comment]
`rancher2_app_v2.rancher-backup` is just installing the rancher backup operator. To perform backups, https://rancher.com/docs/rancher/v2.5/en/backups/back-up-rancher/#2-perform-a-backup

**Comment by mikekuzak** [comment]
@rawmind0 

Hi Thanks for the link, so there is no TF resource to create a backup atm ?

Thanks

**Comment by rawmind0** [comment]
> Hi Thanks for the link, so there is no TF resource to create a backup atm ?

@mikekuzak , exactly, there isn't yet a tf resource to create/launch a backup.
