### ISSUE TITLE
Add support specifying add-on tolerations to rancher2_cluster resource

### ISSUE THREAD

**Issue by dankeder** [rancher/terraform-provider-rancher2#705]
Hi,

RKE allows specifying add-on tolerations. Can the `rancher2_cluster` resource provide similar functionality?

One use case is that we don't want to schedule CoreDNS add-on onto cordoned nodes because they may be subject to OS maintenance, reboots, etc. Currently kube-scheduler happily puts CoreDNS pods onto cordoned nodes and the cluster becomes unstable when something happens to the node.

An example configuration might look like this:

```hcl
resource "rancher2_cluster" "mycluster" {
  name = "mycluster"

  rke_config {
    dns {
      provider = "coredns"

      toleration {
        key = "key1"
        operator = "Equal"
        value = "value1"
        effect = "NoExecute"
        toleration_seconds = 3600
      }

      toleration {
        key = "key2"
        operator = "Equal"
        value = "value2"
        effect = "NoSchedule"
        toleration_seconds = 3600
      }
    }
  }
}
```

References:
https://rancher.com/docs/rke/latest/en/config-options/add-ons/dns/#coredns-tolerations
https://rancher.com/docs/rke/latest/en/config-options/add-ons/#tolerations

**Comment by rawmind0** [comment]
Submitted PR https://github.com/rancher/terraform-provider-rancher2/pull/707 adding tolerations argument

**Comment by rawmind0** [comment]
PR #707 is already merged. The feature will be available at next tfp release

**Comment by dankeder** [comment]
That's great, thank you!
