### ISSUE TITLE
Add support for K8s api verb "deletecollection"

### ISSUE THREAD

**Issue by serverbaboon** [rancher/terraform-provider-rancher2#718]
Can support for the verb "deletecollection" be added to the rancher2_global_role and rancher2_role_template resources.

The following will fail as deletecollection is unsupported.

  rules {
    api_groups = [""]
    resources = ["services/proxy", "pods/portforward"]
    verbs=  ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]
  }
  
 It does look as though there is no difference between verb = ["*"] and the above so I can use that but I wonder if you should still support the verb "deletecollection"

**Comment by rawmind0** [comment]
Added `deletecollection` verb at PR https://github.com/rancher/terraform-provider-rancher2/pull/720

**Comment by rawmind0** [comment]
PR #720 already merged. The `deletecollection` will be available at next tfp release, v1.17.0
