### ISSUE TITLE
How to add a user to cluster? 

### ISSUE THREAD

**Issue by surenraju-zz** [rancher/terraform-provider-rancher2#719]
From documentation I cannot find a way to add Users/Member to a cluster using rancher2_cluster.

https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster#argument-reference

How to add members to a cluster?

**Comment by rawmind0** [comment]
For cluster, https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster_role_template_binding
For project, https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/project_role_template_binding

**Comment by rawmind0** [comment]
Please, reopen the issue the issue if you have more questions about it
