### ISSUE TITLE
How to setup single ssh key to access all nodes of rancher2_cluster

### ISSUE THREAD

**Issue by umeshauv** [rancher/terraform-provider-rancher2#722]
I have created a rancher2_cluster with RKE template and node pool.   I want to generate and use a single ssh key to access all nodes of the cluster.  However, there is no option to set this.   The only option I see is ssh_key_path and it's behaviour is not specified in the document.  Can you please let me know how to setup single ssh key.

**Comment by rawmind0** [comment]
By the moment, i think this option is not supported at Rancher

**Comment by rawmind0** [comment]
Please, reopen the issue the issue if you have more questions about it
