### ISSUE TITLE
Is it possible to list all the clusters configured in rancher

### ISSUE THREAD

**Issue by YohanValette-DXC** [rancher/terraform-provider-rancher2#723]
Hello, I manage AKS clusters on some Azure subscriptions.

I would like to have the ability to **list all the clusters handled by my rancher server** so that I can dynamically detect which AKS are not imported yet.

I had a look at the documentation and found the data source `rancher2_cluster`, but it is required to specify a cluster name.
Would it be possible to have such a data source, but with a filter argument to retrieve either all the managed clusters, or a subset based on labels or others criteria?

**Comment by rawmind0** [comment]
Hi @YohanValette-DXC , by the moment, it's not possible to list all the clusters configured in rancher using this provider. As you mentioned, right now, `rancher2_cluster` datasource is designed to just return 1 cluster. 

This is something that may change at some point, but not a priority at the moment. Even though, we are more than happy to review and accept PRs.

**Comment by rawmind0** [comment]
Please, reopen the issue the issue if you have more questions about it
