### ISSUE TITLE
provider doesn't update `cloud_credential_id` of `rancher2_node_template`, even when the apply seems successful

### ISSUE THREAD

**Issue by wc-s** [rancher/terraform-provider-rancher2#727]
To reproduce:
1. create a `rancher2_node_template` with some cloud credential
2. try to update the template's cloud credential to a different one
3. `terraform plan` will show the diff, `terraform apply` will seem successful, but in the end the node template's cloud credential remains the same and is not successfully changed

**Comment by rawmind0** [comment]
Submitted PR https://github.com/rancher/terraform-provider-rancher2/pull/728 to fix the issue

**Comment by rawmind0** [comment]
PR #728 already merged. Fix will be included at next tf ptovider release v1.17.1
