### ISSUE TITLE
Feature request:  Improve management of AWS STS tokens

### ISSUE THREAD

**Issue by keymon** [rancher/terraform-provider-rancher2#74]
# Current issue

For security, we want to be able to [use STS tokens](https://docs.aws.amazon.com/STS/latest/APIReference/Welcome.html) when creating a AWS based Rancher cluster (EKS or EC2).

Currently rancher and the provider allow to define the properties `access_key`, `secret_key` and `session_token` for the [`eks_config` of the `rancher2_cluster` resource](https://www.terraform.io/docs/providers/rancher2/r/cluster.html#session_token) or [the `amazon_ec2_config` of the `rancher2_node_template` resource](https://www.terraform.io/docs/providers/rancher2/r/nodeTemplate.html#session_token).

In this ticket I will focus on the behaviour of the EKS clusters.

Passing these values does work during the creation, and updates, but with the current approach there are several caveats and it is sub-optimal.

Here is a lit of the issues:

 - "Delete" operations never refreshes the STS token:
    - The STS creds are passed during creation or updates, and saved in rancher. Delete will use the STS from the latest previous create/updated, that might be expired, causing the delete operation to fail.
     - Workaround: do an "apply" to force an update of the STS credentials in rancher before delete. But this is manual, error-prone, and potentially not desirable or possible to run an update. 

 - STS Creds attributes change all the time:
   - Due the nature of STS, creds will likely change in every terraform execution, showing a diff of these attributes in the plan, despite not being a real change in the cluster.
   - Workaround: ignore these attributes with `lifecycle.ignore_changes`, but then you cannot update the token.

 - Inconvenient to generate or get this STS token: 
   - As the STS creds are being passed as value, they must be generated generated and pass them from outside of terraform, e.g by using `TF_VAR_`  variables.

# Alternative implementation 

I want to suggest that the rancher provider does manage these credentials differently:

 - The AWS credentials are passed in the provider, so they are always available for all the operations: create/update/delete. 
 - The resource will pull the credentials from the provider definition unless overrided explicitly. Changes in the creds in the provider shall be ignored for the plan.
 - The delete operation will update first the credentials of the cluster before delete, to guarantee that rancher keeps credentials.
 - The provider can accept a `assume_role` stanza to assume a role and generate a STS token, similar [to the one used in the aws provider](https://www.terraform.io/docs/providers/aws/index.html#assume-role), or just get a STS token. Note this role would be different to the `service_role` for the cluster itself

 - The provider can pull credentials from the usual sources for AWS: env vars, IAM profiles, config files, or explicitelly 

## Example of the definition

```
# A provider with static creds
provider "rancher2" {
  api_url    = "${var.rancher_url}"
  access_key = "${var.rancher_access_key}"
  secret_key = "${var.rancher_secret_key}"
  aws_credentials { 
       access_key = "foo"
       secret_key = "bar"
  } 
}

# A provider getting creds from env/iam profile
provider "rancher2" {
  api_url    = "${var.rancher_url}"
  access_key = "${var.rancher_access_key}"
  secret_key = "${var.rancher_secret_key}"
  aws_credentials { 
       env_or_iam_profile = true
  } 
}

# A provider with creds from the creds file
provider "rancher2" {
  api_url    = "${var.rancher_url}"
  access_key = "${var.rancher_access_key}"
  secret_key = "${var.rancher_secret_key}"
  aws_credentials { 
     shared_credentials_file = "/Users/tf_user/.aws/creds"
     profile                 = "customprofile"
   } 
}

# A provider getting a STS token
provider "rancher2" {
  api_url    = "${var.rancher_url}"
  access_key = "${var.rancher_access_key}"
  secret_key = "${var.rancher_secret_key}"
  aws_credentials { 
    access_key = "${var.rancher_access_key}"
    secret_key = "${var.rancher_secret_key}"
    sts_token {
       duration = 3600
     }
  } 
}

# A provider assuming a role
provider "rancher2" {
  api_url    = "${var.rancher_url}"
  access_key = "${var.rancher_access_key}"
  secret_key = "${var.rancher_secret_key}"
  aws_credentials { 
    assume_role {
       role_arn     = "arn:aws:iam::ACCOUNT_ID:role/ROLE_NAME"
       session_name = "rancher-provider"
       external_id  = "my-terraform-racher"
       duration = 3600
     }
  } 
}
```

## Our use case

Our most interesting use case is getting the token via assume role using credentials from the system (env vars / IAM profile or properties files).  

## Out of scope

Other IaaS might have a similar issue. That is out of scope here.

**Comment by rawmind0** [comment]
Hi @keymon , thanks for your feedback and your proposal.

From rancher v2.2, it's possible to use aws STS token using `session_token`, https://github.com/rancher/rancher/issues/16005. 

Some comments on issues that you are mentioning:

>Here is a lit of the issues:
>
> - "Delete" operations never refreshes the STS token:
>    - The STS creds are passed during creation or updates, and saved in rancher. Delete will use the STS from the latest previous create/updated, that might be expired, causing the delete operation to fail.
>     - Workaround: do an "apply" to force an update of the STS credentials in rancher before delete. But this is manual, error-prone, and potentially not desirable or possible to run an update. 

Yes, assumed on rancher issue mentioned

 >- STS Creds attributes change all the time:
>   - Due the nature of STS, creds will likely change in every terraform execution, showing a diff of these attributes in the plan, despite not being a real change in the cluster.
>   - Workaround: ignore these attributes with `lifecycle.ignore_changes`, but then you cannot update the token.

In fact, it's a real change on cluster, at least form the rancher point of view due to it is saving credentials. Agreed with `lifecycle.ignore_changes` workaround.

 >- Inconvenient to generate or get this STS token: 
 >   - As the STS creds are being passed as value, they must be generated generated and pass them from outside of terraform, e.g by using `TF_VAR_`  variables.

Why?? Why not use aws provider to get STS token??

About your alternative implementation, why not to use aws provider definition on your tf file instead of coupling it inside rancher2 provider?? May be i'm loosing something, but i think you could do the same just adding aws provider definition to your tf file and using its values in the same way you are proposing.

**Comment by keymon** [comment]
> Why?? Why not use aws provider to get STS token??

> About your alternative implementation, why not to use aws provider definition on your tf file instead of coupling it inside rancher2 provider?? May be i'm loosing something, but i think you could do the same just adding aws provider definition to your tf file and using its values in the same way you are proposing.

Maybe it's me missing something, but AFAIK the aws provider can assume a role for it's own resources but I did not find a way to extract those credentials to be used anywhere else, like other provider.

You can create static keys, but you cannot consume the keys from the provider from assume_role, and I think there's no resource or datasource from the official aws provider to assume a time or get a sts token.

Do you know if there's a way? It would be great if you can give me a clue there.

I recall having the same issue in other project, but we ended generating the token from a external script.

You sound like this suggestion is very controversial for you. if there's no option to extract the key from the aws provider, alternatives are:

 - generate the STS token outside terraform
 - write a custom provider for this
 - use a external datasource

One issue of this is that if you delete a full module, including this datasource that generates the credentials, you'll never be able to get new sts credentials and the cluster cannot be deleted anymore. 

Instead, having the provider assuming the role, you'll be always get a sts token even during deletion.

**Comment by keymon** [comment]
I implemented the bit of having the aws credentials in the rancher2 provider and pass them to the create/update/delete, including update the creds before delete in a fork https://github.com/keymon/terraform-provider-rancher2/tree/aws_creds_in_provider?files=1

I did not test that yet in a real cluster, and it is still missing the testing of the resource_delete (seems to be tested only with integration tests). Still WIP. But it can give you an idea of intend.

It does not implement any assume role logic. But it fixes the issues with the update creds before delete and avoid spurious diffs.

**Comment by keymon** [comment]
> In fact, it's a real change on cluster, at least form the rancher point of view due to it is saving credentials. Agreed with lifecycle.ignore_changes workaround.

Note that ignore_changes is a workaround and it's suboptimal as explained before.

In rancher itself, using sts tokens, the right procedure to delete a cluster would be first update the sts token, then delete. What I propose here is support that same behaviour. 

But the only way to get fresh sts tokens during deletion is having the credentials at the provider definition level.

Other advantage of having the credentials in the provider is that they are not stored in the state file.

**Comment by rawmind0** [comment]
> Maybe it's me missing something, but AFAIK the aws provider can assume a role for it's own resources but I did not find a way to extract those credentials to be used anywhere else, like other provider.
> 
> You can create static keys, but you cannot consume the keys from the provider from assume_role, and I think there's no resource or datasource from the official aws provider to assume a time or get a sts token.
> 
> Do you know if there's a way? It would be great if you can give me a clue there.
> 

I'm not an expert on aws provider. AFAIK, aws provider can assume a role just if you configure `aws-cli` in the same host you are running `terraform`, isn't it??  Is this the expected way to support assume role on rancher2 provider?? If the new session_token can't be consumed, then yes, it has to be generated using any of the options you mention below. 

> I recall having the same issue in other project, but we ended generating the token from a external script.
> 
> You sound like this suggestion is very controversial for you. if there's no option to extract the key from the aws provider, alternatives are:
> 
> * generate the STS token outside terraform
> * write a custom provider for this
> * use a external datasource
> 
> One issue of this is that if you delete a full module, including this datasource that generates the credentials, you'll never be able to get new sts credentials and the cluster cannot be deleted anymore.
> 
> Instead, having the provider assuming the role, you'll be always get a sts token even during deletion.

Your suggestion is not very controversial to me. The issue should be addressed if it's possible, but i'm not sure if this is the way to do it. 

Beside you can't check if aws credentials update is needed on eks cluster before delete it, update them by default or may be controlled by a bool argument, seems a good scope to solve it.

Rancher2 provider config shouldn't be coupled to any other provider, just manage data to connect to rancher2 system. Add aws credentials to it, doesn't seem a good scope.  Are you assuming that all created eks clusters will use same aws credentials??  I'd prefer to use another resource like `rancher2_cloud_credential` to inject creds on eks cluster like it's used on aws vm's.

**Comment by rawmind0** [comment]
> > In fact, it's a real change on cluster, at least form the rancher point of view due to it is saving credentials. Agreed with lifecycle.ignore_changes workaround.
> 
> Note that ignore_changes is a workaround and it's suboptimal as explained before.

Agreed, `ignore_changes` is just a workaround not a solution. 

> In rancher itself, using sts tokens, the right procedure to delete a cluster would be first update the sts token, then delete. What I propose here is support that same behaviour.

As metioned on previous comment, update aws credential on eks cluster before delete it, seems a good scope and possible solution, but i don't agree on saving aws credential on rancher2 provider config. I think that using another resource like `rancher2_cloud_credential` could have more proper fit. 

> But the only way to get fresh sts tokens during deletion is having the credentials at the provider definition level.

I don't think it's the only way to get fresh sts tokens. I think that another resource like rancher2_cloud_credential could do the job.

> Other advantage of having the credentials in the provider is that they are not stored in the state file.

**Comment by keymon** [comment]
> Your suggestion is not very controversial to me.

Sorry, the double `??` made me think so :) 

> I'm not an expert on aws provider. AFAIK, aws provider can assume a role just if you configure aws-cli in the same host you are running terraform, isn't it?? Is this the expected way to support assume role on rancher2 provider?? If the new session_token can't be consumed, then yes, it has to be generated using any of the options you mention below.

I don't think the `session_token` can be consumed from the AWS provider. At least I couldn't find a way. And even if it could, or if we use alternative ways to get it and pass it to the rancher provider, there are some caveats as explained below.

> Rancher2 provider config shouldn't be coupled to any other provider,

I am not suggesting to couple to the AWS provider, the other way around! The proposal is that `rancher2_provider` implements logic to retrieve the credentials from the environment (IAM profile, config, env-vars, by calling the corresponding [aws golang client]()https://docs.aws.amazon.com/sdk-for-go/api/aws/credentials/#ChainProvider),  and (if possible) generate a STS token or assume role. 

> Beside you can't check if aws credentials update is needed on eks cluster before delete it, update them by default or may be controlled by a bool argument, seems a good scope to solve it.
> but i don't agree on saving aws credential on rancher2 provider config. I think that using another resource like rancher2_cloud_credential could have more proper fit.

The problem here is how terraform works by design: During a `destroy` operation, the provider resource `delete` does **not** get the latest values from the HCL definition. Instead it will get the state stored in the `tfstate` from the latest `apply` execution. This makes sense from the point of view of terraform, as you can delete a resource by deleting its HCL definition. If the credentials are in the definition of the resource, and you delete the definition, there is no way for terraform to know where it should pull the credentials from.

Instead, by putting the static credentials in the provider (as I implemented here: https://github.com/terraform-providers/terraform-provider-rancher2/compare/master...keymon:aws_creds_in_provider) then terraform developer could keep the provider definition but delete the `cluster_rancher2` definition. In that case the `delete` will work, because the provider will pull the credentials from its definition (that still exist in HCL), and then the resource `delete` can indeed update the rancher cluster with the new STS before doing a delete.

But that does solve the problem completely: one is still forced to keep the provider definition to pull the credentials. If you delete the provider definition (e.g. delete all the HCL including the provider or issue non-targeted `terraform destroy`), same problem arises: Terraform cannot pull new credentials and would use the ones stored in the tfstate.

So the issue is that by design in terraform during a `destroy` operation no other provider will be called and properties will not be updated. It relies on the values stored in the tfstate from previous apply. If a provider (in this case rancher2) requires some values to be refreshed (e.g. STS token) it needs to solve that problem by itself. 

BTW, this is still a problem even with the workarounds I suggested before. You will have to always do a `terraform apply` first to get the creds updated in rancher or in the tfstate, then issue a `terraform destroy`

That is why I suggested the solution: 
 - To allow configure the credentials a the provider level (see https://github.com/terraform-providers/terraform-provider-rancher2/compare/master...keymon:aws_creds_in_provider)
 - Allow the rancher provider to get the credentials directly from environment (using the standard chain provider from the aws client library https://docs.aws.amazon.com/sdk-for-go/api/aws/credentials/#ChainProvider )
 - Allow the rancher provider to assume the role or get a STS token

> Are you assuming that all created eks clusters will use same aws credentials??

I am suggesting we allow define the creds both in the provider and in the resource definition. If the creds are in the provider, then it would be shared across all cluster unless they override them (see my [example code](https://github.com/terraform-providers/terraform-provider-rancher2/compare/master...keymon:aws_creds_in_provider#diff-be6bb0c2ad22a5d89b45891892c43a3cR327))

But having the creds in the provider is not a requirement to solve this issue. It is one way to support delete one resource. But the only requirement is that the `delete` operation pulls the credentials dynamically without relying on the resource definition. If we implement logic to retrieve the creds from the environment/aws config/IAM profile and/or get STS token or assume role, then it should fix the problem.

> I don't think it's the only way to get fresh sts tokens. I think that another resource like rancher2_cloud_credential could do the job.

How will the flow work in this case?

Our use case is that we only allow the usage of STS tokens based on specific criteria (MFA auth), instance IAM profiles. We want to avoid static AWS credentials as much as possible.

The current flow does work fine except the issue explained here: Terraform is the main interface with Rancher, and we pass the STS token to rancher for creation and update via terraform. But delete breaks :(

Additionally, using a different resource to provide credentials to the resource `rancher2_cluster` still has the same issue: You will not have a fresh STS token during deletion because how terraform is designed.

**Comment by keymon** [comment]
BTW, in a similar way, taint a cluster resource would likely fail if the STS token is expired. But that is a very uncommon operation in a EKS cluster.

**Comment by rawmind0** [comment]
> Sorry, the double ?? made me think so :)

No problem, i use to write `??`.. :) 

> I am not suggesting to couple to the AWS provider, the other way around! The proposal is that rancher2_provider implements logic to retrieve the credentials from the environment (IAM profile, config, env-vars, by calling the corresponding aws golang clienthttps://docs.aws.amazon.com/sdk-for-go/api/aws/credentials/#ChainProvider), and (if possible) generate a STS token or assume role.

That's what i mean with couple rancher2 provider, add a dependency with aws sdk. Honestly i don't think it should be done, moreover when it's not in the core functionality of the provider. As this feature could be used on other user cases, i think would be better to submit a PR on aws provider to manage sts token or create another provider to manage it.

I get your point and what you are trying to achieve, but there are 2 issues here:
1. address the deletion on eks cluster when dynamic aws credentials are provided. Agreed to update eks cluster with credentials before delete, but using another resource like `rancher2_cloud_credential`.
2. add aws dependency, logic and credentials on rancher2 provider config to manage sts token updates. I think this should be out of scope of rancher2 provider, and should be included on aws provider or a new provider to do it, due to may be it's a common issue on other providers that try to use sts tokens.

> How will the flow work in this case?

To address point 1 using another resource like `rancher2_cloud_credential`, i was thinking on something like this...

```
resource "rancher2_cloud_credential" "foo" {
  name = "foo"
  description= "Terraform cloudCredential acceptance test"
  amazonec2_credential_config {
	access_key = "XXXXXXXXXXXXXXXXXXXX"
	secret_key = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
        session_token = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  }
}

resource "rancher2_cluster" "foo" {
  name        = "foo"
  description = "EKS kubernetes cluster"
  cloud_credential_id = "${rancher2_cloud_credential.foo.id}"
  eks_config {
    access_key = "${rancher2_cloud_credential.foo.amazonec2_credential_config.0.access_key}"
    secret_key = "${rancher2_cloud_credential.foo.amazonec2_credential_config.0.secret_key}"
    session_token = "${rancher2_cloud_credential.foo.amazonec2_credential_config.0.session_token}"
    ...
  }
}
```

or

```
resource "rancher2_cloud_credential" "foo" {
  name = "foo"
  description= "Terraform cloudCredential acceptance test"
  amazonec2_credential_config {
	access_key = "XXXXXXXXXXXXXXXXXXXX"
	secret_key = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
        session_token = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  }
}

resource "rancher2_cluster" "foo" {
  name        = "foo"
  description = "EKS kubernetes cluster"
  cloud_credential_id = "${rancher2_cloud_credential.foo.id}"
  eks_config {
    access_key = ""
    secret_key = ""
    session_token = ""
    ...
  }
}
```

Add an `cloud_credential_id` argument to `rancher2_cluster` resource definition to be able to map it with a `rancher2_cloud_credential` that will provide creds. 
- Cloud credentials would be defined outside cluster definition.
- Cluster definition could be removed from tf file, without removing cloud credentials. 
- Cloud credentials could be updated without generate a diff on cluster. 
- Cluster credentials could be updated before doing delete (or any other action) on the cluster. 
- Cloud credentials could be updated and cluster deleted on same `terraform apply` execution.

What do you think on a solution like that?? :)

**Comment by keymon** [comment]
> That's what i mean with couple rancher2 provider, add a dependency with aws sdk. Honestly i don't think it should be done, moreover when it's not in the core functionality of the provider. 

I am curious about your concerns in this regard. I don't think it is coupling but just using a pretty standard library (aws sts client). Lots of sofware use libraries like that, the fingerprint is low, the API consistent and we'll defined. Using it to query the aws API would be an optional behaviour to achieve the task at place: "provide rancher the right creds to perform some task"

But if this is a concern, I would propose the option of reading the creds from env vars as I explain below

> As this feature could be used on other user cases, i think would be better to submit a PR on aws provider to manage sts token or create another provider to manage it.

Yep, one still can get those creds using a external datasource + awscli, and still have the issues described here during eks deletion.
Having the aws provider offering those creds is convenient, I'll pursue that in that side, but does not really solve the issue. 

> To address point 1 using another resource like rancher2_cloud_credential, i was thinking on something like this...

I don't think that solves the problem at all, because how terraform works by design:

 - during a destroy operation (explicit destroy, delete of HCL definition, taint, etc) terraform will not do a plan+apply of that resource or of any other resource to update the attributes with a new token. This will only work if the credentials are in the provider definition (and it that case only meanwhile we keep the provider HCL). This is because the provider is always initialised during any operation plan/apply/destroy.

AFAIK with your proposal we achieve not having the credentials in the rancher2_cluster and maybe reuse the credentials by reusing that credentials resource, but that's not something we currently need.

> Cloud credentials could be updated without generate a diff on cluster.

It will still generate the diff, but the problem now moves to rancher2_cloud_credential.

Btw, the reason this is annoying is because it breaks automation that relies on checking that plans are clear.

> Cluster credentials could be updated before doing delete (or any other action) on the cluster.

Still adds an artificial requirement. Now as an operator you must know that any delete operation would require first update this specific resource with a terraform apply, to update the sts token, and immediately do the delete. This is undesirable, adds an ad-hoc step and is error prone because relies on following a correct procedure depending the changes.  

> Cloud credentials could be updated and cluster deleted on same terraform apply execution.

I this you are assuming that the case would be delete only the rancher2_cluster definition, keep rancher2_cloud_credential, and do terraform apply. 
But that has some issues:
 - does not cover use case of target the specific cluster.
 - does not cover delete a full module: very likely all these resources will always be bundled in modules.
 - does not cover a normal terraform destroy.
 - assumes that during a terraform apply, the destruction of a resource will be always be preceded by the apply of the other remaining resources. Not sure that is the case in terraform, is that the case? I couldn't find it documented. :thinking:

I also got a question, the rancher2_cloud_credential would push the credentials into rancher, wouldn't it? Does that support sts? I need to also check the permission model of those credentials, I guess they are accessible only by the user that created it.

## alternative MVP, use env cars

> address the deletion on eks cluster when dynamic aws credentials are provided. 

So the problem is that terraform during a destructive will have only these info available for the delete operation: 

- the latest attribute values from the latest apply (the sts token might and will be likely expired here)
- the provider configuration: fresh info if the HCL remains, old from state if not (so expired)
- but also: operating system environment variables.

So I propose to add an optional attribute to rancher2_cluster, something like 'aws_creds_from_env'. If true, the resource will read the aws creds from the standard aws environment variables, and the delete will do and update of the creds before the deletem. 

This way the operation will always have a fresh token from env, it can be used seamless, the new sts creds will not appear in the plan, the code change is really small, and we do not link to any other library. 

The user would still have to assume role before calling terraform, but in our specific case we already do.

What do you think?

**Comment by keymon** [comment]
@rawmind0 in https://github.com/terraform-providers/terraform-provider-rancher2/pull/84 I implemented the idea of pulling the credentials from environment variables.

I am testing it manually today/tomorrow.
