### ISSUE TITLE
How to include self-made Audit Policy file to RKE2 Cluster with Rancher 2.6

### ISSUE THREAD

**Issue by revog** [rancher/terraform-provider-rancher2#747]
Hello
I have a question regarding the auditpolicy. How can I include my self made audit policy configuration? Is this possible with `additional_manifest` or how can this be achieved?
I've seen that RKE2 generates an empty file on the node located at `/etc/rancher/rke2/audit-policy.yaml`. But this gets overwritten after config changes are applied through Rancher, right?

**Comment by rawmind0** [comment]
Hello @revog ,

it should be something like
```
machine_global_config = <<EOF
  kube-apiserver-arg:
  - "audit-policy-file=<CUSTOM_AUDIT_POLICY_FILE>"
EOF
```

Take a look to https://github.com/rancher/rke2/issues/410

**Comment by revog** [comment]
> Hello @revog ,
> 
> it should be something like
> 
> ```
> machine_global_config = <<EOF
>   kube-apiserver-arg:
>   - "audit-policy-file=<CUSTOM_AUDIT_POLICY_FILE>"
> EOF
> ```
> 
> Take a look to [rancher/rke2#410](https://github.com/rancher/rke2/issues/410)

I was not talking about changing the path, but I would like to change the content of the file with TF. But indeed, I could also create the file with TF and change the path to it by `machine_global_config`.

**Comment by revog** [comment]
> But this gets overwritten after config changes are applied through Rancher, right?

Did several tests and I can decline this. Uploaded audit policy file stays untouched and can easily referenced in `machine_global_config`argument 👍 .
