### ISSUE TITLE
RoleTemplate Rule doesn't allow verb own

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/terraform-provider-rancher2#762]
We are managing our own role templates for projects and would like to add the new projects rules with the verb own. This is what the OOTB project-owner role has. 

https://github.com/rancher/rancher/blob/release/v2.6/pkg/data/management/role_data.go#L267

**Comment by rawmind0** [comment]
The `own` verb was already introduced with PR https://github.com/rancher/terraform-provider-rancher2/pull/731 and included at tf provider release [v1.17.2](https://github.com/rancher/terraform-provider-rancher2/releases/tag/v1.17.2)

**Comment by mitchellmaler** [comment]
Oh wow, not sure how I missed that. 
I’ll look into upgrading the provider then. Thanks.
