### ISSUE TITLE
rancher2_app runs indefinitely on Helm error

### ISSUE THREAD

**Issue by rbkaspr** [rancher/terraform-provider-rancher2#767]
I recently attempted to deploy Sonatype Nexus to an RKE2 cluster running v1.21.4+rke2r3 using the Rancher Terraform provider v1.20.0. 

I had an error in my values file but rather than exiting immediately, the provider continued to attempt to create the app for nearly 10 minutes before I finally aborted the deployment. I diagnosed the underlying Helm issue by attempting a Helm install directly.

I found a similar issue rancher/terraform-provider-rancher2#697, but since the root cause in that case was different I figured I'd open a new issue. Feel free to close this as a dupe if needed and reopen the other issue as appropriate.

**Comment by rawmind0** [comment]
The provider is not attempting to create the app again, this behaviour is defined by Rancher2. The provider should return error if the `appV2OperationWait` is returning error, https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/resource_rancher2_app_v2.go#L68 .

**Comment by rbkaspr** [comment]
My question here is why is it taking 10+ minutes for the provider to return an error (or just not returning an error since I had to manually abort the apply operation) when the Helm render is failing instantly?

**Comment by rawmind0** [comment]
Are you setting `wait` to `true` or `false` https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/app_v2#wait ??

**Comment by rbkaspr** [comment]
I am not setting `wait` so presumably it's defaulting to true.

**Comment by rawmind0** [comment]
Have you tried setting it to `false`?? May your answer is related to it

**Comment by rbkaspr** [comment]
So setting `wait` explicitly to `false` seems to cause the provider to mark the app as successfully deployed even though the underlying Helm render fails, which is **not** desirable behavior. Removing the setting and applying *updates* to the app resource errors out immediately when invalid Helm is applied.  

However, as this issue occurred when a new app was being applied, I'm going to tear the app down completely and try deploying again.

**Comment by rbkaspr** [comment]
Okay, same behavior, if I deploy from scratch with Helm render errors and `wait` unset (defaults to `true`), the app deploy just hangs rather than immediately erroring out as expected.  If I set `wait` explicitly to false, the terraform apply reports success for all resources but the app doesn't actually deploy. This is a **bug**.

**Comment by rawmind0** [comment]
This is not a bug, this is the expected behaviour, app deployment is waiting or not for app rollout, depending on the resource argument. Helm run the deployment but it can't know if you are passing good or bad values to your chart.

**Comment by rbkaspr** [comment]
But under the hood Rancher is just executing a helm install command when an app is created (or at least that's the case in apps deployed manually through the Rancher UI), which should be failing immediately when the bad values cause a render error, and the app is clearly not being created, so why isn't this being propagated back to the Terraform provider?

**Comment by rawmind0** [comment]
I think you are doing rough and simplistic assumptions about how you guess Rancher works, that at some point are not right.  

As already mentioned [here](https://github.com/rancher/terraform-provider-rancher2/issues/767#issuecomment-939923030), once the app is created with an API call (async, not blocking call), an app operation is created (running the helm command) and is being checked to know its result (`Apps & Marketplace->recent operations` at rancher UI). Once the app operation is running (helm command has been executed), Rancher waits (or not depending on `wait` argument value) for app rollout during 10 minutes by default until it's set as error. This logic is not done by the provider. The provider is using the Rancher API and following the same logic than Rancher UI.

**Comment by rbkaspr** [comment]
I understand that the creation process for an app is a bit more complicated than Rancher just running `helm install`, I just didn't think the fine details added much to the discussion.

In any case, regardless of whether the intent is for the provider to use the same behavior as the UI, the observed behavior is different. If I create an app via the provider with bad configs, I either wait 10 minutes to get a generic error and no app CR is created (`wait = true`), or a get an immediate success response but still no app CR created (`wait = false`). At no point in either run configuration is an app CR ever created on the cluster, so I don't expect a helm operation is even being triggered.

If I create the same app with the same incorrect values via the UI, what appears to happen is the bad values **are silently dropped from the app spec** and the app CR is created and rolled out with what valid values remain. While this at least gets the app partially created, it's also not desirable behavior - at least in my opinion - for the app to just silently drop the bad bits and proceed with partial configuration rather than failing and notifying the operator that a mistake was made. Whether you agree with that stance or not, the UI is clearly not doing the same thing as the provider.

**Comment by rawmind0** [comment]
Could you provide a concrete app example to reproduce the behaviour you are talking about??

**Comment by rbkaspr** [comment]
Sure, here you go:
```yaml
Helm Repo
---------------
sonatype     https://sonatype.github.io/helm3-charts

Chart
-------
nexus-repository-manager

values.yaml
----------------
ingress:
  enabled: true
  tls:
    # This should be a list, but I'm writing it as a map
    secretName: example-crt
    hosts:
    # also should be a list, but also purposefully wrong for this example
      nexus.example.com
```

Corresponding TF snippet:
```yaml
resource "rancher2_app" "nexus" {
  catalog_name = sonatype
  name = nexus
  project_id = <redacted>
  target_namespace = nexus
  template_name = nexus-repository-manager
  template_version = 34.1.0
  values_yaml = filebase64("./values.yaml")
}
```

**Comment by rawmind0** [comment]
What you provided is not an `rancher2_app_v2` resource definition. The title is mentioning app v2, and i was talking about it. What app are you talking about, `rancher2_app` or `rancher2_app_v2`??

This would be the app_v2 definition with the data you provided

```
resource "rancher2_app_v2" "foo" {
  cluster_id = <redacted>
  name = "nexus-test"
  namespace = "default"
  repo_name = "sonartype"
  chart_name = "nexus-repository-manager"
  chart_version = "34.1.0"
  values = <<EOF
ingress:
  enabled: true
  tls:
    # This should be a list, but I'm writing it as a map
    secretName: example-crt
    hosts:
    # also should be a list, but also purposefully wrong for this example
      nexus.example.com
EOF
}
```

Result from the provider, the app operation result

```
terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # rancher2_app_v2.foo will be created
  + resource "rancher2_app_v2" "foo" {
      + annotations                 = (known after apply)
      + chart_name                  = "nexus-repository-manager"
      + chart_version               = "34.1.0"
      + cleanup_on_fail             = false
      + cluster_id                  = <redacted>
      + cluster_name                = (known after apply)
      + disable_hooks               = false
      + disable_open_api_validation = false
      + force_upgrade               = false
      + id                          = (known after apply)
      + labels                      = (known after apply)
      + name                        = "nexus-test"
      + namespace                   = "default"
      + repo_name                   = "sonartype"
      + system_default_registry     = (known after apply)
      + values                      = <<~EOT
            ingress:
              enabled: true
              tls:
                # This should be a list, but I'm writing it as a map
                secretName: example-crt
                hosts:
                # also should be a list, but also purposefully wrong for this example
                  nexus.example.com
        EOT
      + wait                        = true
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

rancher2_app_v2.foo: Creating...

Error: [ERROR] installing App V2: helm install --namespace=default --timeout=10m0s --values=/home/shell/helm/values-nexus-repository-manager-34.1.0.yaml --version=34.1.0 --wait=true nexus-test /home/shell/helm/nexus-repository-manager-34.1.0.tgz
coalesce.go:203: warning: destination for tls is a table. Ignoring non-table value []
Error: template: nexus-repository-manager/templates/ingress.yaml:25:16: executing "nexus-repository-manager/templates/ingress.yaml" at <.hosts>: can't evaluate field hosts in type interface {}


  on cattle.tf line 3, in resource "rancher2_app_v2" "foo":
   3: resource "rancher2_app_v2" "foo" {
```

**Comment by rbkaspr** [comment]
Yeah, whoops, I meant `rancher2_app`, I assume v2 is the new recommended way to go, yes?

**Comment by rawmind0** [comment]
Yes,  `rancher2_app_v2` and `rancher2_catalog_v2` are the way to go.
