### ISSUE TITLE
Set cloud provider in rancher_cluster_v2

### ISSUE THREAD

**Issue by braunsonm** [rancher/terraform-provider-rancher2#774]
It doesn't seem possible to set a cloud provider when using custom nodes with the `rancher_cluster_v2`. From what I can tell this should be defined in the `machine_config_v2` from now on but that lacks the ability to have configs for custom nodes.

For instance I am deploying nodes on vSphere but as custom nodes instead due to issues with the vSphere provider. I would like to set the cloud provider to vSphere so the CCM and CSI are deployed.

**Comment by braunsonm** [comment]
Or perhaps this could be set in the `machine_global_config`? However this is not what the Rancher UI uses for setting the cloud provider

**Comment by rawmind0** [comment]
It's possible, it should be defined at `machine_selector_config`, same used by Rancher UI to define cloud provider

```
machine_selector_config {
        config = {
            cloud-provider-name = "aws"
        }
}
```

https://docs.rke2.io/advanced/#installation-on-classified-aws-regions-or-networks-with-custom-aws-api-endpoints

**Comment by braunsonm** [comment]
Thank you I missed the machine selector config.
