### ISSUE TITLE
Cannot create S3 compatible cloud credentials

### ISSUE THREAD

**Issue by braunsonm** [rancher/terraform-provider-rancher2#778]
Hello,

I have an S3 compatible store I would like to write etcd snapshots to. If I create a cluster using `rancher_cluster_v2` I need to provide a `cloud_credential_name`. There currently aren't any options for `rancher2_cloud_credential` that is applicable.

I tried using an `amazonec2` cloud credential but unfortunately it errors that it cannot be found. Pretty sure there needs to be support for S3 Compatible Cloud Credentials in the Terraform provider

**Comment by rawmind0** [comment]
Hello @braunsonm, `cloud_credential_name` is referencing a secret name, not a `rancher2_cloud_credential` resource. A secret should be created with expected data keys: `accessKey` and `secretKey`

**Comment by braunsonm** [comment]
Thanks @rawmind0 can you clarify? If you mean a `rancher2_secret_v2`, that requires the `cluster_Id` which doesn't exist yet since it's being provided to the `rancher2_cluster_v2` :) 

Unless I can use a secret on the `local` cluster

**Comment by rawmind0** [comment]
I got your point, but yes 
 https://github.com/rancher/rancher/blob/v2.6.1/pkg/provisioningv2/rke2/planner/s3args.go#L100
The option to enable etcd S3 backup at cluster V2 creation is nor available at Rancher UI. Take into account that this is a tech preview.

**Comment by braunsonm** [comment]
So right now it's not possible to create the `rancher2_secret_v2` because of cyclic references? The code you linked is a tad confusing due to the fact that it gets `GetCloudCredentialSecret`, and accepts the same parameters as what is in the Rancher UI under `S3-Compatible Cloud Credential`

But you're saying this is not the same thing, and it is not possible to do this via the Terraform provider right now?

**Comment by rawmind0** [comment]
All cloud credentials are saved as secrets at k8s. Anyway, `S3-Compatible Cloud Credential` are not supported yet by this provider. Submitted PR #782 to add support for it

**Comment by braunsonm** [comment]
Thanks for being so quick on these @rawmind0 however even with one of those cloud credentials it doesn't seem to work. (created in the UI). But I don't think that's related to the provider so I made an issue here: https://github.com/rancher/rancher/issues/35163

The properties required for a v2 cluster are odd because you need to specify the endpoint/folder/etc but you ALSO specify those in the S3-Compatible Cloud Credential.

**Comment by rawmind0** [comment]
> Thanks for being so quick on these @rawmind0 however even with one of those cloud credentials it doesn't seem to work. (created in the UI). But I don't think that's related to the provider so I made an issue here: rancher/rancher#35163

Oh got it, it seems there is a possible issue at Rancher level. 

> The properties required for a v2 cluster are odd because you need to specify the endpoint/folder/etc but you ALSO specify those in the S3-Compatible Cloud Credential.

In the S3-Compatible Cloud Credential you specify default endpoint/folder/etc but they can be overwritten with `etcd.s3` values

**Comment by braunsonm** [comment]
Upstream issue has been fixed, it turns out the naming just isn't clear.

I'll close this however @rawmind0 it seems like all the arguments to `s3_config` in the `rancher2_cluster_v2` are required, even though I don't think they are in the Rancher API (only the name is required)

A release for your cloud credential would be nice!
