### ISSUE TITLE
Constant changes detected with registry mirrors

### ISSUE THREAD

**Issue by braunsonm** [rancher/terraform-provider-rancher2#779]
Given the following:

```hcl
resource "rancher2_cluster_v2" "cluster" {
  ....
  rke_config {
    registries {
      mirrors {
        endpoints = ["https://amy-domain.com"]
        hostname = "docker.io"
      }
      mirrors {
        endpoints = ["https://zmy-domain.com"]
        hostname = "edocker.io"
      }
      mirrors {
        endpoints = ["https://xmy-domain.com"]
        hostname = "bdocker.io"
      }
      mirrors {
        endpoints = ["https://dmy-domain.com"]
        hostname = "qdocker.io"
      }
      mirrors {
        endpoints = ["https://cmy-domain.com"]
        hostname = "zdocker.io"
      }
    }
  }
}
```

Any subsequent `terraform apply` show the mirrors as being resorted over and over again. Perhaps this is because of the Rancher API? Or maybe how Terraform handles duplicate mirrors blocks? If it's a terraform issue can we make mirrors an array instead of multiple map blocks?

**Comment by rawmind0** [comment]
Issue reproduced. Submitted PR https://github.com/rancher/terraform-provider-rancher2/pull/783 to fix it

**Comment by rawmind0** [comment]
Issue #783 is already merged. The fix will be available at next tf provider release.
