### ISSUE TITLE
Support labels and annotations for rancher2_cluster_v2

### ISSUE THREAD

**Issue by kgtw** [rancher/terraform-provider-rancher2#784]
The `rancher2_cluster` resource supports annotations & labels (https://github.com/rancher/terraform-provider-rancher2/issues/582), this functionality appears to be missing for the `rancher2_cluster_v2` resource.

**Comment by rawmind0** [comment]
Labels and annotations are already supported by `rancher2_cluster_v2` https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/structure_cluster_v2.go#L91

**Comment by kgtw** [comment]
Ok, looks like docs need updating as there is no mention of them being available for the resource.

**Comment by rawmind0** [comment]
You are right @kgtw . We'll update docs properly.

**Comment by rawmind0** [comment]
Fixed with PR https://github.com/rancher/terraform-provider-rancher2/pull/794

**Comment by rawmind0** [comment]
PR https://github.com/rancher/terraform-provider-rancher2/pull/794 is already merged. The fix will be available on next release
