### ISSUE TITLE
Create a Node Template for AWS i3.xlarge

### ISSUE THREAD

**Issue by doublethink13** [rancher/terraform-provider-rancher2#785]
I need to create a Node Template for an AWS instance of type i3.xlarge.

I need to have the `NVMe` mounted when a node is provisioned via a Node Pool.

How can I accomplish this?

```
ubuntu@gfs1:~$ lsblk
NAME    MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
loop0     7:0    0  93.8M  1 loop /snap/core/8935
loop1     7:1    0    18M  1 loop /snap/amazon-ssm-agent/1566
xvda    202:0    0    40G  0 disk
└─xvda1 202:1    0    40G  0 part /
nvme0n1 259:0    0 884.8G  0 disk
```

**Comment by rawmind0** [comment]
may be using cloud-init??

**Comment by doublethink13** [comment]
My bad, I missed the `userdata` field on the `amazonec2_config` 😅 

For future reference, if everyone needs, this script mounts the volume before the node is added to the cluster:

```
#!/bin/bash

mkfs.ext4 -E nodiscard /dev/nvme0n1
mkdir /mnt/nvme
mount /dev/nvme0n1 /mnt/nvme
```

`lsblk` confirms this.

Also, I found the [description](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/node_template#userdata) of the `userdata` a bit misleading. Passing a string to a file resulted in the template being created with a `userdata` that was the path, not the contents of the file. Instead of passing a path to a file, passing the contents of a file as `file("${path.module}/userdata.sh")` worked fine.

Closing.
