### ISSUE TITLE
Invalid provider configuration due to config.NormalizeURL returning error

### ISSUE THREAD

**Issue by mouellet** [rancher/terraform-provider-rancher2#787]
We're using a dynamic IP from an Azure Load Balancer to build an fqdn as hostname (somewhat like nip.io) when deploying the rancher server and using it as input for the rancher2 provider's `api_url` to bootstrap and configure the server. 

```
provider "rancher2" {
  api_url = "https://${replace(module.load_balancer.ip_address, ".", "-")}.nip.io"
}
```

All of this happens in the same terraform context, so the value for the provider's `api_url` is not known when running a plan.

When updating to v1.21.0, we now get the following output with the `terraform plan` command:
```
╷
│ Error: Invalid provider configuration
│ 
│ Provider "registry.terraform.io/rancher/rancher2" requires explicit
│ configuration. Add a provider block to the root module and configure the
│ provider's required arguments as described in the provider documentation.
│ 
╵
╷
│ Error: [ERROR] Normalizing url: no api_url provided
│ 
│   with provider["registry.terraform.io/rancher/rancher2"],
│   on <empty> line 0:
│   (source code not available)
│ 
```

**Comment by rawmind0** [comment]
Just to confirm, was the same confirm working fine on provider prior to v1.21.0??

**Comment by mouellet** [comment]
Nevemind! This was due to misconfiguration from my part...

**Comment by nomadgis** [comment]
@mouellet wondering if you could add what you did to correct this...

**Comment by clayrisser** [comment]
@mouellet what was the misconfiguration? I am getting the same error.

**Comment by jobwat-servian** [comment]
I'm getting the same error, I've opened a new thread - https://github.com/rancher/terraform-provider-rancher2/issues/938
