### ISSUE TITLE
Cannot delete v2 provisioning cluster that was successfully provisioned and active at one point, but is no longer available

### ISSUE THREAD

**Issue by Oats87** [rancher/terraform-provider-rancher2#788]
If you create a v2 provisioning cluster with Rancher v2.6.2+ using Terraform, i.e.

https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster_v2

If you delete the underlying machines or if the cluster becomes unavailable for any reason i.e. cluster-agent dies or something, you cannot delete it via Terraform because Terraform gets stuck trying to refresh the state for the cluster

```
chriskim@Endeavor tf % terraform destroy -auto-approve
rancher2_cluster_v2.cluster: Refreshing state... [id=fleet-default/mycluster]
╷
│ Error: Setting cluster V2 legacy data: Getting cluster Kubeconfig: Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [message=Post "https://10.43.0.1:443/apis/cluster.cattle.io/v3/namespaces/cattle-system/clusterauthtokens": net/http: TLS handshake timeout, baseType=error, code=ServerError] from [https://<my-rancher>/v3/clusters/c-m-gtxldgsk?action=generateKubeconfig]
│
│   with rancher2_cluster_v2.cluster,
│   on main.tf line 14, in resource "rancher2_cluster_v2" "cluster":
│   14: resource "rancher2_cluster_v2" "cluster" {
│
╵
```

The cluster was created with the snippet:
```
terraform {
	required_providers {
	  rancher2 = {
		source = "rancher/rancher2"
		}
	}
}

provider "rancher2" {
  api_url    = "<my-rancher>"
  token_key = "<goaway>"
}

resource "rancher2_cluster_v2" "cluster" {
    name = "mycluster"
    kubernetes_version = "v1.21.5+rke2r2"

    rke_config {
        etcd {
            # Broken in rancher, see rancher/rancher#35163
            # s3_config {}
        }
        local_auth_endpoint {
            enabled = true
        }
    }
}
```

I then logged into Rancher and used the custom cluster registration command to register the cluster and have it come up to be active

I deleted the underlying infrastructure machines which made the cluster go unavailable, then tried to `destroy` it only to be blocked on destruction.

/cc @braunsonm

**Comment by rawmind0** [comment]
Issue reproduced. Submitted PR https://github.com/rancher/terraform-provider-rancher2/pull/794 with a patch for it

**Comment by rawmind0** [comment]
PR https://github.com/rancher/terraform-provider-rancher2/pull/794 is already merged. The fix will be available on next release
