### ISSUE TITLE
Rancher User for provider gets a new Kubeconfig token (kube_config) each time ran

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/terraform-provider-rancher2#789]
We have noticed that the user used for this provider (providing the bearer token) gets a new Kubeconfig token generated each time we run. If we run plan then it would create two (plan and apply). We grab the kube_config from the rancher2_cluster datasource or created rancher2_cluster output. Is there a reason it generates a new kube_config each time or should it be using the existing one and one shouldn't be always created.

**Comment by pwurbs** [comment]
Yes, this very annoying, because many tokens are created which are all valid.

**Comment by rawmind0** [comment]
Issue reproduced at Rancher v2.6.x. 
Related with issue https://github.com/rancher/terraform-provider-rancher2/issues/802

**Comment by rawmind0** [comment]
Submitted PR https://github.com/rancher/terraform-provider-rancher2/pull/837 to fix the issue

**Comment by sgapanovich** [comment]
### Reproduction ###

Rancher version: 2.6.3
Rancher cluster type: HA
Terraform provider rancher 2 version:  "1.21.0"

----------

New Kubeconfig token is created every time when `terraform apply` or `terraform plan` is run with the following resources
- rancher2_cluster
- rancher2_cluster_v2
- rancher2_cluster_sync
![apply and plan](https://user-images.githubusercontent.com/40282141/148284922-28928784-b61e-4f88-b60c-f083a1047bac.jpg)

the above resources should generate tokens when run first time but should use existing ones when re-running 
- new token generated every time i run `terraform apply` or `terraform plan` (even when there is no changes)

**Comment by rawmind0** [comment]
@sgapanovich  the fix has been included on new release v1.22.2.

**Comment by sgapanovich** [comment]
### Test Environment: ###
Rancher version: 2.6.3
Rancher cluster type: HA
Terraform provider rancher 2 version: "1.22.2"

----------

### Testing: ###

`rancher2_cluster` and `rancher2_cluster_sync` and `rancher2_cluster_v2`:
when running `tf plan` first time - no token is created
when running `tf apply` first time - token is created 
when cluster is provisioned running `tf plan` or `tf apply` does not create new tokens 
if the generated kubeconfig-user token for the resource is deleted (in rancher)
-`tf plan` will generate a new token (will be creating new tokens every time until a token created by `tf apply` assigned to the resource)
-`tf apply` will generate a new token (the token will be assigned to the resource)

----

`data "rancher2_cluster"` and `data "rancher2_cluster_v2"`:
generates a new token every time when running `tf plan` or `tf apply` 
issues with data sources will be addressed in this issue https://github.com/rancher/terraform-provider-rancher2/issues/841  in the upcoming TF releases
