### ISSUE TITLE
Add option enable_cri_dockerd in rke_config

### ISSUE THREAD

**Issue by nickvth** [rancher/terraform-provider-rancher2#792]
Please add this in the rancher2_cluster Resource under rke_config: https://rancher.com/docs/rke/latest/en/config-options/#cri-dockerd

So we can use cri_dockerd in the future.

**Comment by rawmind0** [comment]
Submitted PR https://github.com/rancher/terraform-provider-rancher2/pull/794 adding the new feature

**Comment by rawmind0** [comment]
PR https://github.com/rancher/terraform-provider-rancher2/pull/794 is already merged. The feature will be available on next release.

**Comment by nickvth** [comment]
Great job @rawmind0
