### ISSUE TITLE
possible to import generic cluster

### ISSUE THREAD

**Issue by lachnerd** [rancher/terraform-provider-rancher2#795]
Hi,
is it possible to import some prebuild generic k3s cluster with 
terraform-provider-rancher2 like i can do with the rancher 2 UI.

I can't find any docs or examples for that.

I can only find examples generating clusters with Hardware on some cloud Providers but no cmplete import.

**Comment by rawmind0** [comment]
Have you tried with official docs?? https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster

**Comment by lachnerd** [comment]
yes

"Creating Rancher v2 imported cluster"
````
# Create a new rancher2 imported Cluster
resource "rancher2_cluster" "foo-imported" {
  name = "foo-imported"
  description = "Foo rancher2 imported cluster"
}
```

is no big help.

And the other examples are for RKE & EKS and actively create the cluster ressources but no example for a existing generic cluster that should only be imported.

**Comment by rawmind0** [comment]
This is what you need to create a generic imported cluster like done in UI

```
# Create a new rancher2 imported Cluster
resource "rancher2_cluster" "foo-imported" {
  name = "foo-imported"
  description = "Foo rancher2 imported cluster"
}
```

Then [cluster_registration_token](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster#cluster_registration_token) is computed  and `command` or `insecure_command` is what you need to execute in the k8s cluster to get it imported.

Other option would be if the cluster is already imported in Rancher but you wanted to take its control with terraform, https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster#import

**Comment by lachnerd** [comment]
ok thx i will try that, looks like i have missed that "command" attribute

**Comment by rawmind0** [comment]
Please, reopen issue if required.
