### ISSUE TITLE
rancher2_cluster_sync state_confirm not working as expected in Rancher 2.6.2

### ISSUE THREAD

**Issue by chad-barensfeld-exa** [rancher/terraform-provider-rancher2#797]
It seems the rancher2_cluster_sync state_confirm parameter stopped working as expected. The rancher2_cluster_sync would usually wait at least 10 minutes before completing to ensure all rancher services were working properly before deploying applications. Now it completes in ~10 seconds no matter what I set for state_confirm. This is causing issues when adding rancher2_catalog_v2, it fails in terraform, but works in rancher, and the only way to get around this is to delete the repo manually from rancher UI and run terraform again. I tried the wait_catalogs option but that fails with another error.

Rancher: 2.6.2
Rancher TF provider: 1.21.0

```
resource "rancher2_cluster_sync" "customer" {
  cluster_id    = rancher2_cluster.customer.id
  state_confirm = 120
}

module.rancher.rancher2_cluster.customer: Creation complete after 8s [id=c-g762x]
module.rancher.rancher2_cluster_sync.customer: Creating...
module.rancher.rancher2_cluster_sync.customer: Still creating... [10s elapsed]
module.rancher.rancher2_cluster_sync.customer: Creation complete after 11s [id=c-g762x]
module.rancher.rancher2_catalog_v2.helm: Still creating... [50s elapsed]
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to module.rancher.rancher2_catalog_v2.helm, provider "provider[\"registry.terraform.io/rancher/rancher2\"]"
│ produced an unexpected new value: Root resource was present, but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

**Comment by rawmind0** [comment]
Issue reproduced. Submitted PR https://github.com/rancher/terraform-provider-rancher2/pull/832 to fix it.

**Comment by rawmind0** [comment]
PR #832  is already merged, the fix will be available at next tf provider release.

Please, reopen issue if required.
