### ISSUE TITLE
Please add support for ecr_credential_plugin in Cluster Template resource.

### ISSUE THREAD

**Issue by shanewow** [rancher/terraform-provider-rancher2#798]
Please add support for ecr_credential_plugin within the Cluster Template resource so ECR can be configured through Terraform.

Thanks!

**Comment by rawmind0** [comment]
This is not supported on https://github.com/rancher/rancher. It should be supported there before can be added here

**Comment by shanewow** [comment]
@rawmind0 It is implemented in the Rancher app. We have added a manual step to our deployment process to edit the template after Terraform deployment to utilize the ecr_credential_plugin and it is working for us. Would be nice if we could automate through Terraform. Thanks!

**Comment by hyphloday** [comment]
I'm confused.  This seems to indicate that it is supported:
https://rancher.com/docs/rke/latest/en/config-options/private-registries/
Just not in the terraform provider as @shanewow is pointing out.

**Comment by rawmind0** [comment]
My bad on this. I was thinking on a cloud credential kind instead of private registry config. This may be added for next provider release.

**Comment by rawmind0** [comment]
Submitted PR https://github.com/rancher/terraform-provider-rancher2/pull/821 to add the new feature

**Comment by eumel8** [comment]
headed here from Google for the error 

```
[ERROR] error syncing 'c-g4et6': handler cluster-deploy: Not a valid ECR registry, requeuing
```

in a Rancher 2.6.2 RKE cluster with enabled private registry.

```
  private_registries:
    - ecr_credential_plugin: {}
      is_default: true
      url: mtr.external.otc.telekomcloud.com
```

"Solution" to bring the cluster back from error state was to remove the private_registries entry, update the cluster, and add the entry again. Just to mention if someone runs in the same error.

**Comment by rawmind0** [comment]
PR #821  is already merged. The new feature will be available at next tfp release. Please, reopen the issue if required.
