### ISSUE TITLE
rancher2_cluster_v2 resource updates for RKE2 <-> RKE1 parity enhancements

### ISSUE THREAD

**Issue by snasovich** [rancher/terraform-provider-rancher2#799]
This is an umbrella issue to track any changes necessary to rancher2 Terraform provider (https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster_v2) related to RKE2 provisioning enhancements done as part of "RKE2 <-> RKE1 parity" efforts.

- [x] https://github.com/rancher/terraform-provider-rancher2/issues/869
- [x] https://github.com/rancher/terraform-provider-rancher2/issues/873

**Comment by Jono-SUSE-Rancher** [comment]
Closing this with the 2.6.4 oob TF release
