### ISSUE TITLE
rancher2_auth_config_azuread - no groups available, group-role-mapping not working

### ISSUE THREAD

**Issue by sebastiankomander** [rancher/terraform-provider-rancher2#801]
We use the rancher2_auth_config_azuread resource with Rancher 2.6. 
The app-registration has the following permissions

- Directory.AccessAsUser.All (delegated)
- Directory.Read.All (delegated)
- Group.Read.All (delegated)
- User.Read.All (delegated)
- User.ReadBasic.All (delegated)

and some role mappings

```
data "azuread_groups" "allowedRancherGroups" {
  display_names    = ["aad group 1", "aad group 2"]
  security_enabled = true
}

locals {
  all_allowed_principals = concat([ "local://${data.rancher2_user.admin.id}"], formatlist("azuread_group://%s", data.azuread_groups.allowedRancherGroups.object_ids))
}

resource "rancher2_auth_config_azuread" "ad" {
  application_id        = <client-id>
  application_secret    = <client-secret>
  rancher_url           = "${var.rancher_url}/verify-auth-azure"
  tenant_id             = data.azurerm_subscription.current.tenant_id
  auth_endpoint         = "https://login.microsoftonline.com/${data.azurerm_subscription.current.tenant_id}/oauth2/authorize"
  graph_endpoint        = "https://graph.windows.net/"
  token_endpoint        = "https://login.microsoftonline.com/${data.azurerm_subscription.current.tenant_id}/oauth2/token"
  access_mode           = "required"
  allowed_principal_ids = local.all_allowed_principals
}

data "azuread_groups" "rancherAdmins" {
  display_names    = ["AAD-Group 1", "AAD-Group 2"]
  security_enabled = true
}

data "rancher2_global_role" "admin_role" {
  name = "Admin"
}

resource "rancher2_global_role_binding" "admin-role-mapping" {
  for_each           = toset(data.azuread_groups.rancherAdmins.object_ids)
  global_role_id     = data.rancher2_global_role.admin_role.id
  group_principal_id = each.value
}

```

Logging in using AzureAD works, however role assignment does not work and Rancher indicates that it cannot find groups/users for the IDs. Same goes for the logs:

```
2021/11/17 07:57:07 [ERROR] Unknown error: invalid id 09fca23f-b745-42a1-9384-b45c74f81ed9
```
It's also not possible to search for users and/or groups - no results available.

However, when I manually configure the auth provider, it works - with exactly the same configuration.
And then, searching by users and groups als works fine.

The only difference is that when I configure it manually, I am logged into Azure with a user with elevated privileges. Via Terraform, the pipeline runs with a service principal with the following permissions

Microsoft Graph: 
- Application.Read.All
- Application.ReadWrite.All
- AppRoleAssignment.ReadWrite.All
- Directory.Read.All
- Directory.ReadWrite.All
- Domain.Read.All
- Group.Read.All
- Group.ReadWrite.All
- User.ReadWrite.All

Azure Active Directory Graph
- Application.ReadWrite.All (Application)
- Application.ReadWrite.OwnedBy (Application)
- Directory.AccessAsUser.All (Delegated)
- Directory.Read.All (Delegated + Application)
- Directory.ReadWrite.All (Delegated + Application)
- Group.Read.All (Delegated)
- Group.ReadWrite.All (Delegated)
- User.Read (Delegated)
- User.Read.All (Delegated)

Any ideas on how configuration works with Terraform including roles/group mappings.

**Comment by rawmind0** [comment]
Have you tried  adding the prefix `azuread_group://` to `rancher2_global_role_binding.admin-role-mapping.group_principal_id`??

**Comment by rawmind0** [comment]
Please, reopen the issue if still needed.

**Comment by donydonald1** [comment]
Hello,  
        I know this is old but I am curious as I currently have a project like the one above for my ORG. The rancher_auth_azuread provider works fine but as it is now... all users can log in to the rancher UI with their azure ad but are not able to see a cluster so I was wondering if there is a proper code like the one above which permits me to add azure ad groups to map rancher role/groups?.
        
Please help
