### ISSUE TITLE
Rancher2 Terraform provider - issues VMs on vsphere by enabled CPI/CSI helm charts

### ISSUE THREAD

**Issue by dpaardenkooper** [rancher/terraform-provider-rancher2#803]
Usecase:
Recycling of kubernetes nodes (like Master or Worker) with new VM of of the rancher UI.

Issue: 
After Draining and deleting one node of the cluster, Rancher UI removes 2 workers or 2 master at the same time.
Recreates the VM's but then the "already exist message appears" as rancher tries to provision more than 1 node at the same time. The Rancher UI comes back after it finally creates the right vm's saying that it cannot drain the worker nodes and that it is stuck in mode "drain failed, cant drain with --ignore-daemonsets and ignore-local-data".
investigating it more, the vsphere CPI container stayes locked on its volume, which cannot be released (until you remove the CPI/CSI helm chart).

Environment specs:
- vsphere 7.x (latest and up to date)
- terraform "1.0.7"
- Rancher 2 provider "terraform-provider-rancher2_1.20.1"
- Rancher version (2.5.9 - because of the stability of Windows downstream clusters)
- helm charts CPI and CSI enabled from the repository of rancher itself (because of the airgapped environment);

**Comment by dpaardenkooper** [comment]
wo1 error: cannot delete Pods with local storage (use --delete-local-data to override): kube-system/metrics-server-7df46f66b6-7dp75

**Comment by dpaardenkooper** [comment]
Seams also to be happening without the CSi and CPI helm chart

**Comment by rawmind0** [comment]
Have you proper configured cluster [upgrade_strategy](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster#upgrade_strategy) ?? Both drain errors attached seems related to a wrong cluster upgrade_strategy

**Comment by rawmind0** [comment]
Please, reopen the issue if still needed.
