### ISSUE TITLE
rancher2_cluster_v2 ACE enabled does not work on RKE2

### ISSUE THREAD

**Issue by braunsonm** [rancher/terraform-provider-rancher2#806]
Given:

```
resource "rancher2_cluster_v2" "example" {
  ...
  rke_config {
    local_auth_endpoint {
      enabled = true
    }
  }
}
```

The endpoint will not be enabled and if you download your kubeconfig there will be no ACE endpoints added.

**Comment by rawmind0** [comment]
Submitted PR https://github.com/rancher/terraform-provider-rancher2/pull/815 to fix this issue

**Comment by rawmind0** [comment]
PR #815 is already merged. The fix will be available at next tfp release. Please, reopen issue if required.
