### ISSUE TITLE
rancher2_cluster_v2 does not support checking 'Delete standalone pods'

### ISSUE THREAD

**Issue by braunsonm** [rancher/terraform-provider-rancher2#808]
In the Rancher UI under `Upgrade Strategy` -> Drain Nodes -> `Delete standalone pods` is an option.

This doesn't seem to be available to set using the Terraform Provider for rancher which means any upgrades with standalone pods will fail until corrected.

**Comment by rawmind0** [comment]
The mentioned option is available as  https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster_v2#force
