### ISSUE TITLE
rancher2_cluster_template example does not work

### ISSUE THREAD

**Issue by AndreasDavour** [rancher/terraform-provider-rancher2#811]
I tried to run the example from https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster_template - Creating Rancher v2 RKE cluster template with upgrade strategy. For Rancher v2.4.x or above. (second example) after exchanging the local://user-XXXXX with my local admin user. It did not work and returned a nonsensical message about missing a name field that's already there. What gives?

╷
│ Error: Missing required argument
│ 
│   on mytest.tf line 1, in resource "rancher2_cluster" "mytest":
│    1: resource "rancher2_cluster" "mytest" {
│ 
│ The argument "name" is required, but no definition was found.
╵

# Create a new rancher2 Cluster Template
resource "rancher2_cluster_template" "mytest" {
  name = "mytest"
  members {
    access_type = "owner"
    user_principal_id = "local://user-user-lspwj"
  }
  template_revisions {
    name = "V1"
    cluster_config {
      rke_config {
        network {
          plugin = "canal"
        }
        services {
          etcd {
            creation = "6h"
            retention = "24h"
          }
        }
        upgrade_strategy {
          drain = true
          max_unavailable_worker = "20%"
        }
      }
    }
    default = true
  }
  description = "Terraform cluster template foo"
}

That's exactly the example, so why doesn't it work?

**Comment by AndreasDavour** [comment]
I can see that name there! It's on the second line! If I try to add it again, terraform apply complains it's already there. I knew that.

**Comment by rawmind0** [comment]
The error you are attaching doesn't seem related with `rancher2_cluster_template` definition . As the error is saying, the name seems not defined in the `rancher2_cluster.mytest` resource.
