### ISSUE TITLE
`rancher2_catalog_v2`'s always shows changes made outside of Terraform on `resource_version`

### ISSUE THREAD

**Issue by mouellet** [rancher/terraform-provider-rancher2#812]
Looks like the "catalog" is pooling the helm repository regularly and the `resource_version` is constantly incremented.

```
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # rancher2_catalog_v2.this has been changed
  ~ resource "rancher2_catalog_v2" "this" {
        id                        = "c-kdll9.my-helm-repository"
        name                      = "my-helm-repository"
      ~ resource_version          = "5529" -> "7637"
        # (10 unchanged attributes hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to these changes.
```

This pollutes the plan and can't be ignored.

**Comment by rawmind0** [comment]
The `resource_version` argument is computed and has to be synced at tfstate. Have you considered to use `-refresh-only` plan as terraform recommends,  https://www.terraform.io/docs/cli/commands/plan.html#planning-modes ??

**Comment by mouellet** [comment]
Hi @rawmind0,

I do use a `-refresh-only` before a plan, but even then an update can happen in between!

Should this argument be in the data source only? I don't see the use for such an argument in this resource, especially now that terraform shows diff for changes made outside...

**Comment by rawmind0** [comment]
Hi @mouellet , the `resource_version` argument is required at the resource to be able to update it at k8s side when required. It's a computed argument so it's just for internal use.

**Comment by mouellet** [comment]
Thanks @rawmind0, hopefully we'll have a fix for https://github.com/hashicorp/terraform/issues/28803 soon enough!
