### ISSUE TITLE
machine_config_v2: 500 error metadata.resourceVersion is required for update

### ISSUE THREAD

**Issue by braunsonm** [rancher/terraform-provider-rancher2#816]
1. Create a machine_config_v2
2. Try to update it after it's been created
3. Notice 500 error stating `bad response statusCode [500]. Status [500 Internal Server Error]. Body: [code=ServerError, message=metadata.resourceVersion is required for update] from [...rke-machine-config.cattle.io.vmwarevsphereconfigs/fleet-default/nc-...]

**Comment by braunsonm** [comment]
This also seems to wipe out/destroy some of the configuration after the 500 error occurs. 
For instance the `cloneFrom`, `datacenter` `pool`, `folder`, `network` and `datastore` get cleared causing errors on the next run.

**Comment by rawmind0** [comment]
The issue has been reproduced. Submitted PR https://github.com/rancher/terraform-provider-rancher2/pull/819 to fix it

**Comment by rawmind0** [comment]
PR #819 is already merged. The fix will be included on next tfp release. Please, reopen the issue if required.

**Comment by OA72280** [comment]
Hi! Regarding rancher2 and Terraform" 

When using the terraform destroy  command, it removed only a portion of the k8s cluster in rancher, resulting in an 500 error. Requires my needing to manually delete the cluster in the Rancher UI and re-run the TF destroy command.  

Error: Bad response statusCode [500]. Status [500 Internal Server Error] Body: [baseType=error, code=ServerError, message=Get "10.43.0.1:433/api/v1/namesapces/fio?timeout=45s": cluster agent disconnected] from [https://k3s-rancher.x.local/v3/cluster/c/-m.8kmkoooo/namespaces/fio]

Any insight would be greatly appreciated.

OA
