### ISSUE TITLE
Grab kubeconfig from provisioned cluster

### ISSUE THREAD

**Issue by braunsonm** [rancher/terraform-provider-rancher2#823]
Hello, this is a question or feature suggestion if not already possible.

With the rancher CLI you can get a Kubeconfig with `rancher clusters kf <name>`, is there a similar way to get a kubeconfig for the currently authenticated user with the terraform provider? Maybe even as a datasource?

The use case being that once a cluster is provisioned with the rancher terraform provider, I would like to start deploying things to it in another terraform workspace (since you need to initialize the helm or kubectl provider for example with a kubeconfig). It would be convenient if there was a way to grab that kubeconfig from the tf state.

**Comment by rawmind0** [comment]
Hello @braunsonm , there is already a way to do that. There is a `rancher2_cluster.kube_config` attribute that is saving cluster kubeconfig, https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster#kube_config

**Comment by braunsonm** [comment]
Perfect I don't know how I missed that. I think I just ctrl+F'd `kubeconfig`
