### ISSUE TITLE
rancho2 provider flips monitoring enabled -> disabled (or vice versa) every run

### ISSUE THREAD

**Issue by nrfrush** [rancher/terraform-provider-rancher2#825]
# Description
During a Terraform apply, Rancher will report that nothing has changed within the clusters (minus some nginx settings), but will flip enable_monitoring from true -> false (without Terraform reporting it), leading to monitoring getting disabled.

During a subsequent run, Terraform will recognize monitoring isn't enabled and then go and enable it.

Is there any way to remedy this? Is this intended behavior or a bug?

# Versions
Terraform v1.0.9
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v3.68.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.7.1
+ provider registry.terraform.io/rancher/rancher2 v1.21.0

**Comment by rawmind0** [comment]
This behaviour sounds weird. Could you please provide your cluster tf definition?? Is the `enable_monitoring` value set from a variable??

**Comment by nrfrush** [comment]
@rawmind0 The value is set statically to true

Here's an excerpt on my cluster definition:
```
resource "rancher2_cluster" "XXX" {
  ...
  enable_cluster_monitoring = true
  cluster_monitoring_input {
    answers = {
      "exporter-kubelets.https" = true
      "exporter-node.enabled" = true
      "exporter-node.ports.metrics.port" = 9796
      "exporter-node.resources.limits.cpu" = "200m"
      "exporter-node.resources.limits.memory" = "200Mi"
      "grafana.persistence.enabled" = false
      "grafana.persistence.size" = "10Gi"
      "grafana.persistence.storageClass" = "default"
      "operator.resources.limits.memory" = "500Mi"
      "operator-init.enabled" = "true"
      "prometheus.persistence.enabled" = "false"
      "prometheus.persistence.size" = "50Gi"
      "prometheus.persistence.storageClass" = "default"
      "prometheus.persistent.useReleaseName" = "true"
      "prometheus.resources.core.limits.cpu" = "1000m",
      "prometheus.resources.core.limits.memory" = "4000Mi"
      "prometheus.resources.core.requests.cpu" = "750m"
      "prometheus.resources.core.requests.memory" = "750Mi"
      "prometheus.retention" = "48h"
    }
    ...
}
```

**Comment by rawmind0** [comment]
@nrfrush  thanks for the update. What rancher version are you using?? Starting at Rancher 2.5, the recommended way to enable monitoring on a cluster  is using app v2, https://registry.terraform.io/providers/rancher/rancher2/latest/docs/guides/apps_marketplace#rancher-monitoring  . Have you tested with it??

**Comment by nrfrush** [comment]
@rawmind0 I'm on Rancher 2.4. I do have a variant of the rancher-monitoring Helm v2 chart on which I bumped versions (but nothing on the Rancher side is changing w.r.t enable_monitoring... and Terraform as explained above doesn't indicate when it's going to flip it off).

**Comment by rawmind0** [comment]
Issue reproduced. Submitted PR https://github.com/rancher/terraform-provider-rancher2/pull/832 to fix it.

**Comment by rawmind0** [comment]
PR #832  is already merged, the fix will be available at next tf provider release.

Please, reopen issue if required.
