### ISSUE TITLE
data.rancher2_cluster.kube_config is empty

### ISSUE THREAD

**Issue by dec5e** [rancher/terraform-provider-rancher2#829]
After updating to v1.22.0 I started getting the error:

```
│ Error: Error in function call
│ 
│   on providers.tf line 12, in provider "kubernetes":
│   12:   host     = yamldecode(data.rancher2_cluster.cluster.kube_config).clusters[0].cluster.server
│     ├────────────────
│     │ data.rancher2_cluster.cluster.kube_config is ""
```

My code is:
```terraform
provider "rancher2" {
  api_url  = "https://my.rancher.local"
  insecure = true
}

data "rancher2_cluster" "cluster" {
  name = "my-cluster"
}

provider "kubernetes" {
  host     = yamldecode(data.rancher2_cluster.cluster.kube_config).clusters[0].cluster.server
  insecure = true
}
```

v1.21.0 works as expected.

Possible breaking change might be in https://github.com/rancher/terraform-provider-rancher2/pull/794 as it changed `getClusterKubeconfig` function.

**Comment by rawmind0** [comment]
What Rancher version are you using?? I'm assuming that the mentioned cluster has local cluster auth endpoint enabled, isn't it??  Is the cluster already provisioned?? The cluster  kubeconfig would not be available at Rancher API until the cluster is [`connected`](https://github.com/rancher/terraform-provider-rancher2/pull/794/files#diff-035d1bb527d3ce1fde79a8bf6a191e1c441f7e2074f17caa106ba35a66fefa0bR601)

**Comment by dec5e** [comment]
Rancher version is v2.5.7.
The cluster was created long time ago. "Authorized Cluster Endpoint" is enabled.

**Comment by rawmind0** [comment]
Issue reproduced. The cluster kubeconfig would not be available at Rancher API until the cluster is `connected` just for Rancher 2.6.0 and above

Submitted PR https://github.com/rancher/terraform-provider-rancher2/pull/830 to fix it

**Comment by rawmind0** [comment]
PR #830  is already merged and included at tfp v1.22.1

Please, reopen the issue if required

**Comment by bitnik** [comment]
@rawmind0 we just hit the same problem:

```bash
│ Error: Error in function call
│ 
│   on modules/rancher_worker/outputs.tf line 2, in output "rancher_kube_config":
│    2:   value       = yamldecode(rancher2_cluster.rancher_cluster.kube_config)
│     ├────────────────
│     │ rancher2_cluster.rancher_cluster.kube_config has a sensitive value
│ 
│ Call to function "yamldecode" failed: on line 1, column 1: missing start of document.
```

We use rancher version 2.6.3 and rancher2 provider version 1.22.1. The `cluster_auth_endpoint` is enabled and the cluster is created fresh.

**Comment by bitnik** [comment]
Btw there is sth confuses me; in the [changelog](https://github.com/rancher/terraform-provider-rancher2/blob/master/CHANGELOG.md#1221-december-23-2021) it says "Fix getClusterKubeconfig function to properly generate kubeconfig when rancher2_cluster.LocalClusterAuthEndpoint is enabled for Rancher **lower than v2.6.x**" but in your comment above you say that it is for Rancher 2.6.0 and **above**:

> Issue reproduced. The cluster kubeconfig would not be available at Rancher API until the cluster is connected just for Rancher 2.6.0 and above

**Comment by rawmind0** [comment]
@bitnik , as mentioned here and added a note in the [docs](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster#kube_config), this is expected for Rancher 2.6.0 and above. `The cluster kubeconfig would not be available at Rancher API until the cluster is connected just for Rancher 2.6.0 and above` The Rancher API is not providing the kubeconfig until the cluster is already `connected`, when the `cluster_auth_endpoint` is enabled

**Comment by bitnik** [comment]
Thank you for your quick response! Sorry, I am quite new into this, I think now I understand it. What would be the solution for this, is there a way to wait until cluster is connected? Or do we simply have to plan and apply again?

**Comment by rawmind0** [comment]
@bitnik , I'd recommend you to add a `rancher2_cluster_sync` resource besides `rancher2_cluster`. This resource will wait until the cluster is `active` and it also has the [`rancher2_cluster_sync.kube_config`](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster_sync#kube_config) argument.

**Comment by bitnik** [comment]
thanks a lot for helping @rawmind0, that solved the problem!
