### ISSUE TITLE
What is `docker_version` doing?

### ISSUE THREAD

**Issue by ajfriesen** [rancher/terraform-provider-rancher2#83]
I do not get what the field `docker_version` is doing in this provider.

When using `engine_install_url` you can choose the docker version to install on your host os.
The scripts for that are located here:  https://github.com/rancher/install-docker
Maybe a reference to that repo would be helpful for others in the docs.

When omitting `docker_version`  everything works ok as of my recent testing this morning.

**Comment by rawmind0** [comment]
@ajfriesen  you are right, `docker_version` should be just a informative field but it was set as optional argument. 

I've submitted a PR #88 removing it from `rancher2_node_template` resource definition and including your suggestion about the docs update on `engine_install_url` argument.

**Comment by rawmind0** [comment]
Please, reopen issue if needed.
