### ISSUE TITLE
[rancher2_global_role] global role not found

### ISSUE THREAD

**Issue by rmammadli** [rancher/terraform-provider-rancher2#844]
Hi,

It seems that data source 'rancher2_global_role' can not obtain builtin global roles.

Please see the error below:

```
Error: [ERROR] global role with name "User-Base" not found
```

Code:
```
data "rancher2_global_role" "global" {
  name = "User-Base"
}
```

Terraform: v1.1.2

Provider: rancher2 v1.22.1

Thank you very much in advance!

**Comment by rawmind0** [comment]
Hi @rmammadli , i think there is a typo in your code. There isn't any builtin global role called `User-Base`, have you tried using `User Base` instead?? This should work fine.

**Comment by rmammadli** [comment]
Hi @rawmind0,

thanks a lot, it works like a charm:)
