### ISSUE TITLE
Failed to find schema

### ISSUE THREAD

**Issue by andersjohansson2021** [rancher/terraform-provider-rancher2#848]
Hi guys, im doing a terraform deploy of rke2, want to add the monitoring stack to it. But when i add a rancher2_app_v2 resource and run the script i receive the following "Bad response statusCode [404]. Status [404 Not Found]. Body: [code=NotFound, message=failed to find schema "my-cluster", baseType=error]" Anyone seen this before?

The resource looks as below:
resource "rancher2_app_v2" "monitoring" {
  name      = "rancher-monitoring"
  namespace = "cattle-monitoring-system"
  repo_name = "rancher-charts"
  chart_name = "rancher-monitoring"
  chart_version = var.monchart
  cluster_id = rancher2_cluster_v2.test-cluster.id
  values = file("values.yaml")

  depends_on = [rancher2_cluster_v2.test-cluster]
}

Regards,
/Anders.

**Comment by bugfest** [comment]
Instead of 

`cluster_id = rancher2_cluster_v2.test-cluster.id`

Try with:

`cluster_id = rancher2_cluster_v2.test-cluster.cluster_v1_id`

**Comment by andersjohansson2021** [comment]
Awesome, that got it installed.
However first time i ran the terraform script with the change i received this message:
Getting catalog V2 ID (rancher-charts): Getting Catalog V2: Timeout getting object V2 ID rancher-charts at cluster ID c-m-xrxcqpc4: Unknown schema type [catalog.cattle.io.clusterrepo]
Re-ran the script and it went through.

**Comment by bugfest** [comment]
You might need to wait until the cluster is ready/active. You could use rancher2_cluster_sync: https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster_sync

**Comment by andersjohansson2021** [comment]
Thanks a bundle, we can actually close this. I've added the cluster_sync as you suggested. All work like a charm.
