### ISSUE TITLE
rancher2_cluster_sync.kube_config is empty

### ISSUE THREAD

**Issue by bitnik** [rancher/terraform-provider-rancher2#849]
Versions:

- rancher version: 2.6.3
- rancher2 provider version: 1.22.2

Related code:

```hcl
resource "rancher2_cluster_sync" "wait_for_cluster_is_ready" {
  depends_on = [
    rancher2_cluster.rancher_cluster,
  ]
  cluster_id = rancher2_cluster.rancher_cluster.id
  state_confirm   = 12
  wait_alerting   = false
  wait_catalogs   = false
  wait_monitoring = false
}

output "rancher_kube_config" {
  value       = yamldecode(rancher2_cluster_sync.wait_for_cluster_is_ready.kube_config)
  description = "Kube config of the ahoj cluster"
}
```

Error:

```txt
Error: Error in function call

  on modules/rancher_worker/outputs.tf line 6, in output "rancher_kube_config":
   6:   value       = yamldecode(rancher2_cluster_sync.wait_for_cluster_is_ready.kube_config)
    ├────────────────
    │ rancher2_cluster_sync.wait_for_cluster_is_ready.kube_config has a sensitive value

Call to function "yamldecode" failed: on line 1, column 1: missing start of
document.
```

We had this problem before as well and it was fixed by using `rancher2_cluster_sync.kube_config` instead of `rancher2_cluster.kube_config`, see https://github.com/rancher/terraform-provider-rancher2/issues/829. It worked with rancher2 provider v1.22.1 but since we upgraded to v1.22.2 it started to fail again. This is happenning while we are creating a fresh cluster and if we do plan&apply second time, then there is no error and clusters are up.

**Comment by lapfrank12** [comment]
Same error here, even with `rancher2_cluster_sync.kube_config`.

**Comment by Edge94** [comment]
Hi,

Same error here.

Few weeks ago I was using the old way with Rancher 2.5, but it wasn't working with Rancher 2.6 :
**rancher2_cluster.mycluster.kube_config**

After creating a Suse Rancher case, they gave me the way to use with Rancher 2.6 (getting it from the rancher2_cluster_sync resource) :
**rancher2_cluster_sync.wait_cluster.kube_config**

I was able to make it working the 5th of January and the 7th it wasn't working anymore ... without any change from our side.
So, I reopened a case and I'm waiting for answers.

**Comment by Edge94** [comment]
Hi,

Any suggestion ?

Thanks

**Comment by rawmind0** [comment]
I was not able to consistently reproduce the issue, but it's seems there is a possible race condition, where the cluster may get `Active` condition before `Connected` condition. It should just eventually affects clusters on Rancher 2.6 with local cluster auth endpoint enabled. Working on a fix.

**Comment by rawmind0** [comment]
Submitted PR https://github.com/rancher/terraform-provider-rancher2/pull/859 to fix the issue.

**Comment by rawmind0** [comment]
PR https://github.com/rancher/terraform-provider-rancher2/pull/859 has been merged. Fix will be available at next release. Please, reopen the issue if required
