### ISSUE TITLE
Feature: Add users to clusters created with terraform

### ISSUE THREAD

**Issue by tibers** [rancher/terraform-provider-rancher2#85]
Hi folks. It looks like we can create clusters but I would also like to be able to add members to the cluster I create with this module. It should be pretty trivial to add a user based on their username, right? Suggested mock up:

```
members = {
  "MYAD\tibers" = "owner"
  "MYAD\user1" = "member"
}
```

Support for `Custom` would be cool to have but at least give us the most general tools.

**Comment by rawmind0** [comment]
Hi @tibers, 

you already have this feature available using cluster role template binding.

**Comment by tibers** [comment]
Hi there. Maybe I'm reading it wrong but my understanding was that this was for creating directory bindings if I have something like an LDAP-group-per-cluster: https://www.terraform.io/docs/providers/rancher2/r/clusterRole.html

Or am I reading this wrong? The documentation is light. I was referring to the members tab in the rancher UI which let me add individual users at various permissions levels to a cluster in an ad-hoc way if I have a flat directory structure.

**Comment by rawmind0** [comment]
Cluster role template binding is indeed for assign users or groups to a role template like member, admin,...in a cluster. Just like member tab in rancher ui.

**Comment by tibers** [comment]
Is there example code I can peek at?

**Comment by rawmind0** [comment]
On doc page you have an example, https://www.terraform.io/docs/providers/rancher2/r/clusterRole.html#example-usage

Just needed role template id, user id or principal id and cluster id where to apply.

**Comment by tibers** [comment]
So where I feel that's ambiguous is the clusterid can be computed from the other TF resource to create the cluster, but the user ID is what? The `u-abcd` from within rancher itself or the userid the user logs into the UI with (`MYAD\tibers`)? Similarly the templateid is something like `Owner` or `Owner User`? The rancher docs themselves use them interchangeably in places.

**Comment by rawmind0** [comment]
`cluster_id` is the ID of the cluster that has been created or not from TF. 

`user_id` is the rancher user ID, like you mention the `u-abcd` from within Rancher. You could also use `user_principal_id` instead. Same options for groups. User list can be get from API `https://<RANCHER_URL>/v3/users`

`role_template_id` is the rancher role template ID that defines k8s RBAC rules, like "cluster-admin", "cluster-member".... Role template list can be get from API `https://<RANCHER_URL>/v3/roletemplates`

**Comment by tibers** [comment]
Thank you very much for taking the time to explain this to me!
