### ISSUE TITLE
How do I remove RKE template_revisions?

### ISSUE THREAD

**Issue by burgerjeffrey** [rancher/terraform-provider-rancher2#852]
I would like to do maintenance and remove old RKE templates from my terraform code that were all created with the rancher2 terraform provider.  Has anyone done this before successfully?  I currently have 10 RKE templates with some of them being very old that I want to purge from my code and from the terraform state. Does anyone have any guidance or suggestions on doing this?

**Comment by rawmind0** [comment]
~~By design on Rancher, RKE template_revisions are append only. You can't remove template_revisions from ui neither.~~

**Comment by burgerjeffrey** [comment]
I believe you are incorrect, you can delete RKE template revisions from the Rancher WebUI.

![image](https://user-images.githubusercontent.com/30636081/151892020-07e1782d-6d9f-4f6b-b640-17ecfa581ee8.png)

I found three methods currently to do housecleaning on these RKE template revisions:

Before any method is tried:
    1. Update IaC to remove the obsolete RKE cluster template revision(s)
    2. Manually delete the obsolete RKE template revision(s) from the Rancher WebUI

**Method # 1:**
    1. Edit state to remove the RKE Template
       `terragrunt state pull > 1`
        `vi 1`
        `terragrunt state push 1`
    2. `terragrunt apply`
        validates all is in sync

**Method # 2:**
    1. Remove RKE template and revisions from terraform state
        `terragrunt state rm module.rancher_kubernetes_cluster.rancher2_cluster_template.main`
    2. Import the state of the RKE template and revisions for the DS cluster into terraform state
        `terragrunt import module.rancher_kubernetes_cluster.rancher2_cluster_template.main <id-of-cluster-template>`
    3. `terragrunt apply`
        validates all is in sync

**Method # 3:**
    1. Refresh terraform state with current state of the RKE cluster template and revisions for the DS cluster
        `terragrunt refresh -target module.rancher_kubernetes_cluster.rancher2_cluster_template.main`
    2. `terragrunt apply`
        validates all is in sync

**Comment by rawmind0** [comment]
@burgerjeffrey , you are right. My bad here, forget my previous message. 

Have you tried to remove the rke template revisions from your ft file and apply??  This should work fine, beside that may be you have a weird diff showing as `template_revisions` argument is it's a tf list and the provider will try to reorder it.

**Comment by burgerjeffrey** [comment]
I currently have template revisions V5, V6, V7, V8, V9, V10 & V11.  I removed template revision V5 from the terraform code, when I go to run a terraform apply it wants to do the following:

- delete V5
- modify V6 with properties from V10
- modify V10 with properties from V11
- delete V11

when i typed yes on the terragrunt apply it deleted V6.

if i run another terraform apply, I get the following error:

`Error: [ERROR] Validating cluster template revisions: NO default defined`
  `on .terraform/modules/rancher_kubernetes_cluster/aws_rancher_k8s_cluster/main.tf line 2, in resource` `"rancher2_cluster_template" "main":`
   `2: resource "rancher2_cluster_template" "main" {`

I am using rancher2 terraform provider 1.22.2.

In the Rancher GUI:
![image](https://user-images.githubusercontent.com/30636081/152025539-3475a878-f9b9-4a33-a6f0-045149a4cf18.png)
****

**Comment by rawmind0** [comment]
I'm not able to reproduce your issue. Starting with template revisions V5, V6, V7, V8, V9, V10 & V11(default). I removed template revision V5 from the terraform code. On tf apply, the provider try to reorder the list (seeing at diff messages) but properly removing the V5 template revision. Next, i added V12 properly and removes V7 and V8 also properly.

> `Error: [ERROR] Validating cluster template revisions: NO default defined` 

This error is produced by the (resource_rancher2_cluster_template custom diff validator)(https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/resource_rancher2_cluster_template.go#L109) when no default template revision is found. Is it defined in your tf file??

**Comment by burgerjeffrey** [comment]
Does the order of the template revisions matter if they were created and placed in terraform state with older versions of the rancher2 terraform provider?  Curious if anything changed that make the list more manageable.

**Comment by rawmind0** [comment]
The template revisions are saved in a tf list so the order matters, but the provider is ordering it when it's modified to minimize it.

**Comment by matttrach** [comment]
The last comment on this issue was 2 years ago, but this appears to be a list aggregation issue. It can be problematic to place resources into lists in Terraform because it reorders the items in the list each time an action is taken on one of them. It will always consolidate the list and the index of the items will change, which will often result in resources being recreated. To prevent this always place resources in a map with a set key. A cheap hack for this is to use strings as numbers as the keys like below. As such, I am going to close this issue as stale, but feel free to open a new one if this is still an issue.

`
for_each = {for i in range(length(items)): string(i) => items[i]}
`
