### ISSUE TITLE
rke2_config and Harvester support missing in rancher2_cluster_v2 resource

### ISSUE THREAD

**Issue by ravarga** [rancher/terraform-provider-rancher2#853]
We want to use Terraform to deploy Guest clusters on Rancher/Harvester. 

When I read the rancher2 terraform provider I found out that for Rancher v2.6.x I need the rancher2_cluster_v2 resource for this. However it lacks rke2_config and Harvester support.

When it will be available?

SURE-4001

**Comment by andrehofman** [comment]
I want this too

**Comment by alexdepalex** [comment]
Oh man, so looking forward to this feature.

**Comment by kapej42** [comment]
Yes please

**Comment by rawmind0** [comment]
Harvester is not yet supported by the provider for `rancher2_machine_config_v2`, but rke2 is already supported for [`rancher2_cluster_v2`](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster_v2#creating-rancher-v2-amazonec2-cluster-v2)

**Comment by thedadams** [comment]
This was implemented [here](https://github.com/rancher/terraform-provider-rancher2/pull/861).

**Comment by slickwarren** [comment]
tested using [this as a reference for main.tf](https://github.com/harvester/harvester/issues/2140#issuecomment-1096259994) and versions harvester v1.0.2, rancher v2.6.5, and terraform: 
```
source  = "rancher/rancher2"
      version = "1.23.0"
```
* single node all roles rke2 cluster via terraform -- pass
* single node all roles rke1 cluster via terraform -- pass
* multi node all roles rke2 cluster via terraform -- pass
* single node all roles rke1 cluster via terraform -- pass
* mixed roles per node rke2 cluster via terraform -- pass
* mixed roles per node rke1 cluster via terraform -- pass
