### ISSUE TITLE
Terraform/rancher2auth_config_github: Unauthorized 401: must authenticate

### ISSUE THREAD

**Issue by adam-sdk** [rancher/terraform-provider-rancher2#855]
I'm trying to configure Github authentication for rancher2 following this link : https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/auth_config_github

but when using this resource, I get 401 Unauthorized response.

here is my code : 
```
terraform {
  required_providers {
    rancher2 = {
      source = "rancher/rancher2"
      version = "1.21.0"
    }
  }
}

provider "rancher2" {
  api_url   = "https://{{ rancher_public_domain }}"
  bootstrap = true
}

resource "rancher2_bootstrap" "admin" {
  password = "{{ admin_password }}"
  telemetry = false
  ui_default_landing = "ember"
}

resource "rancher2_auth_config_github" "github" {
  client_id = "<MY_GITHUB_CLIENT_ID>"
  client_secret = "<MY_GITHUB_CLIENT_SECRET>"
  enabled = true
}

output "rancher_username" {
  value = rancher2_bootstrap.admin.user
}

output "rancher_token" {
  value = rancher2_bootstrap.admin.token
  sensitive = true
}

output "rancher_url" {
  value = rancher2_bootstrap.admin.url
```
the error is : 
```
Error: Bad response statusCode [401]. Status [401 Unauthorized]. Body: [message=Unauthorized 401: must authenticate] from [https://{{ rancher_public_domain }}]

  with rancher2_auth_config_github.github,
  on main.tf line 21, in resource "rancher2_auth_config_github" "github":
  21: resource "rancher2_auth_config_github" "github" {
```
the error doesn't occur when i'm not using this resource. Can I have some help ? Thanks

**Comment by rawmind0** [comment]
This tf provider has 2 modes of working, `admin` and `bootstrap` modes. To manage any rancher2 resource (besides rancher2_bootstrap), the admin mode should be defined, please, take a look to the [doc page](https://registry.terraform.io/providers/rancher/rancher2/latest/docs) and the example section to know how to use it.

**Comment by adam-sdk** [comment]
thank you for your answer , found the solution on this topic https://github.com/hashicorp/terraform/issues/27934 .
As said by @[kriswuollett] on the topic , I had to split my 2 stacks :
 one stack for bootstrap  the infra and another stack for using the config.
