### ISSUE TITLE
S3 Cloud Credentials does not store the cert on provisioned hosts correctly

### ISSUE THREAD

**Issue by braunsonm** [rancher/terraform-provider-rancher2#856]
The S3 cloud credentials does not store the CA correctly on the VMs and as suck restores will never work.

Steps:
1. Create an s3_cloud_credential using https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cloud_credential
```
resource "rancher2_cloud_credential" "backups" {
  name = "xyz"
  s3_credential_config {
    access_key = "123"
    secret_key = "123"
    default_endpoint = "https://example.com"
    // note still required even if you skip verify
    default_endpoint_ca = file("my-ca.crt")
    default_skip_ssl_verify = true
  }
}
```
2. Provision an RKE2 cluster and backups using the cloud credentials
3. Backups will work fine, then trigger a restore in the UI
4. The restore will fail because the certificate that is found in `/var/lib/rancher/rke2/etc/config-files/s3-endpoint-ca.crt` will just be a text file that has the contents:
```
/var/lib/rancher/rke2/etc/config-files/s3-endpoint-ca.crt
```
5. The `rancher-system-agent` will throw errors that the certificate is not valid and the restore will never complete.

To make matters worse, the system agent will keep replacing the file with a bad version so you can never fix the problem.

**Comment by matttrach** [comment]
This issue was created 2 years ago, but it appears to be an issue for Rancher rather than the provider. As such, I am going to close this issue as stale, but please feel free to open a new issue in the rancher/rancher project if this is still an issue on the newer versions of Rancher.
