### ISSUE TITLE
Vmware clone from template visual bug

### ISSUE THREAD

**Issue by PetitXander** [rancher/terraform-provider-rancher2#857]
I made a terraform script to create a node template with the following code:

```
resource "rancher2_node_template" "vsphere_template" {
  name = "Vsphere_template"
  cloud_credential_id = rancher2_cloud_credential.creds_vsphere.id
  engine_install_url = "https://releases.rancher.com/install-docker/20.10.sh"
  vsphere_config {
    datacenter = var.datacenter
    datastore = var.datastore
    cpu_count = var.cpu_count
    memory_size = var.memory_size
    disk_size = var.disk_size
    network = ["VM Network"]
    cfgparam = ["disk.enableUUID=TRUE"]
    creation_type = "template"
    clone_from = var.clone_from

  }
}
```

with the following vars file:

```
variable "datacenter" {
  type = string
  default = "StudentDatacenter"
}

variable "datastore" {
  type = string
  default = "####"
}

variable "cpu_count" {
  type = string
  default = "2"
}

variable "memory_size" {
  type = string
  default = "2048"
}

variable "disk_size" {
  type = string
  default = "20000"
}

variable "clone_from" {
  type = string
  default = "ubuntu-focal-20.04-cloudimg"
}
```
As you can see i want to clone from the template "ubuntu-focal-20.04-cloudimg". When I use this template it clones from the correct template. However if i look at the node template in rancher it shows whatever the first template is in the list:
![image](https://user-images.githubusercontent.com/55786870/151975155-6210b14f-f552-4cfb-9d41-748874be56ec.png)

**Comment by GaboFDC** [comment]
Same as #1050 you need yo put the whole path for it to work properly, API manages this but UI don't

**Comment by matttrach** [comment]
The last comment on this issue is over a year old, but it appears to be resolved already. As such, I am going to close this issue as stale, but feel free to open a new one if this is still a valid problem in newer versions of Rancher and the provider.
