### ISSUE TITLE
[FEATURE] The Terraform provider for Harvester should provide a bootstrap feature (similar to rancher2) to setup a password and automatically download the configuration 

### ISSUE THREAD

**Issue by guangbochen** [rancher/terraform-provider-rancher2#862]
**Is your feature request related to a problem? Please describe.**
The Terraform provider for Harvester does not implement a bootstrapping method that can be used after an automatic installation of Harvester. This means, a manual process should happen where a user connects to the UI or a node and gets the KUBECONFIG. This is unfortunate, as the whole process should be more automated.
Suppose someone uses Terraform to provision machines on Equinix (Step 1), they probably want to automatically bootstrap Harvester and continue creating resources inside Harvester (Step 2), without needing to manually connect to a console in between two steps.

**Describe the solution you'd like**
Similarly to the Terraform Rancher2 provider, it should be possible to have a harvester_bootstrap resource (or even use the rancher2 provider) to bootstrap Harvester and output a KUBECONFIG file that can be used by the actual Harvester Terraform configuration.

**Describe alternatives you've considered**
I tried the rancher2_bootstrap resource (now, it does fail with 404 Error code). 

Link to https://github.com/harvester/harvester/issues/1797

**Comment by oxr463** [comment]
Why was this opened here? The harvester provider is here: https://github.com/harvester/terraform-provider-harvester

**Comment by guangbochen** [comment]
This is related to https://github.com/rancher/terraform-provider-rancher2/pull/861, adding Harvester resources support to the `rancher2-terraform-provider`.

**Comment by futuretea** [comment]
Track in https://github.com/harvester/harvester/issues/1797

**Comment by matttrach** [comment]
This appears to be resolved from the Rancher2 provider side with the merge of #861, please reopen or generate a new issue if more is necessary.
