### ISSUE TITLE
[ feature request ] hetzner cloud firewalls

### ISSUE THREAD

**Issue by leonsteinhaeuser** [rancher/terraform-provider-rancher2#865]
Hi there,

when I tried to set up a node template and furthermore tried to configure a firewall rule for a specific node template, I found out that this is currently not possible. 

As a workaround, I attached a label to the node and used a label selector on the firewall side instead. 

Since this is not the way I want to configure firewall rules for nodes, I would appreciate the ability to set the firewall at the node template level (hetzner_config). The underlying node driver https://github.com/JonasProgrammer/docker-machine-driver-hetzner/blob/045f23ef6cb4cfc975beaf5dfee67353645b10e8/driver.go#L46 already provides such functionality. 

If I am correct in my assumptions, the only two files that need to be changed are the following:
- https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/schema_node_template_hetzner.go
- https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/structure_node_template_hetzner.go

**Comment by matttrach** [comment]
The last action on this issue was over a year ago, but I believe this is more a request for Rancher rather than the Terraform provider. As such, I am going to close this issue as stale, but feel free to open a new issue if this is still valid in newer versions of Rancher and the provider.
