### ISSUE TITLE
cluster_auth_endpoint key invalid under rancher2_cluster

### ISSUE THREAD

**Issue by jamiebuxxx** [rancher/terraform-provider-rancher2#87]
Hello, 

I'm having issues trying to enable the `cluster_auth_endpoint` argument under the `rancher2_cluster` resource. Based on what is listed in the doc, it appears to be in the right place.

Here's a snippet of the code:

```
resource "rancher2_cluster" "k8s_rancher_cluster" {
  name = "${var.cluster_name}"
  cluster_auth_endpoint {
    enabled = true,
    fqdn = "${var.api_name}"
  }
...
```

And here's the output I'm receiving:
```
Error: rancher2_cluster.k8s_rancher_cluster: : invalid or unknown key: cluster_auth_endpoint
```
Here is the my Terraform and plugin versions
```
terraform -version
Terraform v0.11.13
+ provider.aws v1.44.0
+ provider.rancher2 v1.3.0
+ provider.template v1.0.0
+ provider.vault v2.1.0
```

**Comment by rawmind0** [comment]
Hi @jamiebuxxx,

it seems you have a typo in `cluster_auth_endpoint`-`enabled` field, ending with `,`. Should work with 

```
resource "rancher2_cluster" "k8s_rancher_cluster" {
  name = "${var.cluster_name}"
  cluster_auth_endpoint {
    enabled = true
    fqdn = "${var.api_name}"
  }
...
```

**Comment by jamiebuxxx** [comment]
Unfortunately, I'm getting the same error even without the `,`.

```
Error: rancher2_cluster.k8s_rancher_cluster: : invalid or unknown key: cluster_auth_endpoint
```
I will try and reinstall the rancher2 terraform plugin to see if that makes a difference.

**Comment by rawmind0** [comment]
Yeah, may be there is something wrong on your terraform installation. Just tested and working fine with `provider.rancher2 v1.3.0`  

```
# terraform -version
Terraform v0.12.2
+ provider.rancher2 v1.3.0
```

**Comment by jamiebuxxx** [comment]
I ended up rebuilding the plugin and everything is working appears to be working as expected. Thanks for the advice.

**Comment by jamiebuxxx** [comment]
However, after upgrading the plugin I'm getting different error

```
rancher2_cluster.k8s_rancher_cluster: Bad response statusCode [401]. Status [401 Unauthorized]. Body: [message=must authenticate] from [https://rancher2.cloud.local/v3]
```
I haven't changed anything in my rancher2 provider since rebuilding the plugin. 

```
provider "rancher2" {
  api_url    = "https://${var.rancher_server}"
  access_key = "${var.rancher2_access_key}"
  secret_key = "${var.rancher2_secret_key}"
}
```
I can confirm that the access_key and secret_key are correct.

**Comment by rawmind0** [comment]
@jamiebuxxx , check for `access_key` and `secret_key` values. It should work fine, i just can reproduce the error if i set wrong values there.

**Comment by jamiebuxxx** [comment]
Weird. I just recreated access_keys and token on the Rancher2 server, add the keys directly in the main.tf file, and still experiencing this error. 

I just confirmed that the version of the plugin that I built before(the one that didn't work with `cluster_auth_endpoint` argument) is working as expected. The new plugin was built from master. I can try to build the plugin from the 1.3.0 release branch. Is there an already compiled executable version of the plugin?

**Comment by rawmind0** [comment]
Normally, you don't need to build the provider. The provider is officially supported by terraform, just execute `terraform init` and the provider should be downloaded. `cluster_auth_endpoint` argument was added on rancher2 provider [v1.2.0](https://github.com/terraform-providers/terraform-provider-rancher2/blob/master/CHANGELOG.md#120-june-12-2019)

If you are using `token_key` you don't need to specify `access_key` nor `secret_key`

**Comment by jamiebuxxx** [comment]
Ah, I see that the plugin is provided now! It was provided before and we need to compile the plugin. After download the plugin during the `terraform init`, everything is working as expected.
