### ISSUE TITLE
[FEATURE] rke2/k3s Rotate Encryption Keys

### ISSUE THREAD

**Issue by jakefhyde** [rancher/terraform-provider-rancher2#870]
Implement encryption key rotation according to https://github.com/rancher/rancher/issues/35436

**Comment by snasovich** [comment]
Blocked by https://github.com/rancher/rancher/issues/35436 at this time.

**Comment by snasovich** [comment]
@timhaneunsoo , this surfaced during doing some housekeeping on TF issues. Was this ever tested? We can test it together with encryption key rotation fixes for next TF release for 2.6.x line (2.0.0). Changing milestone to match and moving "To Test".
cc @sowmyav27

**Comment by snasovich** [comment]
Moving to Q2 milestone to reduce QA scope; the feature has been done for a long time and is likely working.
