### ISSUE TITLE
node_pool name is being set to the hostname_prefix

### ISSUE THREAD

**Issue by cnuber** [rancher/terraform-provider-rancher2#89]
When creating a rancher2_node_pool the name that appears in the UI for the node_pool is the value from hostname_prefix rather than the value from the name field. 

Example:

resource "rancher2_node_pool" "worker_node_pool" {
  cluster_id =  "${rancher2_cluster.cluster.id}"
  name = "worker-node-pool"
  hostname_prefix =  "worker-instance"
  node_template_id = "${rancher2_node_template.nodetemplate.id}"
  quantity = 1
  control_plane = false
  etcd = false
  worker = true
}

Result:

The UI shows:

 Pool: worker-instance 

Expected:

Pool: worker-node-pool

**Comment by rawmind0** [comment]
Do you mean the "Name Prefix" field that you can see under "Node Pools" section on cluster edit/creation?? If so, this field is `hostname_prefix`.

**Comment by cnuber** [comment]
I'm referring to the name next to Pool in the Nodes view for a cluster.  See attached and notice next to Pool it shows nuber-cp-0 which is the hostname prefix, rather than what's been provided in the name field for the node pool.

![Screen Shot 2019-08-07 at 1 50 00 PM](https://user-images.githubusercontent.com/11045170/62645522-65d11400-b91a-11e9-840f-221b5e97d621.png)

**Comment by rawmind0** [comment]
Ok, got it. But this is the same if you create node-pool from rancher UI, it's showing `hostname_prefix`. I think this request should be opened at rancher/rancher repo.

**Comment by rawmind0** [comment]
Please, reopen issue if needed.
