### ISSUE TITLE
Add data source "rancher2_project"

### ISSUE THREAD

**Issue by headcr4sh** [rancher/terraform-provider-rancher2#9]
### Background

We have been rolling our own custom-made Terraform provider for Rancher 2 ([link](https://github.com/iplabs/terraform-provider-rancher2)). Once we realized that an official provider plugin was being developed, we abandoned the project, though.

Now we would like to switch to the new provider but found a few things still missing.

### Missing feature: `data "rancher2_project"`

We would like to access some of the automatically-generated Rancher 2 projects (namely: "Default" and "System") to automatically associate some of our Kubernetes namespaces with them. (Our homegrown provider plugin offers this functionality: [link to go sources](https://github.com/iplabs/terraform-provider-rancher2/blob/master/rancher2/data_project.go))

Example

```hcl
data "rancher2_project" "system" {
  cluster_id = "${var.my_rancher2_cluster_id}"
  name       = "System"
}

resource "kubernetes_namespace" "istio_system" {
  metadata {
    annotations {
      "field.cattle.io/projectId" = "${data.rancher2_project.system.id}"
    }
    name = "istio-system"
  }
}
```

**Comment by rbq** [comment]
`rancher2_cluster` provides the ID of the *System* and *Default* projects. For me this works (TF 0.12.0):

```terraform
resource "rancher2_namespace" "istio_system" {
  name       = "istio-system"
  project_id = rancher2_cluster.YOUR_CLUSTER.system_project_id
}
```
