### ISSUE TITLE
Missing type in rancher2_secret for project level secret

### ISSUE THREAD

**Issue by jympetalmd** [rancher/terraform-provider-rancher2#905]
Hi,

The ressource rancher2_secret is missing the type field for specifying a spec. type, ex. 
`type: kubernetes.io/dockerconfigjson`

I have to use another provider to create the secret, and is at a namespace level...
```
resource "kubectl_manifest" "docker_secret" {
  yaml_body = <<YAML
apiVersion: v1
kind: Secret
metadata:
  name: docker-creds-secret-pure
  namespace: cert-manager
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ${base64encode(jsonencode(
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "auth": "${nonsensitive(var.docker_auth)}",
          "email":"user@cie.com"
        }
      }
    }
  ))}
YAML
}
```
Adding the project ID annotations doesn't seams to trigger the duplication process.

This is especially useful for me for providing a docker pull secret in projects since the the private_registries (rancher2_cluster) doesn't take the auth token like so:
```
    private_registries {
      url = "docker.io"
      is_default = true
    }
    private_registries {
      url = "docker.io"
      user = "user@cie.com"
      password = var.docker_auth
      is_default = false
    }
```

**Comment by nbertram** [comment]
For anyone who like me stumbles on this :confused: self-closing issue later, the solution in this instance is to use the [rancher2_registry](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/registry) resource type, not the `rancher2_secret` resource.
