### ISSUE TITLE
Expose kube_config as a data source

### ISSUE THREAD

**Issue by Buzzglo** [rancher/terraform-provider-rancher2#91]
I have written a module for deploying an RKE cluster and a 2nd one to AVI-fy the same cluster AVI requires access to the master node via the api url /k8/cluster/cluster-id. I cant use dependancies across modules nor can I use it as one module as the cluster-id becomes available before the kube-config is ready to be consumed by AVI. Terraform doesnt have a delay. so I'm forced to run the script in two legs. I think if I could read this as a datasource from the avi module I could loop and keep checking the datasource. 

Maybe add a completed / valid property. Unless terraform can get there stuff working. IDK just a customer trying to automate multiple deployments of clusters.

**Comment by rawmind0** [comment]
@Buzzglo, a bunch of datasources are already added on the provider, including cluster that contains kibe_config PR#60.

We'll cut a new release this week, including these new features.

**Comment by Buzzglo** [comment]
Great stuff cant wait, thanks
