### ISSUE TITLE
rancher2 provider auth broken in 1.4.0

### ISSUE THREAD

**Issue by jeffb4** [rancher/terraform-provider-rancher2#92]
`access_key` and `secret_key` attributes for the rancher2 provider consistently return a 401 unauth with the `1.4.0` provider.

setting `token_key` instead (with access_key and secret_key concatenated) works fine

**Comment by rawmind0** [comment]
@jeffb4 , thanks for reporting this. 

Submitted PR #95 to address it.

**Comment by rawmind0** [comment]
Released v1.4.1 that fix auth issue.

**Comment by rawmind0** [comment]
Please, reopen issue if needed
