### ISSUE TITLE
Add RKE Support for ACI Network Provider to Terraform Provider

### ISSUE THREAD

**Issue by a-blender** [rancher/terraform-provider-rancher2#922]
Add RKE support for the [ACI Network Provider](https://www.cisco.com/c/en/us/solutions/data-center-virtualization/application-centric-infrastructure/index.html) to the rancher2 terraform provider. The [aci_network_provider](https://registry.terraform.io/providers/rancher/rke/latest/docs/resources/cluster#aci_network_provider) is already supported in the docs. It just needs to be added to the provider.

**Comment by a-blender** [comment]
Discussed with @Oats87 since I noticed the `aci_network_provider` field is documented in the terraform docs for the [rke_cluster](https://registry.terraform.io/providers/rancher/rke/latest/docs/resources/cluster#aci_network_provider) resource but not in the [rancher2_cluster](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster#network) resource. This is not a blocker. It will be implemented in the rancher 2 terraform provider, but ACI is not supported as an option in the UI.

**Comment by annablender** [comment]
I had to bump several packages that were out of date in the tf provider go.mod. Golang has also been updated to 1.17. In addition, drone was failing with errors when using the latest golang alpine image `golang 1.17.3-alpine3.16 so @kinarashah and I updated the drone image to golang 1.17.3 and the build image to golang 1.17.3-alpine3.13 because of this issue https://github.com/docker-library/php/issues/1177.

We're suspicious there may be a problem with how drone runs the tf tests so I've commented out the tests in the GNU makefile.

**Comment by a-blender** [comment]
In order for ACI network provider support to work properly, the tf rancher2 provider had to have the rancher/rancher and go client dependencies bumped, as well as go updated to 1.17. The tf provider now uses go 1.17-alpine3.13 instead of 3.14 due to this issue https://github.com/Mellanox/k8s-rdma-shared-dev-plugin/issues/49. Drone was also having issues running tests with that image, so drone now uses go 1.17.3.

The dependency bump PR https://github.com/rancher/terraform-provider-rancher2/pull/959 has been merged. I rebased the updates into  https://github.com/rancher/terraform-provider-rancher2/pull/912 (ACI network provider support) which should fix the CI.

**Comment by a-blender** [comment]
https://github.com/rancher/terraform-provider-rancher2/pull/912 has been merged

**Comment by a-blender** [comment]
We do not have the Cisco infrastructure to test the ACI CNI directly, so the smoke testing done by the community PR's author will suffice https://github.com/rancher/terraform-provider-rancher2/pull/912#issuecomment-1185425672. @fpants I'd also recommend testing ACI config on a non-imported RKE cluster with the terraform rancher2 provider. Thank you for your patience on this issue and please let us know if you run into any issues with provisioning this network plugin.

**Comment by fpants** [comment]
We are using a local build of the rancher2 terraform provider with the code from #912 to provision RKE clusters with the ACI CNI in Rancher. It works as expected, including scaling up and down nodes in node pools.
And thanks again, I'm looking forward to having the functionality officially present in the provider.

**Comment by a-blender** [comment]
That's great. Happy to help!
