### ISSUE TITLE
for_each in rancher2_registry keeps changing the order of the list that has not changed

### ISSUE THREAD

**Issue by sarg3nt** [rancher/terraform-provider-rancher2#923]
Each time we `terraform apply` registries keep getting updated because the list order is getting changed.  Our local data is not changing, you can  `terraform apply` over and over and watch it flip back and forth.  Very annoying because we deploy this with CD and it's saying there are changes every time when there are not.

Here's our code:

```
variable "containerRepositories" {
  type = list(object({
    url      = string
    username = string
    password = string
  }))
  default     = []
  description = "A list of Docker container repositories."
}

 containerRepositories = [
    {
      url      = "dcc-docker-release.<redacted>"
      username = "bld_dcc"
      password = "<redacted>"
    },
    {
      url      = "dcc-docker-dev.<redacted>"
      username = "bld_dcc"
      password = "<redacted>"
    },
    {
      url      = "dcsws-docker-release.<redacted>"
      username = "bld_dcc"
      password = "<redacted>"
    },
    {
      url      = "dcsws-docker-dev.<redacted>"
      username = "bld_dcc"
      password = "<redacted>"
    }
  ]

resource "rancher2_registry" "regcred-build" {
  count        = length(var.containerRepositories) > 0 ? 1 : 0
  name         = "regcred"
  description  = "Registry entry for k8s to talk to customers Artifactory registries"
  project_id   = rancher2_project.jenkins-project-build.id
  namespace_id = rancher2_namespace.jenkins-namespace-build.id
  dynamic "registries" {
    for_each = var.containerRepositories
    content {
      address  = registries.value["url"]
      username = registries.value["username"]
      password = registries.value["password"]
    }
  }
}

```

The result of running terraform apply when there have been no updates. If we apply this, then run it again, they will “switch back”

```
~ resource "rancher2_registry" "regcred" {
        id           = "jenkins-dcs:regcred"
        name         = "regcred"
        # (5 unchanged attributes hidden)

      ~ registries {
          ~ address  = "dcsws-docker-release.<redacted>" -> "dcc-docker-release.<redacted>"
            # (2 unchanged attributes hidden)
        }
      ~ registries {
          ~ address  = "dcc-docker-release.<redacted>" -> "dcsws-docker-release.<redacted>"
            # (2 unchanged attributes hidden)
        }
        # (2 unchanged blocks hidden)
    }
```

We are running Terraform v1.1.9 and rancher/rancher2 v1.23.0

I posted this on the Terraform forum here
https://discuss.hashicorp.com/t/for-each-keeps-changing-the-order-of-a-list-that-has-not-changed/39440
And was told it's a bug in the provider.

Thoughts?

**Comment by jiaqiluo** [comment]
This bug is confirmed and reproduced in terraform-provider-ranche2 v3.2.0

## Causes 

It happens because when terraform-provider-rancher2 flattens the registry credential, it needs to convert a Map into a List, Golang does not guarantee the order of returned objects when traversing a Map, and terraform-provider-rancher2 saves items in the order of receiving, so the order of items in the final List may change even though it is the same set of items. Therefore, Terraform detects and reports changes.


## Reproducion 

The following TF file is used to reproduce the bug. 

<details>
<summary>main.tf</summary>

``` terraform

terraform {
  required_providers {
    rancher2 = {
      source = "rancher/rancher2"
    }
  }
}

variable "rancher_api_url" {
  default = "<sensitive value>"
}

variable "rancher_admin_bearer_token" {
  default = "<sensitive value>"
}
 


provider "rancher2" {
  api_url   = var.rancher_api_url
  token_key = var.rancher_admin_bearer_token
  insecure  = true
}
variable "something" {
  type = map(set(object({
    address  = string
    username = string
    password = string
  })))
  default = {
    "foo" = [
      {
        address = "ddddd.test.com"
        username = "dddd1111"
        password = "dddd1111"
      },
      {
        address = "rrrrr.test.com"
        username = "rrrr3333"
        password = "rrrr3333"
      },
      {
        address = "ppppp.test.com"
        username = "pppp22222"
        password = "pppp22222"
      },
    ]
  }
}

resource "rancher2_registry" "foo" {
  for_each     = var.something
  name         = "test-registries"
  description  = "Terraform registry foo"
  project_id   = "c-jjqch:p-trl5c"
  namespace_id = "ns1"
  dynamic "registries" {
    for_each = each.value
    content {
      address  = registries.value["address"]
      username = registries.value["username"]
      password = registries.value["password"]
    }
  }
}

````

</details>


After invoking the `terraform apply` command multiple times, TF will prompt for the following in-place update in which it switches the order of the registry entries.  

```
>  terraform apply
rancher2_registry.foo["foo"]: Refreshing state... [id=ns1:test-registries]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # rancher2_registry.foo["foo"] will be updated in-place
  ~ resource "rancher2_registry" "foo" {
        id           = "ns1:test-registries"
        name         = "test-registries"
        # (5 unchanged attributes hidden)

      ~ registries {
          ~ address  = "rrrrr.test.com" -> "ddddd.test.com"
          ~ username = "rrrr3333" -> "dddd1111"
            # (1 unchanged attribute hidden)
        }
      ~ registries {
          ~ address  = "ddddd.test.com" -> "ppppp.test.com"
          ~ username = "dddd1111" -> "pppp22222"
            # (1 unchanged attribute hidden)
        }
      ~ registries {
          ~ address  = "ppppp.test.com" -> "rrrrr.test.com"
          ~ username = "pppp22222" -> "rrrr3333"
            # (1 unchanged attribute hidden)
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: n

Apply cancelled.
```
 
## Workaround 

Save only one registry in each rancher2_registry resource.

**Comment by jiaqiluo** [comment]
SURE-6741

**Comment by jiaqiluo** [comment]
wait for RC

**Comment by jiaqiluo** [comment]
Can be validated by using https://github.com/rancher/terraform-provider-rancher2/releases/tag/v4.0.0-rc5

Please refer to my previous comment for reproduction steps

**Comment by Josh-Diamond** [comment]
Ticket #923 - Test Results - ✅ 
---

Reproduced with tfp-rancher2 `v3.2.0`:
1. Using `main.tf` provided in reproduction steps above ^^, create a `rancher2_registry` resource, with multiple registries
2. Once successful, without modifying the `main.tf`, re-run `terraform apply` multiple times and ensure no changes are detected
3. Reproduced - terraform detects changes with no modifications to the `main.tf` file

Screenshot:
<img width="1134" alt="Screenshot 2023-12-01 at 3 42 20 PM" src="https://github.com/rancher/terraform-provider-rancher2/assets/46494969/5bbd2ca3-ef02-434d-89da-c69aae95fe8c">

---

Verified with tfp-rancher2 `v4.0.0-rc5`:
1. Using `main.tf` provided in reproduction steps above ^^, create a `rancher2_registry` resource, with multiple registries
2. Once successful, without modifying the `main.tf`, re-run `terraform apply` multiple times and ensure no changes are detected
3. Verified - no changes detected; as expected

Screenshot:
<img width="1100" alt="Screenshot 2023-12-01 at 3 39 54 PM" src="https://github.com/rancher/terraform-provider-rancher2/assets/46494969/db415795-6dae-4b8d-8d91-2abcb7caae71">
