### ISSUE TITLE
Add ability to set the s3 backup path

### ISSUE THREAD

**Issue by vukor** [rancher/terraform-provider-rancher2#93]
In rancher v2.2.7 release version was "Added ability to set the s3 backup path" - https://github.com/rancher/rancher/releases

Could you please add this ability to the "rancher2_cluster" terraform resource?

Thank you.

**Comment by rawmind0** [comment]
Submited PR #101 to add this feature.

**Comment by vukor** [comment]
Thank you @rawmind0

**Comment by rawmind0** [comment]
Merged PR that address issue. Please, reopen issue if needed.
