### ISSUE TITLE
Add new user project attachment resource

### ISSUE THREAD

**Issue by Shocktrooper** [rancher/terraform-provider-rancher2#931]
In lieu of service tokens creation capability  being done as part of rancher/terraform-provider-rancher2#926 I would also like to be able to assign users to projects so that the token created for a service account user is scoped correctly to the projects that it should access.  Looking through the provider as it is today it seems that it is not possible with terraform to attach users to projects, if this capability does exist today I would appreciate it if someone could point me in the right direction.  If there is not a way to do this today I can pick up this work myself and would like some feedback on design from the maintainers of this resource before I start developing this in the wrong direction.

**Comment by sboschman** [comment]
https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/project_role_template_binding ?

**Comment by Shocktrooper** [comment]
I think that is actually what I was looking for which for some reason I couldn't find in the provider docs. I will check back and close this if it what I was looking for.  Thank you @sboschman !
