### ISSUE TITLE
Import namespace in project with resource quota set is not possible

### ISSUE THREAD

**Issue by stefan-sesser** [rancher/terraform-provider-rancher2#933]
Hi,
I am currently trying to import existing projects and namespaces in terraform. Unfortunately I saw the same error message on some namespaces: 
`can't move namespace. Project <...> has resource quota set`
In the terraform provider code I have found the following:
https://github.com/rancher/terraform-provider-rancher2/blob/6f39677a79339a7f46a652e7b1f2f42cb44c6221/rancher2/import_rancher2_namespace.go#L26
In case the projectID is not empty the NamespaceMove function of the clusterClient will be called. 

In the rancher api i have found the following code:
https://github.com/rancher/rancher/blob/4898daefeaa2b993e62ed7c91cfbea2d6089595c/pkg/api/norman/customization/namespace/namespace.go#L90
In case the actionName is move, the projectID is not empty and the project.Spec.ResourceQuota != nil an error will be thrown. 
For me this looks like it is not possible to import an existing namespace to a project with resource quotas set. This shouldn't be the default behaviour, or?
Thanks

**Comment by stefan-sesser** [comment]
I just tried to import the namespace without the project id:
`terraform import rancher2_namespace.test_namespace <clsuter_id>.test-namespace`
This seems to work now!?

According to: https://www.terraform.io/cli/import `import` only brings it under Terraform management. For me the behavior is strange that import can also change the existing environment. In that case move the namespace to other projects

**Comment by eugene-jetruby** [comment]
This is definitely a bug, and a severe one. `terraform import` should never modify infrastructure. Can this be prioritized?

**Comment by matttrach** [comment]
Is your particular problem resolved then?
> I just tried to import the namespace without the project id: `terraform import rancher2_namespace.test_namespace <clsuter_id>.test-namespace` This seems to work now!?

If so, that is wonderful news! I will open a separate issue to resolve the poor import behavior.

**Comment by ferenc-kiss** [comment]
It is working now with version 4.0.0 for me!

**Comment by matttrach** [comment]
Awesome! Thank you for the feed back! 
I eagerly await a reply from the OP to close this issue.

**Comment by matttrach** [comment]
I have opened https://github.com/rancher/terraform-provider-rancher2/issues/1319 to track the larger problem with importing.

**Comment by matttrach** [comment]
closing this as stale
